docs/adr/0002-videos-languages.rst
docs/adr/index.rst

This ADR describes how we handle videos, their different audio versions,
the subtitles and sign-languages auxialiry videos. In one word:
accessiblity

📝 (adr) Add ADR 0002: videos languages

---

docs/adr/0004-soft-deletion.rst
docs/adr/index.rst
docs/dev.rst

This ADR describes how we'll handle deletion to avoid losing data

📝 (adr) Add ADR 0004: soft-deletion

---

.gitignore
.vscode/settings.json

Someone committed their .vscode folder to the repo 😒. Delete it and add a line to .gitignore to make sure it does not happen again.

🔥(git) delete .vscode folder & gitignore it

---

.circleci/config.yml
.prettierrc
package.json
tslint.json
yarn.lock

We just set up our frontend build, now let's set up our linters along with their CI job.
Note: I'm reusing the existing `/fun` directory. Not sure this is the name we want but changing this is out of scope for this PR.

Set up frontend linters

---

front/components/RootComponent/RootComponent.tsx
front/index.tsx
package.json
yarn.lock

This is pretty straightforward, it's just neatly split into 3 commits.

Start a frontend component structure

---

marsha/core/views.py

The /lti-video view is _expected_ to be called by POST requests as it needs arguments contained in the POST body to operate.
TemplateViews on the other hand, while they are a useful shortcut, can only support GET requests.
Refactor the /lti-video view to use a generic View with just the TemplateResponseMixin so we can enable POST requests and still simply produce a templated response.
NB: disable CSRF protection as this view is only supposed to be called directly through iframes with no prior request to our Django server, and uses other security protocols specified by LTI.

🐛(video) allow POST calls on the /lti-video view

---

front/index.tsx
front/utils/styledComponentsTs.ts
front/utils/theme/baseStyles.ts
front/utils/theme/theme.ts
package.json
yarn.lock

`marsha` does not using any styling right now. It's just an SPA that produces markup.

Start styling the frontend using styled-components

---

setup.cfg

The Marsha server is run in production with gunicorn so it should be installed in the image.
Add gunicorn to the list of dependencies.

Add gunicorn to the list of dependencies

---

CHANGELOG.md
package.json
setup.cfg

Publish a new release that can be deployed/tested with Arnold.

Prepare 1.0.0-alpha.3

---

.dockerignore
Dockerfile
package.json
setup.cfg

The front-end build was missing in Marsha's production image.
Besides the missing front-end build, this PR adds:
- minor improvements to the core Dockerfile
- missing upgraded release version
- masha's back-end packaging improvement

Improve base docker image

---

CONTRIBUTORS.md
package.json
setup.cfg

Add missing front-end build in the Docker production image

🔖(patch) bump release to 1.0.0-beta.2

---

front/components/App/App.spec.tsx
front/components/App/App.tsx
front/components/AppRoutes/AppRoutes.tsx
front/components/RedirectOnLoad/RedirectOnLoad.spec.tsx
front/components/RedirectOnLoad/RedirectOnLoad.tsx
front/components/VideoForm/VideoForm.spec.tsx
front/components/VideoForm/VideoForm.tsx
front/components/withLink/withLink.tsx
front/index.tsx
front/types/AppData.ts

We initially put appData straight into a Context, which allowed us to pass it through easily to any child that needed it.
However, it came from a static value in index and could not be modified. We need to put it in a component's state to be able to change it and have the changes be reflected in our renders.
This is the role App fills.
If/when we need to support more changes than just updating the video, we'll have to consider bringing on a state management solution or building our own.
For now, we think it would add unnecessary complexity to a relatively simple app.

Use an app component to update appdata

---

src/backend/marsha/core/lti.py
src/backend/marsha/core/tests/test_lti.py

The LTI signature is computed using the url of the LTI launch request. When Marsha is placed behind a TLS termination proxy, the url as seen by Django is changed and starts with the "http" scheme instead of "https" as initiated by the consumer. We need to revert to the https url so that the signature we calculate
matches the one calculated by our LTI consumer.
This is normally done in pylti's "verify_request_common" method but it does not support WSGI normalized headers as found in Django's request.META.
Django's request.META contains a "HTTP_X_FORWARDED_PROTO" when pylti is looking for "X-Forwarded-Proto".

Fix marsha when placed behing a TLS termination proxy

---

env.d/development.dist
src/backend/marsha/settings.py

Environment variable DJANGO_CLOUDFRONT_URL is missing in newly created
env.d/development.dist file.
Add DJANGO_CLOUDFRONT_URL environment variable

🐛(project) add missing required environment variable in development.dist

---

docs/env.md
src/backend/marsha/settings.py

We're in the process of making the project more accessible to newcomers. One of the pain points we identified was that there are a lot of required environment variables in both Django & Terraform, and that they are not documented anywhere.
Thoroughly document all our environment variables in the relevant docs file.

📝(env) document available environment variables for Django & TF

---

docs/env.md
env.d/development.dist
src/aws/Makefile
src/aws/cloudfront.tf
src/aws/create_state_bucket/s3.tf
src/aws/env.d/development.dist
src/aws/output.tf
src/aws/s3.tf
src/aws/variables.tf

Fixes https://github.com/openfun/marsha/issues/123
Fixes https://github.com/openfun/marsha/issues/141
I basically followed the TODO list in the issue.
I also renamed the variable `CLOUDFRONT_ACCESS_KEY_ID` to `CLOUDFRONT_TRUSTED_SIGNER_ID` because it was confusing and lead to configuration mistakes.

Improve and document AWS configuration

---

src/backend/marsha/core/lti.py
src/backend/marsha/core/tests/test_lti.py

Our `/lti-video/` view is meant to be run as an iframe target. As an LTI endpoint, it's authenticated and, if compromise, could expose data that should be restricted to authorized users.
~We have some additional attack surface with `iframe-resizer` as `postMessage` as an API is inherently vulnerable to XSS. The library mitigates this by allowing us to whitelist domains on both sides of the iframe barrier.~
NB: Host side whitelisting is not in Marsha's scope as Marsha is supposed to be the iframe target, not the host.
Origin checks should add a layer of protection in case LTI authentication somehow proves insufficient.

Add origin checks to lti video

---

CHANGELOG.md
src/backend/setup.cfg
src/frontend/package.json

- Fix initiate upload to update only the targeted object and not the whole
database table

🔖(patch) bump release to 1.2.1

---

src/backend/marsha/core/api.py
src/backend/marsha/core/tests/test_api_update_state.py

We were setting the `uploaded_on` field to "Now" on all update-state calls regardless of the upload's state. This included READY (which is intended) but also PROCESSING and ERROR.
Those videos were then incorrectly marked as ready to play on the API.
Only set `uploaded_on` when the `update-state` call actually marks the video as READY.

Only set `uploaded_on` for uploads that were successful

---

.circleci/config.yml
Makefile
src/backend/marsha/settings.py
src/backend/setup.cfg

As mentioned in https://github.com/openfun/arnold/issues/69 we need a way to check our application's status. We choose to follow Mozilla's Dockerflow integration pattern.
*nota bene*: I also had to fix `Makefile`'s `PHONY` references

Add healthcheck

---

CHANGELOG.md
src/backend/setup.cfg
src/frontend/package.json

Added
- Improve admin views (show/search ID, configure site portability, performance,...)
- Log a warning on LTI exceptions for easier diagnostic
- Introduce Saga and use it to get timed text tracks
Fixed
- Fix logging and make it configurable by environment variables

🔖(patch) bump release to 2.2.0

---

src/frontend/components/TimedTextListItem/TimedTextListItem.spec.tsx
src/frontend/components/TimedTextListItem/TimedTextListItem.tsx
src/frontend/components/TimedTextListItemConnected/TimedTextListItemConnected.ts

In order to display a timed text track in the video player we need to
update it once it is ready to play.
fetch the timedtextrack `GET` endpoint every minute and change it in the state once it is ready to play.

✨(timedtexttrack) update track when its state changes once uploaded

---

CHANGELOG.md
src/aws/lambda-configure/package.json
src/aws/lambda-encode/package.json
src/aws/lambda-update-state/package.json
src/backend/setup.cfg
src/frontend/package.json

- Manage translations with Crowdin and build them in the CI.
- Remove HLS video support for iOS platforms.

🔖(chore) bump release to 2.5.0

---

src/backend/setup.cfg

Information in the setup configuration file are outdated.
Description...

🔧(backend) update information in setup configuration file

---

CHANGELOG.md
Makefile
bin/pytest

In development we want to be have a command running pytest in a
container and using all the arguments we want with pytest.

✨(tools) Add `bin/pytest` script

---

CHANGELOG.md
Makefile

We've updated the project's Makefile with the following statements in
mind:
1. Every variable should be defined in the ad hoc VARIABLES section with a
relevant subsection
2. Every new rule should be defined in the ad hoc RULES section with a
relevant subsection depending on the targeted service
3. Rules should be sorted alphabetically within their section
4. When a rule has multiple dependencies, you should:
- duplicate the rule name to add the help string (if required)
- write one dependency per line to increase readability and diffs
5. .PHONY rule statement should be written after the corresponding rule

🔧(project) improve Makefile readability

---

CHANGELOG.md
src/aws/lambda-complete/package.json
src/aws/lambda-configure/package.json
src/aws/lambda-encode/package.json
src/backend/setup.cfg
src/frontend/package.json

Fixed
- Allow to use newer version of django-storages
- Force to display captions on firefox.

🔖(patch) bump release to 2.8.1

---

CHANGELOG.md
src/aws/lambda-complete/package.json
src/aws/lambda-configure/package.json
src/aws/lambda-encode/package.json
src/backend/setup.cfg
src/frontend/package.json

Changed
- Configure django core settings to pass all heartbeat checks

🔖(patch) bump release to 2.8.2

---

CHANGELOG.md
src/aws/lambda-complete/package.json
src/aws/lambda-configure/package.json
src/aws/lambda-encode/package.json
src/backend/setup.cfg
src/frontend/package.json

- use secure cookie only in production.
- xapi: played segments list should not contain skipped segments (seek event)
- xapi: completed event is sent when the progression reaches 100%

🔖(patch) bump release to 2.8.3

---

CHANGELOG.md
src/aws/lambda-complete/package.json
src/aws/lambda-complete/yarn.lock
src/aws/lambda-configure/package.json
src/aws/lambda-configure/yarn.lock
src/aws/lambda-encode/package.json
src/frontend/package.json
src/frontend/yarn.lock

in the front application js-yaml has a security issue
in all AWS lambda, handlebars has a security issue

upgrade dependencies containing security issues

---

CHANGELOG.md
src/aws/lambda-complete/package.json
src/aws/lambda-configure/package.json
src/aws/lambda-encode/package.json
src/backend/setup.cfg
src/frontend/package.json

- xapi: be sure to send completed event when progress has reached 100%
- front: add a resolution for js-yaml package to avoid using a version
with a security risk
- aws: add a resolution for handlebars package to avoid using a version
with a security risk

🔖(patch) bump release to 2.8.4

---

CHANGELOG.md
src/frontend/Player/createPlyrPlayer.ts
src/frontend/XAPI/XAPIStatement.spec.ts
src/frontend/XAPI/XAPIStatement.ts
src/frontend/types/XAPI.ts

We don't want to keep a completion threshold equal to  1 because we think
that most of time a user will stop the video before its end. We found a way
to compute a completion threshold using a linear function.

compute xapi completion threshold

---

CHANGELOG.md
src/aws/lambda-complete/package.json
src/aws/lambda-configure/package.json
src/aws/lambda-encode/package.json
src/backend/setup.cfg
src/frontend/package.json

- Compute a completion threshold when xapi is initialized.
- Detect when a user leaves the page to send terminated statement.
- Avoid losing an upload by asking to the user if he really
wants to leave the page.

🔖(minor) bump release to 2.9.0

---

CHANGELOG.md
src/aws/lambda-complete/package.json
src/aws/lambda-configure/package.json
src/aws/lambda-encode/package.json
src/backend/setup.cfg
src/frontend/package.json

- Fix first thumbnail creation.
- Remove undefined values in zustand store when removing a resource.

🔖(patch) bump release to 2.10.1

---

src/frontend/Player/i18n/plyrTranslation.ts

Some descriptions where not accurate. We need top update them to be sure
what we translate.

🌐(front) update some descriptions in plyr translation 

---

src/backend/locale/es_ES/LC_MESSAGES/django.po
src/backend/locale/fr_CA/LC_MESSAGES/django.po
src/backend/locale/fr_FR/LC_MESSAGES/django.po
src/frontend/translations/es_ES.po
src/frontend/translations/fr_CA.po
src/frontend/translations/fr_FR.po

New translations have been added on crowdin, we have to integrate them
in marsha before publishing a new release.

🌐(i18n) update translations

---

CHANGELOG.md
docker/files/usr/local/etc/gunicorn/marsha.py

This is a cherry-pick of commit ab775f078506dd3bfeb398dd1972c60292c3894a in branch `hotfix-2.10.x`

✨(gunicorn) configure worker and threads

---

CHANGELOG.md
src/aws/lambda-complete/package.json
src/aws/lambda-configure/package.json
src/aws/lambda-encode/package.json
src/backend/setup.cfg
src/frontend/package.json

- Change gunicorn configuration to increase number of threads,
worker class and worker tmpdir
- Upgrade @openfun/subsrt in lambda-encode. Patched version parses
most of srt files (a critical feature for us)

🔖(patch) release version 2.10.2

---

CHANGELOG.md
Dockerfile

We want to upgrade the marsha image to python 3.7

🐳(python) upgrade to python 3.7

---

CHANGELOG.md
src/backend/marsha/core/templates/core/lti_development.html
src/frontend/babel.config.js
src/frontend/jest.config.js
src/frontend/package.json
src/frontend/webpack.config.js
src/frontend/yarn.lock

Per #557, we started work to support Internet Explorer 11.
The bare minimum is to have a working video player and document "player". Through tweaks to our build, we managed to achieve this.
We also managed to get file uploads for documents and videos to work. There are still issues with subtitle management.
This is less critical though as we can expect instructors to use a decent browsers, whereas we need to try and support students stuck on IE11.
**The most urgent problems are fixed, but not all boxes on #557 are ticked.**

Support critical features in Internet Explorer 11

---

CHANGELOG.md
src/aws/lambda-complete/package.json
src/aws/lambda-configure/package.json
src/aws/lambda-encode/package.json
src/aws/lambda-migrate/package.json
src/backend/setup.cfg
src/frontend/package.json

- Support critical features (video & document playback) in IE 11.
- Introduce a new setting AWS_BASE_NAME to prefix all AWS settings in the project.
- Use sentry to track errors in the front application.
- New lambda responsible to migrate migrations on AWS.
- Using HTML entities in timed text tracks is allowed. Every tag used
will be escaped and rendered in the web page without being executed.
- Use node 10 engine to run AWS lambdas.

🔖(minor) bump release to 3.1.0

---

CHANGELOG.md
src/aws/lambda-complete/package.json
src/aws/lambda-configure/package.json
src/aws/lambda-encode/package.json
src/aws/lambda-migrate/package.json
src/backend/setup.cfg
src/frontend/package.json

- Fix errors in lambda-migrate function. The timed text tracks migrations can
lead to an infinite loop.

🔖(patch) bump release to 3.1.1

---

CHANGELOG.md
src/aws/lambda-complete/package.json
src/aws/lambda-configure/package.json
src/aws/lambda-encode/package.json
src/aws/lambda-migrate/package.json
src/backend/setup.cfg
src/frontend/package.json

- Polyfill Intl API for browsers not supporting this API.
- Fix video event tracking in Internet Explorer 11.

🔖(patch) bump release to 3.1.2

---

README.md

We want to apply yo the browserstack open-source program. We have first
to edit our readme to add their logo. We also add a little bit more
information about how to run react tests.

📝(Readme) add information about testing front application

---

CHANGELOG.md
src/aws/lambda-complete/package.json
src/aws/lambda-configure/package.json
src/aws/lambda-encode/package.json
src/aws/lambda-migrate/package.json
src/backend/setup.cfg
src/frontend/package.json

- Fetch a resource based on the uploaded_on field and not on its upload_state

🔖(patch) bump release to 3.1.4

---

README.md

Since version 3 we can manage documents with marsha but this information
does not appear in the Readme. We must update it to inform about this
new feature.
Description...

📝(README) add information about document management

---

CHANGELOG.md
src/backend/marsha/core/api.py
src/backend/marsha/core/defaults.py
src/backend/marsha/core/utils/s3_utils.py
src/backend/marsha/settings.py

Some defaults settings where declared in the defaults module and looking
in settings if it was declared to fallback then on a default value. This
don't allow us to change these settings with an environment variable and
moreover fallbacking on default value can also be done in settings
module. We decided to move them in the settings module.

♻️(backend) move defaults settings to settings file

---

CHANGELOG.md
src/aws/lambda-complete/package.json
src/aws/lambda-configure/package.json
src/aws/lambda-encode/package.json
src/aws/lambda-migrate/package.json
src/backend/setup.cfg
src/frontend/package.json

- move defaults settings to settings file

🔖(patch) bump release to 3.1.6

---

CHANGELOG.md
src/aws/lambda-complete/package.json
src/aws/lambda-configure/package.json
src/aws/lambda-encode/package.json
src/aws/lambda-migrate/package.json
src/backend/setup.cfg
src/frontend/package.json

- Load third party js script using EXTERNAL_JAVASCRIPT_SCRIPTS setting

🔖(minor) bump release 3.2.0

---

CHANGELOG.md
src/aws/lambda-complete/package.json
src/aws/lambda-configure/package.json
src/aws/lambda-encode/package.json
src/aws/lambda-migrate/package.json
src/backend/setup.cfg
src/frontend/package.json

I know we have some users waiting for the aspect ratio fix, hence the patch release.
- Videos uploaded in other formats than 16/9 were distorted to fit that ratio. We now do our best to respect their format during encoding and also in the player.

🔖(patch) bump release to 3.2.1

---

CHANGELOG.md
src/aws/lambda-complete/package.json
src/aws/lambda-configure/package.json
src/aws/lambda-encode/package.json
src/aws/lambda-migrate/package.json
src/backend/setup.cfg
src/frontend/package.json

- Upgrade to Django 3
- Upgrade to python 3.8
- Set SECURE_REFERRER_POLICY setting to same-origin
- Force thumbnail to be displayed while the video is not played

🔖(minor) bump release to 3.4.0

---

CHANGELOG.md
src/aws/lambda-complete/package.json
src/aws/lambda-configure/package.json
src/aws/lambda-encode/package.json
src/aws/lambda-migrate/package.json
src/backend/setup.cfg
src/frontend/package.json

Added
- Allow to change video quality while using ABR

🔖(minor) bump release to 3.5.0

---

CHANGELOG.md
src/aws/lambda-complete/package.json
src/aws/lambda-configure/package.json
src/aws/lambda-encode/package.json
src/aws/lambda-migrate/package.json
src/backend/setup.cfg
src/frontend/package.json

- update @openfun/subsrt to 1.0.4 to get a bug fix.

🔖(patch) bump release to 3.5.1

---

CHANGELOG.md
src/aws/lambda-complete/package.json
src/aws/lambda-configure/package.json
src/aws/lambda-encode/package.json
src/aws/lambda-migrate/package.json
src/backend/setup.cfg
src/frontend/package.json

- Allow defining playlist portability to a precise list of other playlists

🔖(minor) bump release to 3.6.0

---

CHANGELOG.md
src/aws/lambda-complete/package.json
src/aws/lambda-configure/package.json
src/aws/lambda-encode/package.json
src/aws/lambda-migrate/package.json
src/backend/setup.cfg
src/frontend/package.json

- Use subtitles as transcript when no transcript has been uploaded
- Register xapi statements in a logger

🔖(minor) bump release to 3.7.0

---

CHANGELOG.md
src/aws/lambda-complete/package.json
src/aws/lambda-configure/package.json
src/aws/lambda-encode/package.json
src/aws/lambda-migrate/package.json
src/backend/setup.cfg
src/frontend/package.json

- Video title in xapi statement
- Replace `random` with `secrets` to generate random strings
- Remove `assert` statements and prepare codebase for activation of `bandit`
linter

🔖(minor) bump release to 3.8.0

---

CHANGELOG.md
src/aws/lambda-complete/package.json
src/aws/lambda-configure/package.json
src/aws/lambda-encode/package.json
src/aws/lambda-migrate/package.json
src/backend/setup.cfg
src/frontend/package.json

Fixed
- Move video title in object.definition property in xapi statement

🔖(patch) bump release to 3.8.1

---

CHANGELOG.md
src/aws/lambda-complete/package.json
src/aws/lambda-configure/package.json
src/aws/lambda-encode/package.json
src/aws/lambda-migrate/package.json
src/aws/utils/update-state/package.json
src/backend/setup.cfg
src/frontend/package.json

- Detect original video framerate and use it in lambda encode
- Limit video encoding resolution to that of the source

🔖(minor) bump release to 3.9.0

---

src/frontend/components/Dashboard/index.spec.tsx
src/frontend/components/DashboardDocument/index.spec.tsx
src/frontend/components/DashboardDocumentTitleForm/index.spec.tsx
src/frontend/components/DashboardThumbnail/index.spec.tsx
src/frontend/components/DashboardTimedTextManager/index.spec.tsx
src/frontend/components/DashboardTimedTextPane/index.spec.tsx
src/frontend/components/DashboardVideoPane/index.spec.tsx
src/frontend/components/DashboardVideoPaneDownloadOption/index.spec.tsx
src/frontend/components/DashboardVideoPaneTranscriptOption/index.spec.tsx
src/frontend/components/TimedTextCreationForm/index.spec.tsx
src/frontend/components/TimedTextListItem/index.spec.tsx
src/frontend/components/TranscriptReader/index.spec.tsx
src/frontend/components/Transcripts/index.spec.tsx
src/frontend/components/UploadField/index.spec.tsx
src/frontend/components/UploadForm/index.spec.tsx
src/frontend/components/VideoPlayer/index.spec.tsx
src/frontend/data/sideEffects/createThumbnail/index.spec.ts
src/frontend/data/sideEffects/createTimedTextTrack/index.spec.ts
src/frontend/data/sideEffects/deleteTimedTextTrack/index.spec.ts
src/frontend/data/sideEffects/getResourceList/index.spec.tsx
src/frontend/data/sideEffects/initiateUpload/index.spec.ts
src/frontend/data/sideEffects/pollForTrack/index.spec.tsx
src/frontend/data/sideEffects/updateResource/index.spec.ts
src/frontend/data/sideEffects/upload/index.spec.ts
src/frontend/data/stores/useTimedTextTrackLanguageChoices/index.spec.tsx
src/frontend/package.json
src/frontend/utils/tests/Deferred.ts
src/frontend/yarn.lock

Testing libraries have lot of deprecations warning, this PR remove all
of them.

🚨(front) remove tests deprecation warning

---

CHANGELOG.md
src/aws/lambda-complete/package.json
src/aws/lambda-configure/package.json
src/aws/lambda-encode/package.json
src/aws/lambda-migrate/package.json
src/aws/utils/update-state/package.json
src/backend/setup.cfg
src/frontend/package.json

- Synchronize scroll with active transcript sentence
- Sideload Playlist in Video and Document resources
- Use `UploadableFileMixin` on `AbstractImage` model
- Fix dashboard read versus update permissions in situations
of playlist portability

🔖(minor) bump release to 3.10.0

---

CHANGELOG.md
src/aws/lambda-complete/package.json
src/aws/lambda-configure/package.json
src/aws/lambda-encode/package.json
src/aws/lambda-migrate/package.json
src/aws/utils/update-state/package.json
src/backend/setup.cfg
src/frontend/package.json

Fixed
- Remove usage of scrollIntoView to synchronize active transcript sentence

🔖(patch) bump release to 3.10.2

---

src/aws/Makefile

Sometime we just want to apply terraform plan without creating all
lambda zip because they didn't change and we already have the zip on our
disk. With this task it will be faster to apply terraform plan.

✨(aws) add an apply task to makefile

---

.circleci/config.yml
CHANGELOG.md
Dockerfile

We want to upgrade our image to python 3.9 and use this version in
production.

🐳(python) upgrade to python 3.9

---

CHANGELOG.md
src/aws/cloudfront.tf
src/backend/marsha/core/serializers.py
src/backend/marsha/core/tests/test_api_timed_text_track.py
src/backend/marsha/core/tests/test_api_video.py
src/backend/marsha/core/tests/test_views_lti_video.py
src/frontend/components/TimedTextListItem/index.tsx

In the dashboard we want to be able to download timed text track already uploaded.

✨(timed text track) allow to download them in dashboard panel

---

src/backend/locale/es_ES/LC_MESSAGES/django.po
src/backend/locale/fr_CA/LC_MESSAGES/django.po
src/backend/locale/fr_FR/LC_MESSAGES/django.po
src/frontend/i18n/es_ES.json
src/frontend/i18n/fr_CA.json
src/frontend/i18n/fr_FR.json

Translations about live feature are not up to date. We want to update
them

🌐(all) update translations

---

CHANGELOG.md
src/aws/lambda-complete/package.json
src/aws/lambda-configure/package.json
src/aws/lambda-encode/package.json
src/aws/lambda-medialive-routing/package.json
src/aws/lambda-medialive/package.json
src/aws/lambda-migrate/package.json
src/aws/utils/update-state/package.json
src/backend/setup.cfg
src/frontend/package.json

- Choose video player with the setting VIDEO_PLAYER
- New player videojs as an alternative to plyr
- Add a fleature flag to control video live streams activation

🔖(minor) bump release to 3.13.0

---

CHANGELOG.md
src/aws/lambda-complete/package.json
src/aws/lambda-configure/package.json
src/aws/lambda-encode/package.json
src/aws/lambda-medialive-routing/package.json
src/aws/lambda-medialive/package.json
src/aws/lambda-migrate/package.json
src/backend/setup.cfg
src/frontend/package.json

- Enable videojs override native feature except on safari

🔖(patch) bump release to 3.13.1

---

src/backend/marsha/core/utils/medialive_profiles/medialive-720p.json

We want to have similar HLS profiles between live and VOD feature in
order to ease the process to transmux a live video to a VOD.

✨(live) homogenize hls profiles between live and VOD

---

CHANGELOG.md
src/aws/lambda-complete/package.json
src/aws/lambda-configure/package.json
src/aws/lambda-encode/package.json
src/aws/lambda-medialive-routing/package.json
src/aws/lambda-medialive/package.json
src/aws/lambda-migrate/package.json
src/aws/utils/update-state/package.json
src/backend/setup.cfg
src/frontend/package.json

- Create a videojs plugin to manage MP4 selection
- Enable videojs useDevicePixelRatio VHS option

🔖(minor) bump release to 3.16.0

---

CHANGELOG.md
src/aws/lambda-complete/package.json
src/aws/lambda-configure/package.json
src/aws/lambda-encode/package.json
src/aws/lambda-medialive-routing/package.json
src/aws/lambda-medialive/package.json
src/aws/lambda-migrate/package.json
src/aws/utils/update-state/package.json
src/backend/setup.cfg
src/frontend/package.json

- Disable native audio and video tracks in Videojs conf
- Remove HLS source in `<VideoPlayer />`

🔖(patch) bump release to 3.16.1

---

src/backend/locale/es_ES/LC_MESSAGES/django.po
src/backend/locale/fr_CA/LC_MESSAGES/django.po
src/backend/locale/fr_FR/LC_MESSAGES/django.po
src/frontend/i18n/es_ES.json
src/frontend/i18n/fr_CA.json
src/frontend/i18n/fr_FR.json

Update i18n with live feature.

🌐(app) update i18n files

---

src/aws/bin/terraform

In the terraform script, the environment file is hardcoded. We want to
be able to use another file (staging, production) by using an
environment variable.

♻️(aws) variabilize terraform env file in terraform script

---

src/aws/Makefile

We want a makefile task to destroy all resources created by terraform.
3 tasks are created to destroy the main terraform, the shared-resources
or both.

🔧(aws) add makefile tasks to destroy all resources

---

Makefile

In the makefile, variables `PROJECT_NAME` and `PROJECT_VERSION` are set
but never used.

🔥(makefile) remove unused variables

---

CHANGELOG.md
docs/env.md
src/backend/marsha/core/tests/test_utils_medialive_utils.py
src/backend/marsha/core/utils/medialive_utils.py
src/backend/marsha/settings.py

We want easily change live configuration related to latency. To do that
we created new settings allowing to change segment duration and playlist
window. But also conf related to FPS.

♻️(back) variabilize live conf related to latency

---

.circleci/config.yml
CHANGELOG.md
Dockerfile
docker-compose.yml

The version of node used in the docker-compose stack and circleci is
outdated. We upgrade it to the current LTS, the version 14.

⬆️(core) upgrade node to version 14

---

src/aws/lambda-elemental-routing/yarn.lock
src/aws/lambda-medialive/yarn.lock
src/aws/lambda-mediapackage/yarn.lock
src/aws/utils/update-state/yarn.lock

Secrity update in lambda functions

---

renovate.json

Renovate configuration has changed and some keys have been renamed. We
must update them

🔧(renovate) update renovate configuration

---

src/frontend/data/queries/fetchList.spec.tsx
src/frontend/data/queries/fetchOne.spec.tsx
src/frontend/data/queries/index.spec.tsx
src/frontend/data/queries/index.tsx
src/frontend/data/queries/updateOne.spec.tsx
src/frontend/data/queries/updateOne.tsx

As playlist portability is feature is pending, we need a way to update playlists through react-query.
Add updateOne query, along with useUpdatePlaylist.

✨(frontend) add updateOne query and useUpdatePlaylist

---

CHANGELOG.md
src/frontend/components/DashboardVideoLiveJitsi/index.spec.tsx
src/frontend/components/DashboardVideoLiveJitsi/index.tsx

We want to allow to share a youtube video with jitsi.

🔧(front) allow to share a youtube video with jitsi

---

src/frontend/components/DashboardVideoLiveJitsi/index.tsx

When jitsi recoirding status change to failing, we try to restart the
connection. For now it was every seconds. We decided to start at 2
seconds and increment to 2 seconds after every retry and don't increment
the delay other 20 seconds.
Description...

♻️(front) incrementally retry to start jitsi recording

---

src/backend/marsha/core/models/video.py
src/frontend/components/ErrorComponents/index.tsx

This commit fix Some translation keys that were wrong or inaccurate

🌐(i18n) fix translation keys

---

CHANGELOG.md
src/aws/lambda-complete/package.json
src/aws/lambda-configure/package.json
src/aws/lambda-elemental-routing/package.json
src/aws/lambda-encode/package.json
src/aws/lambda-medialive/package.json
src/aws/lambda-mediapackage/package.json
src/aws/lambda-migrate/package.json
src/aws/utils/update-state/package.json
src/backend/setup.cfg
src/frontend/package.json

- Redirect instructor to the dashboard when live is stopped

🔖(patch) bump release to 3.20.1

---

CHANGELOG.md
src/aws/lambda-complete/package.json
src/aws/lambda-configure/package.json
src/aws/lambda-elemental-routing/package.json
src/aws/lambda-encode/package.json
src/aws/lambda-medialive/package.json
src/aws/lambda-mediapackage/package.json
src/aws/lambda-migrate/package.json
src/aws/utils/update-state/package.json
src/backend/setup.cfg
src/frontend/package.json

- Add a beta label on live configuration buttons
- VIDEO_LIVE Waffle switch

🔖(minor) bump release to 3.21.0

---

CHANGELOG.md
src/backend/marsha/core/api.py
src/backend/marsha/core/storage/dummy.py
src/backend/marsha/core/storage/s3.py
src/backend/marsha/development/api.py
src/backend/marsha/e2e/test_lti.py
src/backend/marsha/urls.py
src/frontend/components/Dashboard/index.spec.tsx
src/frontend/components/Dashboard/index.tsx
src/frontend/components/InstructorView/index.spec.tsx
src/frontend/components/InstructorView/index.tsx
src/frontend/components/LTINav/index.spec.tsx
src/frontend/components/LTINav/index.tsx

Adds a navigation to LTI views between dashboard and resource preview.
A configurable navigation bar has been added to instructor and dashboard view.

🎨(frontend) add navigation to LTI views

---

src/frontend/index.tsx

In the index an unwanted comma was introduced and was not detected
during the pull request review. The comma is displayed and must be
removed.

🩹(front) clean index rendering

---

docker/files/etc/prosody/prosody.cfg.lua
src/frontend/components/JoinDiscussionAskButton/index.spec.tsx
src/frontend/components/JoinDiscussionAskButton/index.tsx
src/frontend/data/stores/useParticipantWorkflow/index.ts
src/frontend/tsconfig.json
src/frontend/types/libs/converse/index.d.ts
src/frontend/types/libs/window.d.ts
src/frontend/utils/converse.spec.ts
src/frontend/utils/converse.ts

A user can ask to join the discussion while he is not connected to the
chat. We must connect it first and ensure the username is not already
used.

Connect user to chat before asking to join the discussion

---

CHANGELOG.md
src/backend/locale/es_ES/LC_MESSAGES/django.po
src/backend/locale/fr_CA/LC_MESSAGES/django.po
src/backend/locale/fr_FR/LC_MESSAGES/django.po
src/frontend/components/PlaylistPortability/index.tsx
src/frontend/i18n/es_ES.json
src/frontend/i18n/fr_CA.json
src/frontend/i18n/fr_FR.json

Add missing translations for version 3.24.0

🌐(i18n) update missing translations

---

CHANGELOG.md
src/aws/lambda-complete/package.json
src/aws/lambda-configure/package.json
src/aws/lambda-elemental-routing/package.json
src/aws/lambda-encode/package.json
src/aws/lambda-medialive/package.json
src/aws/lambda-mediapackage/package.json
src/aws/utils/update-state/package.json
src/backend/setup.cfg
src/frontend/package.json

🔖(patch) bump release to 3.24.1

---

.circleci/config.yml
CHANGELOG.md
Dockerfile

We want to upgrade our image to python 3.10 and use this version in
production.

🔧(docker) upgrade to python 3.10

---

src/backend/marsha/core/tests/test_utils_medialive_utils.py

The test test_create_mediapackage_harvest_job was incomplete, function call and assertion were missing.

✅(backend) fix create_mediapackage_harvest_job test

---

CHANGELOG.md
src/frontend/components/Chat/SharedChatComponents/InputDisplayNameOverlay/index.spec.tsx
src/frontend/components/Chat/SharedChatComponents/InputDisplayNameOverlay/index.tsx
src/frontend/default/chat.ts
src/frontend/utils/chat/chat.spec.ts
src/frontend/utils/chat/chat.ts

Add a file to store configurable constants, used to set differents parameters
of the chat.
A `default/chat.ts` at the root of the front project, containing default constant variables.

Add default config for the chat

---

src/aws/lambda-mediapackage/package.json
src/aws/lambda-mediapackage/yarn.lock
src/frontend/package.json
src/frontend/yarn.lock
src/mail/yarn.lock

Upgrade node-fetch and nanoid

---

CHANGELOG.md
src/backend/marsha/core/api/live_registration.py
src/backend/marsha/core/tests/test_api_liveregistration.py
src/backend/marsha/settings.py
src/mail/mjml/sample.mjml

We want to inform by email the user that has just registered.
Send email after registering
NB: 
basic  template mail sent

✨(email) mail sent when registering to a scheduled webinar

---

src/frontend/components/PublicPausedLiveVideo/index.spec.tsx
src/frontend/components/PublicPausedLiveVideo/index.tsx
src/frontend/components/PublicVideoDashboard/index.spec.tsx
src/frontend/components/StudentLiveAdvertising/StudentLiveRegistration/RegistrationForm/index.spec.tsx
src/frontend/components/StudentLiveWrapper/index.spec.tsx
src/frontend/components/VideoPlayer/index.tsx

Pause component mounts a layer to display the alert for the student.
But there is an issue on mobile display since the layer may be rendered above
the panel containing the chat or the viewer list.
We rather use a stack to render the pause alert in front of the player.

♻️(frontend) no longer use a layer to present live pause alert

---

src/aws/Dockerfile

With poppler build from source, lambda image size has increased.
Fixes #1344 
This is an attempt to reduce it by merging the layers and removing caches.

⚡(lambda) reduce lambda image size

---

CHANGELOG.md
src/frontend/apps/bbb/DashboardMeeting/index.spec.tsx
src/frontend/apps/bbb/DashboardMeetingStudent/index.spec.tsx
src/frontend/apps/bbb/DashboardMeetingStudent/index.tsx

We have many issues with automatic join to meetings, due to browsers popup management.
Remove automatic meeting joining, and replace it with a button.

🐛(frontend) join BBB meeting through a button click

---

src/backend/setup.cfg

A click update broke black.
https://github.com/psf/black/issues/2964

⬆️(backend) update black

---

src/frontend/components/DashboardVideoLive/index.tsx
src/frontend/components/StudentLiveControlBar/index.tsx
src/frontend/components/StudentLiveInfoBar/index.tsx
src/frontend/components/TeacherLiveInfoBar/index.tsx
src/frontend/components/TeacherLiveLifecycleControls/PauseLiveButton/index.tsx
src/frontend/components/TeacherLiveLifecycleControls/ResumeLiveButton/index.tsx
src/frontend/components/TeacherLiveLifecycleControls/StartLiveButton/index.tsx
src/frontend/components/TeacherLiveLifecycleControls/StopLiveButton/index.tsx
src/frontend/components/TeacherLiveLifecycleControls/index.tsx

With large live title, actions for teacher could not be reach.

Fix teacher live layout bar info

---

src/frontend/components/ActionLink/ActionLink.stories.tsx
src/frontend/components/ActionLink/ActionLink.tsx
src/frontend/components/Chat/SharedChatComponents/ChatMessage/index.tsx
src/frontend/components/Chat/SharedChatComponents/ChatMessageMetadatas/index.tsx
src/frontend/components/LiveVideoPanel/LiveVideoTabPanel/index.tsx
src/frontend/components/LiveVideoPanel/index.tsx
src/frontend/components/StudentLiveAdvertising/StudentLiveRegistration/RegistrationForm/index.tsx
src/frontend/index.tsx
src/frontend/utils/theme/theme.ts

Grommet theme type has been added after we build our own.
Typing our theme help us to customize it by seeing which options are
available for each component.

🎨(frontend) add type to our grommet theme

---

src/aws/lambda-convert/package.json
src/aws/lambda-convert/yarn.lock

https://github.com/openfun/subsrt/releases/tag/v1.0.5

⬆️(aws) upgrade @openfun/subsrt to version 1.0.5

---

src/mail/mjml/partial/footer.mjml
src/mail/mjml/partial/video_access_url.mjml

Mjml file conversion is capricious and sentences
needs to be on the same line to be well formed
in the html files.
reformat MJML files

♻️(emails) format mjml file

---

src/frontend/apps/bbb/DashboardMeetingStudent/index.tsx
src/mail/mjml/reminder.mjml

Quick fix for translations that are preferred.
minor change

🌐(i18n) change translations

---

.circleci/config.yml
CHANGELOG.md
src/backend/marsha/core/tests/test_views_reminders_cancel.py
src/backend/marsha/settings.py

In order to access translations from backend, the path of the
files containing the translations need to be defined.
Add path and a test to confirm translations are loaded

🐛(i18n) back translations

---

.circleci/config.yml
src/frontend/components/DashboardVideoLiveControlPane/widgets/DashboardVideoLiveWidgetsContainer/index.spec.tsx
src/frontend/components/StudentLiveWrapper/index.spec.tsx

Some warning were raised by jest in our tests suite. This commit fix
them all, there is no more error in our tests.

✅(front) fix jest warning in tests

---

CHANGELOG.md
src/frontend/components/DashboardVideoLiveControlPane/index.spec.tsx
src/frontend/components/DashboardVideoLiveControlPane/index.tsx
src/frontend/components/DashboardVideoLiveControlPane/inputs/DashboardVideoLiveWidgetTextAreaInput/index.spec.tsx
src/frontend/components/DashboardVideoLiveControlPane/inputs/DashboardVideoLiveWidgetTextAreaInput/index.tsx
src/frontend/components/DashboardVideoLiveControlPane/widgets/DashboardVideoLiveWidgetSchedulingAndDescription/index.spec.tsx
src/frontend/components/DashboardVideoLiveControlPane/widgets/DashboardVideoLiveWidgetSchedulingAndDescription/index.tsx
src/frontend/components/SchedulingFields/index.tsx

Add a new widget capable of scheduling the live and updating the video's description.

Add a widget for scheduling a live and modifying its description

---

CHANGELOG.md
src/frontend/components/DashboardVideoLive/index.spec.tsx
src/frontend/components/DashboardVideoLive/index.tsx
src/frontend/components/DashboardVideoLiveControlPane/index.spec.tsx
src/frontend/components/DashboardVideoLiveControlPane/index.tsx
src/frontend/components/DashboardVideoLiveControlPane/widgets/DashboardVideoLiveWidgetToolsAndApplications/index.spec.tsx
src/frontend/components/DashboardVideoLiveControlPane/widgets/DashboardVideoLiveWidgetToolsAndApplications/index.tsx
src/frontend/components/PublicVideoDashboard/index.tsx
src/frontend/components/StudentLiveWrapper/index.spec.tsx
src/frontend/components/StudentLiveWrapper/index.tsx
src/frontend/types/tracks.ts
src/frontend/utils/tests/factories.ts

This PR adds a widget on the Instructor view. This widget allows instructor to hide / unhide the chat tab, for him but also for its students.

✨(front) control chat visibility depending on video.has_chat

---

.circleci/config.yml
docker/images/e2e/Dockerfile
src/backend/marsha/e2e/test_lti.py

Playwright image has changed once again…
`pip` and `python` commands have disappeared

Fix ci e2e

---

CHANGELOG.md
src/frontend/Player/createVideojsPlayer.spec.tsx
src/frontend/Player/createVideojsPlayer.ts
src/frontend/data/sideEffects/getLiveSessions/index.spec.ts
src/frontend/data/sideEffects/getLiveSessions/index.ts
src/frontend/default/sideEffects.ts

When a webinar is watched by a student, we want to record his
assiduity to show a live report of attendance. When did the
student start to watch the live? Is the sound on and volume
audible? Does he want to pause the live?... Any information
that will help the instructor to adapt his live and give him
clues to feel more in a real class.
- push attendance for live and students

✨(front) push video live attendance

---

src/backend/locale/es_ES/LC_MESSAGES/django.po
src/backend/locale/fr_CA/LC_MESSAGES/django.po
src/backend/locale/fr_FR/LC_MESSAGES/django.po
src/frontend/i18n/es_ES.json
src/frontend/i18n/fr_CA.json
src/frontend/i18n/fr_FR.json

In order to create version 4.0.0-beta.4 we want to update the french
translations.

🌐(i18n) update french translations

---

CHANGELOG.md
src/frontend/components/StudentLiveWrapper/index.spec.tsx
src/frontend/components/StudentLiveWrapper/index.tsx

When a student goes on stage and leaves the video player
we want to record in the attendances that he is on stage.
log attendance when a user goes on stage

✨(front) push attendance when student is on stage

---

src/backend/pylintrc

Pylint 2.4 removed many rules, showing them as warning.
Also, there is an attempt to reduce his execution time.

Update pylint config

---

CHANGELOG.md
docs/env.md
src/backend/marsha/core/api/video.py
src/backend/marsha/core/stats.py
src/backend/marsha/core/tests/test_api_video_stats.py
src/backend/marsha/core/tests/test_stats.py
src/backend/marsha/settings.py
src/frontend/components/Dashboard/DashboardVideoWrapper/index.spec.tsx
src/frontend/components/DashboardVideoPane/index.spec.tsx
src/frontend/components/DashboardVideoPane/index.tsx
src/frontend/components/DashboardVideoPaneStats/index.spec.tsx
src/frontend/components/DashboardVideoPaneStats/index.tsx
src/frontend/data/queries/fetchOne.spec.tsx
src/frontend/data/queries/fetchOne.tsx
src/frontend/data/queries/index.spec.tsx
src/frontend/data/queries/index.tsx
src/frontend/types/tracks.ts

Display video statistics from potsie

Potsie stat

---

CHANGELOG.md
src/frontend/components/StudentLiveWrapper/UpdateCurrentSharedLiveMediaPage/index.spec.tsx
src/frontend/components/StudentLiveWrapper/UpdateCurrentSharedLiveMediaPage/index.tsx
src/frontend/components/StudentLiveWrapper/index.spec.tsx
src/frontend/components/StudentLiveWrapper/index.tsx

I had troubles with opening / closing PR, the orignal one is here : https://github.com/openfun/marsha/pull/1572#issue-1262585851

Share document with picture in picture (student side) 

---

src/frontend/utils/conversejs/converse-plugins/chatPlugin.ts

- Removal of intempestive report messages when a stanza is unrecognized

Manage chat exceptions and some minor errors

---

Makefile
src/backend/marsha/core/models/base.py
src/backend/marsha/core/templates/core/lti_development.html
src/frontend/data/websocket.spec.ts

Small improvements:
- When the app ran for a long time, the logs can be pretty longs, so when we display them through `make logs` they are all displayed, which can take real long time.
- When we select an existing resource in the developer view, the context_id is not filled in the testing forms.
- When we select a resource in the developer view, details are displayed.
- A frontend test fails often because of a timeout.

Small improvements

---

src/frontend/components/DashboardVideoLive/index.tsx
src/frontend/components/DashboardVideoLiveJitsi/utils.spec.ts
src/frontend/components/DashboardVideoLiveJitsi/utils.ts

We want to allow the instructors to share a video.
Add share video option to jitsi configuration only for instructors

✨(frontend) add jitsi sharevideo button for instructors

---

CHANGELOG.md

In commit d09b549c68d5bb759d2d1e2b110292962c30e862 we forget to change
the entry to the unreleased section.

📝(core) fix changelog section

---

CHANGELOG.md
src/frontend/components/DashboardVideoLiveJitsi/index.tsx
src/frontend/components/ViewersList/index.spec.tsx
src/frontend/components/ViewersList/index.tsx
src/frontend/components/ViewersList/utils.spec.ts
src/frontend/components/ViewersList/utils.ts

Display only number of anonymously connected persons, instead of their pseudo

---

CHANGELOG.md
src/frontend/components/StudentLiveAdvertising/index.spec.tsx
src/frontend/components/StudentLiveAdvertising/index.tsx
src/frontend/package.json
src/frontend/yarn.lock

When a webinar is scheduled, we want to add a link on
the student advertising page to generate an
ICS file and download it.
- add a link on the student advertising page

✨(front) generate an ics file on the scheduled page

---

src/frontend/apps/bbb/DashboardClassroom/index.tsx
src/frontend/components/Chat/InputBar/index.tsx
src/frontend/components/Chat/JoinChatButton/index.tsx
src/frontend/components/DashboardVideoLiveControlPane/customs/DashboardVideoLiveInfoModal/index.tsx
src/frontend/components/DashboardVideoLiveControlPane/inputs/DashboardVideoLiveWidgetTextAreaInput/index.tsx
src/frontend/components/DashboardVideoLiveControlPane/inputs/DashboardVideoLiveWidgetTextInput/index.tsx
src/frontend/components/DashboardVideoLiveControlPane/widgets/DashboardVideoLiveWidgetSchedulingAndDescription/index.tsx
src/frontend/components/StudentLiveAdvertising/index.tsx

The font Roboto-Regular is set as the default one on this project, so there is
no need to re-set it deeper in the component hierarchy.

♻️(front) remove use of Roboto-Regular

---

CHANGELOG.md
src/frontend/Player/createPlayer.ts
src/frontend/components/InstructorDashboardVOD/custom/TimedTrackModalWrapper/index.spec.tsx
src/frontend/components/InstructorDashboardVOD/custom/TimedTrackModalWrapper/index.tsx
src/frontend/components/InstructorDashboardVOD/index.spec.tsx
src/frontend/components/InstructorDashboardVOD/index.tsx
src/frontend/components/InstructorDashboardVOD/widgets/InstructorDashboardVODWidgetUploadClosedCaptions/index.spec.tsx
src/frontend/components/InstructorDashboardVOD/widgets/InstructorDashboardVODWidgetUploadClosedCaptions/index.tsx
src/frontend/components/InstructorDashboardVOD/widgets/InstructorDashboardVODWidgetUploadSubtitles/index.spec.tsx
src/frontend/components/InstructorDashboardVOD/widgets/InstructorDashboardVODWidgetUploadSubtitles/index.tsx
src/frontend/components/InstructorDashboardVOD/widgets/InstructorDashboardVODWidgetUploadTranscripts/index.spec.tsx
src/frontend/components/InstructorDashboardVOD/widgets/InstructorDashboardVODWidgetUploadTranscripts/index.tsx
src/frontend/components/InstructorDashboardVOD/widgets/UploadWidgetGeneric/LanguageSelect/index.spec.tsx
src/frontend/components/InstructorDashboardVOD/widgets/UploadWidgetGeneric/LanguageSelect/index.tsx
src/frontend/components/InstructorDashboardVOD/widgets/UploadWidgetGeneric/TimedTextTrackItem/DeleteTimedTextTrackItemUploadButton/index.spec.tsx
src/frontend/components/InstructorDashboardVOD/widgets/UploadWidgetGeneric/TimedTextTrackItem/DeleteTimedTextTrackItemUploadButton/index.tsx
src/frontend/components/InstructorDashboardVOD/widgets/UploadWidgetGeneric/TimedTextTrackItem/index.spec.tsx
src/frontend/components/InstructorDashboardVOD/widgets/UploadWidgetGeneric/TimedTextTrackItem/index.tsx
src/frontend/components/InstructorDashboardVOD/widgets/UploadWidgetGeneric/index.spec.tsx
src/frontend/components/InstructorDashboardVOD/widgets/UploadWidgetGeneric/index.tsx
src/frontend/components/PublicVideoDashboard/index.spec.tsx
src/frontend/components/StudentLiveWrapper/index.spec.tsx
src/frontend/components/VideoPlayer/index.spec.tsx
src/frontend/components/VideoPlayer/index.tsx
src/frontend/data/queries/index.spec.tsx
src/frontend/data/queries/index.tsx
src/frontend/data/stores/useDeleteTimedTextTrackUploadModal/index.ts
src/frontend/data/stores/useTimedTextTrack/index.tsx
src/frontend/data/stores/useTimedTextTrackLanguageChoices/index.tsx
src/frontend/types/VideoPlayer.ts

Add 3 new widgets to upload and add timed text tracks (subtitles, closed captions and transcripts) to the video.

Add timed text tracks widgets

---

docs/dev.md
src/backend/marsha/.cookiecutter/hooks/post_gen_project.sh
src/backend/marsha/.cookiecutter/{{cookiecutter.app_name}}/api.py

Make documentation slightly more explicit and update the API template to fix a behavior which seems incorrect.

(backend) Improve cookiecutter documentation and template

---

.circleci/config.yml
CHANGELOG.md
src/aws/Dockerfile
src/aws/lambda-complete/package.json
src/aws/lambda-configure/package.json
src/aws/lambda-convert/package.json
src/aws/lambda-elemental-routing/package.json
src/aws/lambda-medialive/package.json
src/aws/lambda-mediapackage/package.json
src/aws/lambda-migrate/package.json
src/aws/utils/update-state/package.json

As aws-lambda-nodejs:16 is available, we want to use it.

📌(aws) update lambdas to nodejs 16

---

CHANGELOG.md
src/.prettierignore
src/frontend/components/DashboardLive/index.spec.tsx
src/frontend/components/DashboardLive/index.tsx
src/frontend/components/LiveInfoBar/index.spec.tsx
src/frontend/components/LiveInfoBar/index.tsx
src/frontend/components/LiveVideoPanel/index.spec.tsx
src/frontend/components/StudentLiveInfoBar/index.spec.tsx
src/frontend/components/StudentLiveInfoBar/index.tsx
src/frontend/components/StudentLiveWrapper/index.spec.tsx
src/frontend/components/StudentLiveWrapper/index.tsx
src/frontend/components/TeacherLiveInfoBar/index.spec.tsx
src/frontend/components/TeacherLiveInfoBar/index.tsx
src/frontend/components/ViewersList/index.spec.tsx
src/frontend/components/ViewersList/index.tsx

- Display the number of participants connected in the viewer panel by status.
- Display the total of connected in the info bar.

✨(frontend) display number of  connected in the participant list

---

CHANGELOG.md
src/aws/lambda-complete/package.json
src/aws/lambda-configure/package.json
src/aws/lambda-convert/package.json
src/aws/lambda-elemental-routing/package.json
src/aws/lambda-medialive/package.json
src/aws/lambda-mediapackage/package.json
src/aws/lambda-migrate/package.json
src/aws/utils/update-state/package.json
src/backend/setup.cfg
src/frontend/apps/lti_site/package.json

- Display total amount of participants for a webinar
- Add missing ended webinar screens
and scheduled is in the past
- Allow to disable chrome sandboxing in puppeteer.
To disable it set DISABLE_PUPPETEER_SANDBOX=1
- Add endpoint to list attendances for a video
- Add a custom render method for our tests, it is based on 
react-testing-library and wrap the test component in most of 
the common application contexts (grommet, intl, react-router, 
react-query, react-hot-toast, breadcrumb, styled-components)
- Add a link to generate an ics file on the scheduled page
- Manage tags on video resource
- Manage license on video resource
- Add a new instructor dashboard VOD composed with widgets:
- Widget for modifying video's title & description. 
- Widget for uploading a new video
- Widget for …

🔖(beta) bump release to 4.0.0-beta.8

---

CHANGELOG.md
src/frontend/apps/lti_site/apps/deposit/components/Dashboard/DashboardInstructor/index.tsx
src/frontend/apps/lti_site/apps/deposit/components/Dashboard/DashboardStudent/UploadFiles/index.tsx
src/frontend/apps/lti_site/apps/deposit/components/Dashboard/DashboardStudent/index.tsx
src/frontend/apps/lti_site/apps/deposit/components/SelectContentTab/index.spec.tsx
src/frontend/apps/lti_site/apps/deposit/components/SelectContentTab/index.tsx

Translations were broken in some deposit app components.
Fix them…

🐛(frontend) fix deposit app translations

---

CHANGELOG.md
src/frontend/apps/lti_site/apps/deposit/components/Dashboard/DashboardStudent/UploadFiles/index.tsx
src/frontend/apps/lti_site/apps/deposit/components/Dashboard/common/DepositedFileRow/index.tsx
src/frontend/apps/lti_site/apps/deposit/components/Dashboard/index.tsx

The responsive UI in the deposit app was badly done. It needed to be rewrite.
Before:
After:

💄(frontend) improve deposit files list

---

src/frontend/yarn.lock

When running yarn install command, the yarn.lock file is updated. We have to commit it. It seems that the last resolution update in the package.json file didn't update the yarn.lock file.

⬆️(front) update yarn.lock file

---

CHANGELOG.md
src/frontend/apps/lti_site/components/VideoWidgetProvider/index.spec.tsx
src/frontend/apps/lti_site/components/VideoWidgetProvider/index.tsx

We want to allow instructor to control the video visibility for a VOD. The related widget is added to the VOD dashboard.
Description...

✨(front) enable visibility widget in VOD dashboard

---

src/backend/marsha/bbb/api.py
src/backend/marsha/bbb/models.py
src/backend/marsha/bbb/permissions.py
src/backend/marsha/bbb/tests/test_api.py

As we want to show users their classrooms, we open the api to them.

✨(backend) allow site users to get classroom lists api

---

src/backend/marsha/bbb/api.py
src/backend/marsha/bbb/permissions.py
src/backend/marsha/bbb/tests/api/classroom/test_classroomdocuments.py
src/backend/marsha/bbb/tests/api/classroom/test_list.py
src/backend/marsha/bbb/tests/api/classroom/test_retrieve.py
src/backend/marsha/core/factories.py

We want the site users to retrieve their classroom.
Open classroom retrieve api to site users.

✨(backend) allow site users to get classroom retrieve api

---

CHANGELOG.md
src/backend/marsha/bbb/tests/test_bbb_utils.py
src/backend/marsha/bbb/utils/bbb_utils.py

The record feature must be enabled on the API call when creating a room instance. Without that, the feature is not usable.

✨(back) enable recording when creating a BBB room instance

---

.circleci/config.yml
CHANGELOG.md
src/frontend/apps/standalone_site/.eslintrc.js
src/frontend/apps/standalone_site/src/App.tsx
src/frontend/apps/standalone_site/src/assets/svg/iko_close.svg
src/frontend/apps/standalone_site/src/features/ClassRooms/components/ClassRooms.tsx
src/frontend/apps/standalone_site/src/features/ClassRooms/components/Create/ClassRoomCreate.spec.tsx
src/frontend/apps/standalone_site/src/features/ClassRooms/components/Create/ClassRoomCreate.tsx
src/frontend/apps/standalone_site/src/features/ClassRooms/components/Create/ClassRoomCreateForm.spec.tsx
src/frontend/apps/standalone_site/src/features/ClassRooms/components/Create/ClassRoomCreateForm.tsx
src/frontend/apps/standalone_site/src/features/Header/Header.tsx
src/frontend/apps/standalone_site/src/features/Menu/components/Burger/Burger.tsx
src/frontend/apps/standalone_site/src/features/Menu/components/Menu.tsx
src/frontend/apps/standalone_site/src/features/Menu/components/MenuItem.tsx
src/frontend/apps/standalone_site/src/features/Menu/store/menuStore.ts
src/frontend/apps/standalone_site/src/features/Playlist/index.ts
src/frontend/apps/standalone_site/src/hooks/useResponsive.tsx
src/frontend/apps/standalone_site/src/routes/AppRoutes.spec.tsx
src/frontend/apps/standalone_site/src/routes/AppRoutes.tsx
src/frontend/apps/standalone_site/src/routes/routes.tsx
src/frontend/apps/standalone_site/src/styles/theme.extend.ts
src/frontend/packages/lib_classroom/src/components/DashboardClassroom/index.tsx
src/frontend/packages/lib_classroom/src/components/index.ts

Feature to create classroom from standalone site.

✨(website) create classroom

---

docs/sprint-reviews/2022-09-30-sprint-review.md
docs/sprint-reviews/2022-11-07-sprint-review.md
docs/sprint-reviews/2022-12-01-sprint-review.md

Minutes of meeting for the sprint reviews #2 and #3.
- Add report for the sprint review #2 held on October 30, 2022
- Add report for the sprint review #3 held on November 7, 2022

📝(sprint) add sprint review #2 and #3

---

src/frontend/apps/standalone_site/src/features/Authentication/components/Authenticator.spec.tsx
src/frontend/apps/standalone_site/src/features/Authentication/components/Authenticator.tsx

Test the URL after the authentication has been made.

✅(frontend) improve Authenticator tests

---

CHANGELOG.md
src/frontend/packages/lib_classroom/src/components/DashboardClassroom/index.spec.tsx
src/frontend/packages/lib_classroom/src/components/DashboardClassroom/index.tsx
src/frontend/packages/lib_classroom/src/components/DashboardClassroomForm/index.spec.tsx
src/frontend/packages/lib_classroom/src/components/DashboardClassroomInstructor/index.spec.tsx
src/frontend/packages/lib_classroom/src/components/DashboardClassroomLayout/index.tsx
src/frontend/packages/lib_classroom/src/components/DashboardClassroomStudent/index.tsx
src/frontend/packages/lib_classroom/src/components/DashboardClassroomStudentCounter/index.spec.tsx
src/frontend/packages/lib_classroom/src/components/DashboardClassroomStudentCounter/index.tsx
src/frontend/packages/lib_classroom/src/components/UploadDocuments/index.spec.tsx
src/frontend/packages/lib_classroom/src/components/UploadDocuments/index.tsx
src/frontend/packages/lib_classroom/src/data/queries/index.spec.tsx
src/frontend/packages/lib_classroom/src/data/queries/index.tsx
src/frontend/packages/lib_classroom/src/data/sideEffects/createClassroomDocument/index.spec.ts
src/frontend/packages/lib_classroom/src/data/sideEffects/createClassroomDocument/index.ts
src/frontend/packages/lib_classroom/src/utils/tests/factories.ts

[Fix the Issue about Eslint in lib-classroom](https://github.com/openfun/marsha/issues/1804)

🚨(lib-classroom) refactorise components in lib-classroom

---

.github/ISSUE_TEMPLATE/Bug_report.md

When want to open an issue for a problem we encountered it is weird to first ask about the expected behavior before even describing the problem. I never know what to write and end-up changing the questions.
First ask about the but, then about what was expected.

🧑‍💻(github) improve bug report issue template

---

CHANGELOG.md
src/frontend/apps/lti_site/components/VideoCreateForm/index.tsx
src/frontend/apps/lti_site/components/VideoWidgetProvider/widgets/SchedulingAndDescription/index.tsx
src/frontend/apps/standalone_site/src/components/Modal/Modal.spec.tsx
src/frontend/apps/standalone_site/src/components/Modal/Modal.tsx
src/frontend/apps/standalone_site/src/components/Modal/ModalButton.spec.tsx
src/frontend/apps/standalone_site/src/components/Modal/ModalButton.tsx
src/frontend/apps/standalone_site/src/components/Modal/index.ts
src/frontend/apps/standalone_site/src/components/SortableTable/index.tsx
src/frontend/apps/standalone_site/src/features/ClassRoom/components/Create/ClassRoomCreate.spec.tsx
src/frontend/apps/standalone_site/src/features/ClassRoom/components/Create/ClassRoomCreate.tsx
src/frontend/apps/standalone_site/src/features/ClassRoom/components/Create/ClassRoomCreateForm.spec.tsx
src/frontend/apps/standalone_site/src/features/ClassRoom/components/Create/ClassRoomCreateForm.tsx
src/frontend/apps/standalone_site/src/features/Menu/components/MenuItem.spec.tsx
src/frontend/apps/standalone_site/src/features/Menu/components/MenuItem.tsx
src/frontend/apps/standalone_site/src/features/Playlist/components/CreatePlaylistForm.spec.tsx
src/frontend/apps/standalone_site/src/features/Playlist/components/CreatePlaylistForm.tsx
src/frontend/apps/standalone_site/src/features/Playlist/components/PlaylistPage.tsx
src/frontend/apps/standalone_site/src/features/PortabilityRequests/components/PortabilityRequests.tsx
src/frontend/apps/standalone_site/src/styles/theme.extend.ts
src/frontend/packages/lib_classroom/src/components/DashboardClassroom/index.tsx
src/frontend/packages/lib_classroom/src/components/index.ts
src/frontend/packages/lib_common/src/theme.ts
src/frontend/packages/lib_components/src/common/Form/index.spec.tsx
src/frontend/packages/lib_components/src/common/Form/index.tsx
src/frontend/packages/lib_components/src/common/SchedulingFields/index.tsx

Harmonize the styles between our apps.
Based on that:
- [Form Design](https://app.abstract.com/projects/a05c2d87-39b7-439e-b7e9-4b1ac6667ce3/branches/a3b41a47-2cc3-47e8-9ee9-05ccb7926eca/commits/d592fc50d7ff9442bb11c6a97c86b0819f01bbc1/files/1d6d9477-aff0-4d93-b3bd-982068b16af3/layers/A1A86794-7B23-4932-8465-929829DFA72C?collectionId=46d1ff46-d277-478b-92db-9d5a7c745f95&collectionLayerId=1462eb23-3f20-4011-82dd-034b8b74543b&mode=design&sha=latest)
- [Modal Design](https://app.abstract.com/projects/a05c2d87-39b7-439e-b7e9-4b1ac6667ce3/branches/a3b41a47-2cc3-47e8-9ee9-05ccb7926eca/commits/latest/files/1d6d9477-aff0-4d93-b3bd-982068b16af3/layers/0A8E6689-98A9-4D61-8E40-C442B96C0F57?collectionId=87bad8d2-4099-4b2d-b1a9-465e84b00355&collectionLayerId=f260c6ce-7eeb-497f-9064-49d8dcbd4b06)
- …

💄(frontend) feature/anthony/common-theme

---

CHANGELOG.md
src/frontend/apps/lti_site/components/TeacherLiveRecordingActions/StopRecording/index.tsx

Fix issue https://github.com/openfun/marsha/issues/1838
Refetch segmentDuration when the component is rerendered.

🐛(lti) fix recording glitch when resizing window

---

CHANGELOG.md
src/frontend/apps/lti_site/components/LiveInfoBar/index.spec.tsx
src/frontend/apps/lti_site/components/LiveInfoBar/index.tsx

Add translation management for the number of viewers
Fix number of viewers now filtering teachers
[Issue linked](https://github.com/openfun/marsha/issues/1845)

🐛(lti) fix translation number of viewers

---

CHANGELOG.md
src/frontend/apps/lti_site/components/LiveModale/index.tsx

Avoid overlap of the buttons on the modal
Set z-index on the modal to end live on mobile view

🐛(lti) fix zindex problem on mobile end live modal

---

CHANGELOG.md
src/frontend/apps/lti_site/components/InstructorWrapper/InstructorView/index.tsx
src/frontend/apps/lti_site/components/LiveInfoBar/index.tsx
src/frontend/apps/lti_site/components/PublicVideoDashboard/PublicVODDashboard/index.spec.tsx
src/frontend/apps/lti_site/components/VideoWidgetProvider/index.spec.tsx
src/frontend/apps/lti_site/components/VideoWidgetProvider/widgets/SchedulingAndDescription/index.tsx
src/frontend/apps/lti_site/components/VideoWidgetProvider/widgets/SharedLiveMedia/index.tsx
src/frontend/apps/lti_site/components/VideoWidgetProvider/widgets/TitleAndDescriptionWidget/index.tsx
src/frontend/apps/lti_site/components/VideoWidgetProvider/widgets/ToolsAndApplications/index.tsx
src/frontend/apps/lti_site/components/VideoWidgetProvider/widgets/VisibilityAndInteraction/index.tsx

Refresh live parameters values displayed when another user change it
Issue https://github.com/openfun/marsha/issues/1905
Update state value when hook changes

🐛(lti) refresh live parameters state

---

src/frontend/apps/standalone_site/src/App.spec.tsx
src/frontend/apps/standalone_site/src/features/HomePage/components/HomePage.spec.tsx
src/frontend/apps/standalone_site/src/features/HomePage/components/HomePage.tsx

The text Homepage in the Homepage component was useless and we decided to remove it.

🔥(front) remove Homepage text in Homepage component

---

CHANGELOG.md
src/backend/marsha/account/tests/api/test_saml_fer_idp_list.py
src/backend/setup.cfg
src/frontend/apps/standalone_site/src/features/Authentication/components/RenaterAuthenticator.spec.tsx
src/frontend/apps/standalone_site/src/features/Authentication/components/RenaterAuthenticator.tsx

Display the Renater IdP's logo on login page
Description...

✨(frontend) Display Renater IdP's logo on login page

---

src/frontend/apps/standalone_site/src/features/Profile/features/AccountSettings/utils.ts

console.log was used for debug purpose and was not remove in the profile feature.

🔊(front) remove unwanted console.log

---

CHANGELOG.md
src/backend/marsha/e2e/test_lti.py
src/backend/marsha/e2e/test_lti_bbb.py
src/backend/marsha/e2e/test_site.py

Some our our e2e tests randomly fails.
Stabilize them.

✅ fix e2e tests

---

CHANGELOG.md
src/frontend/apps/standalone_site/src/App.spec.tsx
src/frontend/apps/standalone_site/src/App.tsx
src/frontend/apps/standalone_site/src/public-path.ts
src/frontend/apps/standalone_site/src/react-app-env.d.ts
src/frontend/apps/standalone_site/src/utils/dom.ts

The CDN url, coming from __webpack_public_path__ was init after the first chunk was loaded, creating an error. 
We wait that the dom is ready before loading the app.

🐛(website) fix firefox chunk CDN invite mode

---

CHANGELOG.md
src/aws/lambda-complete/package.json
src/aws/lambda-configure/package.json
src/aws/lambda-convert/package.json
src/aws/lambda-elemental-routing/package.json
src/aws/lambda-medialive/package.json
src/aws/lambda-mediapackage/package.json
src/aws/lambda-migrate/package.json
src/aws/utils/update-state/package.json
src/backend/setup.cfg
src/frontend/apps/lti_site/package.json
src/frontend/apps/standalone_site/package.json
src/frontend/package.json
src/frontend/packages/lib_classroom/package.json
src/frontend/packages/lib_common/package.json
src/frontend/packages/lib_components/package.json
src/frontend/packages/lib_tests/package.json
src/frontend/packages/lib_video/package.json

- Add a configuration for jwt state preservation with localstorage
- Authentication renater select crashing the site on scroll
- Consider local storage is optional depending on browser settings
- Fix firefox chunk CDN invite mode
- Return 404 for missing static files

🔖(beta) bump release to 4.0.0-beta.14

---

src/backend/marsha/account/social_pipeline/organization.py

Provide more information about new user from Shibboleth roles.

🔊(backend) add role info log for saml_fer

---

CHANGELOG.md
src/backend/marsha/e2e/test_lti_bbb.py
src/backend/marsha/e2e/test_site.py
src/frontend/apps/lti_site/components/PlaylistPortability/index.tsx
src/frontend/apps/lti_site/components/SelectContent/index.tsx
src/frontend/packages/lib_classroom/src/components/ClassroomForm/index.spec.tsx
src/frontend/packages/lib_classroom/src/components/ClassroomForm/index.tsx
src/frontend/packages/lib_classroom/src/components/DashboardClassroomForm/index.spec.tsx
src/frontend/packages/lib_classroom/src/components/DashboardClassroomInfos/index.spec.tsx
src/frontend/packages/lib_classroom/src/components/DashboardClassroomInfos/index.tsx
src/frontend/packages/lib_classroom/src/components/DashboardClassroomInstructor/index.tsx
src/frontend/packages/lib_classroom/src/components/DashboardCopyClipboard/index.spec.tsx
src/frontend/packages/lib_classroom/src/components/DashboardCopyClipboard/index.tsx
src/frontend/packages/lib_components/src/common/CopyClipboard/index.spec.tsx
src/frontend/packages/lib_components/src/common/CopyClipboard/index.tsx
src/frontend/packages/lib_video/src/components/common/VideoWidgetProvider/widgets/VisibilityAndInteraction/index.tsx
src/frontend/packages/lib_video/src/components/live/common/DashboardLiveRaw/index.tsx

Allow the instructors to quickly copy an lti url for the classrooms in order to paste it in an lms.
Add a link like the invite one to the standalone site.

Bbb lti link in standalone site

---

CHANGELOG.md
src/frontend/packages/lib_common/src/theme.ts
src/frontend/packages/lib_components/src/common/SchedulingFields/index.tsx

Issue: https://github.com/openfun/marsha/issues/1945
The size of the dates in the calendar were too big and the layout didn't have enough space to display correctly between the top of the screen and the input field where it was bind.

💄(frontend) fix ux issues in calendar

---

src/backend/marsha/core/management/commands/check_harvested.py
src/backend/marsha/core/management/commands/check_live_state.py
src/backend/marsha/core/management/commands/clean_aws_elemental_stack.py
src/backend/marsha/core/management/commands/clean_medialive_dev_stack.py
src/backend/marsha/core/management/commands/send_reminders.py
src/backend/marsha/core/management/commands/test_mediapackage_harvest.py
src/backend/marsha/core/utils/cloudfront_utils.py
src/backend/marsha/core/utils/medialive_utils.py
src/backend/marsha/core/utils/throttle.py
src/backend/marsha/core/utils/time_utils.py
src/backend/marsha/core/utils/xmpp_utils.py
src/backend/marsha/settings.py

`__init__.py` files are missing, which prevent module detection

✅(backend) add missing `__init__.py` files

---

CHANGELOG.md
src/backend/marsha/settings.py
src/backend/setup.cfg

We want to monitor marsha using scoutapm solution. We need to install it first and configure it in the settings. By default nothing is enabled

➕(brack) install scoutapm package

---

CHANGELOG.md
src/frontend/apps/lti_site/data/queries/index.spec.tsx
src/frontend/apps/lti_site/data/queries/index.tsx
src/frontend/packages/lib_video/src/components/common/DashboardControlPane/DashboardTabStatistics/DashboardTabStatistics.tsx
src/frontend/packages/lib_video/src/components/common/DashboardControlPane/index.tsx
src/frontend/packages/lib_video/src/components/vod/Teacher/Dashboard.spec.tsx
src/frontend/packages/lib_video/src/components/vod/Teacher/Dashboard.tsx
src/frontend/packages/lib_video/src/hooks/useVideoStats/index.spec.tsx
src/frontend/packages/lib_video/src/hooks/useVideoStats/index.tsx

Answer issue https://github.com/openfun/marsha/issues/1946
Move useStatsVideo in lib_video
Add tabs view for stats

:sparkles:(vod) add stats on vod view 

---

CHANGELOG.md
docs/permissions.md
src/backend/marsha/core/api/account.py
src/backend/marsha/core/permissions.py
src/backend/marsha/core/serializers/account.py
src/backend/marsha/core/tests/api/users/test_list.py
src/backend/marsha/core/tests/api/users/test_retrieve.py
src/backend/marsha/core/tests/api/users/test_update.py
src/backend/marsha/core/tests/api/users/test_whoami.py

This provide API to list users belonging to an organization.

✨(backend) add user API endpoints

---

docs/sprint-reviews/2023-01-27-sprint-review#6.md

Review of the past sprint and defining the next.
Minutes of meeting from 2023-01-27

📝(sprint) add sprint review #6 from 2023-01-27

---

Dockerfile
Makefile
docker-compose.yml
docker/files/usr/local/bin/entrypoint
docker/images/dev/Dockerfile
src/backend/pylintrc

We are having issue when running the development docker image for linting the backend. The image is running with the root user, everytime a file is modified we have to change this file ownership because it belongs to root user. We don't want to use the root user anymore but an Un-privileged one.

♻️(docker) change USER management in Dockerfile

---

CHANGELOG.md
src/frontend/packages/lib_video/src/components/common/VideoWidgetProvider/LocalizedTimedTextTrackUpload/TimedTextTrackItem/index.spec.tsx
src/frontend/packages/lib_video/src/components/common/VideoWidgetProvider/LocalizedTimedTextTrackUpload/TimedTextTrackItem/index.tsx

As an instructor I want to download am uploaded timed text track.
To download it, I have to click on the language title. The link to use id the source_url property on the timed text track object.

♻️(lib-video) add subtitles download for teacher

---

src/backend/setup.cfg

This provides a bugfix for shibboleth roles fetch. With this version the whole roles list should be
retrieved.

⬆️(backend) bump social-edu-federation

---

src/frontend/apps/standalone_site/src/features/Contents/components/Contents/Contents.spec.tsx
src/frontend/apps/standalone_site/src/features/Contents/components/Contents/Contents.tsx
src/frontend/apps/standalone_site/src/routes/routes.tsx

Hide the video menu item and the video from the Contents component.

💄(website) hide video from menu and Contents

---

CHANGELOG.md
arnold.yml
src/aws/lambda-complete/package.json
src/aws/lambda-configure/package.json
src/aws/lambda-convert/package.json
src/aws/lambda-elemental-routing/package.json
src/aws/lambda-medialive/package.json
src/aws/lambda-mediapackage/package.json
src/aws/lambda-migrate/package.json
src/aws/utils/update-state/package.json
src/backend/setup.cfg
src/frontend/apps/lti_site/package.json
src/frontend/apps/standalone_site/package.json
src/frontend/package.json
src/frontend/packages/lib_classroom/package.json
src/frontend/packages/lib_common/package.json
src/frontend/packages/lib_components/package.json
src/frontend/packages/lib_markdown/package.json
src/frontend/packages/lib_tests/package.json
src/frontend/packages/lib_video/package.json
src/tray/tray.yml

- Manage xapi request without consumer_site
- rounded button style (#2118)

🔖(beta) bump release to 4.0.0-beta.18

---

CHANGELOG.md
src/frontend/packages/lib_video/src/components/common/VideoWidgetProvider/index.spec.tsx
src/frontend/packages/lib_video/src/components/common/VideoWidgetProvider/index.tsx
src/frontend/packages/lib_video/src/components/common/VideoWidgetProvider/widgets/LicenseManager/index.spec.tsx
src/frontend/packages/lib_video/src/components/common/VideoWidgetProvider/widgets/LicenseManager/index.tsx
src/frontend/packages/lib_video/src/components/common/VideoWizard/CreateVOD/LicenseSelect/index.tsx
src/frontend/packages/lib_video/src/types/SelectOptions.ts

See https://github.com/openfun/marsha/issues/2082
Add the new widget to the teacher dashboard

LicenseManager widget for VOD

---

CHANGELOG.md
src/frontend/packages/lib_classroom/src/components/UploadDocuments/index.spec.tsx
src/frontend/packages/lib_classroom/src/components/UploadDocuments/index.tsx

See https://github.com/openfun/marsha/issues/2100
this component was the only one in the layout not to have a title describing its role.

💄(frontend) add a title to classroom dropzone

---

CHANGELOG.md
src/frontend/packages/lib_common/src/index.ts
src/frontend/packages/lib_common/src/utils.ts
src/frontend/packages/lib_components/src/common/WidgetsContainer/InfoModal/index.spec.tsx
src/frontend/packages/lib_components/src/common/WidgetsContainer/InfoModal/index.tsx

Issue https://github.com/openfun/marsha/issues/2132
The tooltip position on the dashboard was positionned to work inside an iFrame. 
We adapted the code to work outside of an iFrame.

🐛(frontend) fix tooltip position on dashboard

---

CHANGELOG.md
src/frontend/packages/lib_classroom/src/components/ClassroomInfoBar/index.spec.tsx
src/frontend/packages/lib_classroom/src/components/ClassroomInfoBar/index.tsx
src/frontend/packages/lib_classroom/src/components/ClassroomWidgetProvider/widgets/Description/index.tsx
src/frontend/packages/lib_classroom/src/components/ClassroomWidgetProvider/widgets/SupportSharing/UploadDocuments/index.spec.tsx
src/frontend/packages/lib_classroom/src/components/ClassroomWidgetProvider/widgets/SupportSharing/UploadDocuments/index.tsx
src/frontend/packages/lib_classroom/src/components/DashboardClassroomForm/index.tsx
src/frontend/packages/lib_components/src/common/Text/TextAreaInput/index.tsx
src/frontend/packages/lib_video/src/components/common/VideoInfoBar/index.tsx

Some little enhancement can be made on the classroom dashboard : 
- Remove the start date under the title. It's useless and it breaks the info bar
- Align text on the UploadDocuments widget
- Move at the begining the edition icon for the title input. This modification is also made in the lib-video
- Increase description textearea min height. This modification is also made in the lib-video

enhance classroom UI dashboard

---

CHANGELOG.md
src/frontend/apps/standalone_site/src/features/Playlist/components/PlaylistForm.spec.tsx
src/frontend/apps/standalone_site/src/features/Playlist/components/PlaylistForm.tsx
src/frontend/packages/lib_classroom/src/components/ClassroomWidgetProvider/widgets/DeleteClassroom/index.spec.tsx
src/frontend/packages/lib_classroom/src/components/ClassroomWidgetProvider/widgets/DeleteClassroom/index.tsx
src/frontend/packages/lib_video/src/components/common/VideoWidgetProvider/widgets/DeleteVideo/index.spec.tsx
src/frontend/packages/lib_video/src/components/common/VideoWidgetProvider/widgets/DeleteVideo/index.tsx

the common modal components were missing a title and had a little bug on closing button
fix those bugs...

🐛(frontend) fix modal small bugs

---

CHANGELOG.md
src/frontend/apps/standalone_site/src/features/Authentication/components/RenaterAuthenticator.spec.tsx
src/frontend/apps/standalone_site/src/features/Authentication/components/RenaterAuthenticator.tsx
src/frontend/packages/lib_components/src/common/Card/ClosingCard/index.spec.tsx
src/frontend/packages/lib_components/src/common/Card/ClosingCard/index.tsx
src/frontend/packages/lib_components/src/common/Card/index.tsx

Issue: #2191
[Marsha - closing card.webm](https://github.com/openfun/marsha/assets/25994652/541452d6-f627-4f75-b5ec-3c6000121d8c)

🥅(website) display an error when renater auth fails

---

src/frontend/apps/standalone_site/src/features/Playlist/features/UpdatePlaylist/components/AddUserAccessForm.spec.tsx

We have a randomly failing test in front.
It occurs only when launching all standalone test, and seems to be related to a waitfor timeout.
Increase the timeout in this waitfor only.

✅(frontend) fix AddUserAccessForm test

---

CHANGELOG.md
src/frontend/packages/lib_classroom/src/components/DashboardClassroomStudent/index.spec.tsx
src/frontend/packages/lib_classroom/src/components/DashboardClassroomStudent/index.tsx

Add a downloadable ICS file to scheduled classrooms
See https://github.com/openfun/marsha/issues/2248

Generate an ICS file when a classroom is scheduled 

---

CHANGELOG.md
src/backend/marsha/account/factories.py
src/backend/marsha/account/social_pipeline/__init__.py
src/backend/marsha/account/social_pipeline/playlist.py
src/backend/marsha/account/tests/test_social_pipeline_playlist.py

When a user connects from shibboleth and a new association is made, if the user has instructor permission we create a default playlist for him.

✨(back) create a default playlist for new shibboleth user

---

CHANGELOG.md
src/aws/Dockerfile
src/backend/marsha/e2e/test_lti_bbb.py
src/backend/marsha/settings.py

An environment variable had a typo. This seems to break e2e tests.

💚(ci) try to fix e2e tests

---

src/frontend/apps/lti_site/components/LTIRoutes/index.spec.tsx
src/frontend/apps/lti_site/components/LTIRoutes/index.tsx
src/frontend/apps/lti_site/components/PlaylistPortability/route.ts
src/frontend/apps/lti_site/components/VideoWizard/index.tsx
src/frontend/packages/lib_components/src/common/UploadForm/index.tsx
src/frontend/packages/lib_components/src/common/UploadForm/route.ts

After uploading a document, the router didn't have the correct formating to be able to extract the params. 
This PR fixes that.
We add a bunch of tests to the `<LTIRoutes />` component.

🐛(frontend) problem router on upload document

---

src/aws/lambda-complete/yarn.lock
src/aws/lambda-configure/yarn.lock
src/aws/lambda-convert/yarn.lock
src/aws/lambda-elemental-routing/yarn.lock
src/aws/lambda-medialive/yarn.lock
src/aws/lambda-mediapackage/yarn.lock
src/aws/lambda-migrate/yarn.lock
src/aws/utils/update-state/yarn.lock
src/frontend/yarn.lock
src/mail/yarn.lock
src/webtorrent/yarn.lock

Dependanbot upgrades

---

CHANGELOG.md
src/tray/templates/services/webtorrent/deploy.yml.j2
src/tray/templates/services/webtorrent/secret.yml.j2
src/webtorrent/package.json
src/webtorrent/src/app.ts
src/webtorrent/yarn.lock

To monitor errors in the webtorrent application, we want to use and configure sentry.

Webtorrent sentry

---

Dockerfile

New debian version (bookworm) is available, we want to use it as it is the stable version of debian.

⬆️(dockerfile) switch from debian bullseye to bookworm

---

CONTRIBUTORS.md
src/backend/marsha/core/simple_jwt/tokens.py

Helped understand the role of the `LTISelectFormAccessToken` for future developers or future me.

📝(backend) define clearly the role of the inner access token in deep linking

---

CHANGELOG.md
CONTRIBUTORS.md
src/tray/templates/services/app/_deploy_base.yml.j2
src/tray/templates/services/nginx/deploy.yml.j2
src/tray/templates/volumes/media.yml.j2
src/tray/templates/volumes/static.yml.j2
src/tray/vars/all/main.yml

Replace hard coded PVC name for Marsha's volume by variable to allow override.

🔧(arnold) use var to allow override pvc name

---

CHANGELOG.md
src/backend/marsha/bbb/admin.py
src/frontend/apps/lti_site/apps/deposit/components/Dashboard/DashboardStudent/UploadFiles/index.tsx
src/frontend/apps/lti_site/apps/deposit/components/Dashboard/common/DepositedFileRow/index.tsx
src/frontend/apps/lti_site/components/ClaimLink/index.tsx
src/frontend/packages/lib_markdown/src/components/MarkdownEditor/index.spec.tsx

Here are several small bug fixes.
- Remove an non-existent attribute which breaks classroom document admin view.
- Change color of a disabled button in the deposit file student dashboard.
- Remove multiple primary buttons  in the deposit file dashboard.
- Remove multiple calls of playlist is-claimed endpoint.

Misc fixes

---

CHANGELOG.md

Some of the changelog entries were in the wrong version.

🔊(changelog) move changelog to correct version

---

src/frontend/packages/lib_classroom/src/components/DashboardClassroom/index.tsx

We want to increase the refetch poll interval on the classroom dashboard. We increase it from 5 seconds to 45 seconds in a first time.

♻️(front) increase classroom poll refetch interval

---

CHANGELOG.md
src/backend/marsha/bbb/api.py
src/backend/marsha/bbb/tests/api/classroom/test_invite_token.py
src/backend/marsha/settings.py
src/frontend/apps/standalone_site/src/features/App/AppRoutes.spec.tsx
src/frontend/apps/standalone_site/src/features/App/AppRoutes.tsx
src/frontend/apps/standalone_site/src/features/Authentication/api/validateClassroomInviteToken/index.tsx
src/frontend/apps/standalone_site/src/features/Authentication/hooks/useAuthenticator.spec.tsx
src/frontend/apps/standalone_site/src/features/Authentication/hooks/useAuthenticator.tsx
src/frontend/packages/lib_classroom/src/components/DashboardClassroom/index.spec.tsx
src/frontend/packages/lib_classroom/src/components/DashboardClassroom/index.tsx
src/frontend/packages/lib_classroom/src/components/DashboardClassroomError/index.spec.tsx
src/frontend/packages/lib_classroom/src/components/DashboardClassroomError/index.tsx
src/frontend/packages/lib_classroom/src/components/DashboardCopyClipboard/index.spec.tsx
src/frontend/packages/lib_classroom/src/components/DashboardCopyClipboard/index.tsx
src/frontend/packages/lib_classroom/src/data/queries/index.tsx
src/frontend/packages/lib_components/src/common/Card/ClosingCard/index.tsx
src/frontend/packages/lib_components/src/common/ErrorComponents/BoxError/index.tsx

We want to be able to blacklist already used invite token in a classroom. For this, a new settings BBB_INVITE_TOKEN_BLACKLIST is added and this settings will contain a list of blacklist token.

✨(back) allow to blacklist classroom invite token

---

src/tray/templates/services/app/_deploy_base.yml.j2
src/tray/templates/services/app/deploy_app.yml.j2
src/tray/templates/services/app/deploy_celery.yml.j2
src/tray/templates/services/app/deploy_xapi.yml.j2
src/tray/vars/all/main.yml

We need to run celery in its own pod. To do that, we declare a new deployment dedicated to celery.

🔧(tray) create a deployment for celery

---

CHANGELOG.md
src/frontend/apps/standalone_site/vite.config.mts
src/frontend/packages/lib_video/src/components/common/Player/videojs/downloadVideoPlugin/components/DownloadVideoQualityItem.ts
src/frontend/packages/lib_video/src/components/common/Player/videojs/downloadVideoPlugin/index.spec.tsx
src/frontend/packages/lib_video/src/components/common/Player/videojs/downloadVideoPlugin/types.ts
src/frontend/packages/lib_video/src/components/common/Player/videojs/xapiPlugin/index.spec.tsx
src/frontend/packages/lib_video/src/components/common/Player/videojs/xapiPlugin/index.ts

Fixed issue where xAPI statements were not being sent when downloading a video.

✨(front) send xAPI statement for video downloads

---

CHANGELOG.md
docs/peertube-runner.md
src/backend/marsha/core/admin.py
src/backend/marsha/core/api/video.py
src/backend/marsha/core/tasks/timed_text_track.py
src/backend/marsha/core/tasks/video.py
src/backend/marsha/core/tests/api/video/test_initiate_transcript.py
src/backend/marsha/core/tests/api/video/test_transcript_source.py
src/backend/marsha/core/tests/tasks/test_video.py
src/backend/marsha/core/tests/utils/test_transcript.py
src/backend/marsha/core/utils/transcript.py
src/backend/marsha/settings.py
src/backend/setup.cfg
src/frontend/packages/i18n/fr_FR.json
src/frontend/packages/lib_video/src/components/common/VideoWidgetProvider/LocalizedTimedTextTrackUpload/TimedTextTrackItem/index.spec.tsx
src/frontend/packages/lib_video/src/components/common/VideoWidgetProvider/LocalizedTimedTextTrackUpload/TimedTextTrackItem/index.tsx
src/frontend/packages/lib_video/src/components/common/VideoWidgetProvider/LocalizedTimedTextTrackUpload/index.spec.tsx
src/frontend/packages/lib_video/src/components/common/VideoWidgetProvider/LocalizedTimedTextTrackUpload/index.tsx

Adds peertube video transcription generation.
Use django peertube runner connector transcription job once https://github.com/openfun/django-peertube-runner-connector/pull/20 is merged, and connector version 0.7 is released.

Transcript

---

.circleci/config.yml
CHANGELOG.md
docker/images/e2e/Dockerfile

Current playwright image is 1.47.
Using it fixes e2e webkit tests

test playwright noble image

---

CHANGELOG.md
src/tray/templates/services/nginx/configs/marsha.conf.j2

We have separated pods managing the backend and websocket. Peertube runner is using the websocket part of the application, we want to connect to these pods.

🔧(tray) connect runner to ws pods

---

CHANGELOG.md
src/backend/marsha/settings.py

The transcoding resolutions were not configurable. We have to be able to configure them.

♻️(back) allow to configure transcoding resolutions

---

.circleci/config.yml
docker-compose.yml
src/tray/vars/all/main.yml
src/tray/vars/settings.yml

We want to target a higher version of postgresql. We upgrade it to
version 16.4.

⬆️(back) upgrade to postgres 16.4
