.circleci/check-every-commit.sh, .circleci/config.yml, Makefile, setup.cfg
This PR adds a script to do some checks on all commits in the history. We run `make check` and `make test`.
The idea is to have a commit history that is fully working, so we can do a `git bisect` without problem.
This script is used in the circle-ci workflow and will fail the job if at least one commit has a problem.
See https://circleci.com/gh/openfun/marsha/851 for an example of the output. In this job, it's done the first time for every commit. But the result is saved for each commit (in a gist) so it will be really faster next time.
=> Check all commits

setup.cfg
Auto-updating dependencies prevent different developers & the CI from having the same dependency versions. It can also trigger unrelated CI failures when pushing a new branch to the CI or fast-forwarding master to a validated branch.
Pin version numbers to avoid these issues.
=> Pin python dependencies version numbers

.circleci/config.yml, package.json
We're building an open source project that could be useful to others and that is intended to be generic. Using folder names referring to "FUN" does not seem right from that perspective.
Simply use the name of the project instead.
NB: I needed a change in the `package.json` file to clear the deps cache so I found a related change to do there too 😅
=> 👷(circle) rename ~/fun dir to ~/marsha from CI config

env.d/ci, env.d/development, env.d/test, marsha/core/lti.py, marsha/core/templates/core/lti_video.html, marsha/core/tests/test_lti.py, marsha/core/tests/test_templates_lti_video.py, marsha/core/tests/test_views_lti_video.py, marsha/core/views.py, marsha/settings.py, marsha/urls.py, setup.cfg
After an LTI launch request, the frontend application will make requests to the server's API and should be authenticated to related to the LTI launch request.
We chose to use short-lived JWT tokens linked to the resource_link_id (instead of a JWT token linked to a user) because it can carry its own payload without resorting to a session or an object in database. Thus, the video instance will only be created by AWS after the video encoding has completed.
In fact, the previous PR was storing everything in the session but it was not viable because the same browser will initiate several LTI launch request with Marsha if there are several video xblocks on a page in Open edx... The session cookie is unique for a given browser and would be over-written...
=> Add JWT token for authentication after LTI launch request

.gitignore, marsha/core/templates/core/lti_video.html, marsha/settings.py, webpack.config.js
The LTI Video view will be displayed as a single-page javascript app. It therefore needs to load the result of the frontend build and provide a root for react to take charge of.
=> Load javascript in the LTI Video view

front/types/AppData.ts, front/types/Video.ts, marsha/core/templates/core/lti_video.html, marsha/core/tests/test_templates_lti_video.py
The Video record information is available at load time as it comes from the HTML in the initial template provided from the server. We can therefore depend on it being present at all times (after load) and containing the necessary data.
On the other hand, upload policies are not part of the initial payload and need to be separately fetched later on. They thus cannot be part of AppData (and should be removed from our template data elements).
=> Complete AppData type with a Video record

marsha/core/api.py, marsha/core/defaults.py, marsha/core/models/video.py, marsha/core/permissions.py, marsha/core/tests/test_api_video.py, marsha/core/utils.py, marsha/settings.py
We want the frontend to make direct uploads of the video.
=> Add API endpoint to retrieve AWS upload policy

tslint.json
`tslint` recently changed the default (or added a default) for property names in objects. This clashes with the standard way to write JS and with what prettier is enforcing. Change it to only allow quotes when they are strictly necessary.
Also remove the one-line rule for if/else clauses, which makes no sense when writing branching logic with comments that can't be coerced easily into a switch.
The rules on `tslint`'s website for reference:
https://palantir.github.io/tslint/rules/object-literal-key-quotes/
https://palantir.github.io/tslint/rules/one-line/
=> 🔧(tslint) update tslint rules for prettier & style consistency

front/types/AWSPolicy.ts
Update the AWS Policy type to reflect the actual shape of the object we expect to receive from the server as per #34.
Add in "acl" & "key" fields as they are required by the S3 API and implemented on the backend side.
=> ✨(front) update the AWS Policy type

front/components/VideoUploadField/VideoUploadField.spec.tsx, front/components/VideoUploadField/VideoUploadField.tsx, package.json, yarn.lock
The purpose of this component is to let us handle file uploads (almost) as easily as another field by encapsulating the file adding/changing/removing logic.
It will help us keep the Video Form component simpler and lighter by delegating this separate function.
Use `react-dropzone` & component state to make a simple "video upload field"
=> Add a component to handle file upload

__mocks__/react-intl.tsx, front/components/ErrorComponent/ErrorComponent.spec.tsx, front/components/VideoUploadField/VideoUploadField.spec.tsx
Wrapping all components we test that contain strings with an `IntlProvider` and having to account for it in our tests was getting old really quickly.
Write a simple manual mock of `react-intl` to allow us to stop using it in our tests. It still lets us test our strings as it hands back and prints default messages.
=> 🔧(front) add a simple mock for react-intl in our unit tests

terraform/roles.tf, terraform/source/configure/media-convert.js, terraform/source/configure/media-convert.spec.js, terraform/source/configure/presets/preview_jpeg_100p.json, terraform/source/configure/presets/thumbnail_jpeg_1080p.json, terraform/source/configure/presets/thumbnail_jpeg_144p.json, terraform/source/configure/presets/thumbnail_jpeg_240p.json, terraform/source/configure/presets/thumbnail_jpeg_480p.json, terraform/source/configure/presets/thumbnail_jpeg_720p.json, terraform/source/configure/presets/video_mp4_h264_1080p_30fps_5400kbps.json, terraform/source/configure/presets/video_mp4_h264_144p_30fps_300kbps.json, terraform/source/configure/presets/video_mp4_h264_240p_30fps_600kbps.json, terraform/source/configure/presets/video_mp4_h264_480p_30fps_1200kbps.json, terraform/source/configure/presets/video_mp4_h264_720p_30fps_2400kbps.json, terraform/source/encode/index.js
Displaying a thumbnail to display as a placeholder for the video and displaying small preview captures at each second of the video are two different things.
For thumbnails, we only sample one image in each resolution.
For previews, we sample one image per second on the whole video but in a size of  100 pixels.
=> Add media convert preset to capture previews

terraform/lambda.tf, terraform/roles.tf, terraform/source/configure/media-convert.js, terraform/source/configure/media-convert.spec.js, terraform/source/encode/index.js
We want to be able to deploy several independant pipelines, one per environment. When I tried to do it I faced 2 issues:
- presets could not be differentiated by environment
- roles and policies were clashing because their name did not differentiate their environment
=> Make configuration independant by workspace

.gitignore, docker-compose.yml, docker/images/alpine/Dockerfile, env.d/ci, env.d/test, marsha/core/api.py, marsha/core/serializers.py, marsha/core/tests/test_api_video.py, marsha/core/tests/test_views_lti_video.py, marsha/core/utils/aws_cloudfront.py, marsha/core/utils/aws_s3.py, marsha/settings.py, setup.cfg
We want to allow making our videos private in AWS.
The backend must then compute CloudFront signed urls using the RSA private key of an AWS root account.
See AWS documentation for more information: https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-signed-urls.html
=> Activate cloudfront signed urls

front/components/ErrorComponent/ErrorComponent.spec.tsx, front/components/ErrorComponent/ErrorComponent.tsx, front/components/RedirectOnLoad/RedirectOnLoad.spec.tsx, front/components/RedirectOnLoad/RedirectOnLoad.tsx
We recently added two possible error codes from the video upload form, that redirect to `ErrorComponent`.
Note: we can't make the URLs + codes into variables until we have full coverage of the possible values in `ErrorComponent`, otherwise the compiler complains of undefined behavior 😅
This is a pretty cool consequence of doing our routing this way instead of delegating to a more complicated router.
Add relevant help text and error code handling into `ErrorComponent`.
These are not necessarily the final implementation of the `ErrorComponent`, or of handlers for these particular errors. I just thought it best to start from something and make it better later on rather than just drop or throw errors and go 🤷‍♂️
=> ✨(front) add error codes & related strings to ErrorComponent

front/components/AppRoutes/AppRoutes.tsx, front/components/ErrorComponent/ErrorComponent.tsx, front/components/RedirectOnLoad/RedirectOnLoad.spec.tsx, front/components/RedirectOnLoad/RedirectOnLoad.tsx, front/components/VideoForm/VideoForm.tsx, front/components/VideoJsPlayer/VideoJsPlayer.tsx
Using strings directly wherever we define a route or link/redirect to them can cause issues when some of the URL fragments change or when we decide to translate them.
Closes #42 
Using functions returning strings instead gives us a simple API that manages these issues and will enable us to add a helper to build URL localization later on if we need to.
=> ✨(front) use frontend URL fragments from variables

front/components/VideoForm/VideoForm.spec.tsx, front/components/VideoForm/VideoForm.tsx, marsha/core/tests/test_api_video.py, marsha/core/utils/aws_s3.py
We need to update the video status from a lambda once it has finished processing in our mediaconvert pipelines. To enable the lambda to do this update, we need to pass it the JWT that allows the video record to be updated in our django app.
The simplest way to do that is to just add it as metadata that will automatically be available in the relevant lambda(s).
=> Pass jwt as s3 file metadata

front/components/AppRoutes/AppRoutes.tsx
We used HashRouter to manage our frontend routing. This allowed us to have a proper history (even though hidden away by the iframe) as we move around the app.
It is however not ideal with LTI. In some situations we need to reload the iframe, which does not work if we navigater in the browser's history as it then sends a GET with the new URL instead of POSTing the original one with its params.
Using MemoryRouter solves the issue as it does not touch the browser's history at all. We therefore remain on the same URL and can reload our POST request with its params.
=> Use MemoryRouter instead of HashRouter for frontend routing

front/components/ErrorComponent/ErrorComponent.tsx, front/components/Headings/Headings.tsx
For now we use the same ErrorComponent with the same layout to display all our errors. Hopefully users don't see it too often, but we still need to style it.
Add some basic styling to center the content & use proper typography.
As we're using a specific H2, write similar styled components for other heading levels.
=> 💄(front) add some basic styling to error pages

front/components/Button/Button.tsx, front/components/VideoForm/UploadingLoader.tsx, front/components/VideoForm/VideoForm.spec.tsx, front/components/VideoForm/VideoForm.tsx, front/components/VideoUploadField/DropzoneIcon.tsx, front/components/VideoUploadField/DropzonePlaceholder.tsx, front/components/VideoUploadField/VideoUploadField.spec.tsx, front/components/VideoUploadField/VideoUploadField.tsx
We have a working implementation of direct file upload to S3. However, is was lacking any styling and therefore difficult to understand and not esthetically pleasing.
---
---
=> Improve the video upload UI

front/components/VideoJsPlayer/VideoJsPlayer.tsx, front/components/VideoJsPlayer/video.js.css
Our `VideoJsPlayer` using base `video.js` styles is not responsive. It takes the size of the video and does not fill the given iframe.
Also, it does not place the "Play" button correctly.
Make our video.js player component responsive.
Simply use a relative wrapper + absolute content technique to make sure it fills the available space without overflowing or changing the video's aspect ratio.
NB: We're using our own `.css` file to override some styles in the base `video.js` `.css` file. In our opinion vendoring the `video.js` `.css` is not desirable, and we don't want to introduce a third way of styling things.
Stick to `styled-components` for everything else and basic `.css` files for `video.js` only.
=> 💄(front) make the video player responsive

marsha/settings.py
The location of the STATIC_ROOT had been set prior to using Docker and needed to be adapted. 
I changed the STATIC_ROOT location to "/data/static" in line with the common practice at France Université Numérique. 
I also added the possibility to configure it together with MEDIA_ROOT so that it is possible
to install Marsha the traditional way without Docker.
=> Adapt the STATIC_ROOT location to Docker

marsha/settings.py
To deploy Marsha, we need to make some settings more configurable. The location of the AWS private ssh key (required for cloudfront) is one of those.
Instead of hard-coding the location of AWS ssh private key, we've decided to make it overridable via an environment variable. Previous value make a great default, hence we've decided to keep it as is.
=> ⚡️(settings) make AWS ssh key configurable

terraform/s3.tf
The source bucket is expected to receive direct browser uploads from our users. In order to do that, it needs to return the correct cross origin headers.
Just open POST requests as all operations are locked down and need signed policies to be performed.
=> Add CORS rules for the source bucket

terraform/roles.tf
Our lambdas (only `encode` at first but maybe others later on) need to be able to read metadata on existing objects in the relevant S3 source bucket.
There is no specific permission for metadata, so we need to give them read access to those objects. The way to do that is to target the marsha_source by its arn and then select all objects inside it.
=> Add a policy to allow lambdas to read source s3 bucket

marsha/core/serializers.py, marsha/core/tests/test_api_video.py, terraform/cloudfront.tf, terraform/s3.tf, terraform/source/configure/media-convert.js, terraform/source/configure/media-convert.spec.js, terraform/source/configure/presets/video_dash_h264_1080p_30fps_5400kbps.json, terraform/source/configure/presets/video_dash_h264_144p_30fps_300kbps.json, terraform/source/configure/presets/video_dash_h264_240p_30fps_600kbps.json, terraform/source/configure/presets/video_dash_h264_480p_30fps_1200kbps.json, terraform/source/configure/presets/video_dash_h264_720p_30fps_2400kbps.json, terraform/source/configure/presets/video_hls_h264_1080p_30fps_5400kbps.json, terraform/source/configure/presets/video_hls_h264_144p_30fps_300kbps.json, terraform/source/configure/presets/video_hls_h264_240p_30fps_600kbps.json, terraform/source/configure/presets/video_hls_h264_480p_30fps_1200kbps.json, terraform/source/configure/presets/video_hls_h264_720p_30fps_2400kbps.json, terraform/source/configure/presets/video_mp4_h264_1080p_30fps_5400kbps.json, terraform/source/configure/presets/video_mp4_h264_144p_30fps_300kbps.json, terraform/source/configure/presets/video_mp4_h264_240p_30fps_600kbps.json, terraform/source/configure/presets/video_mp4_h264_480p_30fps_1200kbps.json, terraform/source/configure/presets/video_mp4_h264_720p_30fps_2400kbps.json, terraform/source/encode/index.js
The player we chose (https://github.com/sampotts/plyr) supports adaptive bitrate with HLS/DASH so it would be nice if our backend could support it as well.
=> Add Adaptive Bit Rate and encoding improvements

marsha/core/templates/core/lti_development.html, marsha/core/views.py, marsha/urls.py
LTI providers need to respond to a POST request on a route with a specific set of parameters. We also intend it to be used through an iframe.
We therefore need a development view to be able to make multiple POST requests hassle-free during development. Developing in an iframe is also more comfortable as it mimicks the environment the real app will run in.
=> Add a development view to simplify LTI based work

marsha/core/api.py, marsha/core/models/video.py, marsha/core/serializers.py, marsha/core/tests/test_api_subtitle_track.py, marsha/core/tests/test_api_upload_confirm.py, marsha/core/tests/test_api_video.py, marsha/core/tests/test_serializers_upload_confirm.py, marsha/urls.py, terraform/source/encode/index.js
AWS needs to confirm the state of uploads (+processing) it has received.
I added a separate endpoint to handle all upload confirms after making the necessary refactorings.
The pros of this approach:
- simplicity in AWS because it does not need to know about the Marsha objects. AWS only knows S3 object keys and confirms the state of the upload of an object key. The intelligence to know to which object and which version the key belongs is kept in Django in a DRY way with the rest of the code.
- security as we could make the state and stamp fields readonly on the main API. Authentication for this endpoint is specific to AWS and based on signed urls.
The cons of this approach:
- The API scheme for this endpoint is not in line with the other endpoints (/api/{object_type}/{object_id})
=> Add endpoint for AWS to confirm file uploads

terraform/source/encode/index.js
As we were working on the `encode` lambda, we noticed some changes could be made to make it shorter & more idiomatic.
Use template strings instead of concatenation & maps instead of hand-written lists of objects.
=> ♻️(lambda) make the lambda encode more idiomatic

front/components/VideoForm/VideoForm.spec.tsx, front/components/VideoForm/VideoForm.tsx, marsha/core/api.py, marsha/core/tests/test_api_video.py
We planned on sending the client JWT as part of video metadata to enable our lambdas to use it to update the video on the API when upload & transcoding are finished.
This design was scrapped in favor of one where we actually use a shared secret to authenticate the lambdas with the backend server. We therefore should not send the client JWT to S3 anymore.
=> Do not pass client jwt as video metadata

terraform/roles.tf
This reverts commit 11a46d4e5d21540c2b9b3ca9302073eed73ce7ed.
We decided not to use metadata to transmit a JWT to the lambda and instead share a proper secret between the lambda and the Django backend.
It is therefore not necessary for lambdas to have read access on our source s3 buckets.
We should not grant privileges that are not actually required. We can just revert that permission.
=> Revert "add a policy to allow lambdas to read source s3 buckets"

.circleci/config.yml, terraform/source/confirm/index.js, terraform/source/confirm/index.spec.js, terraform/source/confirm/jest.config.js, terraform/source/confirm/package.json, terraform/source/confirm/yarn.lock
We need to notify our Django backend when a file has finished uploading and processing. It exposes an endpoint implemented in #73 and #78. 
Implement the confirm lambda that is triggered by MediaConvert and makes a call on our endpoint. Add simple testing facilities so we can write our init tests for this lambda.
Note: we chose to repeat dependencies and CI config in order to ship now. We should consider a refactor to streamline, complete and generally improve our JS testing to bring lambda testing & linting up to par with what we're doing for the frontend.
=> Implement the confirm upload lambda

terraform/source/configure/jest.config.js, terraform/source/configure/media-convert.js, terraform/source/configure/media-convert.spec.js, terraform/source/configure/package.json, terraform/source/configure/yarn.lock
We're using Jest to run Javascript tests throughout marsha (frontend & confirm lambda) and in our other projects. There's no reason to single out the configure lambda with mocha/chai/sinon tests.
Migrate `configure` tests to Jest.
=> Use jest to test the configure lambda

terraform/cloudfront.tf, terraform/s3.tf
We already allowed cross-origin POST requests on our source bucket to allow video uploads. Conversely, we need to allow cross-origin GET requests on the destination bucket to enable video playback.
Cloudfront needs to pass along CORS related headers to s3 as "Origin" is needed for s3 to send back any CORS headers at all and access control "Request-Headers" & "Request-Method" are necessary for preflight requests.
=> ✨(terraform) set up CORS on s3 & terraform for the destination bucket

front/index.tsx, front/utils/parseDataElements/parseDataElements.spec.ts, front/utils/parseDataElements/parseDataElements.ts
We recently updated the way the backend generates data elements in order to have consistent types & facilitate serialization and deserialization.
These changes result in nested objects being made of just an id and a data-{id} attribute containing a JSON with all the data.
Update parseDataElements to use JSON parse on such elements instead of iterating over attributes for nested objects.
=> ♻️(front) update parseDataElements to load JSON directly

front/components/RedirectOnLoad/RedirectOnLoad.spec.tsx, front/components/RedirectOnLoad/RedirectOnLoad.tsx, front/components/VideoForm/VideoForm.spec.tsx, front/components/VideoPlayer/VideoPlayer.spec.tsx, front/index.tsx, front/types/Video.ts, front/utils/parseDataElements/parseDataElements.spec.ts, front/utils/parseDataElements/parseDataElements.ts
We implemented our Video type in the frontend before this property was available on the backend and we provisionally named it "status". It's actually named "state" on the backend.
Just rename it on the type and at all use sites to conform to the actual shape of a Video object.
=> ♻️(front) rename Video property from "status" to "state"

__mocks__/shaka-player.ts, front/components/RedirectOnLoad/RedirectOnLoad.tsx, front/components/VideoPlayer/VideoPlayer.spec.tsx, front/components/VideoPlayer/VideoPlayer.tsx, front/types/Video.ts, front/types/libs/shaka-player/index.d.ts, package.json, tsconfig.json, yarn.lock
Enable adaptive bitrate streaming for all supported clients.
- Add `shaka-player` to allow DASH ISO playback in browsers (HLS is natively supported on iPhones, which are the only relevant clients for this format)
- update our `VideoPlayer` to load `shaka-player` and set the HLS manifest source
=> Implement adaptive bitrate client-side

marsha/settings.py, setup.cfg
[Sentry](https://sentry.io) is a great tool to track and report application errors. Looks like a requirement for any Django project.
This work integrates Sentry to Marsha. To activate it, you should create a sentry project and set the `DJANGO_SENTRY_DSN` environment variable to point to your project's DSN.
Fix #93
=> ✨(backend) integrate sentry

marsha/settings.py
At the time of writing, available configurations for Marsha are: `Development` and `Test`. Some more configurations are missing to push the project to production.
The following missing configurations have been added to deploy marsha:
- `Production`
- `Staging`
- `PreProduction`
The two later ones derive from the `Production` configuration.
Fix #94
=> 🔧(settings) add production(-derived) configurations

.circleci/config.yml, .gitignore, terraform/Makefile, terraform/source/encode/yarn.lock
As we worked on #92, we noticed there was no test job for the encode lambda, and also deploying the lambdas generated unnecessarily large packages and useless `package-lock.json` files.
=> Improve lambdas build and bundling

marsha/core/lti.py, marsha/core/models/account.py, marsha/core/tests/test_lti.py, marsha/core/tests/test_views_lti_video.py
It seems that the Open edX LTI Xblock does not always send the hostname, for example when calling the LTI Xblock from the CMS. This causes Marsha to refuse the LTI connection because the passport can not be found.
Since the consumer site is already defined by the passport, we can skip checking the hostname and rely on the consumer site linked to the passport (either directly or through a playlist depending on the type of passport) after we have retrieved and verified it. 
This method will also be used for other LMS like Moodle in order to stay coherent.
=> Stop considering hostname from the LTI query

package.json, setup.cfg
This release fixes Marsha to make it work with Open edX (the LTI Xblock does not send its hostname on studio side and advanced settings don't accept all punctuation characters for the passport shared secret).
=> 🔖(patch) bump release to 1.0.0-beta.3

front/components/Loader/Loader.tsx
We're replacing our existing animated Uploading view with a more comprehensive dashboard. We'll need small status icons to use with the status keywords.
This one is meant to be used next to "uploading" or "processing" while one of these tasks is underway.
=> Add a small spinner component

front/components/Loader/Loader.spec.tsx, front/components/Loader/Loader.tsx, front/components/UploadStatusList/UploadStatus.spec.tsx, front/components/UploadStatusList/UploadStatus.tsx, front/components/UploadStatusList/UploadStatusList.spec.tsx, front/components/UploadStatusList/UploadStatusList.tsx, front/testSetup.ts, front/types/Video.ts, front/utils/theme/theme.ts, package.json, yarn.lock
In our dashboard (or elsewhere, later on), we'll need to display the status of an upload along our pipeline, from the initial PENDING to READY or error through all our steps.
NB: actual dashboard to follow in a subsequent PR
=> Add a component to show upload state

front/components/withLink/withLink.tsx
`react-router` does not provide any straightforward way to imperatively navigate to a route as needed.
This can be needed in some circumstances, most notably when we want to use something else than an <a> element as a link, and style it at the same time.
`react-router` & `styled-components` do not play nice together as we would end up with either dropped styles, an extra element in the DOM, or broken types.
We need this as we're using `Button`s as links to views in our incoming `Dashboard` component.
Take advantage of `withRouter` to write a more specialized HOC to enable us to add a link to any component.
With this helper, we can easily add a navigating onClick handler to any element, including a styled element.
NB: types may be imperfect as this was somewhat clunky to type, and tests …
=> Add a higher-order component to route to a view

marsha/settings.py
We should be able to configure logging via an environment variable.
We assign a django-configuration's DictValue to the LOGGING setting.
The string passed as environment variable will be evaluated using ast.literal_eval() and can thus be formatted as Python dictionary.
=> Allow configuring logging via an environment variable

src/aws/lambda.tf
`make lambda` generated zip file and the name used in terraform lambda config file are not
the same.
I changed the terraform config to use the goog file name
=> 🐛(terraform) change expected file name in lambda terraform file

Makefile
It is not possible to stop containers using make command. As it is possible to start them with make I think it should be great to stop them the same way.
Create a stop task to stop all running containers.
=> ✨(makefile) create a stop task

src/frontend/components/App/App.spec.tsx, src/frontend/components/AppRoutes/AppRoutes.tsx, src/frontend/components/RedirectOnLoad/RedirectOnLoad.tsx, src/frontend/types/AppData.ts
When a student retrieves a video never created an exception is raised
and a white page display. 
To prevent this, video should be nullable in AppData interface and deal with this contraint in RedirectOnLoad component. In other component and usage of `AppData.video` I use the `!` notation because I am sure that video is not null.
=> 🐛(front) video is nullable in AppData interface

src/frontend/components/RedirectOnLoad/RedirectOnLoad.spec.tsx
in #132 video is nullable in AppData interface. A test is missing reflecting this new behaviour in `<RedirectOnLoad />`
Implement a new case where `video` is null defining what behaviour is expected.
=> ✅(front) Add test on <RedirectOnLoad /> when video is null

.circleci/config.yml, Dockerfile, Makefile, docker-compose.yml, docker/images/alpine/Dockerfile, docker/images/alpine/dev/Dockerfile, docker/images/dev/Dockerfile, docker/tests/run.sh, docker/tests/statics.sh, src/backend/marsha/README.md
Docker image default `CMD` (running `gunicorn`) is broken as the WSGI script moved to `src/backend/marsha`. Moreover, the front-end build cannot be collected.
=> Fix & test docker image

src/frontend/components/RedirectOnLoad/RedirectOnLoad.spec.tsx, src/frontend/components/RedirectOnLoad/RedirectOnLoad.tsx, src/frontend/types/AppData.ts
to reflect changes made in our code base, an enum is used to represent
all the state the app can have. This will avoid typo and mistake.
use an enum to represent all the app state. We will have a single source of truth for those values.
=> ♻️ (front) use an Enum for app state name

src/frontend/components/AppRoutes/AppRoutes.tsx, src/frontend/components/Dashboard/Dashboard.spec.tsx, src/frontend/components/Dashboard/Dashboard.tsx
When the upload is ready at the end of processing, the instructor can click on a "Watch Video" button to go to the player.
This is broken right now as the video object `<VideoPlayer />` receives from the App state is not up-to-date.
Add a call to App's `updateVideo` in `<Dashboard />` polling to ensure App state contains the most up-to-date video, including the URLs.
=> Fix an issue with VideoPlayer when the video is first ready

docs/env.md, src/aws/env.d/development.dist, src/aws/lambda-encode/src/updateState.js, src/aws/lambda-encode/src/updateState.spec.js, src/aws/lambda-update-state/src/updateState.js, src/aws/lambda-update-state/src/updateState.spec.js, src/aws/lambda.tf, src/aws/variables.tf
We encountered several issues in our lambdas while deploying Marsha on different environments beyond developer machines.
This PR aims to fix those issues as we move forward with marsha deployments.
=> Make lambdas production ready

src/backend/marsha/core/tests/test_lti.py, src/backend/setup.cfg
Our LTI functionality is quite well tested but it assumes that the pylti library is working. As we want to remove this dependency, we start by adding tests that involve the whole LTI process without mocking.
We use oauthlib, an alternative oauth1 library, to calculate our signatures for the test because marsha uses oauth2 behind pylti so we should test it with another implementation.
=> Simulate an LTI launch request to test our LTI verification

src/frontend/components/AppRoutes/AppRoutes.tsx, src/frontend/components/InstructorView/InstructorView.spec.tsx, src/frontend/components/InstructorView/InstructorView.tsx, src/frontend/components/InstructorWrapper/InstructorWrapper.spec.tsx, src/frontend/components/InstructorWrapper/InstructorWrapper.tsx
We need to give instructors a way to change the video they uploaded for any given resource, that is the video that will be displayed in the corresponding location in the LMS.
To achieve this, we decided to implement a more generic `<InstructorView />` that we'll be able to use for other features later on.
We also used an `<InstructorWrapper />` that lets us automatically add the `<InstructorView />` on any view where it is needed, only when the current user is an instructor.
=> ✨(front) implement the instructor view wrapping <VideoPlayer />

.circleci/config.yml, src/frontend/package.json
We use both tslint and prettier to manage our code styles. Prettier was
not configured in package.json. This PR add a prettier script and a more
general one to run both tslint and prettier at the same time. This
command can be used in a pre-commit hook for example.
add two new scripts in package definition:
=> ⚡(front) add helper in yarn script to run easily linters

src/backend/marsha/core/serializers.py, src/backend/marsha/core/tests/test_views_lti_video.py
We encountered an issue where attempting to serialize videos with an associated `TimedTextTrack` would fail due to the `TimedTextTrackSerializer` keeping the UUID as an UUID instance during
serialization instead of converting it to a string.
The string conversion can be forced by explicitly specifying the field content (using `PrimaryKeyRelatedField`) which lets us control how it is serialized.
=> 🐛(videos) fix a 500 error when serializing videos

src/aws/lambda-encode/index.js, src/aws/lambda-encode/index.spec.js, src/aws/lambda-encode/package.json, src/aws/lambda-encode/src/encodeTimedTextTrack.js, src/aws/lambda-encode/src/encodeTimedTextTrack.spec.js, src/aws/lambda-encode/src/encodeVideo.js, src/aws/lambda-encode/yarn.lock, src/aws/roles.tf, src/backend/marsha/core/serializers.py, src/backend/marsha/core/tests/test_serializers_upload_confirm.py
The encode lambda was originally written to handle incoming "create object" events for videos and trigger a MediaConvert job to encode them in all the formats we need.
As we add support for various forms of timed text (subtitles, ccs, transcripts), we need to handle those as well. This can be done directly in JS in the lambda as it is much less demanding than converting video.
We reworked the lambda to convert all incoming subtitles to WebVTT
and write them to the destination bucket. To do this, it needed
additional access rights to s3.
=> Update lambdas to manage timed text

src/backend/marsha/core/serializers.py, src/backend/marsha/core/tests/test_serializers_upload_confirm.py
The update state request serializer uses a regex to validate s3 object keys. It had not been updated to account for changes in the way timedtext files are stored in s3.
Update the regexp to make the "mode" part of the object key mandatory and accept all valid modes (`"st"`, `"ts"`, `"cc"`) to fix the issue.
=> Fix the update-state request serializer

src/frontend/components/Dashboard/Dashboard.spec.tsx, src/frontend/components/Dashboard/Dashboard.tsx, src/frontend/components/Dashboard/DashboardInternalHeading.tsx, src/frontend/components/DashboardConnected/DashboardConnected.spec.tsx, src/frontend/components/DashboardConnected/DashboardConnected.tsx, src/frontend/components/DashboardVideoPane/DashboardVideoPane.spec.tsx, src/frontend/components/DashboardVideoPane/DashboardVideoPane.tsx, src/frontend/components/DashboardVideoPaneButtons/DashboardVideoPaneButtons.spec.tsx, src/frontend/components/DashboardVideoPaneButtons/DashboardVideoPaneButtons.tsx, src/frontend/components/DashboardVideoPaneConnected/DashboardVideoPaneConnected.tsx, src/frontend/components/DashboardVideoPaneHelptext/DashboardVideoPaneHelptext.spec.tsx, src/frontend/components/DashboardVideoPaneHelptext/DashboardVideoPaneHelptext.tsx, src/frontend/components/VideoForm/VideoForm.spec.tsx, src/frontend/components/VideoForm/VideoForm.tsx
As we're about to add timed text management to the Dashboard, we need to use a separate DashboardVideoPane component to display the part of the Dashboard that is about the video and hold the related logic.
To do this, we removed a little "hack" which consisted in having VideoForm display a Dashboard during upload to avoid making upload states shared between components. This meant updating the video directly in the store to reflect its client-side state rather than what the record on the backend "probably" holds.
We also move dashboard-related components to their own folders from components/Dashboard to keep a cleaner structure.
=> Split Dashboard video matters into a separate component

src/aws/Makefile
Lambda needs to be run with node 8 so their package.json enforce this
version. To be sure to use the good version the yarn install is now run
in a docker node container in version 8.
Fixes #111
=> ♻️(aws) run yarn install in docker node to use node 8

src/frontend/components/VideoForm/VideoForm.spec.tsx, src/frontend/components/VideoForm/VideoForm.tsx
There are some circumstances when users need to be able to browse from the video form to the dashboard: when they clicked to update the video but elected not to upload a new file, or when they want to update timed text files before the video.
To accomodate these screnarii, we added a link in the video form that points to the dashboard.
=> ✨(frontend) add a link to the dashboard from the video form

src/frontend/components/Dashboard/Dashboard.spec.tsx, src/frontend/components/Dashboard/Dashboard.tsx, src/frontend/components/DashboardConnected/DashboardConnected.tsx, src/frontend/components/DashboardVideoPane/DashboardVideoPane.spec.tsx, src/frontend/components/DashboardVideoPane/DashboardVideoPane.tsx, src/frontend/components/DashboardVideoPaneButtons/DashboardVideoPaneButtons.spec.tsx, src/frontend/components/DashboardVideoPaneButtons/DashboardVideoPaneButtons.tsx, src/frontend/components/DashboardVideoPaneConnected/DashboardVideoPaneConnected.tsx, src/frontend/components/DashboardVideoPaneHelptext/DashboardVideoPaneHelptext.spec.tsx, src/frontend/components/DashboardVideoPaneHelptext/DashboardVideoPaneHelptext.tsx, src/frontend/components/RedirectOnLoad/RedirectOnLoad.spec.tsx, src/frontend/components/RedirectOnLoad/RedirectOnLoad.tsx, src/frontend/components/UploadStatusList/UploadStatusList.spec.tsx, src/frontend/components/UploadStatusList/UploadStatusList.tsx, src/frontend/components/VideoForm/VideoForm.spec.tsx, src/frontend/components/VideoForm/VideoForm.tsx, src/frontend/components/VideoFormConnected/VideoFormConnected.tsx, src/frontend/components/VideoPlayer/VideoPlayer.spec.tsx, src/frontend/components/VideoPlayer/VideoPlayer.tsx, src/frontend/data/rootReducer.ts, src/frontend/data/videos/reducer.ts, src/frontend/types/AppData.ts, src/frontend/types/tracks.ts
As we're about to add a type for timed text tracks and some related enums, we decided it would be more tidy to keep those types together in the same file, mirrorring the organization of code on the backend side, rather than split them into an arbitrary number of files.
We also need to make apparent the fact that states are shared between different types of tracks, which the name `videoState` does not convey.
=> Group track-related types in a common file

src/backend/marsha/core/api.py, src/backend/marsha/core/tests/test_api_timed_text_track.py
We need to make list GET requests on timed text tracks to display the dashboard and allow users to manage their subtitles, transcripts & closed captions.
Allowing those requests is just a matter of adding the relevant DRF mixin to the TimedTextTrack viewset.
=> ✨(api) allow timed text track list GET requests on the API

src/backend/marsha/core/lti.py, src/backend/marsha/core/permissions.py, src/backend/marsha/core/templates/core/lti_development.html, src/backend/marsha/core/tests/test_api_timed_text_track.py, src/backend/marsha/core/tests/test_api_video.py, src/backend/marsha/core/tests/test_views_lti_video.py, src/backend/marsha/core/views.py
A JWT token should be used for every users allowing us to set information in it. Doing this will avoid us to implement a session. No sensitive information can be stored in the token.
=> refactor JWT token usage

src/backend/marsha/core/tests/test_api_schema.py, src/backend/marsha/urls.py, src/backend/setup.cfg
We're currently missing a schema route on the API. It's useful to get access to choices for some fields that can be dynamically changed on the backend side.
Use Django-Rest-Framework's builtin tool to autogenerate a schema and expose it on an API endpoint.
=> A add a schema view to the API

src/frontend/components/InstructorView/InstructorView.spec.tsx, src/frontend/components/InstructorView/InstructorView.tsx, src/frontend/components/InstructorViewConnected/InstructorViewConnected.spec.tsx, src/frontend/components/InstructorViewConnected/InstructorViewConnected.tsx, src/frontend/components/InstructorWrapper/InstructorWrapper.spec.tsx, src/frontend/components/InstructorWrapper/InstructorWrapper.tsx
We recently updated the upload component (now callled `<UploadForm />`) to be more generic. It now needs to be passed a model name and an object ID.
We did not update the link in the `<InstructorView />` to account for that change.
We need to get the video from context (hence the `Connected` wrapper) and pass it to `<InstructorView />` so it can generate a working link.
=> ♻️(frontend) fix the link to <UploadForm /> in <InstructorView />

src/frontend/components/VideoPlayer/VideoPlayer.spec.tsx
In an environment without EME shaka player should not never been
instantiated. The actual test doesn't simulate this on a mounted
VideoPlayer instance so the test was wrong.
Mount a `<VideoPlayer />` instance to check if shaka player is instanciated or not.
=> ✅(VideoPlayer) correctly test shaka player instantiation

src/frontend/components/UploadForm/UploadForm.tsx, src/frontend/data/bootstrapStore.ts, src/frontend/data/rootReducer.ts, src/frontend/data/timedtexttracks/reducer.ts, src/frontend/types/RouteOptions.ts, src/frontend/types/Schema.ts, src/frontend/types/models.ts, src/frontend/types/tracks.ts
Until now marsha only supported one kind of Resource, Video. As we're adding timed text tracks, we need to add in some relevant types and adapt our data (RootState & reducer) to handle them.
Update types & reducer to handle timed text tracks.
We also took this opportunity to add typings for schemas & route OPTIONS as we are going to need them.
=> Prepare the app to handle timedtexttracks

src/backend/marsha/core/api.py, src/backend/marsha/core/tests/test_api_timed_text_track.py
A list GET on the TimedTextTracks API endpoint with a valid JWT token was returning all timed text tracks. It should only return the objects related to the video pointed by the provided JWT Token. This is a major security issue.
=> 🐛(timedtexttracks) restrict access on list access via API

CHANGELOG.md, src/backend/setup.cfg, src/frontend/package.json
- Prepare the app to handle timedtexttracks (full functionality yet to come)
- Add an API schema view
- Extend timed text track language choices to all Django languages
- Create a JWT token for every roles not just instructors (needed to add context to xAPI requests)
- Allow timed text track list GET requests on the API (permissions are fixed in a separate commit)
- Switch to redux for frontend state management
- Add a link to the dashboard from the video form
- Split Dashboard video matters into a separate component
- Run yarn install in docker node to use node 8
- Minor fixes and improvements on features and tests
=> 🔖(patch) bump release to 1.1.0

CHANGELOG.md, src/backend/marsha/core/tests/test_views_lti_video.py, src/backend/marsha/core/views.py
We can not be sure that the LTI request contains `lis_person_contact_email_primary` parameter. 
`user_id` paramter can also not be present but the probability to have it is higher, we will use this parameter to identify a user.
remove usage of `lis_person_contact_email_primary` and made `user_id` optional.
=> remove email in JWT and made user_id optional

src/backend/marsha/core/api.py, src/backend/marsha/core/tests/test_api_timed_text_track.py
As we're adding a timedtexttrack management interface to the frontend, we need to allow users to delete their own timedtexttrack so we can add the relevant UI element.
Doing this is as simple as adding a mixin to the TimedTextTrackViewSet and making sure the tests reflect this new possibility.
=> ✨(api) allow video token holders to delete related timedtexttracks

CHANGELOG.md, src/backend/setup.cfg, src/frontend/package.json
- Allow video token holders to delete related timedtexttracks
- Remove usage of lis_person_contact_email_primary in the LTI request
- Make user_id optional in JWT
=> 🔖(patch) bump release to 1.1.1

src/backend/marsha/core/lti.py, src/backend/marsha/core/tests/test_lti.py
When duplicating a video, we forgot to set the "resource_id" field so we ended-up with copies that pointed to a file that did not exist in S3.
Furthermore, the video was duplicated endlessly each time the instructor was trying to access it. Big bug indeed.
=> 🐛(video) fix duplicating videos for playlist/site portability

src/aws/lambda-encode/index.js, src/aws/lambda-encode/index.spec.js, src/aws/lambda-encode/src/encodeVideo.js
We forgot to return the MediaConvert Job Data from `encodeVideo` into the handler; this causes it to fail when it attempts to log said Job Data it did not receive.
The problem was not caught in the tests because the whole code block was wrapped in a `try/catch` block to catch side-effect related issues.
We reduced the scope of the `try/catch` to only encompass side effect calls and make the relevant unit test fail. We could then simply update both `encodeVideo` and our mock to have the expected behavior of returning the Job Data.
=> Fix an issue that prevented proper logging for lambda-encode

CHANGELOG.md, src/backend/setup.cfg, src/frontend/package.json
- Fix logging in the lambda-encode after submitting job to MediaConvert
- Fix duplicating videos for playlist/site portability (`resource_id` field
was not set from the origin video as it should)
=> 🔖(patch) bump release to 1.1.2

src/frontend/components/AppRoutes/AppRoutes.tsx, src/frontend/components/Dashboard/Dashboard.tsx, src/frontend/components/Dashboard/route.ts, src/frontend/components/DashboardVideoPane/DashboardVideoPane.tsx, src/frontend/components/DashboardVideoPaneButtons/DashboardVideoPaneButtons.tsx, src/frontend/components/ErrorComponent/ErrorComponent.tsx, src/frontend/components/ErrorComponent/route.ts, src/frontend/components/InstructorView/InstructorView.spec.tsx, src/frontend/components/InstructorView/InstructorView.tsx, src/frontend/components/RedirectOnLoad/RedirectOnLoad.spec.tsx, src/frontend/components/RedirectOnLoad/RedirectOnLoad.tsx, src/frontend/components/RedirectOnLoad/route.ts, src/frontend/components/UploadForm/UploadForm.spec.tsx, src/frontend/components/UploadForm/UploadForm.tsx, src/frontend/components/UploadForm/route.ts, src/frontend/components/VideoPlayer/VideoPlayer.tsx, src/frontend/components/VideoPlayer/route.ts
Route definitions from routable components can be imported in many other components or utilities to perform redirects and simple add links.
This can easily cause circular dependencies as routable components are interlinked to create a consistent UI.
Moving the route definitions to their own files should help us avoid this issue by isolating those most frequently imported values.
=> Isolate route definitions to avoid circular dependencies

CHANGELOG.md, src/backend/setup.cfg, src/frontend/package.json
- Add automatic portability between consumer sites for friend websites or different environments of the same website,
- Enforce either the `consumer site` or the `playlist` field is set on a LTI passport, and not both,
- Improve admin pages for the playlist and video models,
- Add unicity constraints on the playlist and video models,
- Improve string representation for the a playlist model.
- Improve test to secure portability of a video to the same playlist on another site, making sure it has precedence over a video linked to another playlist on the other site,
- Isolate route definitions to avoid circular dependencies in the frontend,
- Add unicity test on timed text tracks to confirm soft deleted records are ignored,
- Copy related tracks correctly when duplicating a video,
- Replace …
=> 🔖(patch) bump release to 1.2.0

src/backend/marsha/core/api.py, src/backend/marsha/core/tests/test_api_timed_text_track.py, src/backend/marsha/core/tests/test_api_video.py
We use an `update` query to reset the `upload_state` on a video (resp timed text track) when initiating an upload. The query was mistakenly targetting all objects in the database instead of only the precise object targetted by the API endpoint.
I added a filter to target the specific object of the API endpoint.
=> 🐛(video) fix initiate upload updating all objects instead of just one

src/backend/marsha/core/tests/test_api_timed_text_track.py
A test added recently was failing randomly due to the uniticy constraint on a timed text track (the trio video+language+mode must be unique).
Making sure the language is different on each timed text track we create in the test ensures that we avoid the unicity constraint on video+language+mode.
Nothing urgent as the test suite can be relaunched to pass. We can save it for the next release.
=> 🐛(timedtexttrack) fix randomly failing test due to unicity constraints

.circleci/config.yml, Dockerfile, docker/images/alpine/Dockerfile, src/aws/lambda-configure/package.json, src/aws/lambda-encode/package.json, src/aws/lambda-update-state/package.json, src/aws/lambda.tf
Node 9 is EOL and Node 8 is soon to be, and is already an old version at this point.
Switch Node versions in Dockerfiles & CircleCI builds to Node 10, which is the current LTS. To do this cleanly we also changed the `engines` field in lambdas to accept versions above 8.
=> Use node 10 to run builds & tests

src/frontend/components/AppRoutes/AppRoutes.tsx, src/frontend/components/AppRoutesConnected/AppRoutesConnected.tsx, src/frontend/components/DashboardConnected/DashboardConnected.spec.tsx, src/frontend/components/DashboardConnected/DashboardConnected.tsx, src/frontend/components/DashboardTimedTextPaneConnected/DashboardTimedTextPaneConnected.tsx, src/frontend/components/DashboardVideoPane/DashboardVideoPane.tsx, src/frontend/components/DashboardVideoPaneConnected/DashboardVideoPaneConnected.tsx, src/frontend/components/InstructorViewConnected/InstructorViewConnected.spec.tsx, src/frontend/components/InstructorViewConnected/InstructorViewConnected.tsx, src/frontend/components/InstructorWrapperConnected/InstructorWrapperConnected.tsx, src/frontend/components/RedirectOnLoadConnected/RedirectOnLoadConnected.tsx, src/frontend/components/TimedTextCreationFormConnected/TimedTextCreationFormConnected.ts, src/frontend/components/TimedTextListItemConnected/TimedTextListItemConnected.ts, src/frontend/components/UploadForm/UploadForm.tsx, src/frontend/components/UploadFormConnected/UploadFormConnected.tsx, src/frontend/components/VideoPlayerConnected/VideoPlayerConnected.spec.tsx, src/frontend/components/VideoPlayerConnected/VideoPlayerConnected.tsx, src/frontend/data/rootReducer.ts, src/frontend/types/AppData.ts
Typings for `RootState['context']` were inaccurate: by using `Nullables`, we had technically correct but imprecise types. This forced us to manage those `Nullable` values in places where they were not really `Nullable`.
We can instead parameterize `RootState` to more reliably represent the actual values: when app state is ERROR, some keys hold `null`, when it is not, they  hold the actual values.
Closes #197.
=> Improve context typings to reflect the actual values

CHANGELOG.md, src/backend/setup.cfg, src/frontend/package.json
Added
- Refactor LTI to include video UUID in the launch url. The new endpoint
is of the form /lti/vidoes/<uuid>
- Write an actual README.md file
- Add renovate.json to follow frontend dependencies
- Add a link to the dashboard on the instructor view
- Add a TimedText pane to let users manage tracks in Dashboard
- Allow resource deletion in the `resourceById` reducer
Fixed
- Rework the video dashboard to make it more compact
- Fix and improve Typescript types
=> 🔖(patch) bump release to 2.0.0

src/frontend/components/Dashboard/Dashboard.tsx
Description...
We need to hide the `<DashboardTimedTextPane />` for now to enable new deployments.
We want to avoid confusing users until we are able to display the subtitles, closed captions & transcripts in the video player and to make some improvements to the timed text uploading process.
Description...
We can easily add it back as soon as we want by just adding back `<DashboardTimedTextPaneConnected />` to the `<Dashboard />`.
=> 🚑(frontend) hide the <DashboardTimedTextPane />

CHANGELOG.md, src/backend/setup.cfg, src/frontend/package.json
Fixed
- Fix database migration that was removing the `resource_id` field a bit too
fast and replace it by just a data migration ensuring backward compatibility
- Hide the timed text track pane from the dashboard
=> 🔖(patch) bump release to 2.0.1

src/backend/marsha/settings.py
The static files (css/js) often change but because the files keep the same name, a browser that has it in its cache will not get the new files immediately and will therefore continue to use an outdated version
of such files.
Django proposes a file storage that automatically renames the files to include a hash of their content in their name. The mapping between the original file name and the hashed name is stored in a manifest file
(hence the name of the storage backend).
=> 🔧(storage) use manifest static files storage class for deployed environments

src/backend/marsha/core/serializers.py, src/backend/marsha/core/tests/test_serializers_update_state.py
The update state serializer rejected incoming requests for timed text for languages that had codes longer than 2 letters. This prevented them from being marked as PROCESSING and READY.
This was due to an expectation in the KEY REGEX for the serializer that language codes where 2 letters long, when they can be longer and include dashes.
Just update the regex to accept longer codes with dashes. Update the test to secure this behavior.
=> Fix an issue in the update-state serializer

src/frontend/utils/types.ts
We implemented the `Diff` util for types to help with the implementation of `Omit` (and as something that could be useful on its own).
It turns out TypeScript includes a built-in implementation in `Exclude` since version 2.8, which means we do not need to bake our own.
Remove `Diff`.
=> 🔥(frontend) remove Diff type util

src/backend/marsha/core/admin.py, src/backend/marsha/core/lti.py, src/backend/marsha/core/models/video.py, src/backend/marsha/core/tests/test_lti.py, src/backend/marsha/core/tests/test_views_lti_video.py, src/backend/marsha/core/tests/test_views_openedx_lti_video.py, src/backend/marsha/core/views.py, src/backend/marsha/settings.py
We need to improve usability for admin users to help them understand when they get LTI Errors.
=> Improve usability for admin users (understanding LTI Exceptions)

src/frontend/data/bootstrapStore.ts, src/frontend/utils/types.ts
Redux devtools are a must have when working with redux. It eases a lot
the lifecycle development and has no impact on performance.
This PR target PR #215
=> ✨(redux) enable devtools to ease development

.circleci/config.yml
We want to automatically deploy the master branch to our staging environment :tada: 
For this, we first need to keep a Docker image up-to-date with the master branch.
Modify the CircleCI configuration to also push Docker images to DockerHub for each build on the `master` branch and tags them `master` and `alpine-master`.
=> 👷(circleci) build a docker image on master

src/aws/lambda-encode/src/encodeTimedTextTrack.js, src/aws/lambda-encode/src/encodeTimedTextTrack.spec.js
The encodeTimedTextTrack lambda did not add vtt extension to destination files. It is impossible to retrieve them from the backend without this extension.
Force to add the `.vtt` extension in the encode lambda.
=> 🐛(timedtext) add vtt extensions to destination files

.circleci/config.yml
We were using a `package.json` checksum as cache key, but this is not ideal as it means we still get cache hits if `yarn.lock` is updated when `package.json` is not.
We can use `yarn.lock` instead: whenever `package.json` is updated, `yarn.lock` will
necessarily be updated too.
=> 🔧(ci) use yarn.lock instead of package.json checksum as cache key

src/frontend/components/VideoPlayer/VideoPlayer.spec.tsx, src/frontend/components/VideoPlayer/VideoPlayer.tsx, src/frontend/components/VideoPlayerConnected/VideoPlayerConnected.tsx, src/frontend/data/bootstrapStore.ts, src/frontend/types/tracks.ts
Timed text tracks are present in the video object when marsha is loaded.
We must use them instead of querying again the timed text track API
endpoint. This endpoint can consume a lot of resource.
in `bootstrapStore` we populate the `resource.timedtexttracks` state. Doing this we can keep video and timestexttracks reducer separated and the timedtexttracks can still be maintain like we do right now.
Once this PR merged, I will update #234 to allow the `OPTIONS` method of this endpoint to be fetched by students.
=> ♻️(timedtext) load timed text tracks from object video if present

src/frontend/components/Dashboard/Dashboard.tsx, src/frontend/components/TimedTextListItem/TimedTextListItem.tsx
When a track is missing (PENDING upload state) the button should not be replace but upload.
With this last modification I think everything we can enable timed text tracks in the Dashboard. The upload form explain what you are uploading so there is no need to change it IMO.
display a `Upload` button when a track is not uploaded yet.
=> enhance <TimedTestListItem /> buttons

src/frontend/components/TimedTextCreationForm/TimedTextCreationForm.spec.tsx, src/frontend/components/TimedTextCreationForm/TimedTextCreationForm.tsx, src/frontend/components/TimedTextCreationFormConnected/TimedTextCreationFormConnected.ts, src/frontend/components/TimedTextListItem/TimedTextListItem.spec.tsx, src/frontend/components/TimedTextListItem/TimedTextListItem.tsx, src/frontend/components/TimedTextListItemConnected/TimedTextListItemConnected.ts, src/frontend/data/bootstrapStore.ts, src/frontend/data/rootReducer.ts, src/frontend/data/rootSaga.ts, src/frontend/data/sagas/getTimedTextTrackLanguageChoices/index.spec.ts, src/frontend/data/sagas/getTimedTextTrackLanguageChoices/index.ts, src/frontend/data/timedTextTrackLanguageChoices/action.ts, src/frontend/data/timedTextTrackLanguageChoices/reducer.spec.ts, src/frontend/data/timedTextTrackLanguageChoices/reducer.ts, src/frontend/types/LanguageChoice.ts
We want to manage language choices in redux store. Once in the store we
can connect every component using them. This will avoid multiple call to
the API for nothing.
Description...
=> ✨(frontend) add a saga to handle timed text tracks languages choices

src/frontend/components/VideoPlayer/VideoPlayer.spec.tsx, src/frontend/components/VideoPlayer/VideoPlayer.tsx
The player must start as fast as possible and show a thumbnail of the video.
Fix #241 
AWS craft thumbnails for us, we just have to use them as a video poster. The thumbnails seem to always be the first video frame.
=> ⚡️(player) use a poster to speed up player displaying

src/frontend/components/DashboardTimedTextManager/DashboardTimedTextManager.tsx, src/frontend/components/TimedTextCreationForm/TimedTextCreationForm.spec.tsx, src/frontend/components/TimedTextCreationForm/TimedTextCreationForm.tsx
Once a timed text track created, it is not possible to create an other
one with the same language. To avoid this mistake the language should not
be available in the language select box.
Fix #236 
For each mode we need to know every languages already created and them exclude them from the list of available languages.
=> 🐛(timedtexttrack) exclude existing language in language choices

src/frontend/components/VideoPlayer/VideoPlayer.spec.tsx, src/frontend/components/VideoPlayer/VideoPlayer.tsx, src/frontend/components/VideoPlayerConnected/VideoPlayerConnected.spec.tsx, src/frontend/components/VideoPlayerConnected/VideoPlayerConnected.tsx
We can display the language label instead of its code in the player
captions' list.
=> ✨(player) display language label in Plyr captions

src/backend/marsha/core/api.py, src/backend/marsha/core/tests/test_api_timed_text_track.py
As a student we need to access the OPTIONS endpoint to
retrieve all languages label.
=> 🐛(api) allow student to access metadata timedtexttrack's action

src/frontend/Player/createPlayer.spec.ts, src/frontend/Player/createPlayer.ts, src/frontend/Player/createPlyrPlayer.spec.ts, src/frontend/Player/createPlyrPlayer.ts, src/frontend/components/TranscriptReader/TranscriptReader.spec.tsx, src/frontend/components/TranscriptReader/TranscriptReader.tsx, src/frontend/components/TranscriptReaderConnected/TranscriptReaderConnected.tsx, src/frontend/components/TranscriptSentence/TranscriptSentence.spec.tsx, src/frontend/components/TranscriptSentence/TranscriptSentence.tsx, src/frontend/components/Transcripts/Transcripts.spec.tsx, src/frontend/components/Transcripts/Transcripts.tsx, src/frontend/components/TranscriptsConnected/TranscriptsConnected.tsx, src/frontend/components/VideoPlayer/VideoPlayer.spec.tsx, src/frontend/components/VideoPlayer/VideoPlayer.tsx, src/frontend/components/VideoPlayerConnected/VideoPlayerConnected.tsx, src/frontend/data/player/actions.ts, src/frontend/data/player/reducer.spec.ts, src/frontend/data/player/reducer.ts, src/frontend/data/rootReducer.ts, src/frontend/package.json, src/frontend/tsconfig.json, src/frontend/types/libs/vtt.js/index.d.ts, src/frontend/types/tracks.ts, src/frontend/yarn.lock
When transcripts are available, the user can select which one to use. Once selected we want to synchronize it with the video and highlight the text currently active.
Our transcript are WebVTT files. We found a library implementing the WebVTT spec in javascript. This lib can parse a file and manage every cues (a cue is a file's chunk).
Once a transcript parsed we just have to synchronize the cues with the video. We listen `timeupdate` from plyr player and we update a timer in the redux store.
=> Display transcript along the video.

CHANGELOG.md, src/aws/lambda-configure/package.json, src/aws/lambda-encode/package.json, src/aws/lambda-update-state/package.json, src/backend/setup.cfg, src/frontend/package.json
- Replace shaka-player by dashjs.
- Play timed text tracks in player.
- Enable timex text tracks in dashboard.
- Display transcripts along side video.
- Real languages display in the player (captions section).
- Language choices are fetch once and then cached in the redux store.
=> 🔖(chore) bump release to 2.3.0

src/aws/lambda-configure/package.json, src/aws/lambda-configure/yarn.lock, src/aws/lambda-encode/package.json, src/aws/lambda-encode/yarn.lock, src/aws/lambda-update-state/package.json, src/aws/lambda-update-state/yarn.lock
There is a security issue in version before 1.2.1 of merge
The CVE is available here https://nvd.nist.gov/vuln/detail/CVE-2018-16469
=> 📌(AWS) force merge version to at least version 1.2.1

CHANGELOG.md, src/aws/lambda-configure/package.json, src/aws/lambda-encode/package.json, src/aws/lambda-update-state/package.json, src/backend/setup.cfg, src/frontend/package.json
- Upgrade `merge` to version 1.2.1 in AWS lambda.
=> 🔖(chore) bump release to 2.3.1

src/frontend/components/VideoPlayer/VideoPlayer.spec.tsx, src/frontend/components/VideoPlayer/VideoPlayer.tsx, src/frontend/utils/isAbrSupported.ts
The `<VideoPlayer />` did not run a feature check before initializing dashjs. This caused an exception on iOS devices as they do not offer the MSE that dashjs relies on. There, ABR is supported through builtin HLS instead.
We can simply add a check for MSE and only load dashjs when they are available. iOS can then use HLS and other non-MSE-compatible browsers will just use MP4 sources.
We took this opportunity to stop loading MP4 sources when dashjs is enabled as loading the MP4 sources adds a UI to select video definition, which is always overridden by dashjs.
=> Add a feature check for MSE support before using DashJS in the player

.circleci/config.yml, Dockerfile, Makefile, docker/images/alpine/Dockerfile, src/frontend/package.json
Having compiling translation task inscluded in the yarn build task is confusing and circleci keep unwanted cache when build production step is executed. We want to split the translation and the build in two different steps and avoid having docker cache when the product image is built
=> Docker translation step

docker-compose.yml
Previous image used in the project does not exists anymore, it was
deleted by its owner. We built a new one available on the fundocker
account.
=> 🐛(crowdin) use fundocker image to run crowdin-cli

src/frontend/components/VideoPlayer/VideoPlayer.spec.tsx, src/frontend/components/VideoPlayer/VideoPlayer.tsx
iOS devices are supposed to manage Adaptive bitrate playback with the HLS spec natively. For a reason we have yet to uncover, we get errors as we try to play an HLS video (our current theory is that our manifest file and/or video fragments may be in a format iOS devices do not support).
We therefore removed HLS from the sources so iOS devices will just use regular old `.mp4` files.
We cannot be sure yet that this works as our development environments fail due to CORS issues (that do not exist on staging & production environments).
=> 💩(player) attempt to fix video playback on iOS devices

docker/compose/ci/docker-compose.yml
CI does not use our new fundocker/crowdin image so it fails to upload
translations when a branch is merged on master.
=> 🐛(crowdin) use fundocker/crowdin image in CI docker-compose

Dockerfile
To compile translated messages in the translation file, we need the
source extracted by babel-plugin-react-intl. To extract them we need to
build the project and to build the project we need a translation file...
So we fake an empty translation file and then do what we describe before
to have a valid build including translations.
=> 🐛(docker) change frontend build to fix translations

src/frontend/babel.config.js, src/frontend/package.json, src/frontend/yarn.lock
Babel-preset-env 7.4.0 can be used with core-js 3 and core-js 2. We have
to explicitly which version we want to use or we will have a warning
message when building the project. You can find more information here
https://github.com/zloirock/core-js/blob/master/docs/2019-03-19-core-js-3-babel-and-a-look-into-the-future.md#usebuiltins-usage-with-corejs-3
=> 🔧(front) use core-js 3 combined with babel-preset-env

CHANGELOG.md, UPGRADE.md, docs/env.md, env.d/ci, env.d/development.dist, env.d/test, src/aws/cloudfront.tf, src/backend/marsha/core/serializers.py, src/backend/marsha/core/storage.py, src/backend/marsha/settings.py, src/backend/setup.cfg
Two bugs prevented us from deploying the new feature of hosting static files on S3/CloudFront:
- django-storages incompatibility with ManifestStaticFilesStorage backend
- repeated protocol in the cloudfront urls computed by the static files storage backend (https://https://cloudfront-url)
- Downgrade django-storages to 1.6.3 which is the last version to work with ManifestStaticFilesStorage,
- Refactor CloudFront url setting to align on what django-storages is doing : one setting for protocol and one setting for domain.
=> Fix moving static files to s3

CHANGELOG.md, src/aws/lambda-configure/package.json, src/aws/lambda-encode/package.json, src/aws/lambda-update-state/package.json, src/backend/setup.cfg, src/frontend/package.json
- Upload a custom video thumbnail
- use S3 to store and Cloudfront to distribute static files
- Replace the `CLOUDFRONT_URL` setting by a `CLOUDFRONT_DOMAIN` setting to uniformize with what
django-storages is doing and share the same settings.
- Downgrade django-storages to 1.6.3, the last version compatible with ManifestStaticFilesStorage
=> 🔖(patch) bump release to 2.6.0

.circleci/config.yml
We need a way to remind us to update the project's `CHANGELOG` when we submitting a PR.
One may believe that this is another annoying task, but the experience we had with Arnold's repository shows that it drastically speeds up the release cycle since almost everything has already been prepared upfront.
You may have noticed that this job **is not required** to merge a PR since the `CHANGELOG` does not have to be updated for every submitted changes.
=> 👷(circleci) add check CHANGELOG job

docs/env.md
We recently refactor the Terraform project and removed an env file that was specific to the create state bucket project. Some references to this file were left out in documentation.
=> 📝(aws) remove reference to specific env file for create state bucket

CHANGELOG.md, src/backend/marsha/core/permissions.py, src/backend/marsha/core/tests/test_api_thumbnail.py, src/backend/marsha/core/tests/test_api_timed_text_track.py, src/backend/marsha/core/tests/test_api_video.py, src/backend/marsha/core/tests/test_views_lti_video.py, src/backend/marsha/core/views.py, src/frontend/components/InstructorView/InstructorView.spec.tsx, src/frontend/components/InstructorView/InstructorView.tsx, src/frontend/components/InstructorViewConnected/InstructorViewConnected.spec.tsx, src/frontend/components/InstructorViewConnected/InstructorViewConnected.tsx, src/frontend/data/context/reducer.spec.ts, src/frontend/data/context/reducer.ts, src/frontend/types/jwt.ts
A video can be portable and when an instructor sees it from another playlist it should not be possible to edit it. 
We introduce a new property in the JWT token allowing us to know if the instructor can edit or not a video. If he can't, the dashboard is disabled and the API is not accessible for him.
=> Deactivate video modification when the video is not in the original consumer site

.circleci/config.yml
We choose to migrate all jobs to docker executor. All jobs start instantly and we don't need anymore to cache and restore docker images.
~~I don't know if we have to keep the `build-dev` job, nothing use the image built in this job, we just ensure that the image used for development purpose is correctly build.~~ I decided to remove it. To develop we need to build it locally so if it fails it will not work anymore on our machine before pushing here.
=> ♻️ (circleci) Use docker environment executor to speed up tests

CHANGELOG.md, src/aws/lambda-configure/package.json, src/aws/lambda-encode/package.json, src/aws/lambda-update-state/package.json, src/backend/locale/es_ES/LC_MESSAGES/django.po, src/backend/locale/fr_CA/LC_MESSAGES/django.po, src/backend/locale/fr_FR/LC_MESSAGES/django.po, src/backend/setup.cfg, src/frontend/package.json, src/frontend/translations/es_ES.po, src/frontend/translations/fr_CA.po
- LRS credentials can be configured at the consumer site level.
- Configure in the consumer site admin panel if by default videos can show a download link.
- Do not allow video modification when the consumer site used is not the one used
to create the video.
=> bump version 2.7.0

CHANGELOG.md, src/aws/lambda-configure/package.json, src/aws/lambda-encode/package.json, src/aws/lambda-update-state/package.json, src/backend/setup.cfg, src/frontend/package.json
Fixed
- Correctly load static js chunks from cloud-front CDN
=> 🔖(patch) bump release to 2.7.1

CHANGELOG.md, src/backend/marsha/core/models/base.py, src/backend/marsha/core/serializers.py, src/backend/marsha/core/storage.py, src/backend/marsha/core/tests/test_admin_passport.py, src/backend/marsha/core/tests/test_api_thumbnail.py, src/backend/marsha/core/tests/test_api_timed_text_track.py, src/backend/marsha/core/tests/test_api_update_state.py, src/backend/marsha/core/tests/test_api_video.py, src/backend/marsha/core/tests/test_api_xapi_statement.py, src/backend/marsha/core/tests/test_lti.py, src/backend/marsha/core/tests/test_models_consumer_site.py, src/backend/marsha/core/tests/test_models_deletion.py, src/backend/marsha/core/tests/test_models_passport.py, src/backend/marsha/core/tests/test_models_playlist.py, src/backend/marsha/core/tests/test_models_timed_text_track.py, src/backend/marsha/core/tests/test_models_video.py, src/backend/marsha/core/tests/test_serializers_update_state.py, src/backend/marsha/core/tests/test_utils_time_utils.py, src/backend/marsha/core/tests/test_views_lti_video.py, src/backend/marsha/core/tests/test_views_openedx_lti_video.py, src/backend/marsha/core/xapi.py, src/backend/pylintrc
We want to have a similar pylint configuration between our django
projects. Most of the pylintrc file is copied here, some rules are kept:
argument-rgx, method-rgx, const-rgx
Description...
=> ♻️(backend) copy pylint config from richie project

CHANGELOG.md, src/aws/lambda-complete/package.json, src/aws/lambda-configure/package.json, src/aws/lambda-encode/package.json, src/backend/setup.cfg, src/frontend/package.json
- Automate python dependencies upgrade with pyup.
- Create command bin/pytest.
- Use pytest to run backend tests.
- Rename lambda-update-state lambda in lambda-complete.
- Keep only one docker-compose file.
- Move gitlint directory into lib directory.
- Upgrade to django 2.2
- Remove docker alpine images
- Standardize the project's `Makefile` to make it more easily maintainable by
our peers
- Copy pylint config from Richie project.
=> 🔖(patch) bump release to 2.8.0

CHANGELOG.md, src/backend/marsha/core/storage.py, src/backend/marsha/settings.py, src/backend/setup.cfg
Django-storages version we use has a security issue but it was
impossible to upgrade it because newer version are not compatible with
boto3. Hopefully a workarounf exists allowing us ti use newer versions.
The workaround can be fount in the issue reporting the bug:
https://github.com/jschneier/django-storages/issues/382#issuecomment-377174808
=> 🐛(backend) workaround allowing to use newer version of django-storages

CHANGELOG.md, src/frontend/Player/createPlyrPlayer.ts, src/frontend/components/VideoPlayer/index.spec.tsx, src/frontend/components/VideoPlayer/index.tsx
On firefox, if there is no video source the captions are not loaded. To
fix this issue we always add the source tags even if dashjs is used and
we don't need them.
=> 🐛(front) force to display captions on firefox

CHANGELOG.md, src/backend/marsha/settings.py
Heartbeat endpoint warns us that some settings are not well configured,
we have to set them in the settings:
- SECURE_BROWSER_XSS_FILTER
- SESSION_COOKIE_SECURE
- SECURE_CONTENT_TYPE_NOSNIFF
- CSRF_COOKIE_SECURE
Some settings are only changed in production, they will not work in
Development and Test:
- SECURE_SSL_REDIRECT
- SECURE_HSTS_SECONDS
We also disable check of X_FRAME_OPTIONS because we want to use the
value SAMEORIGIN, without this value it is not possible to serve the
site in a frame.
This PR will also closes #146
=> 🚨(backend) configure django core settings to pass all heartbeat checks

src/backend/marsha/settings.py
~~Django should not be responsible to apply SECURE_HSTS_SECONDS and
SECURE_HSTS_SECONDS rules. It should be the nginx or other reverse proxy
responsibility. The https connection will be made with it, not with
django.~~
In a first time this PR "harcoded" a list of silenced system checks. We finally choose to just allow to configure this setting freely using environment variable.
- ~~[x] Add SECURE_HSTS_SECONDS and SECURE_HSTS_SECONDS checks in SILENCED_SYSTEM_CHECKS list~~
=> ✨(backend) allow to configure SILENCED_SYSTEM_CHECKS setting

src/aws/lambda-encode/index.js, src/aws/lambda-encode/index.spec.js, src/aws/lambda-encode/src/copyDocument.js, src/aws/lambda-encode/src/copyDocument.spec.js
New `document` resource needs to be manage on AWS. We only need to copy it from the source to the destination bucket.
Note: we need to change this lambda name now.
=> manage document resource on AWS

CHANGELOG.md, src/backend/marsha/settings.py
In development we cannot use all secure cookie settings because we
don't use https certificate. These settings should be used only in
production.
=> 🐛(backend) use secure cookie only in production

CHANGELOG.md, src/frontend/Player/createPlyrPlayer.spec.ts, src/frontend/Player/createPlyrPlayer.ts, src/frontend/XAPI/XAPIStatement.spec.ts, src/frontend/XAPI/XAPIStatement.ts, src/frontend/types/XAPI.ts
As explained in #400, the `completed` event is not sent at the good time. While working on this fix, we noticed that the played segments were wrong and it was impossible to compute the progression, and thus, impossible to know when the video is completed.
Fixes #400
=> rework on xAPI played segments and completed event

CHANGELOG.md, src/frontend/XAPI/XAPIStatement.spec.ts, src/frontend/XAPI/XAPIStatement.ts
In some cases the time code sent in the last paused event, when the video
ended, can be higher than the duration sent by plyr itself. In this case
the progression is higher than 100% and if we return it the completed event
is not sent because the progression is not strictly equal to 100%.
=> 🐛(xAPI) be sure to send completed event when progress has reached 100%

CHANGELOG.md, src/frontend/Player/createPlyrPlayer.ts, src/frontend/XAPI/XAPIStatement.spec.ts, src/frontend/XAPI/XAPIStatement.ts
The terminated statement should be sent when a user leave the page
containing the played video. This statement will be also responsible to
send a paused statement if the video is still playing.
=> ✨(xAPI) send terminated statement when use leave the page

CHANGELOG.md, src/frontend/components/UploadForm/UploadForm.spec.tsx, src/frontend/components/UploadForm/UploadForm.tsx
When an upload is on going, this upload can be lost if the user leaves
the page. To be sure this is what he wants, we stop event
propagation in the beforeunload event and the browser will asks
confirmation to leave the page.
This PR closes #157
=> ✨(xAPI) prevent to lose an upload when a page is leaved

CHANGELOG.md, src/frontend/Player/createPlyrPlayer.ts, src/frontend/XAPI/XAPIStatement.spec.ts, src/frontend/XAPI/XAPIStatement.ts, src/frontend/types/XAPI.ts
There is a confusion in the video xapi documentation. In one place time
should be added in the interacted payload and in the summary it doesn't
appear. we think we should add it, it can be good to know at what time
the interaction was made.
=> 🐛(xAPI) add time in interacted xapi payload

CHANGELOG.md, src/frontend/components/InstructorView/InstructorView.spec.tsx, src/frontend/components/InstructorView/InstructorView.tsx
When an instructor view one of its video but in an other playlist the
`Go to dashboard` should be hide.
Closes #402
=> ♻️(front) hide dashboard button when a video is in read only

CHANGELOG.md, src/aws/bin/state, src/aws/bin/terraform
We must pin the terraform version we use to version 0.11.14. There are
breaking changes in version 0.12 and we have to do a migration. Moreover,
we also need to migrate the AWS version which also contains breaking
changes. In a first time we will use a version we know and compatible
with our existing configuration, workspaces and states.
Description...
=> 📌(AWS) pin terraform to version 0.11.14

CHANGELOG.md, src/backend/marsha/core/admin.py
When adding this field on the model, we forgot to add it to the admin view. In some cases, it is convenient to be able to modify this flag directly from the admin.
Add the `show_download` field of the:
=> 🚸(video) add the `show_download` flag to the video admin view

CHANGELOG.md, src/frontend/components/VideoPlayer/index.spec.tsx, src/frontend/components/VideoPlayer/index.tsx, src/frontend/utils/isAbrSupported.ts
We have file to be used by iOS base on the HLS spec but we remove them
in version 2.5.0. We noticed that when both HLS and mp4 are used, the
ios player will not used the HLS file. Here we only used the HLS file if
the browser can play it, we use mp4 file otherwise.
=> 🚧(front) reactivate HLS support

CHANGELOG.md, src/frontend/yarn.lock
Versions of handlebars and lodash packages we rely on as transitive dependencies expose security vulnerabilities as notified by GitHub.
By updating the lockfile we get to use more recent, safe versions.
=> 🔒(frontend) update yarn.lock to use secure dependencies

CHANGELOG.md, src/frontend/data/sideEffects/upload/index.ts
The Dashboard video pane component is supposed to poll the video until it is ready, when it renders a non-ready video. 
This was not happening when uploading a new video to replace an existing, ready one, because the dashboard was first called with outdated data pertaining to the ready video.
We just had to move around the redirection to the dashboard video pane when the user picks the replacement video, to make sure it happens after the video object has been updated to its new state.
=> 🐛(frontend) fix an issue with video polling

CHANGELOG.md, src/frontend/Player/createPlyrPlayer.ts
By default plyr has seek time configured to 10 seconds when you use
keyboard shorcuts. This time is too long and we decided to set it to 5
seconds like on youtube.
=> ♻️(front) shorten plyr seek time

src/frontend/__mocks__/react-intl.tsx, src/frontend/components/InstructorView/index.spec.tsx, src/frontend/components/InstructorView/index.tsx
In InstructorView component, the message display when a video is read
only is too long and too complicated. We choose to replace to a
reference to the context_id the video belong to.
There was also a problem with the react-intl mock. It was needed to improve it a little bit. We should definitely remove it when possible.
Closes #465
=> ♻️(front) change message in <InstructorView /> when a video is read only

CHANGELOG.md, src/frontend/Player/createPlyrPlayer.ts, src/frontend/components/TranscriptSentence/index.spec.tsx, src/frontend/components/TranscriptSentence/index.tsx, src/frontend/data/stores/useTranscriptTimeSelector/index.tsx
A user can click on a word when the transcript is shown and then the
video will seek to the start time of the selected cue.
Using a zustand will help us to be in sync between the `TranscriptSentence` component and the plyr player. When the store is updated, the player can be updated once it has subscribed to the same store.
closes #406
=> ✨(front) seek to the cue's start time when a user click on it

CHANGELOG.md, src/aws/lambda-complete/package.json, src/aws/lambda-configure/package.json, src/aws/lambda-encode/package.json, src/backend/setup.cfg, src/frontend/package.json
- Add the `show_download` flag to the video admin view.
- Translate plyr interface.
- Seek the video to the time corresponding to a transcript sentence
when a user click on it.
- Hide dashboard button in instructor view when a video is in read only.
- Reactivate HLS support.
- Only one play button in the plyr is active for a screen reader.
- Remove usage of react-redux
- Change seek time to 5 seconds in plyr configuration.
- Fix an issue that prevented replacement videos from being shown as "ready"
in the dashboard.
- Add time in interacted xapi payload.
- Pin Terraform to version 0.11.14.
- Change arial-label on play button when its state changes.
- Update `handlebars` and `lodash` packages to safe versions.
=> 🔖(minor) bump release to 2.10.0

CHANGELOG.md, src/frontend/data/stores/useThumbnail/index.spec.tsx, src/frontend/data/stores/useThumbnail/index.tsx
The method useThumbnail.getThumbnail() was not returning null when there
was no thumbnail but undefined and this is not what we want. We want to
return null. A test is added to be sure that null is really return.
=> 🐛(front) ensure useThumbnail return null when there is no thumbnail

CHANGELOG.md, src/frontend/data/stores/actions.ts, src/frontend/data/stores/useTimedTextTrack/index.spec.tsx
When we remove a resource in a zustand store using the removeResource,
the undefind value is kept and return when doing a Object.values in
useTimedTextTrack store for example and leed on to unwanted behaviour.
=> 🐛(front) remove undefined values in stores when removing resource

CHANGELOG.md, src/backend/marsha/core/models/file.py, src/backend/marsha/core/models/video.py, src/backend/marsha/core/tests/test_api_thumbnail.py, src/backend/marsha/core/views.py, src/backend/marsha/urls.py, src/frontend/components/DashboardThumbnail/index.spec.tsx, src/frontend/components/DashboardThumbnail/index.tsx, src/frontend/components/UploadForm/index.tsx, src/frontend/data/sideEffects/createThumbnail/index.spec.ts, src/frontend/data/sideEffects/createThumbnail/index.ts, src/frontend/data/sideEffects/upload/index.spec.ts, src/frontend/data/sideEffects/upload/index.ts, src/frontend/data/stores/actions.spec.ts, src/frontend/data/stores/generics.spec.ts, src/frontend/data/stores/generics.ts, src/frontend/data/stores/useThumbnail/index.spec.tsx, src/frontend/data/stores/useThumbnail/index.tsx, src/frontend/types/models.ts, src/frontend/types/stores.ts
The resource name put in the lti view does not come from a reliable
model property. We decided to create a dedicated one and use it also to
manage urls. The same resource name is used in the front application.
=> ♻️(resources) share same resource name between front and back

CHANGELOG.md, src/aws/lambda-complete/yarn.lock, src/aws/lambda-configure/yarn.lock, src/aws/lambda-encode/yarn.lock, src/frontend/data/sideEffects/getResourceList/index.spec.tsx, src/frontend/data/sideEffects/getResourceList/index.ts, src/frontend/yarn.lock
Regenerate the lockfile to ensure only versions >= 2.0.1 of `set-value `and versions >= 1.3.2 of `mixin-deep` (safe versions) are used.
Closes #494.
Closes #495.
Closes #496.
=> 🔒(dependencies) bump set-value and mixin-deep to safe versions

CHANGELOG.md, src/backend/marsha/core/lti/__init__.py, src/backend/marsha/core/templates/core/lti.html, src/backend/marsha/core/tests/test_views_lti_document.py, src/backend/marsha/core/tests/test_views_lti_video.py, src/backend/marsha/core/views.py, src/frontend/Player/createPlayer.spec.ts, src/frontend/Player/createPlyrPlayer.spec.ts, src/frontend/Player/createPlyrPlayer.ts, src/frontend/components/DashboardTimedTextManager/index.spec.tsx, src/frontend/components/DashboardTimedTextPane/index.spec.tsx, src/frontend/components/DashboardVideoPaneDownloadOption/index.spec.tsx, src/frontend/components/InstructorWrapper/index.spec.tsx, src/frontend/components/InstructorWrapper/index.tsx, src/frontend/components/RedirectOnLoad/index.spec.tsx, src/frontend/components/RedirectOnLoad/index.tsx, src/frontend/components/TimedTextListItem/index.spec.tsx, src/frontend/components/Transcripts/index.spec.tsx, src/frontend/data/appData.ts, src/frontend/data/stores/generics.spec.ts, src/frontend/index.tsx, src/frontend/types/AppData.ts, src/frontend/utils/parseDataElements/parseDataElements.spec.ts, src/frontend/utils/parseDataElements/parseDataElements.ts
Since we have several roles having the same permissions rules it is not relevant anymore in the front application to rely on them. To have less complexity, we want to know if the user can edit the resource.
Do not expose the role in the state, add a new boolean property to know if the user can edit the resource.
=> do not expose the user role anymore but if he can edit the resource

src/frontend/components/DashboardTimedTextPane/index.spec.tsx, src/frontend/components/DashboardVideoPane/index.spec.tsx, src/frontend/components/DashboardVideoPane/index.tsx, src/frontend/components/UploadForm/index.spec.tsx
There were some error messages in tests output. Most of them are logged by the `report` function. Now the ouput does not looks like a Christmas tree anymore.
=> Remove error message in tests output

src/frontend/components/AppRoutes/index.tsx, src/frontend/components/DashboardDocument/index.tsx, src/frontend/components/DashboardPaneButtons/index.spec.tsx, src/frontend/components/DashboardPaneButtons/index.tsx, src/frontend/components/DashboardVideoPane/index.tsx, src/frontend/components/DocumentPlayer/route.ts, src/frontend/components/RedirectOnLoad/index.spec.tsx, src/frontend/components/RedirectOnLoad/index.tsx, src/frontend/components/VideoPlayer/route.ts, src/frontend/components/routes.ts, src/frontend/types/AppData.ts
It is redundant to declare a route for each player. They can have only
one specifying the resource targeted.
=> ♻️(front) create only one route to manage all players

src/aws/cloudfront.tf, src/frontend/components/DashboardThumbnail/index.tsx
Our default cloudfront rule is "not" secure as it does not force to use
signed url. If a rule need to disable signed url we will explicitly
create one like we did for thumbnails
=> default cloudfront rule must accept signed urls

CHANGELOG.md, src/aws/cloudfront.tf, src/aws/lambda-encode/src/copyDocument.js, src/aws/lambda-encode/src/copyDocument.spec.js, src/backend/marsha/core/serializers.py, src/backend/marsha/core/tests/test_api_document.py
The url for documents was missing in the cloudfront documentation and we used the default behaviour. We must add one for document forcing to sign the url
=> manage documents url in cloudfront configuration

CHANGELOG.md, docker/files/usr/local/etc/gunicorn/marsha.py
The Gunicorn configuration we have is an example of how to configure Gunicorn when running Marsha in a container. We discovered that the number of workers and threads must be increased when Gunicorn is used in a container and the `tmpdir` used by workers should use a filesystem mounted in memory instead of a filesystem [1].
[1] https://pythonspeed.com/articles/gunicorn-in-docker/
- increase the number of threads
- change the worker class to use `gthread`
- change worker tmpdir
=> ✨(gunicorn) configure worker and threads

CHANGELOG.md, src/aws/lambda-encode/package.json, src/aws/lambda-encode/yarn.lock
A new release of @openfun/substr containing a patch we want is
available. We upgraded it in lambda-encode project.
Patched version parses most of srt files (a critical feature for us).
=> ⬆️(dependencies) update @openfun/substr in lambda-encode

src/backend/marsha/core/tests/test_views_lti_video.py, src/backend/marsha/core/views.py, src/frontend/types/jwt.ts
The `video_id` parameter in the JWT token was replaced by `resource_id` when more resources were added. At the time, we forgot to remove it although it is not being used anymore.
=> 🔥(permissions) remove outdated video_id parameter from JWT token

CHANGELOG.md, src/backend/marsha/core/lti/__init__.py, src/backend/marsha/core/permissions.py, src/backend/marsha/core/tests/test_api_document.py, src/backend/marsha/core/tests/test_api_thumbnail.py, src/backend/marsha/core/tests/test_api_timed_text_track.py, src/backend/marsha/core/tests/test_api_video.py, src/backend/marsha/core/tests/test_views_lti_document.py, src/backend/marsha/core/tests/test_views_lti_video.py, src/backend/marsha/core/views.py
The "IsReadable" flag was passed in `app_data` and "read_only" flag was passed in the JWT token.
We propose to move all permission flags to the JWT token so they are available in the form to the frontend and to the API backend.
=> ♻️(permissions) group all permissions in the JWT token

src/backend/marsha/core/lti/__init__.py, src/backend/marsha/core/tests/test_views_lti_video.py
When bypassing LTI verification, we need to create the consumer site on the fly. The consumer site domain was taken from the lti request in a convoluted way.
Take the consumer site domain from the HTTP referer as this is what we use when actually validating the LTI request.
=> ♻️(lti) refactor consumer site domain check in bypass requests

.circleci/config.yml, CHANGELOG.md
The circle-ci job uploading translations on crowdin is failing since few
days because there is an issue with the tar version used in our crowdin
image. We think it's a circle-ci regression, they remove the fallback on
their tools to use the good tar commad. We decided to add tar in our
crowdin image and to use it in our i18n job.
=> ⬆️ (circle) upgrade crowdin image version

CHANGELOG.md, src/backend/marsha/core/lti/__init__.py, src/backend/marsha/core/lti/utils.py, src/backend/marsha/core/tests/test_lti.py, src/backend/marsha/core/tests/test_lti_utils.py, src/backend/marsha/core/tests/test_views_lti_cache.py, src/backend/marsha/core/tests/test_views_lti_document.py, src/backend/marsha/core/tests/test_views_lti_video.py, src/backend/marsha/core/views.py, src/backend/marsha/settings.py
We need to make sure that Marsha can scale to very heavy loads. In particular, we have noticed that signing the CloudFront urls is compute intensive. 
I propose to focus on caching the result of LTI views for student because this is were all the load comes from.
The cache duration is set to 10 seconds. This ensures that we cut the load and at the same time:
- don't impact the freshness of data served to students,
- avoid building a complicated and bug prone cache invalidation machinery,
- don't impact the validity of CloudFront urls (10 seconds is negligible compared to the validity of our signed urls).
=> ⚡️(lti) cache database queries and serialization in LTI views

src/frontend/components/TimedTextListItem/index.spec.tsx, src/frontend/components/TimedTextListItem/index.tsx, src/frontend/data/sideEffects/pollForTrack/index.tsx
When a timed text track was already in READY state and is_ready_to_show
set to true, it was blocked in pending state if we use the replace
feature. The issue is in the useEffect of TimedTextListItem component,
we start polling only when the is_ready_to_show property was equal to
false. Doing like this is wrong, we have to check the updload state and
start polling when the state is pending, uploading and processing.
=> 🐛(front) change how we poll timed text track when we replace them

src/backend/marsha/core/tests/test_views_lti_development.py, src/backend/marsha/core/tests/test_views_lti_document.py, src/backend/marsha/core/tests/test_views_lti_video.py, src/backend/marsha/core/views.py, src/backend/marsha/urls.py
We usually name our test methods by the name of the module they are testing, from the most generic to the most specific. It allows to target tests with the desired granularity via pytest's `-k` flag.
This was materialized in FUN's handbook: https://openfun.gitbooks.io/handbook/content/python.html#test-files
While working on the lti views I noticed that some names were not following this practice.
=> ♻️(project) rename test methods and view class as per handbook guideline

docs/env.md, src/backend/marsha/settings.py
A lot of different unique resources are requested via the LTI views, so 10 seconds is not enough to efficiently cache requests. 
We think a 60 seconds delay before a student sees modifications made by an instructor does not impact user experience. So we propose to bump the application data cache duration to 60 seconds.
While doing this, I realized that we forgot to add the `APP_DATA_CACHE_DURATION` setting to our environment variables documentation.
=> Bump application data cache duration to 60 seconds

src/frontend/components/InstructorView/index.spec.tsx, src/frontend/components/InstructorView/index.tsx, src/frontend/components/InstructorWrapper/index.spec.tsx, src/frontend/components/InstructorWrapper/index.tsx, src/frontend/components/RedirectOnLoad/index.spec.tsx, src/frontend/components/RedirectOnLoad/index.tsx, src/frontend/types/AppData.ts, src/frontend/types/jwt.ts
A new object permissions is in the JWT token, it replaces the property
read_only from the JWT token and isEditable from AppData. read_only is
replaced by can_access_dashboard and isEditable by can_update.
=> ♻️(front) group all permissions in the JWT token

src/frontend/components/DashboardDocument/index.spec.tsx, src/frontend/components/DashboardDocument/index.tsx, src/frontend/components/DashboardDocumentTitleForm/index.spec.tsx, src/frontend/components/DashboardDocumentTitleForm/index.tsx
Maintaining the title state in the DashboardDocument was not easy and
has unwanted behaviour like updating the form input once already render.
We choose to create a dedicated component, rendered only when the
document is in ready state. The document's title should not be updated
anymore at this step and we should not have unwanted behaviour anymore.
=> ♻️(front) create a dedicated component to manage document title form

src/backend/marsha/core/views.py, src/frontend/public-path.js
In commit #d9c3fd5 we decided to rely on the CLOUDFRONT_DOMAIN setting to
determine which staticfiles_storage is used and then use the `url`
method to compute a base url. In local this work fine but we use the s3
storage class it doesn't work anymore because the hack used to have the
url without filename does not work. To fix this, we want the js folder
path, we know it always exists and it is exactly the path we want in
front application. So we compute the url for the js folder and we don't
have to append /js at the end of the base url in the front application.
We can use the value in meta name public-path directly.
=> ♻️(statics) change how static base url is computed

src/backend/marsha/core/tests/test_views_lti_video.py, src/backend/marsha/core/views.py, src/backend/marsha/settings.py
In order to compute the static base url we choose to create a new
setting ABSOLUTE_STATIC_URL instead of relying on the staticfiles_storage
class. This settings is computed and can not be overriden with an
environment variable. In production we compute it using the
CLOUDFRONT_DOMAIN.
=> ✨(back) introduce a new setting ABSOLUTE_STATIC_URL

.circleci/config.yml
We use in our Dockerfile a base image based on python 3.7 but we missed
to change the python version used in our CI. In the circle-ci
configuration file we must change the images used to python 3.7
=> 🔧(circleci) migrate image to python 3.7

src/frontend/components/InstructorView/index.spec.tsx, src/frontend/components/InstructorView/index.tsx
We change how permissions are handle. We migrate everything in the JWT
token creating a persmissions object. We made a mistake using the
can_access_dashboard property. We simply rename the old permission name
without changing it's behaviour and we invert the wanted behaviour.
=> 🐛(front) fix bad usage of permissions.can_access_dashboard from JWT

README.md
Adding a link to the wikipedia page for LTI as the abbreviation might not be
known to laymen.
It's not clear for everybody what LTI stands for.
Explicit what LTI is by adding a link to its wikipedia page.
Fixes #544
=> 📝(readme) add a link to the wikipedia page for LTI

.circleci/config.yml, CHANGELOG.md, src/aws/Makefile, src/aws/lambda-complete/package.json, src/aws/lambda-configure/package.json, src/aws/lambda-encode/package.json, src/aws/lambda.tf, src/aws/state.tf
It is now possible to use node version 10 for lambda functions. We are
interested to upgrade the engine version used, this will allow us to use
new features introduce in node 10 and moreover node 10 is the current
LTS version.
=> ✨(AWS) upgrade lambdas to use node 10

CHANGELOG.md, src/aws/lambda-migrate/index.js, src/aws/lambda-migrate/index.spec.js, src/aws/lambda-migrate/src/migrations/0001_encode_timed_text_tracks.js, src/aws/lambda-migrate/src/migrations/0001_encode_timed_text_tracks.spec.js, src/aws/lambda.tf, src/aws/roles.tf
There are some issues on the timed text tracks migration script executed in the lambda-migrate function. Not using async-handler lead to hide important errors. The first one is calling the `lambda.InvokeAsync` does not provide error messages when the lambda is executed... and in fact our permissions does not allow to invoke a lambda...
The second is how pagination is made on the `S3.listObject` method. I didn't understand how the `NextMarker` in the response is set and in our case it leads to an infinite loop. To avoid this I switched to the `S3.listObjectV2` method where they totally changed how pagination is made and it is no longer confusing at all.
=> Fix lambda-migrate issues

CHANGELOG.md, src/backend/marsha/core/lti/__init__.py, src/backend/marsha/core/tests/test_lti.py
In the LTI.verify method we check if the referer matches the
URL for the consumer_site associated with the passport. In some cases
users block the referer for privacy concern and we can not do the check
and an error is raised. To avoid this error we choose to not verify the
domain if the referer is absent.
- allow to make LTI request without HTTP referer
=> 🐛(back) ignore domain check if http referer is missing

CHANGELOG.md, src/frontend/index.tsx, src/frontend/package.json, src/frontend/yarn.lock
Some browsers have not implement the Intl API. For them we have to install a polyfill and use it only if the native API is not implemented.
=> Polyfill Intl API is not implemented

src/frontend/index.tsx, src/frontend/package.json, src/frontend/types/libs/custom-event-polyfill/index.d.ts, src/frontend/yarn.lock
Plyr uses CustomEvents as specified in the browser API spec. This is not available in IE11, which we intend to support; to have any tracking available for IE11 users, and avoid piles of error reports.
Add a polyfill and lazy-load it only when necessary
=> 🏁(frontent) polyfill CustomEvents for IE11

src/frontend/Player/createPlyrPlayer.ts
Our own Plyr's listeners are declared in the same module we instantiate
Plyr. We can directly use the instance instead of relying on event
object to retrieve Plyr instance. This should avoid errors with missing
information in the event object.
Fixes #567
=> 🐛(front) use plyr instance directly in event listeners

CHANGELOG.md, src/frontend/index.tsx
To know if Intl is present, simply testing Intl variable is not a good
solution, we still have the same error saying can't find variable Intl.
To test it, we should test if global.Intl is not undefined, if it is we
must import the Intl polyfill.
=> 🐛(front) test if Intl exists using global object

CHANGELOG.md, src/backend/marsha/core/serializers.py, src/backend/marsha/core/tests/test_api_xapi_statement.py, src/backend/marsha/core/tests/test_serializers_xapi_statement.py, src/backend/marsha/core/tests/test_xapi.py, src/backend/marsha/core/xapi.py, src/frontend/XAPI/XAPIStatement.spec.ts, src/frontend/XAPI/XAPIStatement.ts
When a statement is sent, the front application sets in its payload the timestamp statement, so we use the client timestamp. In some cases this timestamp is not relevant at all, it can be configured in the future or in the past...
Fixes #536
=> Xapi timestamp

CHANGELOG.md, src/aws/lambda-complete/package.json, src/aws/lambda-configure/package.json, src/aws/lambda-encode/package.json, src/aws/lambda-migrate/package.json, src/backend/setup.cfg, src/frontend/package.json
- Host plyr's icons SVG on Marsha's infrastructure.
- Correctly load Intl polyfill
- XAPI timestamp is set in the backend.
=> 🔖(patch) bump release to 3.1.3

CHANGELOG.md, src/aws/lambda-encode/index.js, src/aws/lambda-encode/index.spec.js, src/aws/lambda-encode/src/encodeTimedTextTrack.js, src/aws/lambda-encode/src/encodeTimedTextTrack.spec.js
Firefox does not interpret html entities present in captions or
subtitles. We choose to only encode them in transcript and do nothing
for subtitles and captions, plyr handle them correctly.
The existing migration can be run again to fix the issue.
Description...
=> 🐛(AWS) encode only transcripts and simply convert others

CHANGELOG.md, src/aws/lambda-complete/package.json, src/aws/lambda-configure/package.json, src/aws/lambda-encode/package.json, src/aws/lambda-migrate/package.json, src/backend/setup.cfg, src/frontend/package.json
- Firefox does not interpret html entities in subtitles. Only transcripts
are encoded.
=> 🔖(patch) bump release to 3.1.4

.circleci/config.yml, Makefile, docker-compose.yml, docker/images/dev/Dockerfile
A dockerize image exists and we choose to use it as a service in
our docker-compose configuration. Not having dockerize installed in the
development image will lighten it a little bit and speed its build.
Closes #546
=> ♻️(recycle) remove dockerize in dev image

CHANGELOG.md, src/frontend/Player/createPlyrPlayer.spec.ts, src/frontend/Player/createPlyrPlayer.ts, src/frontend/utils/isAbrSupported.ts
When browser does not support ABR, user should be able to choose the
video quality. It wasn't possible because video sources where not in the
DOM when plyr is instantiated. The only way to have them is to recreate
sources (video source and timed text track) and inject them in plyr
instance.
Fixes #593
=> 🐛(front) choose video quality when ABR is not available

CHANGELOG.md, src/frontend/Player/createPlyrPlayer.spec.ts, src/frontend/Player/createPlyrPlayer.ts, src/frontend/XAPI/XAPIStatement.spec.ts, src/frontend/XAPI/XAPIStatement.ts
In some cases fetching all video data can take more time than expected
and some data are missing in the canplay event. Do be sure to have all
needed data we have to use others events (loadedmetadata and loadeddata)
and initialize the module only when the data are avaialble in one of
this 3 events.
Fixes #573
=> 🐛(xapi) initliaze xapi module only when all video data are available

src/frontend/Player/createPlyrPlayer.spec.ts, src/frontend/Player/createPlyrPlayer.ts
In commit fe357 we set plyr sources if ABR is not available but not when
hls is also not available. The consequence is that hls is no more used
when available in favor of mp4 sources. A fix is to set the sources when
ABR and HLS are not available.
=> 🐛(front) set plyr sources also if hls is not available

CHANGELOG.md, src/aws/lambda-complete/package.json, src/aws/lambda-configure/package.json, src/aws/lambda-encode/package.json, src/aws/lambda-migrate/package.json, src/backend/setup.cfg, src/frontend/package.json
Fixed
- Start ABR at a lower level corresponding to 480p
- Let the user choose video quality when ABR is disabled
- Initialize xapi module only when all video data are available
=> 🔖(patch) bump release to 3.1.7

CHANGELOG.md, docs/env.md, src/backend/marsha/core/templates/core/lti.html, src/backend/marsha/core/tests/test_views_lti_video.py, src/backend/marsha/core/views.py, src/backend/marsha/settings.py, src/frontend/components/VideoPlayer/index.tsx
We want to use third party js and not commit them in the project because they are only used by a particular marsha client and it makes no sense to add them in marsha. The idea here is add js script in the LTI template usinga django setting. This settin can accept a comma separated list of url
example:
```
DJANGO_EXTERNAL_JAVASCRIPT_SCRIPTS=https://unpkg.com/@ungap/url-search-params@0.1.2/min.js,https://example.com/demo.js"
```
With this example, two script tags will added to the lti template.
=> Allow to load external js sources in LTI template

CHANGELOG.md, src/aws/lambda-configure/presets/cmaf_video_h264_1080p_30fps_5400kbps.json, src/aws/lambda-configure/presets/cmaf_video_h264_144p_30fps_300kbps.json, src/aws/lambda-configure/presets/cmaf_video_h264_240p_30fps_600kbps.json, src/aws/lambda-configure/presets/cmaf_video_h264_480p_30fps_1200kbps.json, src/aws/lambda-configure/presets/cmaf_video_h264_720p_30fps_2400kbps.json, src/aws/lambda-configure/presets/video_mp4_h264_1080p_30fps_5400kbps.json, src/aws/lambda-configure/presets/video_mp4_h264_144p_30fps_300kbps.json, src/aws/lambda-configure/presets/video_mp4_h264_240p_30fps_600kbps.json, src/aws/lambda-configure/presets/video_mp4_h264_480p_30fps_1200kbps.json, src/aws/lambda-configure/presets/video_mp4_h264_720p_30fps_2400kbps.json, src/frontend/components/VideoPlayer/VideoPlayer.css
All our video presets for AWS MediaConvert, which control the way in which videos are encoded to all the formats we need in Marsha, included the "STRETH_TO_OUTPUT" option.
This is not what we want (we'd rather have black bars than distorted output for eg. 4/3 videos) and was only there due to the files we used as boilerplates to bootstrap our MediaConvert presets.
We can just remove the `ScalingBehavior` param entirely as it's optional.
=> 🐛(encoding) remove STRETCH_TO_OUTPUT option from MediaConvert presets

CHANGELOG.md, src/frontend/yarn.lock
GitHub pushed a security advisory for one of our transitive dependencies.
We can fix it by regenerating the lockfile, which will pick up a new version of the relevant dependency (`serialize-javascript`).`
=> 🔒(frontend) regenerate yarn.lock to fix security issue

CHANGELOG.md, src/backend/marsha/core/storage.py, src/backend/setup.cfg
Django-storages 1.8 came out and fixes a bug that we solved with a workaround. See PR https://github.com/openfun/marsha/pull/387
The bug was fixed in `django-storages` 1.7.2 as detailed in their [CHANGELOG](https://github.com/jschneier/django-storages/blob/master/CHANGELOG.rst).
I bumped the version of `django-storages` to 1.8.
I then removed the workaround introduced in commit 6e7ee9b that was making `django-storages` 1.7.1 work with Django's `ManifestStaticFilesStorage` backend.
=> ⬆️(storage) bump django-storages to v1.8

CHANGELOG.md, src/backend/marsha/core/views.py, src/backend/marsha/settings.py, src/frontend/components/InstructorView/index.spec.tsx, src/frontend/components/InstructorView/index.tsx, src/frontend/types/jwt.ts
Create a setting in the back application to put Marsha in maintenance mode. Once in maintenance mode, the dashboard is not accessible
=> Maintenance mode

CHANGELOG.md, src/aws/lambda-complete/package.json, src/aws/lambda-configure/package.json, src/aws/lambda-encode/package.json, src/aws/lambda-migrate/package.json, src/backend/setup.cfg, src/frontend/package.json
- New setting MAINTENANCE_MODE to disable the dashboard when Marsha is
in maintenance
- Upgrade django-storages to 1.8 and remove the workaround introduced in
marsha 2.8.1 to ensure compatibility with ManifestStaticFilesStorage.
- Regenerate frontend yarn lockfile to get new version of vulnerable package
`serialize-javascript`.
=> 🔖(minor) bump release to 3.3.0

.dockerignore
Some directories to ignore were missing in `.dockerignore` file. `venv` and
`node_modules` were not ignored recursively resulting in a very big
image built locally. Also `src/aws` is ignored, we don't use it through
the docker image but directly deploy on AWS using terraform.
=> 🐳(build) enhance .dockerignore file

.dockerignore
We ignored all statics in marsha backend. This is a mistake, only js
folder should be ignored.
=> 🐛(statics) ignore only js statics in .dockerignore

CHANGELOG.md, src/backend/marsha/settings.py, src/backend/setup.cfg
Our code base is compatible with Django 3. We only need to upgrade
`django-safedelete` to a recent version to be compatible with Django 3.
=> ⬆️ (backend) upgrade to Django 3

.circleci/config.yml, CHANGELOG.md, Dockerfile, src/backend/setup.cfg
Python 3.8 is available since several months, it's time for us to use it in Marsha.
=> upgrade to python 3.8

CHANGELOG.md, src/backend/marsha/settings.py
Django 3.0 introduces a new setting `SECURE_REFERRER_POLICY` in its
`SecurityMiddleware`. There is no value by default but heartbeat requires
to set one in production. We only need the referer for the admin module
so we choose to use `same-origin`, this is the the value recommended by
the documentation to prevent CSRF issues:
https://docs.djangoproject.com/en/3.0/ref/middleware/#referrer-policy
=> 🐛(back) set SECURE_REFERRER_POLICY setting to same-origin

CHANGELOG.md, src/frontend/Player/createPlyrPlayer.ts
We have a regression on the thumbnail display feature. Before we forced
the frame code to 0 on the first seeked event because it happened before
the initialize event. We changed how the initialize event is caught and it
can happen now before the first seeked event. To fix this we have to
check in the initialized event itself if we have to reset the
`currentTime` property.
=> 🐛(front) force to display thumbnail while the video is not played

src/backend/setup.cfg
It is impossible to deploy statics on AWS with django-storages 1.9.0 we
must upgrade it to version 1.9.1 which contains a fix for AWS.
Description...
=> ⬆️(back) upgrade django-storages to version 1.9.1

CHANGELOG.md, src/frontend/Player/createDashPlayer.spec.ts, src/frontend/Player/createDashPlayer.ts, src/frontend/Player/createPlyrPlayer.spec.ts, src/frontend/Player/createPlyrPlayer.ts, src/frontend/components/DashboardThumbnailDisplay/index.tsx, src/frontend/components/VideoPlayer/index.tsx, src/frontend/types/XAPI.ts, src/frontend/types/libs/plyr/index.d.ts, src/frontend/types/tracks.ts
Our user would like to choose the video quality and not let ABR decide
for them which one to use. But the main issue we had was the incompatibility
between plyr quality selector and dashjs. We found that plyr allow to
completely override the selector behaviour. The way we override it let
us change dashjs settings by setting the max bitrate the player can
choose, we don't rely anymore on plyr behaviour.
ABR is still working, if bandwith go down the player will choose a lower quality but it will not be able to upscale it as he want, it will be stop by the value we set in the settings.
Closes #589
=> ✨(front) allow to change video quality while using ABR

src/aws/lambda-complete/yarn.lock, src/aws/lambda-configure/yarn.lock, src/aws/lambda-encode/yarn.lock, src/aws/lambda-migrate/yarn.lock, src/frontend/yarn.lock
Bumps [acorn](https://github.com/acornjs/acorn) to version 6.4.1.
- [Release notes](https://github.com/acornjs/acorn/releases)
=> ⬆️ (front) Bump acorn to version 6.4.1

LICENSE
Without copyright holder, the project license is broken.
=> 📄(project) add missing license copyright holder

CHANGELOG.md, src/backend/marsha/core/api.py, src/backend/marsha/core/lti/__init__.py, src/backend/marsha/core/tests/test_api_xapi_statement.py, src/backend/marsha/core/tests/test_xapi.py, src/backend/marsha/core/xapi.py, src/backend/marsha/settings.py, src/backend/setup.cfg
We want to log xapi statement in a logger and also to configure a logger
by consumer site. We use for that a special logger name convention,
prefixing the domain name byt `xapi.`. For example for the consumer
site with domaine name foo.education you have to create a logger name
`xapi.foo.education` and configure as you want the associated handler
and formatter depending where you want to log the statements.
=> ✨(back) register xapi statement in a logger

CHANGELOG.md, src/backend/marsha/core/lti/__init__.py, src/backend/marsha/core/tests/test_lti.py
Some browsers, like Brave, [replace referer header value by the referred-to and not the referred-from value][1]. In this case the referred-to value will match value added in the ALLOWED_HOSTS setting and in this case we choose to trust this domain as a valid passport domain name.
[1]: https://bit.ly/35CvPXa
=> 🐛(backend) referer can match ALLOWED_HOSTS as a valid passport

CHANGELOG.md, src/aws/lambda-complete/package.json, src/aws/lambda-configure/package.json, src/aws/lambda-encode/package.json, src/aws/lambda-migrate/package.json, src/backend/setup.cfg, src/frontend/package.json
- Referer can match ALLOWED_HOSTS as a valid passport domain name
=> 🔖(patch) bump release to 3.7.1

src/backend/marsha/core/api.py, src/backend/marsha/core/tests/test_api_document.py, src/backend/marsha/core/tests/test_api_thumbnail.py, src/backend/marsha/core/tests/test_api_timed_text_track.py, src/backend/marsha/core/tests/test_api_video.py, src/backend/marsha/core/utils/s3_utils.py, src/frontend/components/UploadForm/index.spec.tsx, src/frontend/data/sideEffects/upload/index.spec.ts, src/frontend/data/sideEffects/upload/index.ts, src/frontend/types/AWSPresignedPost.ts
To upload a file on s3, a form is crafted with a policy, signature and
more fields defining upload conditions. Since now all of this was
computed by us but we found that boto3 is able to do this job, it is
less error prone and we have less code to maintain.
=> ♻️(S3) use boto3 to generate upload form

.circleci/config.yml, CHANGELOG.md, CONTRIBUTORS.md, Makefile, src/backend/.bandit, src/backend/marsha/core/lti/__init__.py, src/backend/marsha/core/models/account.py, src/backend/marsha/core/utils/cloudfront_utils.py, src/backend/setup.cfg
We would like to check for security issues in marsha's backend source code.
FYI, the following errors were reported by `bandit` : 
```
Test results:
>> Issue: [B101:assert_used] Use of assert detected. The enclosed code will be removed when compiling to optimised byte code.
Severity: Low   Confidence: High
Location: marsha/core/lti/__init__.py:174
More Info: https://bandit.readthedocs.io/en/latest/plugins/b101_assert_used.html
173	        try:
174	            assert consumer_key
175	        except AssertionError:
--------------------------------------------------
>> Issue: [B311:blacklist] Standard pseudo-random generators are not suitable for security/cryptographic purposes.
Severity: Low   Confidence: High
Location: marsha/core/models/account.py:170
More Info: …
```
=> 👷(linters) lint backend source code with bandit

CHANGELOG.md, src/backend/marsha/core/tests/test_xapi.py, src/backend/marsha/core/xapi.py
We want to add the video title in all xapi statements. To do that, we
added it in the object property. We use the language map name in this
property to store it.
=> ✨(XAPI) add video title in xapi statement

CHANGELOG.md, src/backend/marsha/core/tests/test_xapi.py, src/backend/marsha/core/xapi.py
The name property is not set at the good level. We added it in the
option property but it should be in the object.definition property
=> 🐛(xapi) move video title in definition property

CHANGELOG.md, src/aws/lambda-encode/src/encodeVideo.js, src/aws/lambda-encode/src/utils/framerateConverter.js, src/aws/lambda-encode/src/utils/framerateConverter.spec.js, src/aws/lambda.tf
All our mediaconvert presets are using a 29.970 fps but a user can
upload a video with a different framerate. Using mediainfo we detect the
original framerate and keep it in the job creation.
=> ✨(AWS) detect framerate from original video 

CHANGELOG.md, src/aws/lambda-encode/src/encodeVideo.js
For some videos, mediainfo doesn't have bitrate info which result in
missing audio in the encoded video. To fix this issue, we test if the
BitRate property is present and fallback on default bitrate if absent.
=> 🐛(AWS) fallback on default audio bitrate when absent in mediainfo

CHANGELOG.md, src/aws/lambda-complete/package.json, src/aws/lambda-configure/package.json, src/aws/lambda-encode/package.json, src/aws/lambda-migrate/package.json, src/backend/setup.cfg, src/frontend/package.json
- Fallback on default audio bitrate when absent in mediainfo
=> 🔖(patch) bump release to 3.9.1

CHANGELOG.md, CONTRIBUTORS.md, src/frontend/components/TranscriptReader/index.tsx, src/frontend/components/TranscriptSentence/index.spec.tsx, src/frontend/components/TranscriptSentence/index.tsx
Is your feature request related to a problem or unsupported use case? Please describe.
When a video is played and a transcript shown, both are synchronized. We know which sentence is active by highlighting it. But in most of case we have a scroll bar and this scroll bar is not synchronized with the active transcript sentence.
The active sentence should always be visible in the screen. To do that the scroll position should change to always display it.
=> Synchronize scroll with active transcript sentence

src/aws/lambda-complete/yarn.lock, src/aws/lambda-configure/yarn.lock, src/aws/lambda-encode/yarn.lock, src/aws/lambda-migrate/yarn.lock, src/aws/utils/update-state/yarn.lock
Lodash v4.17.19 contains a security fix. This version should be used in
all lambda projects.
=> ⬆️(dependencies) upgrade lodash to version 4.17.19

CHANGELOG.md, src/backend/marsha/core/models/base.py, src/backend/marsha/core/models/file.py, src/backend/marsha/core/models/video.py, src/backend/marsha/core/tests/test_api_update_state.py
Thumbnail can not be updated from the update state endpoint because its
model doesn't have the update_upload_state method. To fix it, we choose
to add the UploadableFileMixin to the AbstractImage class which already
contains required fields to manage an upload state.
=> 🐛(back) use UploadableFileMixin on AbstractImage model

CHANGELOG.md, src/backend/marsha/core/serializers.py, src/backend/marsha/core/tests/test_api_document.py, src/backend/marsha/core/tests/test_api_video.py, src/backend/marsha/core/tests/test_views_lti_development.py, src/backend/marsha/core/tests/test_views_lti_video.py, src/frontend/components/AppRoutes/index.tsx, src/frontend/components/DashboardDocument/index.spec.tsx, src/frontend/components/DashboardDocumentTitleForm/index.spec.tsx, src/frontend/components/DashboardThumbnail/index.spec.tsx, src/frontend/components/DashboardVideoPane/index.spec.tsx, src/frontend/components/DashboardVideoPaneDownloadOption/index.spec.tsx, src/frontend/components/DashboardVideoPaneTranscriptOption/index.spec.tsx, src/frontend/components/DocumentPlayer/index.spec.tsx, src/frontend/components/InstructorView/index.spec.tsx, src/frontend/components/InstructorView/index.tsx, src/frontend/components/InstructorWrapper/index.spec.tsx, src/frontend/components/InstructorWrapper/index.tsx, src/frontend/types/file.ts, src/frontend/types/tracks.ts
Permission object in JWT token was misused. To determine if a user can
see the instructor view it must have can_access_dashboard set to true
and to see the dashboard button in the instructor view it must have
can_update set to true. We did the opposite so when an instructor saw a
video from an other playlist it didn't see the message telling him that
the video is coming from an other playlist but it see the student view.
Also the info shown in the instructor view when a video is in read only is wrong. We are showing the current context_id and we want to display the original one.
=> fix how permissions are used to display dashboard

CHANGELOG.md, src/aws/lambda-encode/src/encodeVideo.js, src/frontend/Player/i18n/plyrTranslation.ts
Some videos don't have Audio playlist, so the Audio part of mediainfo
result is missing. Also, we have to manage videos having height smaller
than 144px. If this happen we force sizes array with 144 value.
Also with new react-intl version we must escape string interpolation for plyr translation.
=> Manage case where info are missing in mediainfo result

CHANGELOG.md, src/aws/lambda-complete/package.json, src/aws/lambda-configure/package.json, src/aws/lambda-encode/package.json, src/aws/lambda-migrate/package.json, src/backend/setup.cfg, src/frontend/package.json
- Use formatjs/cli to manage message extraction and don't
rely anymore on babel react-intl plugin.
- Manage case where info are missing in mediainfo result
=> 🔖(patch) bump release to 3.10.1

CHANGELOG.md, src/frontend/components/TranscriptReader/index.tsx
To synchronize active sentence of a transcript we were using
scrollIntoView function. It works but it also move the entire page to
have the sentence of the middle of the entire view port (all the
browser) and this a bug because the video can be not visible.
To solve this issue, we remove the usage of this function and instead we
compute where the scroll position should be and never focus on it.
=> 🐛(front) remove usage of scrollIntoView to synchronize active transcript sentence

Makefile
During bootstrap the migrate fails because the database is not running.
To fix this we call run task after build task. Moreover to avoid migrate
to fail if the database is not up and running we explicitely start it.
=> 🐛(makefile) call run task in bootstrap

src/backend/setup.cfg
urllib3 before 1.25.9 allows CRLF injection if the attacker controls
the HTTP request method, as demonstrated by inserting CR and LF
control characters in the first argument of putrequest().
See: CVE-2020-26137. (NOTE: this is similar to CVE-2020-26116.)
=> ⬆️(back) upgrade urllib3 to version 1.25.10

CHANGELOG.md, src/backend/marsha/core/admin.py
The video seach feature was not working in the admin. One of the
searchable field is portable_to and portable_to is a primary key. To fix
this problem, we choose to explicitly search on some fields in the
portable_to table: title, lti_id and id.
Fixes #736
=> 🐛(back) fix video search in the admin

CHANGELOG.md, src/backend/marsha/core/tests/test_settings.py, src/backend/marsha/settings.py
When an error is reported to sentry fron the backend application, the
environment and release info are not set correctly. The bug is explained
in issue #723. To fix it, we don't call anymore method in the post_setup
method because this method is a classmethod and can't access to object's method.
Fixes #723
=> 🐛(back) fix sentry configuration to have env and release info

.circleci/config.yml
Docker will start a rate limit on puling images on docker hub. This rate
limit is based on the IP used for anonymous users, this is the circle ci IP
that will be used so the rate limit will be reached quickly. If the pull
is made with a connected user the rate limit is on a per-user basis so we
should not reach it once connected.
=> ♻️(ci) stop pulling images anonymously

.circleci/config.yml
When docker builds an image, it first pulls the image used at the FROM step
in the dockerfile. We also have to login on dockerhub before starting a
pull to not have a rate limit issue.
This commit completes commit c8a7a72
=> ♻️(ci) connect to dockerhub before building images

CHANGELOG.md, src/aws/lambda-complete/package.json, src/aws/lambda-configure/package.json, src/aws/lambda-encode/package.json, src/aws/lambda-migrate/package.json, src/backend/setup.cfg, src/frontend/package.json
- Rework front i18n workflow
- Remove usage of react-intl-po
- Fix admin video search
- Rework sentry configuration to have environment and version info
=> 🔖(minor) bump release to 3.11.0

src/backend/marsha/core/api.py, src/backend/marsha/core/tests/test_api_video.py, src/backend/marsha/core/tests/test_utils_medialive_utils.py, src/backend/marsha/core/utils/medialive_utils.py
Once a live is stopped we can delete all the aws elemental stack used,
we will not use them again.
=> ✨(back) delete aws elemetal stack once a live stopped

CHANGELOG.md, src/backend/marsha/core/lti/utils.py, src/backend/marsha/core/models/file.py, src/backend/marsha/core/models/video.py, src/backend/marsha/core/tests/test_lti_utils.py, src/backend/marsha/core/tests/test_views_lti_video.py
The LTI module fetches a resource when a request is incoming. It was not possible to manage specific ready clauses depending on the type of resource requested as the clauses are defined in the resource model itself and used in lti.utils.get_or_create_resource function.
=> 🐛(back) manage ready clauses in lti resource finder

src/aws/lambda-encode/src/encodeTimedTextTrack.js, src/aws/lambda-encode/src/encodeTimedTextTrack.spec.js
The regex changing the timed text track destination key was replaced by
a simple text replacement. This modification is wrong because we also
remove other part of the source key. This issue was not detected by the
tests because they were not relevant at all, this PR refactor them with real
case values.
=> ♻️(aws) fix regex changing timed text track destination key

CHANGELOG.md, src/aws/lambda-configure/presets/cmaf_audio_aac_128kbps.json, src/aws/lambda-configure/presets/cmaf_audio_aac_160kbps.json, src/aws/lambda-configure/presets/cmaf_audio_aac_192kbps.json, src/aws/lambda-configure/presets/cmaf_audio_aac_64kbps.json, src/aws/lambda-configure/presets/cmaf_audio_aac_96kbps.json, src/aws/lambda-configure/presets/cmaf_video_h264_1080p_30fps_5400kbps.json, src/aws/lambda-configure/presets/cmaf_video_h264_144p_30fps_300kbps.json, src/aws/lambda-configure/presets/cmaf_video_h264_240p_30fps_600kbps.json, src/aws/lambda-configure/presets/cmaf_video_h264_480p_30fps_1200kbps.json, src/aws/lambda-configure/presets/cmaf_video_h264_720p_30fps_2400kbps.json
since 2020/11/20 AWS has fix an issue in job creation on container
value. The value we used (MPD) was not valid for CMAF content but the
job was not rejected. It is not the case anymore, we must use CMFC
value.
AWS warn with this mail : 
```
We have found that certain jobs with invalid job settings are not being properly rejected and can successfully be submitted to the service. These jobs will sometimes complete, but do not produce the desired results. In other cases, they eventually fail and return an error. We are in the process of adding a validation to reject jobs containing these invalid job settings. This change will go into effect by November 20, 2020.
We have reviewed past job creation data and found you have submitted one of these job configurations. Please review your job …
```
=> 🐛(aws) change all container preset value by CMFC

CHANGELOG.md, src/backend/marsha/core/serializers.py, src/backend/marsha/core/tests/test_api_video.py, src/backend/marsha/core/tests/test_utils_medialive_utils.py, src/backend/marsha/core/tests/test_views_lti_video.py, src/backend/marsha/core/utils/medialive_utils.py, src/frontend/Player/createPlyrPlayer.spec.ts, src/frontend/Player/createPlyrPlayer.ts
Since now, only HLS endpoint was created in a mediapackage channel. We
decided to also add a dash one in order to use it on compatible
browsers.
=> manage dash endpoint in live mode

CHANGELOG.md, src/aws/lambda-encode/src/copyDocument.js, src/aws/lambda-encode/src/copyDocument.spec.js
In lambda-encode, the function copying a document from a source bucket
to a destination was downloaded all the document in the lambda and then
upload it in the destination bucket. This code can be highly optimized
by using the CopyObject function, no data are downloaded in the lambda.
=> ♻️(aws) copy object from source to destination s3 bucket in lambda-encode

CHANGELOG.md, src/aws/lambda-complete/package.json, src/aws/lambda-configure/package.json, src/aws/lambda-encode/package.json, src/aws/lambda-medialive-routing/package.json, src/aws/lambda-medialive/package.json, src/aws/lambda-migrate/package.json, src/aws/utils/update-state/package.json, src/backend/setup.cfg, src/frontend/package.json
Added
- Manage live streaming using AWS Elemental
- Download timed text track in video dashboard
- Create shared resources between terraform workspaces
- Add dash endpoint to mediapackage channel
Changed
- use input to execute lambda_migrate instead of env var
- copy document from s3 source to s3 destination in lambda copying document
Fixed
- manage ready clauses in LTI resource finder
- Change preset container by CMFC
=> 🔖(minor) bump release to 3.12.0

CHANGELOG.md, src/backend/marsha/core/serializers.py, src/backend/marsha/core/tests/test_api_timed_text_track.py, src/frontend/components/TimedTextListItem/index.tsx, src/frontend/types/tracks.ts
Existing videos don't have extension property set. To be compatible
with this case we allow to serialize a timed text track object with
source_url set to None. A migration must be done to set the extension
field.
=> 🐛(timed text track) manage resource without extension

CHANGELOG.md, src/aws/lambda-complete/package.json, src/aws/lambda-configure/package.json, src/aws/lambda-encode/package.json, src/aws/lambda-medialive-routing/package.json, src/aws/lambda-medialive/package.json, src/aws/lambda-migrate/package.json, src/aws/utils/update-state/package.json, src/backend/setup.cfg, src/frontend/package.json
- Allow to serialize a timed text track without extension
=> 🔖(patch) bump release to 3.12.1

CHANGELOG.md, src/backend/marsha/core/admin.py, src/backend/marsha/core/defaults.py, src/backend/marsha/core/tests/test_views_lti_cache.py, src/backend/marsha/core/tests/test_views_lti_video.py, src/backend/marsha/core/views.py, src/backend/marsha/settings.py, src/backend/setup.cfg, src/frontend/components/DashboardPaneButtons/index.spec.tsx, src/frontend/components/DashboardPaneButtons/index.tsx, src/frontend/components/DashboardVideoPane/index.spec.tsx, src/frontend/types/AppData.ts, src/frontend/utils/isFeatureEnabled.spec.ts, src/frontend/utils/isFeatureEnabled.ts
We want to manage feature flag. We decided to use [django-waffle](https://waffle.readthedocs.io/en/stable) lib. We
install and configure it. For now a simple flag is added to enable or
not video live feature.
=> Feature flag capabilities

src/frontend/package.json, src/frontend/yarn.lock
We have identified an [issue](https://github.com/videojs/http-streaming/issues/1013) in videojs. The bug is in a nested
dependency, [mux.js](https://github.com/videojs/mux.js). A new version of mux.js containing a fix is
available and we don't to wait a new videojs release to have this fix. A
temporary solution is to add a resolution in our package.json file. This
resolution will be removed once a new release of videojs available.
=> 📌(front) temporary ping mux.js to version 5.7.0

src/frontend/package.json, src/frontend/yarn.lock
In commit 558d5c6 we pin mux.js for @videojs/http-streaming and two
versions of mux.js were living in our node_modules. Globally pinning it
using glob pattern resolve the issue. Now only mux.js 5.7.0 is living in
out node_modules.
=> 📌(front) globally pin mux.js

src/backend/setup.cfg
package flake8-per-file-ignores is not compatible anymore with the
version of flake8 we use, we don;t use it and is integrated in flake8
now.
=> ➖(back) remove flake8-per-file-ignores dev dependency

.circleci/config.yml, bin/lambda
lambda-publish job use a machine executor. It is not possible to
activate docker in docker with this executor. This step must be removed
=> 🐛(aws) remove docker in docker for lambda-publish job

CHANGELOG.md, src/frontend/Player/createVideojsPlayer.spec.tsx, src/frontend/Player/createVideojsPlayer.ts
Videojs can override ARB native browser feature. When enabled,
videojs-http-streaming is used instead of native support of ABR. Lot of
broser have capabilities to run ABR content but lot of features can be
missing. Exception made for safari.
=> 🐛(front) enable videojs override native feature except on safari

src/aws/lambda-complete/yarn.lock, src/aws/lambda-configure/yarn.lock, src/aws/lambda-encode/yarn.lock, src/aws/lambda-medialive-routing/yarn.lock, src/aws/lambda-medialive/yarn.lock, src/aws/lambda-migrate/yarn.lock, src/aws/utils/update-state/yarn.lock, src/frontend/yarn.lock
Bumps node-notifier in all directories containing a node_modules. This upgrade fixes a security issue.
https://github.com/mikaelbr/node-notifier/blob/v8.0.1/CHANGELOG.md
- bumps node-notifier from 8.0.0 to 8.0.1
=> ⬆️ (node) bump node-notifier from 8.0.0 to 8.0.1

CHANGELOG.md, src/aws/env.d/development.dist, src/aws/lambda-complete/package.json, src/aws/lambda-configure/package.json, src/aws/lambda-encode/package.json, src/aws/lambda-medialive-routing/package.json, src/aws/lambda-medialive/package.json, src/aws/lambda-migrate/package.json, src/aws/utils/update-state/package.json, src/backend/setup.cfg, src/frontend/package.json
- Publicly access video or document, bypassing LTI check
- revert removal of mediaconvert presets configuration
- use absolute path to register presets in lambda-configure function
=> bump release to 3.14.0

src/aws/.terraform.lock.hcl, src/aws/bin/terraform, src/aws/provider.tf, src/aws/shared_resources/provider.tf
Terraform 0.14 is available. We want to upgrade it before a new version is released to ease its upgrade.
A lock file is now generated and committed here.
=> Upgrade terraform to version 0.14

src/aws/lambda-mediapackage/src/check.js, src/aws/lambda-mediapackage/src/check.spec.js, src/backend/marsha/core/api.py, src/backend/marsha/core/defaults.py, src/backend/marsha/core/management/commands/check_harvested.py, src/backend/marsha/core/models/video.py, src/backend/marsha/core/serializers.py, src/backend/marsha/core/tests/test_api_update_state.py, src/backend/marsha/core/tests/test_api_video.py, src/backend/marsha/core/tests/test_command_check_harvested.py, src/backend/marsha/core/tests/test_views_lti_video.py, src/backend/marsha/core/tests/test_views_public_video.py, src/backend/marsha/settings.py
To manage the video lifecycle when a live has ended, we need new `upload_state` values and a management command to clean the lives that were not converted to VOD.
The 2 new upload states are : 
- harvesting: set when the harvest job is created
- harvested: set when the video transmuxing process is done
When the transmux process is done, all live info in the video object is clean and the `is_ready_to_show` property is `False`. Doing this, only an instructor can see the video.
=> Manage live to vod lifecycle in backend application

CHANGELOG.md, src/backend/marsha/core/api.py, src/backend/marsha/core/tests/test_api_thumbnail.py, src/backend/marsha/core/views.py, src/backend/marsha/settings.py
When the django model raised a ValidationError, this exception is not managed by DRF. To fix this issue we have to override the DRF exception_handler.
The solution was found in this gist :
https://gist.github.com/twidi/9d55486c36b6a51bdcb05ce3a763e79f
Also, the `TimedTextTrackViewSet` now uses the `ModelViewSet` because it was using all the mixin used in the `ModelViewSet`.
=> 🐛(back) handle Django ValidationError as an accepted exception

CHANGELOG.md, src/aws/lambda-complete/package.json, src/aws/lambda-configure/package.json, src/aws/lambda-encode/package.json, src/aws/lambda-medialive-routing/package.json, src/aws/lambda-medialive/package.json, src/aws/lambda-migrate/package.json, src/aws/utils/update-state/package.json, src/backend/setup.cfg, src/frontend/package.json
- Switch to QVBR rate control mode in live profiles
- Handle Django ValidationError as an accepted exception
- Dash endpoint in mediapackage channel
- Useless medialive profiles
- All dash usage
=> 🔖(minor) bump release to 3.15.0

CHANGELOG.md, src/frontend/Player/createVideojsPlayer.spec.tsx, src/frontend/Player/createVideojsPlayer.ts, src/frontend/Player/videojs/qualitySelectorPlugin/components/QualitySelectorMenuButton.ts, src/frontend/Player/videojs/qualitySelectorPlugin/components/QualitySelectorMenuItem.ts, src/frontend/Player/videojs/qualitySelectorPlugin/index.ts, src/frontend/Player/videojs/qualitySelectorPlugin/middleware.ts, src/frontend/Player/videojs/qualitySelectorPlugin/types.ts, src/frontend/components/VideoPlayer/index.spec.tsx, src/frontend/components/VideoPlayer/index.tsx, src/frontend/types/libs/video.js/extend.d.ts, src/frontend/utils/isMSESupported.ts
All browsers are not compatible with the Media Source Element API. When
they are not, videojs does not fallback on other available sources. To
force using them, we detect if the MSE API is available, if not only MP4
sources are loaded and the quality selector plugin is activated.
A plugin to manage MP4 source is added in this PR. It allows to switch between all available resolutions.
=> Manage situation where HLS is not usable

CHANGELOG.md, src/frontend/Player/createVideojsPlayer.spec.tsx, src/frontend/Player/createVideojsPlayer.ts
By default, Videojs Http Streaming component disable an option called
`useDevicePixelRatio`. This option take the device pixel ratio into
account when doing rendition switching. This means that if you have a
player with the width of 540px in a high density display with a device
pixel ratio of 2, a rendition of 1080p will be allowed. This option
enabled combined with the undocumented option `limitRenditionByPlayerDimensions`
set to true by default will allow to use a higher rendition on devices
allowing it.
=> 🔧(front) enable videojs useDevicePixelRatio VHS option 

CHANGELOG.md, src/backend/marsha/core/api.py, src/backend/marsha/core/forms.py, src/backend/marsha/core/permissions.py, src/backend/marsha/core/serializers.py, src/backend/marsha/core/templates/core/site.html, src/backend/marsha/core/tests/test_api_playlist.py, src/backend/marsha/core/tests/test_api_timed_text_track.py, src/backend/marsha/core/tests/test_api_user.py, src/backend/marsha/core/tests/test_api_video.py, src/backend/marsha/core/views.py, src/backend/marsha/settings.py, src/backend/marsha/urls.py, src/frontend/components/DashboardTimedTextPane/index.spec.tsx, src/frontend/components/LTIRoutes/index.tsx, src/frontend/components/SiteHeader/index.tsx, src/frontend/components/SiteLayout/index.tsx, src/frontend/components/SiteRoutes/index.tsx, src/frontend/components/SiteSidebar/index.tsx, src/frontend/data/sideEffects/getCurrentUser/index.tsx, src/frontend/data/sideEffects/getResourceList/index.spec.tsx, src/frontend/data/sideEffects/getResourceList/index.ts, src/frontend/data/stores/useCurrentUser/index.tsx, src/frontend/index.tsx, src/frontend/types/AppData.ts, src/frontend/types/User.ts
We want to enable users to upload several videos at once, so they can easily add them to courses in a CMS later on.
To do this, we chose to create a new Marsha site, in a new frontend with a separate entry point from the LTI frontend.
We chose to defer more frontend building wrt. CRUD management of playlists & videos as well as the videos & timed text track upload experience to later PRs.
By hiding the site behind a DEBUG flag, we can move forward with this PR, continually merge our work into main (hopefully breaking it down to smaller pieces), and only release the site when we're ready.
In our opinion this PR is a good starting point with the basic architecture of a new site as well as a bunch of basic API routes we need to go any further.
=> Add mass upload of videos through a new Marsha site

CHANGELOG.md, src/frontend/Player/createVideojsPlayer.spec.tsx, src/frontend/Player/createVideojsPlayer.ts
In the VHS conf we enable the overrideNative option, except for safari
browser. This option must be combined with deactivating native audio and
video tracks support.
=> 🐛(front) disable native audio and video tracks in Videojs conf

CHANGELOG.md, src/frontend/Player/createVideojsPlayer.spec.tsx, src/frontend/Player/createVideojsPlayer.ts, src/frontend/components/VideoPlayer/index.spec.tsx, src/frontend/components/VideoPlayer/index.tsx
When we set the HLS source in the `<video />` tag, the browser try to load
it but fails if the browser is not able to do it. Videojs will load it
because it has polyfills to play HLS source in a browser havinf
MediaSource extension. The solution is to remove the HLS source in the
`<video />` tag and configure directly videojs player with accurate
sources dependening if media sources are available or not.
=> 🐛(front) remove HLS source in <VideoPlayer />

.circleci/config.yml
In the hub-ffmpeg-transmux job, in the step publishing the image on
docker hub, there is a syntax error. The fi closing the if testing if we
have a tag or not is missing.
=> 🐛(circle) add missing fi instruction

src/aws/lambda-medialive/index.js, src/backend/marsha/core/api.py, src/backend/marsha/core/defaults.py, src/backend/marsha/core/tests/test_api_video.py, src/frontend/components/DashboardVideoLive/index.tsx, src/frontend/components/ObjectStatusPicker/index.spec.tsx, src/frontend/components/ObjectStatusPicker/index.tsx, src/frontend/types/tracks.ts
A medialive channel has many pipelines. One by RTMP input. Each pipeline
triggers events and these events are listen by the medialive lambda. In
a first time we thought that this events are always triggers twice (one
by pipeline) and choose to listen only pipeline 0. In reality, this
assert is not always true. Sometimes, I didn't found why, only one
pipelin is triggering an event so we can miss them if they are not on
the pipeline 0. To solve this issue, all the events are listened again
and we update first the live state in the update_live_state endpoint. If
the state is already updated, we stop the process and return a status
200 to stop lambda retries mechanism.
=> ♻️(back) avoid concurrent requests on video live update state endpoint

CHANGELOG.md, src/frontend/components/Loader/index.spec.tsx, src/frontend/components/Loader/index.tsx, src/frontend/components/ObjectStatusPicker/UploadStatus.spec.tsx, src/frontend/components/ObjectStatusPicker/UploadStatus.tsx, src/frontend/components/Offscreen.tsx
The existing <Loader /> in marsha was only appropriate for use in the LTI view as it forced a `fixed` position with an overlay
covering the whole viewport.
It also lacked some accessibility related elements.
We made available a new <Spinner /> component from the same file, which enables users to use only the animated spinner without the whole full-screen overlay.
We also made some accessibility improvements to said <Spinner /> which we refactored into the basis for <Loader />.
=> ♻️(frontend) rework <Loader /> to expand use cases

CHANGELOG.md, src/backend/marsha/core/defaults.py, src/backend/marsha/core/tests/test_views_lti_cache.py, src/backend/marsha/core/tests/test_views_lti_video.py, src/backend/marsha/core/views.py, src/frontend/Player/createPlayer.spec.ts, src/frontend/index.tsx, src/frontend/types/AppData.ts
We want to easily enable or disable sentry in the front application. To do that we choose to use a feature flag like we did to enable the video live.
=> Disable usage of sentry in the front application

src/backend/marsha/core/management/commands/check_live_state.py, src/backend/marsha/core/tests/test_command_check_live_state.py
In the check_live_state management command, when a live need to be
stopped, we set the live state to STOPPED. That was good before we made
the live to VOD feature. Since we have to first set with STOPPING state.
The STOPPED will by set by calling the update live state endpoint.
=> ♻️(back) change status in check_live_state command

CHANGELOG.md, src/backend/marsha/core/management/commands/check_live_idle.py, src/backend/marsha/core/tests/test_command_check_live_idle.py, src/backend/marsha/settings.py
It is possible to configure a live and never use it. The medialive
channel stays in IDLE state but we pay its allocation. The management
commande check_live_idle is here to check these live and delete them
after 7 days stuck in idle state.
closes #797
=> ✨(back) management command checking live stuck in idle

CHANGELOG.md, src/aws/lambda-medialive/src/channelStateChanged.js, src/aws/lambda-medialive/src/channelStateChanged.spec.js, src/backend/marsha/core/api.py, src/backend/marsha/core/defaults.py, src/backend/marsha/core/serializers.py, src/backend/marsha/core/tests/test_api_video.py, src/frontend/components/DashboardVideoLive/index.tsx, src/frontend/components/ObjectStatusPicker/index.spec.tsx, src/frontend/components/ObjectStatusPicker/index.tsx, src/frontend/types/tracks.ts
When a medialive channel is created, it is not possible to start it directly. We have to wait a few seconds. A `CREATED` event is fired. Once this event managed then the channel can be started.
Fix #796
=> Introduce creating live state

CHANGELOG.md, src/backend/marsha/core/api.py, src/backend/marsha/core/permissions.py, src/backend/marsha/core/serializers.py, src/backend/marsha/core/tests/test_api_organization.py, src/backend/marsha/core/tests/test_api_playlist.py, src/backend/marsha/urls.py
As part of our new Marsha site, we want to be able to display the name and related meta-data for an organization or a playlist on its detailed view.
For now, only administrators are granted access to these views, so we're likewise restricting the API route to administrators.
=> Add retrieve endpoints for playlist & organization

src/frontend/components/DashboardTimedTextPane/index.spec.tsx, src/frontend/components/DashboardTimedTextPane/index.tsx, src/frontend/components/DashboardVideoHarvested/index.spec.tsx, src/frontend/components/DashboardVideoHarvested/index.tsx, src/frontend/components/DashboardVideoLiveConfigureButton/index.spec.tsx, src/frontend/components/DashboardVideoLiveConfigureButton/index.tsx, src/frontend/components/DashboardVideoLiveStartButton/index.spec.tsx, src/frontend/components/DashboardVideoLiveStartButton/index.tsx, src/frontend/components/DashboardVideoLiveStopButton/index.spec.tsx, src/frontend/components/DashboardVideoLiveStopButton/index.tsx, src/frontend/components/DashboardVideoPane/index.spec.tsx, src/frontend/components/DashboardVideoPane/index.tsx, src/frontend/components/ErrorComponent/route.ts, src/frontend/components/ErrorComponents/index.spec.tsx, src/frontend/components/ErrorComponents/index.tsx, src/frontend/components/ErrorComponents/route.ts, src/frontend/components/LTIRoutes/index.tsx, src/frontend/components/RedirectOnLoad/index.spec.tsx, src/frontend/components/RedirectOnLoad/index.tsx, src/frontend/components/TimedTextCreationForm/index.spec.tsx, src/frontend/components/TimedTextCreationForm/index.tsx, src/frontend/components/TimedTextListItem/index.spec.tsx, src/frontend/components/TimedTextListItem/index.tsx, src/frontend/components/UploadForm/index.spec.tsx, src/frontend/components/UploadForm/index.tsx, src/frontend/components/VideoPlayer/index.tsx
The general use error component already in marsha is meant to take up the whole screen in the context of the LTI iframe Marsha operates in.
This is not appropriate for the new marsha site, where we want most errors to be colocated with the content they are linked with instead.
Instead of creating a second error component, we added a "generic" kind of error to the available codes and created a second component in the same file that can display a simple error message in the page flow instead of taking up the whole screen.
=> ♻️(frontend) rework <ErrorComponent /> to reuse it in site

CHANGELOG.md, src/frontend/components/VideoPlayer/index.spec.tsx, src/frontend/components/VideoPlayer/index.tsx
We recently reorder how sources are added in the video tag. Since, the
resolution array is order from the higher resolution to the lowest. To
display the higher thumbnail available we have to keep the first
resolution in this array and not the last like we did before.
=> 🐛(front) display higher resolution thumbnail available

CHANGELOG.md, src/aws/lambda-complete/package.json, src/aws/lambda-configure/package.json, src/aws/lambda-elemental-routing/package.json, src/aws/lambda-encode/package.json, src/aws/lambda-medialive/package.json, src/aws/lambda-mediapackage/package.json, src/aws/lambda-migrate/package.json, src/aws/utils/update-state/package.json, src/backend/setup.cfg, src/frontend/package.json
- Create a new lambda (lamba-mediapackage) called when an harvest job is done
- Create a harvest job when a live is ended
- Component to switch a live to VOD
- Switch to enable sentry in front application
- Management command checking live stuck in IDLE
- Add new live state CREATING
- Open retrieve endpoints for organizations & playlists
- Medialive profiles use 24FPS instead of 30
- Increase Medialive profiles segment to 4 seconds
- Increase Mediapackage endpoint segment to 4 seconds
- Rollback Medialive control rate mode to CBR
- Static files are managed using whitenoise
- Display higher resolution thumbnail available
=> 🔖(minor) bump release to 3.17.0

CHANGELOG.md, src/frontend/components/BreadCrumbs/index.spec.tsx, src/frontend/components/BreadCrumbs/index.tsx
We're using react-router-dom to build the new Marsha site. We're creating a page tree, using nested switches to enable easy routing and to keep our "place" in the app even if we reuse the same routes in different locations, in different sub-switches in the site.
To help users navigate this and provide them affordances for going back and forth, we decided to use breadcrumbs. This is a somewhat automatic implementation that attempts to make it as easy as possible to add the crumbs dynamically throughout the app.
=> ✨(frontend) add a set of components to manage breadcrumbs

src/backend/marsha/core/tests/test_lti_utils.py
The test about portability when an instructor or student tries to
retrieve a resource on an other playlist or ohter consumer, even
when ready, was sometimes failing because the resource was, sometimes,
portable to an other consumer site. We updated the test to reflect the
exact case we want.
=> ✅(back) update portability tests

src/backend/marsha/core/tests/test_api_update_state.py, src/backend/marsha/core/tests/test_api_video.py, src/backend/marsha/core/utils/api_utils.py
All the tests about an update state using a signature process used an
already computed signature. On a specific test, we randomly generate the
request body, it's not possible to process the signature. We choose to
create a dedicated function generating a heash given a secret and a
message and use this function in all the tests to generate the
signature.
=> ✅(back) update state signature tests

src/backend/marsha/core/tests/test_views_site.py, src/backend/marsha/core/views.py
In the newly created Site view some data are missing in the data
context. This PR add these data and add basic tests to test this view.
=> 🐛(back) add missing data context in site view

src/frontend/components/LTIRoutes/index.tsx, src/frontend/components/UploadForm/index.tsx, src/frontend/package.json, src/frontend/yarn.lock
To upgrade to videojs 7.11 we had to remove the yarn.lock file to
resolve videojs dependencies issue. Doing this, a more recent version of
@types/react-router is installed, LTIRoutes component must be adapt with
its new types.
=> 📌(front) pin videojs to version 7.11.4

src/backend/marsha/core/tests/test_views_lti_video.py, src/backend/marsha/core/views.py, src/frontend/types/AppData.ts, src/frontend/utils/isFeatureEnabled.spec.ts, src/frontend/utils/isFeatureEnabled.ts
We have now many views and all are rendering `app_data` and some of them are common to all views. We must refactor how they are computed because we had several cases where some new attributes are added at one place and not in an other.
=> Refactor how app_data is computed in backend views

CHANGELOG.md, src/aws/lambda-complete/package.json, src/aws/lambda-configure/package.json, src/aws/lambda-elemental-routing/package.json, src/aws/lambda-encode/package.json, src/aws/lambda-medialive/package.json, src/aws/lambda-mediapackage/package.json, src/aws/lambda-migrate/package.json, src/aws/utils/update-state/package.json, src/backend/setup.cfg, src/frontend/package.json
Added
- Add a series of components to power breadcrumbs.
- Add a frontend component to use SVG icons in Marsha.
Fixed
- Avoid blank page when feature flags are not set.
=> 🔖(patch) bump release to 3.17.1

.gitignore, CHANGELOG.md, CONTRIBUTORS.md, Makefile, bin/get_ngrok_url, docker-compose.yml, src/aws/bin/terraform
Every time we relaunch ngrok, a new url is used, and we need to edit src/aws/env.d/development to specify it.
Also, ngrok needs to be installed on host machine.
When we run `make ngrok`, a container launches ngrok, and a prompt asks if we want to apply current external url to Cloudfront.
=> 🔨(ngrok) inject current ngrok url in aws configuration

.circleci/config.yml
The working_dir used in the job build-ffmpeg-transmux-docker was not
working as expected. The docker context is still the root project. So we
are changing the working directory to the root project and build the
image from this directory.
=> 🐛(circle) change working_dir for hub-ffmpeg-transmux job

src/aws/bin/terraform
The PR #904 was made to change the env file used by the bin/terraform
script. Unfortunately when rebasing this PR the usage of the good env
file was erased...
=> 🐛(aws) change env file used in bin/terraform

docker-compose.yml
We'd like to be able to use the python debugger on the live app in development.
Our docker-compose file needs some updates to enable developers to `docker attach` to the app container and allow them to use the python debugger.
We basically did the exact same thing in Richie earlier (https://github.com/openfun/richie/commit/6cac32d4273b60bb53c896de7dbdd8a3b2441d3c)
=> 🧐(backend) improve backend debugging experience

.gitignore
We had `data` in gitignore entries as we used to use a folder of that name for statics. However, it is also used as a folder name in the frontend.
Remove the entry from gitignore to enable us to add new files in the data folder.
=> 🙈(frontend) remove data from gitignore entries

README.md
Scripts related to the AWS part of Marsha's stack are broken for Mac users by default, as the version of `getopt` available by default in macOS is not compatible with versions on other Unixes.
It can be fixed by installing the GNU version and adding it to the PATH. We decided to add a small disclaimer in the docs so new users don't waste time trying to figure this out.
=> 📝(terraform) add a bit of information on `getopt` for mac users

src/backend/marsha/settings.py
In settings file, pylint is throwing an error since its last update
(2.7.4) when we configure sentry. We don't have alternative to configure
pylint so we choose to ignore this error.
=> 🚨(back) ignore pylint error in settings file

CHANGELOG.md, docs/env.md, env.d/development.dist, src/backend/marsha/core/api.py, src/backend/marsha/core/serializers.py, src/backend/marsha/core/tests/test_api_video.py, src/backend/marsha/core/tests/test_utils_xmpp_utils.py, src/backend/marsha/core/tests/test_views_lti_development.py, src/backend/marsha/core/tests/test_views_lti_video.py, src/backend/marsha/core/tests/test_views_public_video.py, src/backend/marsha/core/utils/xmpp_utils.py, src/backend/marsha/core/views.py, src/backend/marsha/settings.py, src/backend/setup.cfg, src/frontend/components/Chat/index.spec.tsx, src/frontend/components/Chat/index.tsx, src/frontend/components/DashboardVideoLive/index.spec.tsx, src/frontend/components/DashboardVideoLiveStartButton/index.spec.tsx, src/frontend/components/DashboardVideoLiveStopButton/index.spec.tsx, src/frontend/components/VideoPlayer/index.tsx, src/frontend/data/sideEffects/initiateLive/index.spec.ts, src/frontend/data/sideEffects/startLive/index.spec.ts, src/frontend/data/sideEffects/stopLive/index.spec.ts, src/frontend/package.json, src/frontend/types/libs/window.d.ts, src/frontend/types/tracks.ts, src/frontend/utils/tests/factories.ts, src/frontend/utils/window.ts, src/frontend/webpack.config.js, src/frontend/yarn.lock
To add more interactivity during a live video, we want to add a chat. We choose to use the XMPP protocol, marsha will not be responsible to manage the XMPP server.
The back application will create a room when a live is started and then destroy it once a live ended.
In the front application, converse.js lib will be responsible to create the chat UI and interaction
During development of this PR we used a [prosody](https://prosody.im/) server. We used the last version available and installed several community modules : 
- [jitsi-meet-tokens](https://github.com/jitsi/lib-jitsi-meet/blob/master/doc/tokens.md): Allow to use a `JWT` authentication. The token is created by the marsha's backend and added to the BOSH url. 
- [mod_token_affiliation](https://github.com/emrahcom/emrah-buster-templates/ …
=> Add chat feature implementing XMPP protocol

CHANGELOG.md, src/frontend/Player/createHlsPlayer.spec.ts, src/frontend/Player/createHlsPlayer.ts, src/frontend/Player/createPlayer.spec.ts, src/frontend/Player/createPlayer.ts, src/frontend/Player/createPlyrPlayer.spec.ts, src/frontend/Player/createPlyrPlayer.ts, src/frontend/Player/createVideojsPlayer.spec.tsx, src/frontend/Player/createVideojsPlayer.ts, src/frontend/components/DashboardThumbnailDisplay/index.tsx, src/frontend/components/DownloadVideo/index.spec.tsx, src/frontend/components/DownloadVideo/index.tsx, src/frontend/components/VideoPlayer/index.tsx, src/frontend/types/tracks.ts
Currently, video urls can be None if the video is not uploaded.
Frontend video type now accepts nullable urls.
Also, player components now takes urls lists as properties, instead of complete video objects.
=> 🐛(front) align video type with backend serializer

CHANGELOG.md, Makefile, docker-compose.yml, docker/files/docker-entrypoint-initdb.d/init_user_db.sh, docker/files/etc/nginx/conf.d/default.conf, docker/files/etc/prosody/prosody.cfg.lua, env.d/development.dist
To easily work on the marsha chat we added and configured a prosody
server in the docker-compose stack. The server is ready to be used, is
starting using the `make run` command and an admin can be created by
running `make prosody-admin`.
=> ✨(docker) add a prosody server in docker-compose stack

CHANGELOG.md, Dockerfile, docker/tests/statics.sh, src/backend/marsha/core/templates/core/resource.html, src/backend/marsha/core/templates/core/site.html, src/backend/marsha/core/tests/test_views_lti_video.py, src/backend/marsha/core/views.py, src/frontend/package.json, src/frontend/webpack.config.js
As webpack use hashes to name files it generate, old files stay in place. So
after several builds, we can have a js folder with a very large amount of files
which is not efficient and furthermore can produce issues and slow down script
executions.
In order to clean these files before each build, we need to put them in a
dedicated directory to not remove other js scripts placed in static/js directory
=> 🚚(frontend) clean built frontend files before each build

CHANGELOG.md, src/backend/marsha/core/tests/test_views_lti_select.py, src/backend/marsha/core/views.py
With a recent commit which builds frontend js on a static subdirectory, public path needs an update.
Update static_base_url in LTISelectView.
=> 🐛(lti-select) fix public path on lti select view

CHANGELOG.md, src/frontend/components/Chat/index.spec.tsx, src/frontend/components/Chat/index.tsx, src/frontend/components/Chat/route.ts, src/frontend/components/DashboardVideoLive/index.spec.tsx, src/frontend/components/DashboardVideoLive/index.tsx, src/frontend/components/LTIRoutes/index.tsx, src/frontend/types/libs/window.d.ts, src/frontend/utils/converse.spec.ts, src/frontend/utils/converse.ts
As an instructor I would like to see only the chat box during a live
without seeing the video itself. A route is added redirecting to the
chat component and a button is added in the dashboard. An instructor can
see the chat only or the video and the chat in the same page.
Description...
=> Display chat box without video player

src/backend/setup.cfg
Before implementing the LTI select view, oauthlib was used only in our
tests and was in the dev section in the setup.cfg file. We must move it
in the prod requirement, we are using it in the LTI module.
=> 🐛(back) move oauthlib from dev to prod requirement

CHANGELOG.md, src/backend/marsha/core/tests/test_lti.py, src/backend/marsha/core/tests/test_views_lti_respond.py, src/backend/marsha/core/tests/utils.py
In our tests, we use 3 times the same code to generate signed LTI requests.
Factorize it into a new tests.utils module.
=> ♻️(tests-back) factorize LTI signature

src/backend/marsha/settings.py
The new settings to configure live latency must be cast in integer to be
used by boto3 client.
=> 🐛(back) cast live settings in integer

src/backend/marsha/core/api.py, src/backend/marsha/core/permissions.py, src/backend/marsha/core/tests/test_api_thumbnail.py, src/backend/marsha/core/tests/test_api_timed_text_track.py
As we see it, permissions as currently implemented in Django-rest-framework are currently broken. More specifically, the `OR` (`|`) combination of permissions is completely broken when attempting to combine permissions that use both `has_permission()` and `has_object_permission()`.
As can be seen [in the DRF source code](https://github.com/encode/django-rest-framework/blob/master/rest_framework/permissions.py#L68), the semantics of the `OR` combination are: `if any of the combined permissions' has_permission() and any of the combined permissions' has_object_permission() return True, return True`.
This results in undefined behavior when permissions are written in a straightforward way: to avoid any issue, all `has_object_permission()` calls should re-call `has_permission()` to make sure …
=> Update API endpoint permission implementations

src/frontend/Player/createVideojsPlayer.spec.tsx
In createVideoJsPlayer tests we render a real Video component. In the
video component we fetch available timed text track languages in the
useEffet hook. As we are in a node context, fetch is not defined and a
warning was display. To resolve this issue we choose to mock the call to
getChoices.
=> 🚨(front) remove warning fetch not found

src/frontend/Player/createPlyrPlayer.spec.ts, src/frontend/Player/createVideojsPlayer.spec.tsx, src/frontend/components/UploadForm/index.spec.tsx, src/frontend/components/UploadManager/LTIUploadHandlers.spec.tsx, src/frontend/components/VideoPlayer/index.spec.tsx, src/frontend/data/sideEffects/getResourceList/index.spec.tsx, src/frontend/utils/types.ts
the type jestMockOf exists now in jest library. We can remove this
helper and use jest.MockedFunction instead.
=> 🔥(front) remove jestMockOf utility

CHANGELOG.md, src/backend/marsha/core/lti/__init__.py, src/backend/marsha/core/serializers/file.py, src/backend/marsha/core/serializers/video.py, src/backend/marsha/core/tests/test_utils_url_utils.py, src/backend/marsha/core/tests/test_views_lti_select.py, src/backend/marsha/core/utils/url_utils.py, src/backend/marsha/core/views.py
URLs returned by LTI Deep linking faces the same problem fixed by this commit fd11cd0259c211aefcaaae3c46ad15254eac5976
When behind a proxy, djjango is reached in http, so generated urls are using http too.
Apply the same process found in fd11cd0259c211aefcaaae3c46ad15254eac5976
=> 🐛(lti-select) fix content urls when placed behind a TLS termination proxy

.circleci/config.yml
In order to build the docker image, we need to change the docker layer
caching version like we did in the build-docker job.
=> 🐛(CI) change docker layer caching version in hub job

src/aws/lambda-complete/yarn.lock, src/aws/lambda-configure/yarn.lock, src/aws/lambda-encode/yarn.lock, src/aws/lambda-migrate/yarn.lock, src/frontend/yarn.lock
Upgrade lodash and hosted-git-info
=> ⬆️ Security upgrade for npm

CHANGELOG.md, src/backend/marsha/core/api.py, src/backend/marsha/core/tests/test_api_video.py
In the new marsha site, administrators for playlists as well as organizations need to be able to create videos, upload files for
them and generally manage them.
To let them do this, we need to open the relevant API endpoints to them, using user-level authentication (in addition to the existing resource-based permissions).
=> ✨(api) open video endpoints for playlist & organization admins

CHANGELOG.md, src/backend/marsha/core/api.py, src/backend/marsha/core/defaults.py, src/backend/marsha/core/serializers/video.py, src/backend/marsha/core/tests/test_api_video.py, src/backend/marsha/core/tests/test_views_lti_video.py, src/backend/marsha/core/views.py, src/backend/marsha/settings.py, src/frontend/components/DashboardPaneButtons/index.spec.tsx, src/frontend/components/DashboardPaneButtons/index.tsx, src/frontend/components/DashboardVideoLive/index.spec.tsx, src/frontend/components/DashboardVideoLive/index.tsx, src/frontend/components/DashboardVideoLiveConfigureButton/index.spec.tsx, src/frontend/components/DashboardVideoLiveConfigureButton/index.tsx, src/frontend/components/DashboardVideoLiveJitsi/index.spec.tsx, src/frontend/components/DashboardVideoLiveJitsi/index.tsx, src/frontend/components/DashboardVideoLiveRaw/index.spec.tsx, src/frontend/components/DashboardVideoLiveRaw/index.tsx, src/frontend/components/DashboardVideoLiveStopButton/index.tsx, src/frontend/components/DashboardVideoPane/index.spec.tsx, src/frontend/components/DashboardVideoPane/index.tsx, src/frontend/data/sideEffects/initiateLive/index.spec.ts, src/frontend/data/sideEffects/initiateLive/index.ts, src/frontend/tsconfig.json, src/frontend/types/AppData.ts, src/frontend/types/libs/JitsiMeetExternalAPI/index.d.ts, src/frontend/types/libs/window.d.ts, src/frontend/types/tracks.ts
We want to stream jitsi in marsha live as an alternative to tools like OBS Studio. Jitsi is fully integrated in marsha using its [IFrame API](https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-iframe). An instructor will start a live with jitsi, jitsi is added like an iframe the configured to use medialive RTMP settings.
=> jitsi streamed in marsha live

src/frontend/components/Chat/index.spec.tsx, src/frontend/components/Chat/index.tsx, src/frontend/components/LTIRoutes/index.tsx, src/frontend/components/VideoPlayer/index.tsx
Since now the xmpp info injected in the chat component where retrieved
in the video object and it works fine like this if the component is
mounted in the VideoPlayer component. But if we mounted directly using
the chat only feature, the data used come from the appData and can be
outdated. We must retrieve the video from the state to be sure to have
up to date data.
=> ♻️(front) use video object from state in Chat component

CHANGELOG.md, src/frontend/components/DashboardThumbnail/index.spec.tsx, src/frontend/components/DashboardThumbnail/index.tsx, src/frontend/components/TimedTextListItem/index.tsx, src/frontend/components/UploadForm/index.spec.tsx, src/frontend/components/UploadForm/index.tsx, src/frontend/components/UploadManager/LTIUploadHandlers.spec.tsx, src/frontend/components/UploadManager/LTIUploadHandlers.tsx, src/frontend/components/UploadManager/index.spec.tsx, src/frontend/components/UploadManager/index.tsx, src/frontend/data/sideEffects/getResource/index.spec.tsx, src/frontend/data/sideEffects/getResource/index.tsx
In #897 a new upload manager was created and we faced multiple bugs with release v3.18.0:
- The object involved in the upload process is never updated if it already exists because its `upload_state` is always `ready`. So the dashboard never display the progress bar and the processing message
- The thumbnail dashboard was failing once you click on `replace this thumbnail`
- Impossible to chain multiple time the same upload process. If you uploaded a wrong thumbnail you can not replace unless you refresh the browser
=> Fix issues with new upload process

CHANGELOG.md, src/aws/lambda-complete/package.json, src/aws/lambda-configure/package.json, src/aws/lambda-elemental-routing/package.json, src/aws/lambda-encode/package.json, src/aws/lambda-medialive/package.json, src/aws/lambda-mediapackage/package.json, src/aws/lambda-migrate/package.json, src/aws/utils/update-state/package.json, src/backend/setup.cfg, src/frontend/package.json
- Jitsi streamed in marsha live
- Fetch fresh resource data after initiate-upload endpoint called
- Reset upload manager state before starting a new upload
=> 🔖(minor) bump release to 3.19.0

CHANGELOG.md, src/frontend/components/DashboardVideoLive/index.spec.tsx, src/frontend/components/DashboardVideoLive/index.tsx, src/frontend/components/DashboardVideoLiveRunning/index.spec.tsx, src/frontend/components/DashboardVideoLiveRunning/index.tsx
During a jitsi live, we want to show/hide the Chat component below the
jitsi client.
=> ✨(front) display Chat in Dashboard during a jitsi live

CHANGELOG.md, src/backend/marsha/core/api.py, src/backend/marsha/core/serializers/video.py, src/backend/marsha/core/tests/test_views_public_video.py, src/backend/marsha/core/views.py
A live can be set a public. But the chat is never display because the
`user_id` is used to configure the prosody JWT token. To allow the chat
usage with a public live, we can use the `session_id` instead of the
`user_id`.
=> ✨(back) use chat when a live is publicly available

CHANGELOG.md, src/backend/marsha/core/models/video.py, src/backend/marsha/core/tests/test_models_video.py, src/backend/marsha/core/tests/test_views_lti_video.py, src/backend/marsha/core/tests/test_views_public_video.py
When the uploaded_state switch to DELETED, `is_ready_to_show` property
on the video object must be false, there is nothing to show.
=> 🐛(back) prevent to display a deleted video

renovate.json
We mutualized renovate configuration in the github repo
openfun/renovate-configuration. We can use it without any modification
in marsha.
=> 🔧(renovate) use configuration from renovate-configuration repo

CHANGELOG.md, src/frontend/utils/converse.spec.ts, src/frontend/utils/converse.ts
The default conversejs theme is flashy with orange/red colors which can
remind a "danger" zone in a web context. The concord theme is a light
theme without any color.
Also `muc_instant_rooms` is disabled to inform conversejs that the xmpp server
only accepts registered rooms and `show_client_info` is disabled to hide
the info icon displaying info about conversejs configuration.
=> ♻️(front) Use conversejs concord theme

src/backend/marsha/core/factories.py, src/backend/marsha/core/lti/__init__.py, src/backend/marsha/core/serializers/video.py, src/backend/marsha/core/tests/test_api_organization.py, src/backend/marsha/core/tests/test_api_playlist.py, src/backend/marsha/core/tests/test_api_user.py, src/backend/marsha/core/tests/test_api_video.py, src/backend/marsha/core/tests/test_api_xapi_statement.py, src/backend/marsha/core/tests/test_lti.py, src/backend/marsha/core/tests/test_views_lti_cache.py, src/backend/marsha/core/tests/test_views_lti_development.py, src/backend/marsha/core/tests/test_views_lti_document.py, src/backend/marsha/core/tests/test_views_lti_video.py, src/backend/marsha/core/tests/test_views_public_video.py, src/backend/marsha/core/tests/test_views_site.py, src/backend/marsha/core/tests/test_xapi.py, src/backend/marsha/core/views.py, src/backend/marsha/core/xapi.py, src/frontend/types/jwt.ts
The LTI request can send the user username and/or email. We want to use them in the application and in the future match LTI user and site user to authenticate them easily.
The username can be set in two different LTI property, we need to handle this case. Also the JWT token `user_id` property is moved in the newly created `user` property. This property is a dict with user info.
=> use username value if present in the LTI request

CHANGELOG.md, src/frontend/types/libs/window.d.ts, src/frontend/utils/converse.spec.ts, src/frontend/utils/converse.ts
When a user is connected on Marsha we can know the username set in the LTI request. We decided to use this username as chat nickname. Also we log out the chat user when the window is closed to prevent non restorable session when marsha will be used later.
=> Improve chat session

CHANGELOG.md, src/frontend/Player/createPlayer.spec.ts, src/frontend/Player/createPlayer.ts, src/frontend/components/VideoPlayer/index.spec.tsx, src/frontend/components/VideoPlayer/index.tsx, src/frontend/scss/_main.scss, src/frontend/scss/generic/accessibility.scss, src/frontend/types/VideoPlayer.ts
When a live begins, you have to wait a few seconds before the hls
manifest is created and available. If the player starts fetching this
missing manifest, it fails and never restart. We choose to poll the
manifest while it returns a 200 status code and then the player is
created. A waiting message is display during this period.
=> ✨(front) display a waiting message while live is not available

CHANGELOG.md, src/frontend/Player/createVideojsPlayer.spec.tsx, src/frontend/Player/createVideojsPlayer.ts
For a live video we must disable the speed menu, it's not possible to
read the video faster or slower.
Description...
=> 🐛(front) disable speed menu for live video

.circleci/config.yml, src/frontend/.storybook/main.js
A [recent commit](https://github.com/openfun/marsha/commit/bbfe50a6201c605cf4242e4ba0cedb986a05ed1c#diff-12ee508ecc1901fe1a1d71ed459dba8454f3160983ee18b2c51b76ade45235d3) from Renovate Bot broke storybook build.
Related issue: https://github.com/storybookjs/storybook/issues/15067
Thanks to @jbpenrath, who find a solution, a config is added to storybook as a workaround until version 6.3.
Also, to prevent future similar issues, a job has been added to Circle CI for running a storybook build.
=> Fix storybook build

CHANGELOG.md, src/frontend/components/DashboardVideoLiveJitsi/index.spec.tsx, src/frontend/components/DashboardVideoLiveJitsi/index.tsx, src/frontend/types/libs/JitsiMeetExternalAPI/index.d.ts
Jitsi recording can be stopped. If it's a failure, an event is emitted
we can listen. In this event we wait 1 sec before stating again the
record. While the record is not started the same event is emitted again
and again.
=> 🐛(front) manage jitsi recording interruption

src/frontend/data/sideEffects/pollForTrack/index.spec.tsx, src/frontend/data/sideEffects/pollForTrack/index.tsx
The pollForTrack tests were failing time to time, only in local, not on
the CI. With jest 27 this test is always failing. We rewrite them using
the modern fake timer implementation and changing how jest timer is used.
=> ♻️(front) rewrite pollForTrack tests

CHANGELOG.md, src/frontend/Player/createVideojsPlayer.spec.tsx, src/frontend/components/Chat/index.tsx, src/frontend/components/LTIRoutes/index.tsx, src/frontend/components/PublicVideoDashboard/index.spec.tsx, src/frontend/components/PublicVideoDashboard/index.tsx, src/frontend/components/VideoPlayer/index.spec.tsx, src/frontend/components/VideoPlayer/index.tsx
The VideoPlayer was the main component managing the video player but
also every feature linked to the video public part like the download
links, displaying transcripts and the chat. We decided to create a
component dedicated to manage a public video dashboard and depending the
video type it displays the needed components. Splitting it will allow us
to choose how to display the components independently of each other.
=> ✨(front) create a component to manage a public video dashboard

CHANGELOG.md, src/backend/marsha/core/api.py, src/backend/marsha/core/models/video.py, src/backend/marsha/core/tests/test_api_video.py, src/backend/marsha/core/tests/test_lti_utils.py, src/backend/marsha/core/tests/test_models_video.py, src/backend/marsha/core/tests/test_views_lti_video.py, src/frontend/Player/createPlayer.ts, src/frontend/Player/createVideojsPlayer.spec.tsx, src/frontend/Player/createVideojsPlayer.ts, src/frontend/components/LTIRoutes/index.tsx, src/frontend/components/PublicVideoDashboard/index.spec.tsx, src/frontend/components/PublicVideoDashboard/index.tsx, src/frontend/components/RedirectOnLoad/index.spec.tsx, src/frontend/components/RedirectOnLoad/index.tsx, src/frontend/components/VideoPlayer/index.spec.tsx, src/frontend/components/VideoPlayer/index.tsx, src/frontend/components/WaitingLiveVideo/index.spec.tsx, src/frontend/components/WaitingLiveVideo/index.tsx, src/frontend/data/sideEffects/pollForLive/index.spec.tsx, src/frontend/data/sideEffects/pollForLive/index.tsx
We want to display a waiting message while a live is not ready to be played. For this a component `<WaitingLiveVideo />` is created and this component can poll the hls urls while not created and update the video resource in the store once avaiable. At this time the player is created and the video automatically played.
=> Wait while a live is ready to be played

src/frontend/components/DashboardVideoLiveRunning/index.spec.tsx, src/frontend/components/DashboardVideoLiveRunning/index.tsx
In the dashboard, when the live is streamed by jitsi the chat must be
used in standalone mode otherwise we don't see it on the screen.
Description...
=> 🐛(front) force to display chat in standalone on jitsi dashboard

CHANGELOG.md, src/aws/lambda-complete/package.json, src/aws/lambda-configure/package.json, src/aws/lambda-elemental-routing/package.json, src/aws/lambda-encode/package.json, src/aws/lambda-medialive/package.json, src/aws/lambda-mediapackage/package.json, src/aws/lambda-migrate/package.json, src/aws/utils/update-state/package.json, src/backend/setup.cfg, src/frontend/package.json
- Display chat in dashboard during a jitsi live
- Use chat when a live is publicly available
- Set chat nickname when user is connected
- Display a waiting message while live is not available
- Add Playrwright testing (with basic cloud storage mocking)
- Update circleci config to version 2.1
- Add a parametrized cicrcleci job to run e2e tests on 3 browsers
(chromium, firefox and webkit)
- Move DevelopmentLTIView to a new development directory
- Add a variable to set frontend video polling interval
- Add a component responsible to manage public video dashboard
- Add a waiting workflow while a live is not ready
- Allow to play a youtube video in jitsi
- Switch from classic to jitsi live when a classic is created
- Use conversejs concord theme
- Prevent to display a deleted video
- Disable …
=> 🔖(minor) bump release to 3.20.0

src/backend/marsha/core/api.py, src/backend/marsha/core/permissions.py, src/backend/marsha/core/serializers/video.py, src/backend/marsha/core/tests/test_api_timed_text_track.py
TimedTextTrack related endpoints rely on resource ids on token users as used in the LTI app.
To allow users to perform the same tasks on their videos in the new marsha site, we need to open the API endpoints to users logged in to the marsha site, with the appropriate playlist or organization access
=> ✨(api) update TimedTextTrack endpoints for use in marsha site

CHANGELOG.md, src/frontend/components/ErrorComponents/index.tsx, src/frontend/components/PublicVideoDashboard/index.spec.tsx, src/frontend/components/PublicVideoDashboard/index.tsx
When a live is stopped, an instructor show the page saying the video is
not found. We should redirect him to the dashboard when the live is
stopped or stopping and he has update permission.
=> 🐛(front) redirect instructor to the dashboard when live is stopped

CHANGELOG.md, CONTRIBUTORS.md, src/frontend/components/DashboardPaneButtons/index.tsx, src/frontend/components/DashboardVideoLiveConfigureButton/index.tsx
The feature to start a live is still on a beta version. We want to alert users
about this point. We add a temporary beta label on the two buttons.
No test for this proposal as jest-dom doesn't detect the added CSS. It's a temporary label added, WDYT ?
=> 💄(frontend) Add a beta label on live configuration buttons

CHANGELOG.md, src/backend/marsha/core/defaults.py, src/backend/marsha/core/tests/test_views_lti_cache.py, src/backend/marsha/core/tests/test_views_lti_video.py, src/backend/marsha/core/views.py, src/frontend/components/DashboardPaneButtons/index.spec.tsx, src/frontend/components/DashboardPaneButtons/index.tsx, src/frontend/types/AppData.ts, src/frontend/utils/isFeatureEnabled.spec.ts
VIDEO_LIVE switch is enabled, we will not use it anymore. We can
remove it to not make unnecessary sql queries.
=> Remove live switch

src/backend/marsha/core/tests/test_views_lti_cache.py
CacheLTIViewTestCase fails regularly on Circle CI.
This is a temporary workaround: request time limit has been increased.
=> ✅(lti-view-cache-tests) increase request limit

CHANGELOG.md, src/frontend/components/ConfirmationLayer/index.spec.tsx, src/frontend/components/ConfirmationLayer/index.tsx, src/frontend/components/DashboardConfirmButton/index.spec.tsx, src/frontend/components/DashboardConfirmButton/index.tsx, src/frontend/components/DashboardVideoLiveStartButton/index.spec.tsx, src/frontend/components/DashboardVideoLiveStartButton/index.tsx, src/frontend/components/DashboardVideoLiveStopButton/index.spec.tsx, src/frontend/components/DashboardVideoLiveStopButton/index.tsx
Starting or stopping a live had no confirmation. This is an action that can't be reversed.
To prevent users from making errors, it is now necessary to confirm both actions.
Add new components to confirm an action to stop and start video
https://user-images.githubusercontent.com/76939263/124787696-fbcbaa00-df48-11eb-847a-498c4db06e51.mp4
=> ✨(front) add confirmation before starting/stopping a live

Makefile
Once ngrok session expired, you have to stop ngrok and then restart it.
Running make ngrok-apply does not do it for us. This commit stop ngrok
before running again ngrok.
Closes #1055
=> ♻️(make) stop ngrok before running a new ngrok-apply

docker/files/etc/nginx/conf.d/default.conf, docker/files/etc/prosody/prosody.cfg.lua, src/backend/marsha/core/serializers/video.py, src/backend/marsha/core/tests/test_api_video.py, src/backend/marsha/core/tests/test_utils_xmpp_utils.py, src/backend/marsha/core/tests/test_views_lti_video.py, src/backend/marsha/core/tests/test_views_public_video.py, src/backend/marsha/core/utils/xmpp_utils.py, src/backend/marsha/settings.py, src/frontend/components/Chat/index.spec.tsx, src/frontend/components/PublicVideoDashboard/index.spec.tsx, src/frontend/types/tracks.ts, src/frontend/utils/converse.spec.ts, src/frontend/utils/converse.ts
We want to connect to a xmpp server using a websocket instead of using a bosh connection. Websockets provide a more modern and effective two-way communication protocol between the browser and a server, effectively emulating TCP at the application layer and therefore overcoming many of the problems with existing long-polling techniques for bidirectional HTTP (such as BOSH).
=> Connect to xmpp server using a websocket

CHANGELOG.md, src/frontend/components/ConfirmationLayer/index.tsx, src/frontend/components/DashboardConfirmButton/index.spec.tsx, src/frontend/components/DashboardConfirmButton/index.tsx, src/frontend/components/DashboardVideoLive/index.spec.tsx, src/frontend/components/DashboardVideoLive/index.tsx, src/frontend/components/DashboardVideoLiveJitsi/index.spec.tsx, src/frontend/components/DashboardVideoLiveJitsi/index.tsx, src/frontend/components/DashboardVideoLiveStartButton/index.spec.tsx, src/frontend/components/DashboardVideoLiveStartButton/index.tsx
When a live is starting by a non moderator in a jitsi live, the live is
started on AWS but never in jitsi. Now only moderators can start a jitsi
live.
Closes #1041
=> ✨(front) only jitsi moderators can start a live

CHANGELOG.md, src/backend/marsha/core/management/commands/clean_mediapackages.py, src/backend/marsha/core/tests/test_command_clean_mediapackages.py, src/backend/marsha/core/tests/test_utils_medialive_utils.py, src/backend/marsha/core/utils/medialive_utils.py, src/backend/setup.cfg
When a mediapackage channel has no medialive channel, nor pending harvest job, it is considered useless, and thus can be deleted.
A management command has been added to delete them.
closes #1048
=> ✨(back) management command to delete orphan mediapackage channels

CHANGELOG.md, src/aws/lambda-complete/package.json, src/aws/lambda-configure/package.json, src/aws/lambda-elemental-routing/package.json, src/aws/lambda-encode/package.json, src/aws/lambda-medialive/package.json, src/aws/lambda-mediapackage/package.json, src/aws/lambda-migrate/package.json, src/aws/utils/update-state/package.json, src/backend/setup.cfg, src/frontend/package.json
- Add a confirmation before starting or stopping a live
- Use a tabbed navigation on LTI resource views
- Only jitsi moderators can start a live
- Management command deleting orphan mediapackage channel
=> 🔖(minor) bump release to 3.22.0

CHANGELOG.md, src/backend/marsha/core/admin.py
We want to create groups to assign them to some users. The group model
was not added to the admin, this commit add it.
=> ✨(back) Add user group to admin site

src/aws/.terraform.lock.hcl, src/aws/bin/terraform, src/aws/output.tf, src/aws/provider.tf
Terraform version has been released in june. Only one change is needed
for us to upgrade to this version, we have to flag the AWS secret access
key as sensitive. AWS provider is also updated to version 3.55
=> ⬆️(aws) upgrade terraform to version 1

CHANGELOG.md, src/aws/user.tf
Management command clean_mediapackages lists mediapackage harvest jobs.
Related permission was missing.
=> 🛂(aws) add mediapackage:ListHarvestJobs permission

CHANGELOG.md, src/backend/marsha/core/api.py, src/backend/marsha/core/models/video.py, src/backend/marsha/core/tests/test_api_video.py, src/backend/marsha/core/utils/medialive_utils.py
If a live is stopped and mediapackage does not have created a manifest,
the harvest job will failed and the mediapackage stack will not be
detroyed. Before creating an harvest job we test if the manifest exists
and if not the mediapacakge stack is deleted and the video upload_state
set to DELETED.
=> ✨(back) do not create harvest job when there is no manifest

CHANGELOG.md, src/aws/lambda-complete/package.json, src/aws/lambda-configure/package.json, src/aws/lambda-elemental-routing/package.json, src/aws/lambda-encode/package.json, src/aws/lambda-medialive/package.json, src/aws/lambda-mediapackage/package.json, src/aws/lambda-migrate/package.json, src/aws/utils/update-state/package.json, src/backend/setup.cfg, src/frontend/package.json
- Add user group to admin site
- Do not create an harvest job if no manifest is created
- Add aws permission to list mediapackage harvest jobs (fixes unusable 3.22.0 version)
=> 🔖(minor) bump release to 3.23.0

CHANGELOG.md, src/backend/marsha/core/management/commands/clean_medialive_dev_stack.py, src/backend/marsha/core/tests/test_command_clean_medialive_dev_stack.py, src/backend/marsha/core/tests/test_utils_medialive_utils.py, src/backend/marsha/core/utils/medialive_utils.py, src/backend/marsha/settings.py
During development we can forget to delete resources on AWS medialive
but these resources are charged. We want to delete as soon as possible a
development stack. We think that a development stack should not live
more than 30 minutes and should be deleted after this delay.
=> Command clean media stack

CHANGELOG.md, CONTRIBUTORS.md, src/frontend/XAPI/VideoXAPIStatement.spec.ts, src/frontend/XAPI/VideoXAPIStatement.ts
xAPI logs are returned with played segments. However, there might be overlapping and it could dramatically increase the log size. The information of overlapping segments is neither necessary in the logs. It has been fixed to only keep global information about which segments are played.
Apply the reduction logic of `getProgress` function to `playedSegments` updating in xAPI handling
=> Merge overlapping played segments in xAPI logs

src/aws/lambda-mediapackage/package.json, src/aws/lambda-mediapackage/yarn.lock
node-fetch v3.0.0 introduces several breaking changes. In our case, this package
is used by fetch-mock and this package is not yet compatible with this new
version of node-fetch.
-  [x] pin node-fetch to version less than 3
=> 📌(aws) pin node-fetch to version less than 3

CHANGELOG.md, src/aws/lambda-complete/package.json, src/aws/lambda-configure/package.json, src/aws/lambda-elemental-routing/package.json, src/aws/lambda-encode/package.json, src/aws/lambda-medialive/package.json, src/aws/lambda-mediapackage/package.json, src/aws/lambda-migrate/package.json, src/aws/utils/update-state/package.json, src/backend/setup.cfg, src/frontend/package.json
- Playlist portability management through LTI (resource sharing between courses)
- Command to clean all development environments having a living stack on AWS medialive
and mediapackage
- Allow a participant to join a Jitsi conference
- Merge overlapping played segments for xAPI events
=> 🔖(minor) bump release to 3.24.0

.circleci/config.yml, CHANGELOG.md
The lint-changelog job was not played on our CI. We activated it and we
must reformat the changelog now.
=> Reformat changelog to remove lines exceeding 80 chars

CHANGELOG.md, src/frontend/types/libs/converse/index.d.ts, src/frontend/utils/converse.spec.ts, src/frontend/utils/converse.ts
We want to use [smacks feature](https://modules.prosody.im/mod_smacks) when converse connect to the XMPP server using a websocket connection.
> By default XMPP is as reliable as your network is. Unfortunately in some cases that is not very reliable - in some network conditions disconnects can be frequent and message loss can occur.
> To overcome this, XMPP has an optional extension (XEP-0198: Stream Management) which, when supported by both the client and server, can allow a client to resume a disconnected session, and prevent message loss.
=> 🔧(front) enable smacks in converse conf when websocket is used

src/aws/lambda-complete/yarn.lock, src/aws/lambda-configure/yarn.lock, src/aws/lambda-encode/yarn.lock, src/frontend/yarn.lock
Bumps [tmpl](https://github.com/daaku/nodejs-tmpl) from 1.0.4 to 1.0.5.
- [Release notes](https://github.com/daaku/nodejs-tmpl/releases)
- [Commits](https://github.com/daaku/nodejs-tmpl/commits/v1.0.5)
=> ⬆️(dependencies)  Bump tmpl to version 1.0.5

CHANGELOG.md, src/backend/marsha/core/tests/test_views_public_document.py, src/backend/marsha/core/tests/test_views_public_video.py, src/backend/marsha/core/tests/test_views_site.py, src/backend/marsha/core/views.py, src/frontend/types/jwt.ts
LTI context is a notion related to LTI. If a resource is visualized
from a public context, without an LTI Passeport, we shouldn't
specify any `context_id`. This notion is confusing and not
properly true. To avoid any misunderstanding, we erase from
the token the key `context_id` in a public context.
Getting rid of the key context_id in the token generated for a public resource
=> 🩹(back) public token has no LTI context

CHANGELOG.md, src/frontend/Player/createVideojsPlayer.ts
For a live video, no event to detect when the video is fully initialized is
triggered before the first "play" action. To mitigate this, we can call
"initialize" on the first "interact" action and abort the interact itself.
The first interact action is when the first quality to play is chosen, the
default one. To choose it, all quality available must be read in the HLS
manifest. So we can consider at this time that the video is initialized.
Closes #1065
=> 🐛(front) force xapi initialized action for a live video

CHANGELOG.md, src/frontend/Player/createVideojsPlayer.spec.tsx, src/frontend/Player/createVideojsPlayer.ts
The video html element dispatches 2 differents events related to
playback. `play` and `playing`. In a VOD context using one or the other
lead to the same result. Moreover, when we used plyr player, we follow
its documentation [1] to implement video events and listen the correct one
in order to send XAPI request, and this documentation is not really the
same as the MDN one [2].
In a live context, the `playing` is triggered when a new video fragment is
loaded. So we can have thousands of `played` XAPI events and this is
wrong. We must listen video `play` event. And this event is also the
good one to listen in a VOD context.
[1]: https://github.com/sampotts/plyr#events
[2]: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video#events
=> 🐛(front) listen video play event instead of playing

CHANGELOG.md, src/backend/marsha/core/utils/xmpp_utils.py
As explain in the XEP-0045 [1] spec, when we want to create a reserved
room, we should request first the initial room config, modify it and
then submit it. Currently we directly submit a modification form without
the initial config.
[1]: https://xmpp.org/extensions/xep-0045.html#createroom-reserved
=> ♻️(back) request initial MUC config before modifying it

src/aws/lambda-complete/yarn.lock, src/aws/lambda-configure/yarn.lock, src/aws/lambda-elemental-routing/yarn.lock, src/aws/lambda-encode/yarn.lock, src/aws/lambda-medialive/yarn.lock, src/aws/lambda-mediapackage/yarn.lock, src/aws/lambda-migrate/yarn.lock, src/aws/utils/update-state/yarn.lock
Bumps [ansi-regex](https://github.com/chalk/ansi-regex) from 5.0.0 to 5.0.1.
- [Release notes](https://github.com/chalk/ansi-regex/releases)
- [Commits](https://github.com/chalk/ansi-regex/compare/v5.0.0...v5.0.1)
---
updated-dependencies:
- dependency-name: ansi-regex
dependency-type: indirect
=> ⬆️(front) bump ansi-regex to version 5.0.1

CHANGELOG.md, src/aws/lambda-complete/package.json, src/aws/lambda-configure/package.json, src/aws/lambda-elemental-routing/package.json, src/aws/lambda-encode/package.json, src/aws/lambda-medialive/package.json, src/aws/lambda-mediapackage/package.json, src/aws/lambda-migrate/package.json, src/aws/utils/update-state/package.json, src/backend/setup.cfg, src/frontend/package.json
- Enable smacks in converse conf when websocket is used
https://modules.prosody.im/mod_smacks
- Request initial MUC config before modifying it
- Trigger XAPI initialized action before a first play
for a live video
- Listen video play event instead of playing to send the XAPI played event
=> 🔖(minor) bump release to 3.25.0

.circleci/config.yml, src/aws/Dockerfile
The amazon/aws-lambda-nodejs host on docker hub use the ARM64
architecture, it seems it is a bug. docker hub is a mirror of ECR public
repo host on amazon. We choose to directly use the image hosted on ECR
to avoid this kind of issue. The image can be found at this url
https://gallery.ecr.aws/lambda/nodejs
We also updated the ubuntu image used in circleci to use a more recent one with more recent tools.
=> 🔧(aws) use amazon lambda image from ECR public repo 

CHANGELOG.md, src/frontend/babel.config.js, src/frontend/index.tsx, src/frontend/package.json, src/frontend/types/libs/custom-event-polyfill/index.d.ts, src/frontend/yarn.lock
We stop the suppor for IE11. We can remove this browser from the target
list defined in babel.
custom-event-polyfill was used build marsha for IE11. IE11 is not
supported any more, this polyfill can be removed.
=> Remove support of IE11

src/backend/marsha/e2e/test_lti.py
When selecting a LTI video, selected content were escaped before checking for his presence, and a wait were missing,causing webkit test to fail.
=> ✅(e2e-webkit) fix LTI select test

CHANGELOG.md, src/aws/lambda-medialive/src/channelStateChanged.js, src/aws/lambda-medialive/src/channelStateChanged.spec.js, src/backend/marsha/core/api.py, src/backend/marsha/core/defaults.py, src/backend/marsha/core/serializers/video.py, src/backend/marsha/core/tests/test_api_video.py, src/backend/marsha/core/tests/test_utils_medialive_utils.py, src/backend/marsha/core/utils/medialive_utils.py, src/frontend/components/DashboardVideoLive/index.spec.tsx, src/frontend/components/DashboardVideoLive/index.tsx, src/frontend/components/DashboardVideoLiveConfigureButton/index.spec.tsx, src/frontend/components/DashboardVideoLiveJitsi/index.spec.tsx, src/frontend/components/DashboardVideoLiveJitsi/index.tsx, src/frontend/components/ObjectStatusPicker/index.spec.tsx, src/frontend/components/ObjectStatusPicker/index.tsx, src/frontend/components/PublicVideoDashboard/index.spec.tsx, src/frontend/components/PublicVideoLiveJitsi/index.spec.tsx, src/frontend/types/tracks.ts
We want to create a live video without creating all the associated mediaelement stack. To do this, the `initiate-live` is changed, no call to AWS are made, just the video properties are modified.
The mediaelement stack creation is postpone when the start button is clicked for the first time. We detect that nothing is created on AWS, we create all the stack and then we start it.
=> Postpone AWS creation stack to the first live start action

src/backend/setup.cfg
Renovate does not upgrade black. This dependency is not stable and only
pre-release are posted on pypi. We want to update black to the last
version.
=> ⬆️(back) upgrade black to version 21.10b0

.circleci/config.yml, CHANGELOG.md, Makefile, src/backend/marsha/core/admin.py, src/backend/marsha/core/tests/test_views_lti_video.py, src/backend/marsha/core/views.py, src/frontend/.storybook/main.js, src/frontend/components/SelectContent/index.spec.tsx, src/frontend/components/SelectContent/index.tsx, src/frontend/index.tsx, src/frontend/jest.config.js, src/frontend/settings.ts, src/frontend/types/AppData.ts, src/frontend/utils/parseDataElements/parseDataElements.spec.ts, src/frontend/utils/parseDataElements/parseDataElements.ts, src/frontend/webpack.config.js
We need a clean way to manage more resource types in Marsha.
Classic Django apps will be created in `src/backend/marsha/`
New apps will be created in `src/frontend/apps/`
If appName exists in appData,  matching  `src/frontends/apps/${appData.appName}/Routes` file will be loaded in `src/frontend/index.tsx` 
And if `src/frontends//apps/${name}/SelectContentTab` exists, it will be loaded in `SelectContent` component.
=> Custom frontend and backend apps

CHANGELOG.md, src/backend/marsha/core/models/video.py, src/backend/marsha/core/tests/test_api_video.py, src/backend/marsha/core/tests/test_lti_utils.py
If a video was scheduled and still in the IDLE live_state, users should
be allowed to access this video to wait for the live to start.
Allowing access independently of starting_date date, past and future
=> ✨(backend) access to videos with a scheduled date past

.circleci/config.yml
Playwright image has recently intruduced apt cache cleaning and installing chrome requires wget
Add `apt update` and `apt install wget` before installing chrome in e2e circle-ci job.
=> 💚(e2e) fix chrome install

src/frontend/Player/createVideojsPlayer.spec.tsx, src/frontend/Player/createVideojsPlayer.ts, src/frontend/components/PublicPausedLiveVideo/index.spec.tsx, src/frontend/components/PublicPausedLiveVideo/index.tsx, src/frontend/components/PublicVideoDashboard/index.spec.tsx, src/frontend/components/PublicVideoDashboard/index.tsx, src/frontend/components/VideoPlayer/index.spec.tsx, src/frontend/components/VideoPlayer/index.tsx, src/frontend/types/libs/m3u8-parser/index.d.ts, src/frontend/types/tracks.ts, src/frontend/utils/resumeLive.spec.ts, src/frontend/utils/resumeLive.ts
in #1207 we managed all the mechanism allowing an instructor to start and stop the live. Once this done we have to manage this feature for a student.
We have to pause the player once the live paused and then resume it without interruption once the live resumed itself.
A dedicated component is created to manage a live once this one paused. It adds a layer over the player, displaying a waiting message and since when the live is paused.
To detect when the live is paused, we listen the video `pause` event and if in this event the video is a live and the video is ended, we fetch the video to refresh its state.
To detect when the live is resumed, the HLS manifest poll and parsed to see if the #EXT-X-ENDLIST` tag is removed. When removed, we can refresh the video to start it again.
=> Start and stop live for student view

src/backend/marsha/settings.py
As BBB usage is optional, BBB_API_SECRET, it shouldn't be mandatory to set it.
BBB_API_SECRET has been moved from SecretValue to Value, so it can be defaulted.
=> 🔧(settings) change BBB_API_SECRET setting type

src/backend/marsha/core/api/video.py, src/backend/marsha/core/tests/test_api_video.py
Every time a live is started, we created the chat room. This is useless,
the room is closed at the end. Reconfiguring the room at every start
can, sometimes, hide already existing messages. Not reconfiguring it
should reduce errors.
=> ♻️(back) create chat room on first live start

CHANGELOG.md, src/frontend/components/SubscribeScheduledVideo/index.spec.tsx, src/frontend/components/SubscribeScheduledVideo/index.tsx
If a user is on the registration page and the instructor starts the
live earlier, the user needs to be redirected to be part of the live.
We've decided to check every sixty seconds the state of the video to
deal with this case.
Add a timer to check the object video
=> 🐛(front) scheduled video started before

src/frontend/components/ScheduledVideoForm/index.spec.tsx
2 tests were failing because of the expected string misformating the first 10 days or months.
Tricks the format
=> ✅(frontend) fix scheduled video form tests

CHANGELOG.md, src/frontend/data/stores/useLivePanelState/index.spec.ts, src/frontend/data/stores/useLivePanelState/index.ts
New live layout needs to be control, we use a store to save the state and control the layout
Create the store and test functions exposed to control its state
The state will contains:
- the status of the panel (open or close)
- the list of available tabs (called detail) we can display in the panel
- the current detail selected
And 2 functions to update the state
=> ✨(frontend) create store to control live layout panel

CHANGELOG.md, src/frontend/Player/createPlayer.spec.ts, src/frontend/Player/createPlayer.ts, src/frontend/components/UploadManager/LTIUploadHandlers.spec.tsx, src/frontend/components/WaitingLiveVideo/index.spec.tsx, src/frontend/components/WaitingLiveVideo/index.tsx, src/frontend/data/sideEffects/getResource/index.spec.tsx, src/frontend/data/sideEffects/getResource/index.tsx, src/frontend/data/sideEffects/pollForLive/index.spec.tsx, src/frontend/data/sideEffects/pollForLive/index.tsx, src/frontend/utils/resumeLive.spec.ts
If urls of video are not created loading the component WaitingLiveVideo,
live will never be able to start as video object is not updated.
We update the store in this specific case.
update store in pollVideo
=> 🐛(front) update store while waiting for live

CHANGELOG.md, src/frontend/data/sideEffects/pollForLive/index.spec.tsx, src/frontend/data/sideEffects/pollForLive/index.tsx
When users are waiting for the live to start, there is two different
cases. The first one, urls of the manifest exist and in that case, we
only fetch this url, having a timeout of two seconds is fine. The
second case is when the video doesn't have a manifest ready to read,
we then need to fetch the API to update the video store. We want to
wait another 30 seconds in this case not to load our server.
Setting timeout to 30 seconds to update the store, 2 seconds otherwise
=> ⚡️(frontend) specific timeout set while manifest is not ready

CHANGELOG.md, src/backend/marsha/core/serializers/video.py, src/backend/marsha/core/tests/test_api_video_live_pairing.py, src/frontend/components/DashboardVideoLive/index.spec.tsx, src/frontend/components/DashboardVideoLive/index.tsx, src/frontend/components/DashboardVideoLivePairing/index.spec.tsx, src/frontend/components/DashboardVideoLivePairing/index.tsx, src/frontend/components/DashboardVideoPane/index.spec.tsx, src/frontend/data/queries/actionOne.spec.tsx, src/frontend/data/queries/actionOne.tsx, src/frontend/data/queries/index.spec.tsx, src/frontend/data/queries/index.tsx
We want to allow pairing external devices to Marsha live. External devices are cameras or set-top boxes that can act as video and sound sources for a live in Marsha.
This PR should be merged after #1213 
- usage of any request method
- usage of empty body request
- request a secret
- displays the secret
- displays a countdown timer initially set to 1 minutes
(Following demo has an expiry set to 5 seconds)
#1196
=> ✨ Add a mechanism to connect external devices to a video live

CHANGELOG.md, src/backend/marsha/core/serializers/video.py, src/backend/marsha/core/tests/test_api_video.py, src/backend/marsha/core/tests/test_views_lti_development.py, src/backend/marsha/core/tests/test_views_lti_video.py, src/backend/marsha/core/tests/test_views_public_video.py
Allow instructors to publish their video publicly
Fixes #1242
=> ✨(backend) add public availability to video api

CHANGELOG.md, src/aws/Dockerfile, src/aws/lambda-complete/package.json, src/aws/lambda-configure/package.json, src/aws/lambda-elemental-routing/package.json, src/aws/lambda-encode/package.json, src/aws/lambda-medialive/package.json, src/aws/lambda-mediapackage/package.json, src/aws/lambda-migrate/package.json, src/aws/utils/update-state/package.json, src/backend/locale/es_ES/LC_MESSAGES/django.po, src/backend/locale/fr_CA/LC_MESSAGES/django.po, src/backend/locale/fr_FR/LC_MESSAGES/django.po, src/backend/marsha/bbb/models.py, src/backend/setup.cfg, src/frontend/i18n/es_ES.json, src/frontend/i18n/fr_CA.json, src/frontend/i18n/fr_FR.json, src/frontend/package.json
- Prepare backend to manage apps
- Prepare frontend to manage apps
- Add BBB backend app
- Add BBB frontend app
- Add configuration to filter app with feature flags
- Start and stop a live
- Add a form to create a scheduled video on the Dashboard
- Add frontend components to register an email for scheduled webinars
- Add API endpoints to pair an external device to Jitsi live videos
- Add a store in the frontend to control live layout
- Add frontend components to pair an external device to Jitsi live videos
- Add public availability to video api
- Postpone AWS creation stack to the first live start action
- Scheduled videos have a live_state set to IDLE
- Allow access to videos with a scheduled date past
- Users with empty email in their token can register to scheduled webinars
- Users …
=> Prepare 3.27.0

src/backend/marsha/core/api/video.py, src/backend/marsha/core/serializers/file.py, src/backend/marsha/core/tests/test_api_shared_live_media.py, src/backend/marsha/settings.py
We want to control the type of media a user can used for a shared live
media. A new setting containing allowed MIME Types is created, we first
check if the given MIME Type in the initiate upload request is allowed
and we guess it if not present. When retrieved we use this exact same
MIME Type in the condition of the S3 presigned url. Doing this, AWS
will also check the MIME Type once the file uploaded on S3 and can
rejects it if the uploaded file does not have this MIME Type.
=> ✨(back) whitelist allowed media uploaded for a shared live media

CHANGELOG.md, src/backend/marsha/core/tests/test_views_lti_video.py, src/backend/marsha/core/tests/test_views_public_document.py, src/backend/marsha/core/tests/test_views_public_video.py, src/backend/marsha/core/tests/test_views_site.py, src/backend/marsha/core/views.py, src/frontend/types/jwt.ts
The consumer site is sent during the LTI connexion. Models in Marsha
due to LTI’s protocol and video’s portability are sometimes complex.
For instance, a playlist with a context_id can have multiple
consumer_site. It makes it hard to link a user with his consumer
site. We've decided to simplify access to this information by adding
it directly in the JWT token.
Description...
- add consumer_site in JWT token
=> 🩹(back) add consumer_site in JWT token

src/backend/marsha/core/api/video.py, src/backend/marsha/core/serializers/video.py, src/backend/marsha/core/views.py
Several ways were used to determine if the current user is an admin or
not in the serializers. To do that we injected `roles` and
`can_return_live_info` and look in the serializer for these  values. We
must remove of these keys in the serializer to keep only `is_admin` to
be less confusing and less error prone. `can_return_live_info` was
introduce in a first time to allow to return live_info for student when
they want to join a discussion. But finally we decided to inject these
informations from the front directly instead of the back application to
not disclose sensitive informations. We forget to change its name.
=> ♻️(back) only use is_admin in serializer context

CHANGELOG.md, src/backend/marsha/core/tests/test_api_video_live_pairing.py, src/backend/marsha/settings.py, src/backend/setup.cfg
The recently added `/api/pairing-challenge` url will be used in a
browser to a not recognized domain. This requests are rejected because
CORS headers are not activated in Marsha. We added the
django-cors-headers package responsible to manage them. The
configuration is not fully made to not block the strategy you want to
use. You have to decide on your marsha instance the strategy you want by
configuring one of the following setting `CORS_ALLOWED_ORIGINS`,
`CORS_ALLOWED_ORIGIN_REGEXES` and `CORS_ALLOW_ALL_ORIGINS`.
The full documentation is available here
https://github.com/adamchainz/django-cors-headers#configuration
=> ✨(back) allow to configure CORS headers

src/backend/marsha/core/templates/core/lti_development.html, src/backend/marsha/development/views.py, src/backend/marsha/e2e/test_lti.py, src/backend/marsha/e2e/test_lti_bbb.py
The username used in the LTI development view was set using an hidden
input. We want to choose it, so the hidden input is now a textbox but
moreover we suggest randomly a username, you can use it or choose the
one you want.
=> 💄(dev) generate random username suggested in the lti dev view

src/backend/marsha/development/urls.py, src/backend/marsha/development/views.py, src/backend/marsha/urls.py
In the DevelopmentViewset we use packages required only in development
environment. But this module is imported in marsha.urls and we have a
ModuleNotFoundError in an environment have DEBUG set to False. To avoid
this error, an `urls` module is created in marsha.development and is
loaded in marsha.urls using django.urls.include only when DEBUG is True.
=> 🐛(back) load development urls only when DEBUG is true

src/backend/marsha/development/__init__.py
The development init module import all views. With this import, marsha
is not working in non development environment. This commit complete
commit 3e4a8ed1a0ce3d71ba5283613169e50c0bbc562d.
=> 🐛(back) remove development views from init module

.circleci/config.yml
Installing current js dependencies on an old node_modules can lead to using outdated packages.
A cache search fallback has been removed to prevent this.
=> 👷(yarn) prevent old cache usage for js dependencies

renovate.json
We don't want to upgrade to react router v6 for now. It's a long process
to upgrade it. We decided to ignore this version for now and ignore all
packages depending on it like storybook.
=> Ignore react router in renovate

CHANGELOG.md, src/backend/marsha/asgi.py, src/backend/marsha/core/api/video.py, src/backend/marsha/core/permissions.py, src/backend/marsha/settings.py, src/backend/marsha/websocket/__init__.py, src/backend/marsha/websocket/application.py, src/backend/marsha/websocket/apps.py, src/backend/marsha/websocket/consumers/__init__.py, src/backend/marsha/websocket/consumers/video.py, src/backend/marsha/websocket/defaults.py, src/backend/marsha/websocket/layers.py, src/backend/marsha/websocket/middlewares/__init__.py, src/backend/marsha/websocket/middlewares/jwt.py, src/backend/marsha/websocket/routing.py, src/backend/marsha/websocket/tests/test_consumers_video.py, src/backend/marsha/websocket/tests/test_layers.py, src/backend/marsha/websocket/tests/test_middleware_jwt.py, src/backend/marsha/websocket/tests/test_utils_channel_layers.py, src/backend/marsha/websocket/utils/__init__.py, src/backend/marsha/websocket/utils/channel_layers_utils.py
We want to manage websockets in a dedicated application. For this we
created a new one marsha.websocket and is added to the INSTALLED_APPS
setting.
To identify a user when he tries to connect to the websocket, we want to
use the already existing JWT token. It is not possible to use the
existing mechanisms used with DRF and it's not possible to add
additional headers when a connection to a websocket is made. The token
must be added to the `jwt` query string argument and if valid the token
is added to the consumer scope. Unfortunately it is not possible to
check at this point the resour
he first consumer we need is one related to the Video model object. The
consumer is responsible to accept or not the websocket connection. In
this consumer we check if the resource_id in the token and the id …
=> Create websocket application

CHANGELOG.md, docker-compose.yml, src/backend/marsha/asgi.py, src/backend/marsha/core/api/video.py, src/backend/marsha/core/permissions.py, src/backend/marsha/settings.py, src/backend/marsha/websocket/__init__.py, src/backend/marsha/websocket/application.py, src/backend/marsha/websocket/apps.py, src/backend/marsha/websocket/consumers/__init__.py, src/backend/marsha/websocket/consumers/video.py, src/backend/marsha/websocket/defaults.py, src/backend/marsha/websocket/layers.py, src/backend/marsha/websocket/middlewares/__init__.py, src/backend/marsha/websocket/middlewares/jwt.py, src/backend/marsha/websocket/routing.py, src/backend/marsha/websocket/tests/test_consumers_video.py, src/backend/marsha/websocket/tests/test_layers.py, src/backend/marsha/websocket/tests/test_middleware_jwt.py, src/backend/marsha/websocket/tests/test_utils_channel_layers.py, src/backend/marsha/websocket/utils/__init__.py, src/backend/marsha/websocket/utils/channel_layers_utils.py, src/backend/setup.cfg
We will use the [channel layers](https://channels.readthedocs.io/en/stable/topics/channel_layers.html) feature from django channels. For this we need to install `channels-redis` package, add a redis instance in our docker-compose file and then configure a default channel layer.
This PR is part of #1246
=> Install and configure redis

src/backend/marsha/core/templates/core/resource.html, src/frontend/components/Button/index.tsx, src/frontend/components/LiveVideoPanel/index.tsx, src/frontend/utils/theme/theme.ts
Live button theme is slightly different when displayed on small screen to be properly responsive
Use the Responsive context from grommet to update button's style on small screens
Small layout:
Default layout:
=> Live student buttons responsive

renovate.json
As django is pinned as `<4` in setup.cfg, we want to allow updates for `3.2+` security releases.
Remove django from ignored renovate updates.
=> 🔧(renovate) enable django updates

src/frontend/components/Badge/index.spec.tsx, src/frontend/components/Badge/index.tsx, src/frontend/components/Button/index.spec.tsx, src/frontend/components/Button/index.tsx
Live action button wrongly uses role.
HTML role attribute should conform to https://www.w3.org/TR/wai-aria/  specifications.
Use data-testid if this is really required, else use byRole or byText instead.
=> 🐛(frontend) fix live actions button testId

CHANGELOG.md, src/backend/marsha/core/serializers/video.py, src/backend/marsha/core/tests/test_api_video.py, src/backend/marsha/core/tests/test_utils_xmpp_utils.py, src/backend/marsha/core/utils/xmpp_utils.py
The provided user_id to generate the prosody JWT token is useless and
not used. We can remove it, it will be easier to generate this token in
a non request context.
=> 🔥(back) remove user id in prosody JWT token

Makefile
The help task was self documenting the makefile as expected. It should
display first the name task and then its documentation suffixed by ## in
the makefile. This is the same help task used in other openfun projects
but the usage of MAKEFILE_LIST is modified because we include other
files in our makefile and this variable will contains all file name
included. So we have to use only the first word and not all.
=> 🎨(make) change help task to better display self documenting makefile

.circleci/config.yml
Mjml files are converted into text and html files. If we want
to use these generated files in the code, circle will need
these files in the job test-back otherwise it won't go through.
We change the config so the job test-back can use them.
Change config of circle
=> 🔧(circle) add html and text files to job test-back

src/frontend/package.json, src/frontend/utils/conversejs/converse.ts, src/frontend/utils/conversejs/entry.js, src/frontend/yarn.lock
We are not using converse UI anymore and installing the whole
converse.js package is heavier. We only want to use @converse/headless
package. In order to use, we have to copy an entrypoint front the
converse.js project that loads the library and add it to
window.converse
To ease its usage and modification we keep it in javascript instead of
typescript.
=> ♻️(front) use @converse/headless instead of converse.js

.circleci/config.yml
In test-front job we can increase the number of worker to 2 in order to
speed execution.
=> 👷(circle) increase jest worker to 2

Makefile
We have a task to down the docker-compose stack and one to run it. By
creating the reset stack we can now down the stack, recreate it, apply
the migration and create the prosody admin user.
=> 🔨(make) add reset task

src/backend/marsha/core/management/commands/dev_simulate_reminders.py, src/backend/marsha/core/tests/test_command_dev_simulate_reminders.py, src/backend/marsha/core/tests/test_command_send_reminders.py
Changing emails templates and checking the results without any
tool is complicated. To simplify this task, we create a command
that can only be used in the development environment and that
sends a simple of the four distinct reminders mails. This way
we can easily check the final layout of each mail.
Create a command that creates data and execute send_reminders command, make sure it can only be executed on the development environment.
=> 🔨(command) add a development command to simulate emails

renovate.json, src/frontend/package.json, src/frontend/yarn.lock
We switch from converse.js to @converse/headless package but we still
have to use version 8.0.1, version 9 is not usable for us. We pin this
new package to version 8.0.1 and we ignore new version in renovate.json
configuration.
=> 📌(front) pin @converse/headless to version 8.0.1

src/frontend/data/websocket.spec.ts, src/frontend/data/websocket.ts
To know if we have to connect to the websocket using the ws or wss
protocol, we check the current protocol used to connect to the page,
this protocol is present in window.location.protocol. Depending the
browser implementation, the procotol can include the final `:`
=> 🐛(front) better detect https protocol to connect to the websocket

CHANGELOG.md, renovate.json, src/backend/marsha/core/tests/test_api_document.py, src/backend/marsha/core/tests/test_api_shared_live_media.py, src/backend/marsha/core/tests/test_api_thumbnail.py, src/backend/marsha/core/tests/test_api_timed_text_track.py, src/backend/marsha/core/tests/test_api_update_state.py, src/backend/marsha/core/tests/test_api_video.py, src/backend/marsha/core/tests/test_api_video_shared_live_media.py, src/backend/marsha/core/tests/test_command_check_live_state.py, src/backend/marsha/core/tests/test_command_send_reminders.py, src/backend/marsha/core/tests/test_models_video.py, src/backend/marsha/core/tests/test_serializers_update_state.py, src/backend/marsha/core/tests/test_utils_time_utils.py, src/backend/marsha/core/utils/time_utils.py, src/backend/marsha/settings.py, src/backend/setup.cfg
We can upgrade Django to version 4. We only need to upgrade dockerflow first and then we choose to remove usage of pytz.
Description...
=> Upgrade to Django 4

src/frontend/utils/conversejs/converse-plugins/chatPlugin.ts
When using websockets to establish a connection with the prosody server (
instead of bosh), server is sending stream stanzas (which consists of a stanza
beginning by a 'a' or 'r' tag'. These stanzas are unrecognized by the front and
an error is raised. This current commit introduces a condition to ignore these
stanzas when they are received, and so prevent errors to be raised.
=> 🩹(front) fix stream stanza raising an error

src/frontend/components/PublicVideoDashboard/index.spec.tsx, src/frontend/components/StudentLiveAdvertising/StudentLiveScheduleInfo/index.spec.tsx, src/frontend/components/StudentLiveAdvertising/StudentLiveScheduleInfo/index.tsx, src/frontend/components/StudentLiveAdvertising/index.spec.tsx
Scheduled live delay from now calculation is bugged, it calculates absolute delta from two dates but does not refer to calendar interval.
Use start of days to calculate the number of days before schedule date.
=> fix live schedule info 

src/frontend/components/PublicVideoDashboard/index.spec.tsx, src/frontend/components/StudentLiveWrapper/StudentLiveViewerWrapper/index.tsx
Currently, when a live is paused then resume, the student is presented with the
waiting screen as if the live has not started yet.
We now render the waiting screen only as long as the live has not started once
(aka until the manifest can be fetch). During a pause and when the live is
restarting after a pause, the student is advertise only with the pause screen.
=> ⚡️(frontend) display the student waiting screen only until live has started once

src/frontend/components/StudentViewersList/index.tsx
When there are a lot of viewers,  viewers list length exceeds tab height. The
user can now scroll throught this list.
This PR fixes the issue #1354
=> 🐛(front) fix unscrollable viewers list in tabs

src/frontend/components/Chat/index.tsx, src/frontend/components/DashboardVideoLiveRunning/index.tsx
The chat wasn't rendering as desired in the instructor view and messages were
overlapping 'Pair external device button'. Now the chat has a fixed set to 'large' and a nice blue border when rendered in instructor view.
This PR fixes issue #1355 
This is what is in place now, in the instructor view :
=> 🐛(front) fix unscrollable chat messages in instructor view

src/frontend/types/libs/converse/index.d.ts, src/frontend/utils/conversejs/converse.spec.ts, src/frontend/utils/conversejs/converse.ts
Using only @converse/headless package and not the UI part, there are 
some settings which are not useful anymore. On another hand, some new 
settings are added : 
- idle_presence_timout : set to 0, in order to disable this feature, 
and prevent inactive users to be disconnected
- 18n :  set to 'en' which is the language loaded by default. It preventsconverse 
from displaying an error when trying to load missing localized files (which are 
not needed anyway, because converse UI part is not used)
- ping_interval : reducing ping_interval (default 60) make disconnection 
noticing faster
=> 🔧(front) update converse initialization settings

src/aws/lambda-complete/yarn.lock, src/aws/lambda-convert/yarn.lock, src/aws/lambda-medialive/yarn.lock, src/aws/utils/update-state/yarn.lock
Bumps [ajv](https://github.com/ajv-validator/ajv) to 6.12.6.
- [Release notes](https://github.com/ajv-validator/ajv/releases)
=> ⬆️(aws) Bump ajv to 6.12.6

CHANGELOG.md, src/backend/marsha/core/lti/__init__.py, src/backend/marsha/core/tests/test_lti.py, src/backend/marsha/settings.py
In a LTI request, the locale is defined using the property
launch_presentation_locale in the request. When this one is missing,
since now we were fallbacking with `en` value. We want to configure this
default value and we created a new settings for this named
DEFAULT_LTI_LAUNCH_PRESENTATION_LOCALE
=> ♻️(back) configure with settings the default lti locale

CHANGELOG.md, src/backend/marsha/settings.py
The setting CSRF_TRUSTED_ORIGINS has evolved and we now must configure
it on each marsha instance to allow the usage of CSRF protection.
=> 🔧(back) allow to configure CSRF_TRUSTED_ORIGINS django setting

CHANGELOG.md, src/aws/lambda-complete/package.json, src/aws/lambda-configure/package.json, src/aws/lambda-convert/package.json, src/aws/lambda-elemental-routing/package.json, src/aws/lambda-medialive/package.json, src/aws/lambda-mediapackage/package.json, src/aws/lambda-migrate/package.json, src/aws/utils/update-state/package.json, src/backend/setup.cfg, src/frontend/package.json
- Add model and API endpoints to manage a shared live media
- Add component to display chat, viewers and apps during a live in a panel
- Add `consumer_site` in JWT token
- Allow CORS headers configuration
- Extract SVG pages from PDF files for shared live media in lambda-convert
- Add fields `is_registered`,`live_attendance`,`username` for liveRegistration
- Add DRF endpoint to start attendance monitoring using liveRegistration model
- Add a new chat, using react components and design complying with the mockup
- Add anonymous_id and display_name in LiveRegistration model
- Add new endpoint to set display_name
- Add API endpoints to start, navigate and end a live media sharing
- Add fields `allow_recording`, `estimated_duration`, `has_chat` and
`has_live_media` for Video model and API
- …
=> 🔖(major) bump release to 4.0.0-beta.1

CHANGELOG.md, src/backend/marsha/core/serializers/video.py, src/backend/marsha/core/tests/test_api_video.py, src/backend/marsha/core/tests/test_api_video_shared_live_media.py, src/backend/marsha/core/tests/test_views_lti_video.py, src/backend/marsha/core/tests/test_views_public_video.py, src/backend/marsha/settings.py, src/frontend/components/Chat/index.spec.tsx, src/frontend/components/LiveVideoPanel/index.spec.tsx, src/frontend/components/PublicVideoDashboard/index.spec.tsx, src/frontend/components/PublicVideoLiveJitsi/index.spec.tsx, src/frontend/components/StudentLiveControlBar/index.spec.tsx, src/frontend/components/StudentLiveWrapper/index.spec.tsx, src/frontend/components/VideoPlayer/index.spec.tsx, src/frontend/types/XMPP.ts, src/frontend/types/libs/converse/index.d.ts, src/frontend/utils/conversejs/converse.spec.ts, src/frontend/utils/conversejs/converse.ts
Converse allow to use multiple persistent store. By default the one used
is IndexedDB. This is a modern persistent store avaiable in browsers but
have some caveats. Browsers have more and more mechanisms to protect
user private life, like not allowing the usage of IndexedDB database
when the script using it is not on the same domain (cross domain). In
that specific case (private browsing or by default with Brave), converse
is not usable and does not fallback on an other storage. For this we
want to configure the persistent store used by converse and we can
configure it by changing the XMPP_CONVERSE_PERSISTENT_STORE setting.
=> 🐛(back) allow to configure converse persistent store

src/frontend/apps/bbb/DashboardMeeting/index.tsx, src/frontend/apps/bbb/types/models.ts, src/frontend/apps/bbb/utils/tests/factories.ts
When we start a meeting, no attendees can exists, so the MeetingInfo type must allow it.
Factory should not create an empty array by default.
Description...
=> 🐛(frontend) declare meeting attendees nullable

CHANGELOG.md, CONTRIBUTORS.md, src/backend/marsha/core/admin.py, src/backend/marsha/core/tests/test_admin.py
The `link_field` helper to forge admin URL to the foreign key object was
using the local model's application name instead of the linked model's
application name, resulting in an error for the BBB admin display, as
the ``bbb.Meeting`` model has a foreign key to ``core.Playlist`` model
and the helper was trying to resolve a ``bbb.Playlist`` which doesn't
exist.
Use the linked model application name to reverse the URL properly.
=> :bug:(backend) change model app in `link_field`

.circleci/config.yml, Makefile, bin/lambda
Since docker 18.09 docker introduces a new backend builder image called
buildkit. This new builder improves build performance and should speed
the build. We activate it on circleci by using a newer version of
docker.
=> speed up docker build by activating DOCKER_BUILDKIT

CHANGELOG.md, Dockerfile, docker/images/dev/Dockerfile, docker/images/e2e/Dockerfile
Files of the marsha Python package where copied directly into the
`/builder/` directory making the `setup.cfg` at the same level as the
Django applications' module, resulting in a wrong interpretation of the
package structure: each Django application was considered as a Python
package (thanks to the `find:` automatic attribute).
The issue raised on my side was the `markdown` application overwritting
the `markdown` original package... For instance, the bug was visible in
the `back-builder` image, were the `bbb` application was directly inside
the `/install/lib/python3.10/site-packages/bbb/` folder and so on.
Replace the inline file copy, to a different one to properly copy files into a `/builder/marsha/` directory to generate a `marsha` package.
- Why do we install the `marsha` package …
=> 🐛(docker) Preserve marsha package structure

src/backend/marsha/core/api/live_registration.py, src/backend/marsha/core/serializers/live_registration.py, src/backend/marsha/core/tests/test_api_liveregistration.py, src/frontend/components/Chat/ChatLayout/index.spec.tsx, src/frontend/components/Chat/ChatLayout/index.tsx, src/frontend/components/Chat/SharedChatComponents/InputBar/index.spec.tsx, src/frontend/components/Chat/SharedChatComponents/InputBar/index.tsx, src/frontend/components/Chat/SharedChatComponents/InputDisplayNameOverlay/index.spec.tsx, src/frontend/components/Chat/SharedChatComponents/InputDisplayNameOverlay/index.tsx, src/frontend/components/Chat/StudentChat/index.spec.tsx, src/frontend/components/Chat/StudentChat/index.tsx, src/frontend/components/Chat/index.spec.tsx, src/frontend/components/Chat/index.tsx, src/frontend/components/PublicVideoLiveJitsi/index.spec.tsx, src/frontend/data/sideEffects/setLiveRegistrationDisplayName/index.spec.ts, src/frontend/data/sideEffects/setLiveRegistrationDisplayName/index.ts, src/frontend/data/stores/useChatItemsStore/index.ts, src/frontend/utils/conversejs/converse.ts, src/frontend/utils/initWebinarContext.ts
We want to have a unique display_name by user for a live streaming. We decided to save this display name in the liveRegistration record and use it every time the user connects to the live. This feature uses the `anonymous_id` if the user does not come from a LTI connection.
=> Manage display_name to connect to the chat

src/backend/marsha/core/templates/core/lti_development.html, src/backend/marsha/development/views.py
When we test the same resource both on instructor and student views, we
have to copy paste data on two different tabs.
Now, we display last 5 videos, documents, and meetings, and when we
click them, the form is filled with matching data.
Also, random resource_link_id, user_id, lis_result_sourcedid, and
lis_person_contact_email_primary are generated.
Lastly, the third form now opens a new tab, allowing us to easily
inspect the frontend app with react developer tools.
https://user-images.githubusercontent.com/720491/157286572-4ae07145-e456-449d-a183-0614e7449968.mp4
=> 🧑‍💻(backend) add helpers to development lti form

src/frontend/components/Chat/index.spec.tsx, src/frontend/components/Chat/index.tsx, src/frontend/components/Chat/route.ts, src/frontend/components/ConverseInitializer/index.spec.tsx, src/frontend/components/ConverseInitializer/index.tsx, src/frontend/components/DashboardVideoLive/index.spec.tsx, src/frontend/components/DashboardVideoLive/index.tsx, src/frontend/components/LTIRoutes/index.tsx, src/frontend/components/LiveVideoPanel/index.spec.tsx, src/frontend/components/LiveVideoPanel/index.tsx, src/frontend/components/PublicVideoDashboard/index.spec.tsx, src/frontend/components/PublicVideoLiveJitsi/index.spec.tsx, src/frontend/components/StudentLiveWrapper/index.spec.tsx, src/frontend/components/StudentLiveWrapper/index.tsx, src/frontend/utils/conversejs/converse.ts
Converse is initialize when 'components/Chat/index.tsx' file is loaded but we
can have scripts using converse from window even if converse has not been
initialized yet.
Especially, current implementation works only because we are importing Chat file
in base routeur for the application.
To fix this issue, a new component is created to be responsible for the
initialization of converse and mount component using converse only when this is
done.
=> 🐛(frontend) fix converse initialisation

src/frontend/components/StudentLiveAdvertising/StudentLiveRegistration/RegistrationForm/index.spec.tsx, src/frontend/components/StudentLiveAdvertising/StudentLiveRegistration/RegistrationForm/index.tsx
If the user has no email in its JWT token, he can enter one by using an
input. This input was removed after he enter a first caracter because we
were checking if the entered value was not empty to display this input
or not. We have to do this check on the initial email value and not the
one entered by the user.
=> 🐛(front) keep input register email display

src/frontend/components/PublicVideoDashboard/index.spec.tsx, src/frontend/components/StudentLiveAdvertising/StudentLiveRegistration/RegistrationForm/index.spec.tsx, src/frontend/components/StudentLiveAdvertising/StudentLiveRegistration/RegistrationForm/index.tsx, src/frontend/components/StudentLiveAdvertising/StudentLiveRegistration/index.spec.tsx, src/frontend/components/StudentLiveAdvertising/StudentLiveRegistration/index.tsx, src/frontend/components/StudentLiveAdvertising/index.spec.tsx, src/frontend/data/sideEffects/updateLiveSession/index.spec.ts, src/frontend/data/sideEffects/updateLiveSession/index.ts
A live session can already exists when a user wants to register to the
live. Instead of creating one, we update this one by settings
is_registered to true and the choosen email.
=> (front) update live session on register when one already exists

CHANGELOG.md, src/backend/marsha/core/serializers/video.py, src/backend/marsha/core/tests/test_api_video.py, src/backend/marsha/core/tests/test_views_lti_video.py
When a live is created, it has a IDLE live_state and the XMPP room is
not created at this time. Returning the XMPP info in the serializer is a
mistake and lets think that the XMPP room can be used by the front
application which is not the case.
=> 🐛(back) expose XMPP info for a live once this one started

src/frontend/components/DashboardThumbnail/index.spec.tsx, src/frontend/components/DashboardTimedTextPane/index.spec.tsx, src/frontend/data/websocket.spec.ts, src/frontend/data/websocket.ts, src/frontend/utils/getOrInitAnonymousId.spec.ts, src/frontend/utils/getOrInitAnonymousId.ts, src/frontend/utils/initWebinarContext.ts
To connect to a websocket, we need to add the anonymous_id in the query
string when the current token in a public one.
=> ✨(front) manage anonymous_id with websocket

CHANGELOG.md, src/backend/marsha/core/tests/test_utils_medialive_utils.py, src/backend/marsha/core/utils/medialive_utils.py, src/backend/marsha/settings.py
The medialive input waiter can fails when we try to delete the aws
stack. If the max attempt is reached, a WaiterError is raised, the
endpoint return a 500 and then it is not possible any more to stop a
live. To fix this issue, the WaiterError exception is catch and sent to
sentry and the stop endpoint continues its job.
=> 🐛(back) continue stopping live even if input waiter fails

src/backend/marsha/core/templates/core/lti_development.html
To be more accurate with how Marsha is used in a LMS, we decided to
limit the iframe width where the LTI request is used in the development
template. Doing this, we don't have to integrate Marsha in LMS to detect
some bugs.
=> 🔨(dev) limit iframe width

CHANGELOG.md, src/backend/marsha/core/api/video.py, src/backend/marsha/core/tests/test_api_video_recording.py
When the recording is started or stopped, the video is not dispatched in
the websocket. No other participant are aware that the video is
recording.
Fixes #1476
=> 🐛(back) dispatch video in the websocket when start/stop recording

CHANGELOG.md, src/frontend/components/PublicVideoDashboard/index.spec.tsx, src/frontend/components/PublicVideoDashboard/index.tsx
LiveVideoWrapper component could be loaded without
the initialization of the LiveSession. This resulted
in not being able to register, as two LiveSessions
were created simultaneously.
Force the creation of the LiveSession before loading LiveVideoWrapper component
=> 🐛(front) Fix registration to scheduled events

src/frontend/components/Chat/SharedChatComponents/ChatMessageMetadatas/index.tsx
The width of the user's avatar icon was crushed and was not making a square, as
it was supposed to do.
=> 🩹(front) fix avatar icon's crushed width in chat

.circleci/config.yml
For crowdin to detect the translations needed for emails,
the circle ci needs to run the i18n job after the job
that generates emails.
add build-mail as a dependance
=> ♻️(i18n) emails must be generated before the i18n job

CHANGELOG.md, src/aws/lambda-complete/package.json, src/aws/lambda-configure/package.json, src/aws/lambda-convert/package.json, src/aws/lambda-elemental-routing/package.json, src/aws/lambda-medialive/package.json, src/aws/lambda-mediapackage/package.json, src/aws/lambda-migrate/package.json, src/aws/utils/update-state/package.json, src/backend/setup.cfg, src/frontend/package.json
- Add a view to cancel reminder mails, link added in the footer of mails
- Prevent multiple join to BBB meetings
- Introduce anonymous_id mechanism
- Create a direct access to a video out of an LMS context for a public
or LTI ressource, based on a liveregistration
- Auto-set in the localstorage anonymousId if it's set in the JWT token
- Persist live video participants
- Add a vertical slider on the live view, to resize the panel on the
right (and close / open it)
- Add PATCH endpoint to update a LiveSession
- Add start and stop live recording
- Generate a JWT token to connect to jitsi
- Save livesession registration date
- rename LiveRegistration model in LiveSession
- Disable jitsi prejoin page
- Admin can access all LiveSession belonging to a video
- Move on-stage request functional (in …
=> 🔖(beta) bump release to 4.0.0-beta.2

.circleci/config.yml
The email templates are missing in the build-back-i18n job and so their
translations string too. This is because the marsha workspace is not
attached in this job. We attach it in this commit to resolve this
issue.
=> 🔧(ci) attach workspace in build-back-i18n job

CHANGELOG.md, src/frontend/components/DashboardVideoHarvested/index.spec.tsx, src/frontend/components/DashboardVideoHarvested/index.tsx, src/frontend/components/DashboardVideoPane/index.spec.tsx, src/frontend/data/queries/index.spec.tsx, src/frontend/data/queries/index.tsx
Updating the video using a PUT request is not the better way to update a
video. The title is null when the video is created but we force it to
not be null when the user tries to update it. Using a PUT request, we
send the entire object and, sometimes, the title can be null. To fix
this issue, we decided to use a PATCH request and send only the needed
fields in the body.
=> patch video to publish it once harvested

CHANGELOG.md, src/backend/marsha/core/tests/test_api_livesession.py, src/backend/marsha/core/tests/test_command_send_reminders.py, src/mail/bin/html-to-plain-text, src/mail/mjml/partial/footer.mjml, src/mail/mjml/partial/hello.mjml, src/mail/mjml/partial/video_access_url.mjml, src/mail/mjml/register.mjml, src/mail/mjml/reminder.mjml, src/mail/mjml/reminder_date_updated.mjml
Previous commit 2c72a92a already indicated that mjml files were capricious.
New lines were inserted in html and text files and disrupted the
translation of the file. To be consistent, all the spaces before the `trans`
tags have been deleted. For text versions of emails, the word wrapping has
been set so that `trans` instructions don't get broken. In order to keep
the conversion of the mjml files into html and text reliable, tests have
been added to make sure, there are no `trans` tags that don't get properly
transformed.
format mjml files, test there is no tag trans in the mail content, stop wordwrapping with the conversion to text
NB: in the documentation of html-to-text it said that word wrapping can be canceled with the value Null or False, unfortunately, it doesn't give the right …
=> 🎨(emails) mjml conversion to html and text

src/backend/locale/fr_FR/LC_MESSAGES/django.po, src/backend/marsha/core/management/commands/send_reminders.py, src/backend/marsha/core/tests/test_api_livesession.py
When preparing the release of Marsha 4.0.0-beta.3 the detection
of a translation was missing. We need to add it.
Other translations have changed and are used in tests, so we
need to update the code.
Add translation detection + change translation to match crowdin update
=> 🐛(i18n) mail object translations

CHANGELOG.md, src/frontend/components/Dashboard/DashboardVideoWrapper/index.spec.tsx, src/frontend/components/DashboardVideoLive/index.spec.tsx, src/frontend/components/DashboardVideoLive/index.tsx, src/frontend/components/DashboardVideoLiveControlPane/index.spec.tsx, src/frontend/components/DashboardVideoLiveControlPane/index.tsx, src/frontend/components/DashboardVideoLiveControlPane/widgets/DashboardVideoLiveWidgetLivePairing/index.spec.tsx, src/frontend/components/DashboardVideoLiveControlPane/widgets/DashboardVideoLiveWidgetLivePairing/index.tsx, src/frontend/components/DashboardVideoLiveControlPane/widgets/DashboardVideoLiveWidgetTemplate/index.spec.tsx, src/frontend/components/DashboardVideoLivePairing/index.spec.tsx, src/frontend/components/DashboardVideoLivePairing/index.tsx
The appairing component was mounted alone in the top of the dashboard.
Now we have a dashboard decoupled in widgets. The appairing should live
now in a dedicated widget and remove it from the top.
=> ♻️(front) move appairing component in a dashboard widget

src/frontend/components/SelectContent/index.spec.tsx, src/frontend/components/SelectContent/index.tsx
When we add multiple custom apps, the loaded tabs in the lti select resource view weren't working.
Clicking on one of the custom tabs was always displaying the last one.
Wrap each lazy loaded tab in his own suspense component.
=> 🐛(frontend) fix lti select view tabs

src/aws/cloudfront.tf, src/aws/lambda-convert/src/convertSharedLiveMedia.js, src/aws/lambda-convert/src/convertSharedLiveMedia.spec.js, src/backend/marsha/core/serializers/shared_live_media.py, src/backend/marsha/core/tests/test_api_shared_live_media.py, src/backend/marsha/core/tests/test_api_video.py
Some feature are missing to correctly use shared live media feature. First the source file was not copied to the destination bucket and we need it to download it in the video dashboard. Then, the generated url to access it was not accurate with the choosen S3 key and finally there was no rule in the cloudfront distribution to access it.
=> Manage access to shared live media with cloudfront

CHANGELOG.md, UPGRADE.md, docs/env.md, env.d/development.dist, src/aws/.terraform.lock.hcl, src/aws/cloudfront.tf, src/aws/output.tf, src/aws/provider.tf, src/backend/marsha/core/serializers/file.py, src/backend/marsha/core/serializers/shared_live_media.py, src/backend/marsha/core/serializers/timed_text_track.py, src/backend/marsha/core/serializers/video.py, src/backend/marsha/core/tests/test_api_shared_live_media.py, src/backend/marsha/core/tests/test_api_timed_text_track.py, src/backend/marsha/core/tests/test_api_video.py, src/backend/marsha/settings.py
Previously we used the trusted signer from the AWS root account. This
strategy is no more recommanded. The recommanded way is to manage the
public keys in the cloudfront account. This keys can be created by an
IAM user and easily rotate.
First you have to install `hashicorp/tls` provider by running `./bin/terraform init` in the `src/aws` directory.
Then the new terraform plan must be applied:
```bash
$ cd src/aws
$ make apply
```
Once done, a new ssh key pair has been generated. The public key is in the cloudfront management public keys and you have to use the corresponding ssh private key in your marsha installation. You have to retrieve it and replace your actual ssh private key by this one.
```bash
$ ./bin/terraform output cloudfront_ssh_private_key
```
You also have to remove the …
=> Use cloudfront public keys management insterad of AWS root account

src/frontend/components/DashboardVideoLiveControlPane/index.tsx
When we are using the Dashboard video live control panel with 2 columns,
we want to have the general and the description on the right side with
the general widget before the description one.
=> ♻️(front) reorganize widget order in the live dashboard

src/frontend/components/SchedulingFields/index.tsx
The calendar was displayed under the date input and part of it was sometimes
appearing outside the iframe, making it unusable. The current behavior is now
to be always displayed above the dateinput and given our application layout, it
guarantees it will always have enought space to display.There was also a
problem with the calendar button on the date input, which wasn't disabled when
the prop 'disabled' was on. It is now fixed by disabling pointerEvents on its
parent component.
=> 🩹(front) fix calendar display

.gitignore, src/frontend/package.json
When we want to have a list of the failing tests, regular jest output
isn't very convenient. A script shortcut has been added to display them
nicely.
Also, a quick and dirty test coverage command has been added to target a
specific component, run his test and display the coverage report on it
only.
=> 🧑‍💻(frontend) add jest test helper commands

renovate.json
We upgraded jest to version 28 but we missed to remove it from the
package to ignore to update with renovate. We must remove it to accept
future releases.
=> 🔧(renovate) remove jest from ignored packages

docs/env.md, src/aws/lambda.tf, src/aws/variables.tf
Depending the environment you are using this lambda, you can change the
allocated memory by using the TF_VAR_lambda_convert_memory environment
variable. For example in production you can increase it to convert large
shared live media.
=> ♻️(aws) allow to configure allocated memory to lambda convert

src/frontend/components/VideoPlayer/index.tsx
Videojs player is never destroyed.
To destroy the videojs player, a condition based on the component state was
present to ensure the player exists.
But this conditions uses a variable that we capture in the closure and never
refreshed.
Use the local player variable instead.
=> 🐛(frontend) videojs player is never destroyed

docs/cache.md, src/backend/marsha/core/cache.py, src/backend/marsha/core/tests/test_cache.py, src/backend/marsha/core/utils/throttle.py, src/backend/setup.cfg
When redis is down and used as cache backend we want to fallback on an
other backend cache to avoid denial of service. For this we have copied
the fallback cache used in the openfun/richie project and we adapt it to
our use case. For example we don't need to clear any cache if redis is
up again, the cache we are using has a lifetime.
=> create fallback cache strategy when redis is down 

CHANGELOG.md, src/aws/lambda-complete/package.json, src/aws/lambda-configure/package.json, src/aws/lambda-convert/package.json, src/aws/lambda-elemental-routing/package.json, src/aws/lambda-medialive/package.json, src/aws/lambda-mediapackage/package.json, src/aws/lambda-migrate/package.json, src/aws/utils/update-state/package.json, src/backend/setup.cfg, src/frontend/package.json
- Add a control pane destined to contain widgets for the instructor to
control the live
- Add a widget to modify live title and allow / disallow live recording
- Add a widget to schedule live and modify description
- Add a widget to hide / unhide the chat, for the instructor and for its
students
- Add Markdown document edition (new feature)
- Add a widget to make live publicly available and get the shareable url
- New field deleted_by_cascade on all model inheriting from SafeDeleteModel
Field added in django-safedelete version 1.2.0
- CLOUDFRONT_SIGNED_PUBLIC_KEY_ID settings is added. It contains the
public key id created on AWS cloudfront public keys
- Push attendances for students watching a live
- Add a login page to authenticate Marsha users
- Allow live restarting after harvesting
- …
=> 🔖(beta) bump release to 4.0.0-beta.4

CHANGELOG.md, src/backend/marsha/core/serializers/base.py, src/backend/marsha/core/serializers/shared_live_media.py, src/backend/marsha/core/serializers/timed_text_track.py, src/backend/marsha/core/serializers/video.py, src/backend/marsha/core/tests/test_api_shared_live_media.py, src/backend/marsha/core/tests/test_api_timed_text_track.py, src/backend/marsha/core/tests/test_api_video.py, src/backend/marsha/core/tests/test_views_lti_cache.py, src/backend/marsha/core/utils/cloudfront_utils.py, src/backend/marsha/settings.py
Since the beginning of marsha we used predefined signed url to request
cloudfront. So we needed to generate a signed url for each resources we
want to fetch. Signing a url is a low operation and when we introduced
shared_live_media resources we had a bottleneck on the video and
shared_live_media serializer. To fix this issue, we decided to use a
custom policy[1]. This custom policy target at once all the resource
belonging to a given video. We sign this this policy once and then we
catch all the needed parameters to use them with all the resources
related to this video.
[1]: https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-signed-urls.html#private-content-choosing-canned-custom-policy
=> ♻️(back) use custom policy to generate cloudfront signed url

CHANGELOG.md, src/frontend/components/DashboardVideoLiveJitsi/index.spec.tsx, src/frontend/components/DashboardVideoLiveJitsi/index.tsx
Non moderator will also execute the start-streaming command in jitsi
when a moderator start streaming resulting in log of notification error
telling that the user is not allowed to start streaming.
Fixes #1554
=> 🐛(front) do not execute start streaming in jitsi for non moderator

src/frontend/components/DashboardVideoLiveJitsi/index.spec.tsx, src/frontend/components/DashboardVideoLiveJitsi/index.tsx
When the DashboardVideoLiveJitsi is mounted and the video.live_state is
already running but jitsi was not streaming, nothing happened. Now when
the first moderator joins, jitsi will start streaming.
=> 🐛(front) start jitsi streaming once component load and already running

src/backend/marsha/settings.py
Last simplejwt update introduced JWTStatelessUserAuthentication as a
replacement for JWTTokenUserAuthentication.
Even if they provided backward compatibility, we align our code with
their current implementation.
=> 👽️(backend) use newly added JWTStatelessUserAuthentication

CHANGELOG.md, src/aws/lambda-complete/package.json, src/aws/lambda-configure/package.json, src/aws/lambda-convert/package.json, src/aws/lambda-elemental-routing/package.json, src/aws/lambda-medialive/package.json, src/aws/lambda-mediapackage/package.json, src/aws/lambda-migrate/package.json, src/aws/utils/update-state/package.json, src/backend/setup.cfg, src/frontend/package.json
- Push attendance when a student is on stage
- Add Legacy LTI configuration XML
- Add an instructor widget to modify join the discussion mode
- Prevent join API calls in join mode denied
- Use custom policy to generate cloudfront signed url
- Upgrade front and mail apps to node version 16, the current LTS
- On LTI select request, only send title and description for existing resources
- Adding a new resource through LTI select (deeplinking) now creates it
with data from Moodle activity titles and description.
- Fetch video data after websocket reconnection
- Use Roboto-Regular by default in our UI
- Do not execute start streaming in jitsi for non moderator
- Prevent scroll when hovering a select on an iframe
=> 🔖(beta) bump release to 4.0.0-beta.5

src/backend/marsha/websocket/consumers/video.py, src/backend/marsha/websocket/middlewares/jwt.py, src/backend/marsha/websocket/tests/test_consumers_video.py, src/backend/marsha/websocket/tests/test_middleware_jwt.py, src/frontend/data/websocket.spec.ts, src/frontend/data/websocket.ts
When a JWT is invalid and the current video does not match the JWT, we
want to close the websocket with a 4003 code. Unfortunately, the code
can't be specified during handshake process. We must first accept the
connection and close it immediatly with the wanted code.
=> close websocket with specific code when JWT invalid

CHANGELOG.md, src/backend/marsha/core/api/video.py, src/backend/marsha/core/tests/test_api_video.py, src/backend/marsha/core/tests/test_views_lti_select.py, src/backend/marsha/core/views.py, src/backend/marsha/e2e/test_lti.py, src/frontend/components/LTIRoutes/index.tsx, src/frontend/components/SelectContent/index.spec.tsx, src/frontend/components/SelectContent/index.tsx, src/frontend/data/queries/index.spec.tsx, src/frontend/data/queries/index.tsx, src/frontend/types/AppData.ts, src/frontend/utils/tests/factories.ts
In the LTI select view (deeplinking) we want to separate webinars from VOD.
When a user adds a new webinar here, the AWS stack is created.
=> ✨(lti-select) split webinars from videos

src/backend/marsha/core/models/video.py, src/backend/marsha/core/tests/test_models_video.py, src/backend/marsha/core/tests/test_xapi.py, src/backend/marsha/core/xapi.py
The activity_type in a video XAPI statement depends if it's a live or
not. We use the new model property is_live to check this.
=> 🐛(back) correctly check if video is live to set the activity_type 

CHANGELOG.md, src/aws/lambda-complete/package.json, src/aws/lambda-configure/package.json, src/aws/lambda-convert/package.json, src/aws/lambda-elemental-routing/package.json, src/aws/lambda-medialive/package.json, src/aws/lambda-mediapackage/package.json, src/aws/lambda-migrate/package.json, src/aws/utils/update-state/package.json, src/backend/setup.cfg, src/frontend/package.json
- Add a widget for the instructor to upload thumbnail
- Add video stats from configurable grafana backend
- Add shared media support for the teacher
- Manage live media sharing with picture-in-picture on student side
- Add a webinar tab to the LTI select view
- A thumbnail resource can be deleted and recreated.
=> 🔖(beta) bump release to 4.0.0-beta.6

CHANGELOG.md, src/backend/marsha/core/api/video.py, src/backend/marsha/core/tests/test_api_video.py
When the live restart we need to delete the stopped_at key.
We reset the started_at to the current timestamp of the
last restart.
delete the stopped_at and set started_at to the new timestamp
=> ✨(back) started_at and ended_at are reseted on running

src/backend/marsha/settings.py
The cache_key used in the LiveSessionThrottle only take care of the
current request. We should restrict more this cache_key by adding the
current anonymous_id.
Also, the throtlle used in the application is not configurable. We want to
ajust it to a given situation. For this, the settings are overriding
using REST_FRAMEWORK_ANON_THROTTLE_RATE and
REST_FRAMEWORK_LIVE_SESSION_THROTTLE_RATE environment variable.
=> Configure rest framework throttling

CHANGELOG.md, src/backend/marsha/core/templates/core/lti_development.html, src/backend/marsha/markdown/api.py, src/backend/marsha/markdown/models.py, src/backend/marsha/markdown/tests/test_api.py, src/backend/marsha/markdown/tests/test_views_lti.py, src/backend/marsha/markdown/urls.py, src/frontend/apps/markdown/types/models.ts
The path to request a markdown document in LTI was
/lti/markdown_documents while we are using /api/markdown-documents for
the API. We choose to normalize every routes and choose
markdown-documents.
=> ♻️(markdown) rename route in markdown-documents

CHANGELOG.md, src/backend/marsha/core/migrations/0051_migrate_live_state.py
In the migration 0049 we apply some modification that were pending since
a while to finish the beta process without any pending migration. Doing
this, we missed to migrate some data in the database. The video
upload_state and live_state choices have changed. We must migrate the
corresponding data to have a coherent database.
=> 🐛(back) missing migration migrating video upload_state and live_state data

CHANGELOG.md, src/aws/lambda-complete/package.json, src/aws/lambda-configure/package.json, src/aws/lambda-convert/package.json, src/aws/lambda-elemental-routing/package.json, src/aws/lambda-medialive/package.json, src/aws/lambda-mediapackage/package.json, src/aws/lambda-migrate/package.json, src/aws/utils/update-state/package.json, src/backend/setup.cfg, src/frontend/package.json
- Allow instructor to share a video and use breakout rooms
- Add resizing feature to the picture in picture mode
###Changed
- stopped_at is deleted and started_at is reinitialized when the
live is restarted
- Display number of anonymous instead of their pseudos
- Rename markdown route in markdown-documents
- Missing migration to migrate video upload_state and live_state data
=> 🔖(beta) bump release to 4.0.0-beta.7

src/frontend/data/websocket.spec.ts
In the websocket test suite, when we try to reconnect to a new websocket
when the first one close, we had performance issue and the test can take
up to 10 seconds. The solution is to clean all connections.
=> ⚡️(front) clean websockets in test to speed them

CHANGELOG.md, src/frontend/utils/tests/imageSnapshot.tsx
Chrome uses multiples layers of sandboxing and the host should be
configure to work with these sandbox. Since ubuntu 22.04 I found no way
to configure chrome sandboxing and I am not able anymore to run the all
test suite without disabling the sandbox. Disabling the sandbox is
optional and you must use an environment variable for this. To disable
it, the environment variable to use is DISABLE_PUPPETEER_SANDBOX and you
must set it to 1 to disable sandboxing.
=> 🔨(front) allow to disable chrome sandboxing with puppeteer

CHANGELOG.md, src/backend/marsha/core/migrations/0052_migrate_livesession_liveattendance.py, src/backend/marsha/core/tests/test_migration_livesession.py
Previous commit 67f8233b transformed milliseconds keys to
keys in seconds. For data existing in the database, a migration
is needed to do this conversion.
Description...
For existing record containing wrong keys, data are transformed
=> 🗃️(marsha) migration live_attendance's key are timestamps

src/backend/marsha/core/tests/test_api_xapi_statement.py
One of our test was wrongly mocking an XAPI call.
Maybe some change on the targeted server suddenly broke it.
See https://app.circleci.com/pipelines/github/openfun/marsha/7595/workflows/09889488-699d-4b54-befc-cacfc7f1cf90/jobs/231970
Fix the mock in the test.
=> ✅(backend) fix a broken test

CHANGELOG.md, src/frontend/components/Dashboard/DashboardVideoWrapper/index.spec.tsx, src/frontend/components/Dashboard/DashboardVideoWrapper/index.tsx
Once a webinar ended, there is no reason, no matter the video
upload_state, to redirect the user to the webinar dashboard. It must be
redirected to the VOD dashboard.
=> 🐛(front) redirect to the VOD dashboard when the live_state is ended

src/backend/marsha/core/simple_jwt/__init__.py, src/backend/marsha/core/simple_jwt/tokens.py, src/backend/marsha/core/simple_jwt/utils.py, src/backend/marsha/core/tests/test_simple_jwt_tokens.py, src/backend/marsha/core/tests/test_views_lti_respond.py, src/backend/marsha/core/views.py, src/backend/marsha/settings.py, src/backend/marsha/websocket/middlewares/jwt.py
Marsha uses different kind of JWT along the way, this PR aims to make different uses more explicit.
Refactor JWT use in Marsha to separate their concerns between JWT for resource and JWT for user (and other JWTs).
This first step, moves the JWT creation to a dedicated module.
Three classes are introduced here:
- `LTISelectFormAccessToken` not used for authentication
- `ResourceAccessToken` built from resource or live session
- `UserAccessToken` for user authentication
The tokens in the testing suite are still forged using the `AccessToken` class and will require a global refactor to use proper class in each case. This will be done in another pull request.
=> ♻️(backend) don't mix JWT usages

src/backend/marsha/core/simple_jwt/factories.py, src/backend/marsha/core/simple_jwt/tokens.py, src/backend/marsha/core/tests/test_api_organization.py, src/backend/marsha/core/tests/test_api_playlist.py, src/backend/marsha/core/tests/test_api_shared_live_media.py, src/backend/marsha/core/tests/test_api_timed_text_track.py, src/backend/marsha/core/tests/test_api_user.py, src/backend/marsha/core/tests/test_api_video.py, src/backend/marsha/core/tests/test_views_site.py
Turn the current "user authentication JWT" into a JWT with a specific kind (`user_access`).
First step to be able to use a different kind is to update all the test suite to use the proper JWT. Two solutions exist for this :
- Call the `UserAccessToken.for_user` in tests
- Create a factory to ease (slightly) the process of user token creation
Choice has been made in this pull request to create a factory even if does not provide real help, it might be consistent with further developments (for `ResourceAccessToken` probably).
=> (backend) update user related JWT kind

src/backend/marsha/core/tests/test_views_lti_video.py, src/backend/marsha/core/views.py
Reduce code complexity by explicitly splitting LTI and "public" behavior for JWT management.
`BaseLTIView` defines `_get_app_data` method and accept both with and without LTI process. On the other hand `BaseView` inherits from `BaseLTIView` and redefines `_get_app_data` method for public access. 
In both views, the "with or without" LTI complexity is propagated all along the way until the JWT creation. This pull request aims at making both path more distinct to improve readability and understanding of "what happens, when".
=> ♻️(backend) Simplify marsha base views (for JWT use)

src/backend/marsha/core/simple_jwt/permissions.py, src/backend/marsha/core/simple_jwt/tokens.py, src/backend/marsha/core/tests/test_simple_jwt_tokens.py, src/backend/marsha/core/views.py
Use `ResourceAccessToken` creation method according to the context (LTI or not)
Split creation methods and make them all rely on the simplest one: `for_resource_id`
=> ♻️(backend) Split `ResourceAccessToken` creation methods

src/backend/marsha/core/simple_jwt/tokens.py, src/backend/marsha/core/tests/test_views_lti_respond.py, src/backend/marsha/core/tests/test_views_lti_select.py
Turn the current "LTI select form JWT" into a JWT with a specific kind (`lti_select_form_access`).
This JWT does not require a dedicated factory as its use is very limited in code and the major part of the tests asserts broken JWTs don't work.
=> ♻️(backend) update "LTI select form" related JWT kind

src/frontend/Player/createPlayer.ts, src/frontend/components/PublicVideoDashboard/index.spec.tsx, src/frontend/components/StudentLiveWrapper/index.spec.tsx, src/frontend/components/VideoPlayer/index.spec.tsx, src/frontend/components/VideoPlayer/index.tsx, src/frontend/data/stores/useTimedTextTrack/index.tsx, src/frontend/data/stores/useTimedTextTrackLanguageChoices/index.tsx, src/frontend/types/VideoPlayer.ts
When subtitles were added / removed in the useTimedTextTrack store, VideoPlayer
was rerendering and adding new track tags in the DOM. But VideoPlayer was not
able to correctly manage this use case and was crashing because it wasn't able
to remove old track tags. This commit aims to fix this flaw.
With this commit, this process is now managed
programmatically, which is resulting in a better functionning of the videojs API.
=> 🐛(front) fix player crash when subtitles are updated

src/backend/marsha/.cookiecutter/{{cookiecutter.app_name}}/api.py, src/backend/marsha/bbb/api.py, src/backend/marsha/core/api/account.py, src/backend/marsha/core/api/base.py, src/backend/marsha/core/api/file.py, src/backend/marsha/core/api/live_session.py, src/backend/marsha/core/api/playlist.py, src/backend/marsha/core/api/shared_live_media.py, src/backend/marsha/core/api/thumbnail.py, src/backend/marsha/core/api/timed_text_track.py, src/backend/marsha/core/api/video.py, src/backend/marsha/core/api/xapi.py, src/backend/marsha/core/permissions.py, src/backend/marsha/core/serializers/live_session.py, src/backend/marsha/core/serializers/shared_live_media.py, src/backend/marsha/core/serializers/thumbnail.py, src/backend/marsha/core/serializers/timed_text_track.py, src/backend/marsha/core/simple_jwt/authentication.py, src/backend/marsha/core/simple_jwt/tokens.py, src/backend/marsha/core/tests/test_simple_jwt_tokens.py, src/backend/marsha/core/tests/test_views_site.py, src/backend/marsha/markdown/api.py, src/backend/marsha/settings.py, src/backend/marsha/urls.py, src/backend/marsha/websocket/consumers/video.py
This aims at make API views more explicit for authorization between user and resource.
We want to stop using the `request.user` when talking about a resource.
=> ♻️(backend) Make different JWT authentication more explicit in API views

CHANGELOG.md, src/frontend/components/StudentLiveRecordingInfo/index.spec.tsx, src/frontend/components/StudentLiveRecordingInfo/index.tsx, src/frontend/components/StudentLiveWrapper/index.spec.tsx, src/frontend/components/StudentLiveWrapper/index.tsx
We want to inform a student when a live is recording. A label is added on top of the player while recording is on and removed once the recording is stopped.
Fixes #1390
=> Notify students when a recording is started

.circleci/config.yml, docker/images/e2e/Dockerfile, src/backend/marsha/core/api/base.py, src/backend/marsha/core/models/file.py, src/backend/marsha/core/models/video.py, src/backend/marsha/core/serializers/base.py, src/backend/marsha/core/tests/test_utils_api_utils.py, src/backend/marsha/core/utils/api_utils.py, src/backend/setup.cfg
This uncouples the model application and name from the key received by the `lambda convert`.
~Add a mapping between the key received by `update_state` API and the associated resource model.~
Generates a mapping between the key received by `update_state` API and the associated resource model by adding the S3 identifier to the model description.
=> ♻️(backend) make updateable models state dynamic

CHANGELOG.md, src/backend/marsha/core/api/video.py, src/backend/marsha/core/metadata.py, src/backend/marsha/core/services/video_recording.py, src/backend/marsha/core/tests/test_api_video.py, src/backend/marsha/core/tests/test_services_video_recording.py, src/frontend/components/TeacherLiveRecordingActions/StopRecording/index.spec.tsx, src/frontend/components/TeacherLiveRecordingActions/StopRecording/index.tsx, src/frontend/data/queries/index.spec.tsx, src/frontend/data/queries/index.tsx, src/frontend/data/queries/metadata.spec.tsx, src/frontend/data/queries/metadata.tsx, src/frontend/types/metadata.ts
If a video record is too short, lower than the video segment length, the mediapackage harvest job will fail. We have to control, for each record slice this record length and not allow to stop recording while the length is lower than the segment length.
Fixes #1626
=> Avoid record length lower than a video segment length

src/backend/marsha/core/serializers/base.py, src/backend/marsha/core/tests/test_api_shared_live_media.py, src/backend/marsha/core/tests/test_api_timed_text_track.py, src/backend/marsha/core/tests/test_api_video.py, src/backend/marsha/core/tests/test_serializers_base.py, src/backend/marsha/core/tests/utils.py
Allow other resources to generate the Cloudfront URL parameters.
Make the Cloudfront URL parameters function generic.
=> ♻️(back) cloudfront URL parameter for resource

src/aws/.terraform.lock.hcl, src/aws/bin/terraform, src/aws/provider.tf, src/aws/s3.tf
We need to use a more recent version of AWS provider to use some new properties introduction on the lambda function like the ephemeral storage.
=> Upgrade terraform and AWS provider

.circleci/config.yml, .dockerignore, .gitignore, Makefile, crowdin/config.yml, docker-compose.yml, src/frontend/apps/lti_site/components/VideoWidgetProvider/widgets/TitleAndDescriptionWidget/index.tsx, src/frontend/apps/lti_site/components/VideoWidgetProvider/widgets/TitleAndRecordConfigWidget/index.tsx
The frontend i18n directory has been moved to the `apps/lti_site` directory. This change must be reflect on the config of tooling using i18n like crowdin
=> Update frontend i18n path 

CHANGELOG.md, src/frontend/apps/lti_site/components/LocalizedTimedTextTrackUpload/index.tsx, src/frontend/apps/lti_site/components/VideoWidgetProvider/widgets/UploadSubtitles/ToggleSubtitlesAsTranscript/index.spec.tsx, src/frontend/apps/lti_site/components/VideoWidgetProvider/widgets/UploadSubtitles/ToggleSubtitlesAsTranscript/index.tsx, src/frontend/apps/lti_site/components/VideoWidgetProvider/widgets/UploadSubtitles/index.spec.tsx, src/frontend/apps/lti_site/components/VideoWidgetProvider/widgets/UploadSubtitles/index.tsx
Implement the toggle to use subtitle as transcript, in the Subtitles widget on the dashboard.
The toggle appears if the video has subtitles and no transcripts. 
When the toggle is on, the subtitles will be the transcript.
Create a new component, child of [UploadSubtitles](https://github.com/openfun/marsha/blob/feature/anthony/toggle_allowing_subtitle/src/frontend/apps/lti_site/components/VideoWidgetProvider/widgets/UploadSubtitles/index.tsx).
=> ✨(frontend) toggle to use subtitle as transcript

src/aws/lambda-convert/src/scanDepositedFile.spec.js, src/backend/marsha/deposit/admin.py, src/backend/marsha/deposit/models.py, src/frontend/apps/lti_site/apps/deposit/components/Dashboard/index.spec.tsx, src/frontend/apps/lti_site/apps/deposit/components/Dashboard/index.tsx, src/frontend/apps/lti_site/apps/deposit/components/SelectContentTab/index.tsx
The word fileDepository is used many times in string translations or in
the string description. We must split it in two words: file depository.
=> 🌐(front) split fileDespository string in translations sentences

CHANGELOG.md, src/frontend/apps/lti_site/components/VideoWidgetProvider/widgets/UploadSubtitles/ToggleSubtitlesAsTranscript/index.tsx
Translations ids were wrong in ToggleSubtitlesAsTranscript components.
```
[@formatjs/cli] [WARN] [FormatJS CLI] Duplicate message id: "components.DownloadVideo.enableDownloadToggleSuccess", but the `description` and/or `defaultMessage` are different.
[@formatjs/cli] [WARN] [FormatJS CLI] Duplicate message id: "components.DownloadVideo.disallowDownloadToggleSuccess", but the `description` and/or `defaultMessage` are different.
[@formatjs/cli] [WARN] [FormatJS CLI] Duplicate message id: "components.DownloadVideo.allowDownloadToggleFail", but the `description` and/or `defaultMessage` are different.
```
=> 🐛(frontend) fix translations

.circleci/config.yml, CHANGELOG.md, docker-compose.yml, src/aws/lambda-convert/index.js, src/aws/lambda-convert/index.spec.js, src/aws/lambda-convert/src/convertSharedLiveMedia.js, src/aws/lambda-convert/src/convertSharedLiveMedia.spec.js, src/aws/lambda-convert/src/copyDocument.js, src/aws/lambda-convert/src/copyDocument.spec.js, src/aws/lambda-convert/src/encodeTimedTextTrack.js, src/aws/lambda-convert/src/encodeTimedTextTrack.spec.js, src/aws/lambda-convert/src/encodeVideo.js, src/aws/lambda-convert/src/resizeThumbnails.js, src/aws/lambda-convert/src/resizeThumbnails.spec.js, src/aws/lambda-convert/src/scanDepositedFile.js, src/aws/lambda-convert/src/scanDepositedFile.spec.js, src/aws/lambda-convert/src/utils/framerateConverter.js, src/aws/lambda-convert/src/utils/framerateConverter.spec.js, src/aws/lambda-elemental-routing/src/mediapackage.spec.js, src/aws/lambda-mediapackage/index.spec.js, src/aws/lambda-mediapackage/src/check.spec.js, src/aws/lambda-mediapackage/src/harvest.spec.js, src/aws/lambda-mediapackage/src/utils/recordSlicesState/index.spec.js, src/aws/lambda-migrate/src/migrations/0001_encode_timed_text_tracks.spec.js
When a timed text track format is not supported, we want to update the
state with an error and stop the lambda. There is no need to throw an
error and launch the retry lambda strategy.
Also, I added in this PR a fix about how lambda are linted. The usage or prettier was wrong.
Fixes #1700
=> update state with an error when TTT format is not supported 

src/frontend/apps/lti_site/components/VideoWidgetProvider/widgets/DownloadVideo/index.tsx, src/frontend/apps/lti_site/components/VideoWidgetProvider/widgets/UploadSubtitles/ToggleSubtitlesAsTranscript/index.tsx, src/frontend/apps/lti_site/components/graphicals/ToggleInput/index.spec.tsx, src/frontend/apps/lti_site/components/graphicals/ToggleInput/index.tsx
The ToggleInput component label is always truncated. In some specific cases we don't want to truncate it to fully display the label linke in the DownloadVideo and ToggleSubtitlesAsTranscript components.
=> ♻️(front) allow to not truncate ToggleInput label

CHANGELOG.md, src/frontend/apps/lti_site/components/VideoWizard/CreateVOD/index.spec.tsx, src/frontend/apps/lti_site/components/VideoWizard/CreateVOD/index.tsx
When the video title is already set and we are in the VOD creation wizard this existing title should be set in the textbox. This specific case occurs when the video is not created with a classic LTI request but in the LTI select process.
Fixes #1713
=> 🐛(front) use video title in creation wizard if it exists

src/frontend/apps/lti_site/apps/markdown/components/SelectContentTab/index.tsx
In the markdown select content tab, the data was refreshed every 10 seconds. This is not necessary. React-query will already refetch the data when the user will switch between tabs.
=> ♻️(front) remove refetch interval for markdown select-content tab

src/backend/marsha/account/tests/test_views_model_auth.py, src/backend/marsha/account/tests/test_views_social_edu_federation_saml_auth.py, src/backend/marsha/account/urls.py, src/backend/marsha/account/views/model_auth.py, src/backend/marsha/core/api/account.py, src/backend/marsha/core/serializers/account.py, src/backend/marsha/core/simple_jwt/factories.py, src/backend/marsha/core/simple_jwt/tokens.py, src/backend/marsha/core/tests/test_api_challenge_token.py, src/backend/marsha/settings.py, src/backend/marsha/urls.py
To allow the frontend authentication when it will become a single page application, we need to provide a new authentication loop.
The authentication is still made using the Django pages, except at the end, the user is redirected to a "frontend" view with a challenge token. The frontend can then make a request to the backend's API to get a real access token (and maybe later, a pair of access token and refresh token).
=> [backend] Redirect user to frontend with challenge token after login

bin/generate_frontend_lti_app, docs/dev.md, src/frontend/apps/lti_site/apps/.cookiecutter/hooks/post_gen_project.sh, src/frontend/apps/lti_site/apps/.cookiecutter/{{cookiecutter.app_name}}/components/Dashboard{{cookiecutter.model}}/index.tsx, src/frontend/apps/lti_site/apps/.cookiecutter/{{cookiecutter.app_name}}/components/Dashboard{{cookiecutter.model}}/route.ts, src/frontend/apps/lti_site/apps/.cookiecutter/{{cookiecutter.app_name}}/components/RedirectOnLoad/index.spec.tsx, src/frontend/apps/lti_site/apps/.cookiecutter/{{cookiecutter.app_name}}/components/RedirectOnLoad/index.tsx, src/frontend/apps/lti_site/apps/.cookiecutter/{{cookiecutter.app_name}}/components/RedirectOnLoad/route.ts, src/frontend/apps/lti_site/apps/.cookiecutter/{{cookiecutter.app_name}}/components/Routes.tsx, src/frontend/apps/lti_site/apps/bbb/components/DashboardClassroom/route.ts, src/frontend/apps/lti_site/apps/bbb/components/RedirectOnLoad/index.spec.tsx, src/frontend/apps/lti_site/apps/bbb/components/RedirectOnLoad/index.tsx, src/frontend/apps/lti_site/apps/bbb/components/RedirectOnLoad/route.ts, src/frontend/apps/lti_site/apps/bbb/components/Routes.tsx, src/frontend/apps/lti_site/apps/deposit/components/Dashboard/route.ts, src/frontend/apps/lti_site/apps/deposit/components/RedirectOnLoad/index.spec.tsx, src/frontend/apps/lti_site/apps/deposit/components/RedirectOnLoad/index.tsx, src/frontend/apps/lti_site/apps/deposit/components/RedirectOnLoad/route.ts, src/frontend/apps/lti_site/apps/deposit/components/Routes.tsx
Add different checks on the app root route to behave more like the `LTISite` and allow to easily add checks on the `app_data.state`.
Add a `RedirectOnLoad` component which purpose is to make verification then redirect to the corresponding route.
=> ♻️(frontend) use redirect on load for apps

src/backend/marsha/bbb/api.py, src/backend/marsha/bbb/permissions.py, src/backend/marsha/bbb/tests/api/classroom/test_classroomdocuments.py, src/backend/marsha/bbb/tests/api/classroom/test_create.py, src/backend/marsha/bbb/tests/api/classroom/test_service_create.py, src/backend/marsha/bbb/tests/api/classroom/test_service_end.py, src/backend/marsha/bbb/tests/api/classroom/test_service_join.py, src/backend/marsha/bbb/tests/api/classroom/test_update.py
We want the site users to use classroom api.
Open classroom update api to site users.
=> ✨(backend) allow site users to use classroom api

CHANGELOG.md, CONTRIBUTORS.md, src/frontend/apps/lti_site/components/LocalizedTimedTextTrackUpload/index.tsx
turns out that uploading the same file again doesn't trigger the handleChange method on chromium based browsers, and reseting the nativeEvent value solves this bug
=> fix bug on subtitles upload

CHANGELOG.md, src/frontend/apps/lti_site/apps/classroom/components/DashboardClassroomForm/index.tsx
The debounce time in the classroom creation form is too fast for a user-friendly use. By increasing it, the user-journey is more convenient.
- Increase the debounce time in the form
=> Increase classroom form debounce time

src/frontend/apps/lti_site/apps/classroom/components/UploadDocuments/index.spec.tsx, src/frontend/apps/lti_site/apps/classroom/components/UploadDocuments/index.tsx
While uploading, a file was rendered twice. One time in the uploadmanager, and one other in the existing classroomdocuments. Also, the progressbar and the filename were wrongly displayed.
Fixes #1751
=> 🐛(frontend) fix classroom file upload

README.md
This adds few notes on own to start the standalone frontend.
I also tried to update the makefile but did not manage to run the standalone site inside a Node docker because it requires access to the backend which would request more work (and I don't know if it's wanted to add it to makefile).
The error is this one:
`Proxy error: Could not proxy request /api/auth/challenge/ from localhost:3000 to http://localhost:8060/.`
Update root readme file.
=> 📝(frontend) add standalone site startup

CHANGELOG.md, src/aws/lambda-complete/package.json, src/aws/lambda-configure/package.json, src/aws/lambda-convert/package.json, src/aws/lambda-elemental-routing/package.json, src/aws/lambda-medialive/package.json, src/aws/lambda-mediapackage/package.json, src/aws/lambda-migrate/package.json, src/aws/utils/update-state/package.json, src/backend/setup.cfg, src/frontend/apps/lti_site/package.json
- Add router to the layout
- Add menu interaction
- Integrate internationalisation library (react-intl)
- ESLint Fragment mandatory rule
- ESlint better import order rule
- Integrate design Homepage in the standalone website:
- Menu
- Header
- Homepage
- Catch and design error with react-error-boundary
- Enable visibility widget in VOD dashboard
- introduce initialized upload state
- Add BBB presentation upload
- Authenticate the user in the standalone site
- Allow to target a specific resource in LTI Select
- move the lti data queries to the lib_components package
- call api update-state with an error when the timed text track format is not supported by @openfun/subsrt
- rename front application bbb in classroom
- rename lti/filedepositories in lti/deposits
- Fix …
=> 🔖(beta) bump release to 4.0.0-beta.9

CHANGELOG.md, src/backend/marsha/core/lti/utils.py, src/backend/marsha/core/tests/test_lti_utils.py, src/frontend/apps/lti_site/apps/markdown/components/RedirectOnLoad/index.spec.tsx, src/frontend/apps/lti_site/apps/markdown/components/RedirectOnLoad/index.tsx
When a resource is not ready, it should not raise a portability error for intructors or administrators when playlist is ported.
This will prevent the future case where an instructor uploads many videos from the standalone site and copy links in the LMS, request portability, accept it while the video are still uploading.
=> ✨(back) resource not ready and portability

src/frontend/apps/lti_site/components/DashboardLiveJitsi/utils.spec.ts, src/frontend/apps/lti_site/components/DashboardLiveJitsi/utils.ts, src/frontend/apps/lti_site/types/libs/JitsiMeetExternalAPI/index.d.ts
As Jitsi config has been updated, we want to align our type with it.
Fixes #1754 
First I tried to replace our type with @types/gjitsi/meet, but it not seems ap to date (ie: conferenceInfo is missing here)
So I checked every item, `prejoinConfig` is the only one that changed.
=> 👽️(frontend) update jitsi default config

CHANGELOG.md, renovate.json, src/aws/lambda-complete/package.json, src/aws/lambda-configure/package.json, src/aws/lambda-convert/package.json, src/aws/lambda-elemental-routing/package.json, src/aws/lambda-medialive/package.json, src/aws/lambda-mediapackage/package.json, src/aws/lambda-migrate/package.json, src/aws/utils/update-state/package.json, src/backend/setup.cfg, src/frontend/apps/lti_site/package.json
Since we are using channels-redis 4, we have connection issues to redis. We must downgrade it to version <4 and block its upgrade, also django-channels upgrade, while this issue exists.
An issue is open on channels-redis repo lookink what we are experiencing https://github.com/django/channels_redis/issues/332
=> ⬇️(back) pin channels-redis to version <4

.circleci/config.yml, .gitignore, Dockerfile, Makefile, crowdin/config.yml, src/frontend/apps/lti_site/package.json, src/frontend/compile-translations.js, src/frontend/package.json, src/frontend/yarn.lock
Translations are only for now in the lti_site apps. We have to rework all
the translation workflow to be able to translate standalone_site app and
all packages.
To avoid to translate multiple times the same translation or group them
in only one file, source translations are split in 3 files. One for the
lti_site, one for standalone_site and one for all packages containing
translations (This is all extract-* commands).
Then, to compile them, we use the compile-translations.js script to
merge the packages translations with the lti_site or the
standalone_site.
The `compile-translations.js` script is imported from [Richie](https://github.com/openfun/richie) project.
=> ♻️(front) rework frontend translations workflow

src/backend/marsha/core/api/playlist.py, src/backend/marsha/core/tests/api/playlists/test_list.py
The playlist list action results were not reflecting the permissions added on this viewset. The list action was returning the playlist belonging to organizations the user is member. But this is not true. First playlist can be "orphan", not belonging to an organization but also a user can be a playlist administrator without being an organization administrator. The queryset is modified this way.
Also filters backend have been adding, allowing to order and filter the list action. It is possible to order on `created_on` and `title`. And to filter the `organization`.
=> Refactor playlist list action

CHANGELOG.md, src/frontend/apps/lti_site/components/PublicVideoDashboard/PublicVODDashboard/index.spec.tsx, src/frontend/apps/lti_site/components/VideoWidgetProvider/index.spec.tsx, src/frontend/apps/lti_site/components/VideoWidgetProvider/index.tsx, src/frontend/apps/lti_site/components/VideoWidgetProvider/widgets/SharedLiveMedia/SharedLiveMediaItem/index.spec.tsx, src/frontend/apps/lti_site/components/VideoWidgetProvider/widgets/SharedLiveMedia/SharedLiveMediaItem/index.tsx, src/frontend/apps/lti_site/components/VideoWidgetProvider/widgets/SharedLiveMedia/index.spec.tsx, src/frontend/apps/lti_site/components/VideoWidgetProvider/widgets/SharedLiveMedia/index.tsx, src/frontend/yarn.lock
This PR updates the existing `SharedLiveMedia` widget, originally designed to fit in the Live section of the app, to make it compatible with the VOD views. 
To do so we introduce `isTeacher` and `isLive` parameters and build the component regarding to them.
Teacher view :
Student view :
=> Add SharedLiveMedia to public and teach VOD Dashboards

.gitignore, src/frontend/apps/standalone_site/.eslintrc.js, src/frontend/apps/standalone_site/package.json, src/frontend/apps/standalone_site/src/setupProxy.js, src/frontend/yarn.lock
Allow locale configuration to proxy backend (and later be able to deploy a backend on aws for dev purposes)
Use the configuration of the backend adress to configure the proxy.
You can override this config in your local environnement in the file .env.local and target the backend you wish.
=> 🧑‍💻(frontend) configure site proxy

src/backend/marsha/core/management/commands/check_live_state.py, src/backend/marsha/core/tests/test_command_check_live_state.py
In the management command, live_info.started_at is used but stored as a string instead of an integer in database. We must cast it first in integer and then multiple it by 1000 to obtain a timestamp in milliseconds.
=> 🐛(back) cast started_at in int in check_live_state command

CHANGELOG.md, src/backend/marsha/core/api/video.py, src/backend/marsha/core/tests/test_api_schema.py, src/backend/marsha/settings.py, src/backend/marsha/urls.py, src/backend/setup.cfg
To ease the use of Marsha API, we would like to have a page serving swagger listing all available routes for the API. For this, we are using drf-spectacular.
=> ✨(back) install and configure drf-spectacular to serve a swagger ui

CHANGELOG.md, src/backend/marsha/bbb/api.py, src/backend/marsha/bbb/permissions.py, src/backend/marsha/bbb/tests/api/classroom/test_create.py, src/backend/marsha/deposit/api.py, src/backend/marsha/deposit/permissions.py, src/backend/marsha/deposit/tests/api/filedepositories/test_create.py, src/backend/marsha/markdown/api.py, src/backend/marsha/markdown/permissions.py, src/backend/marsha/markdown/tests/api/markdown_documents/test_create.py
When creating one of these resources, we don't yet the resource primary key. But the permission class checking if the user can create a new resource id based on the resource id. For the first resource created in the targeted playlist, the permission returns `True` and `False` for all other resource creation. 
The core permission `IsParamsPlaylistAdmin` and `IsParamsPlaylistAdminThroughOrganization` must be used like we do for the video creation.
=> Manage permissions for classroom, deposit and markdown creation

CHANGELOG.md, src/backend/marsha/core/management/commands/clean_aws_elemental_stack.py, src/backend/marsha/core/tests/test_command_clean_aws_elemental_stack.py, src/backend/marsha/core/tests/test_command_clean_medialive_dev_stack.py, src/backend/marsha/settings.py
Once a live started, all AWS elemental stack are created. Once stopped, the instructor must do an action. Restart it and/or convert it in VOD. If nothing is done, the AWS element resources are leaved unused and use the quota we have on our AWS account.
This resources unused must be removed after several days of inactivity and the video move in a DELETED state.
This PR is part of #1779
=> ✨(back) add management command clean_aws_elemental_stack

CHANGELOG.md, src/aws/lambda-complete/package.json, src/aws/lambda-configure/package.json, src/aws/lambda-convert/package.json, src/aws/lambda-elemental-routing/package.json, src/aws/lambda-medialive/package.json, src/aws/lambda-mediapackage/package.json, src/aws/lambda-migrate/package.json, src/aws/utils/update-state/package.json, src/backend/setup.cfg, src/frontend/apps/lti_site/package.json, src/frontend/apps/standalone_site/package.json, src/frontend/package.json, src/frontend/packages/lib_classroom/package.json, src/frontend/packages/lib_common/package.json, src/frontend/packages/lib_components/package.json, src/frontend/packages/lib_tests/package.json
- Migrate app classroom from LTI to lib-classroom package
- Create lib-classroom package
- Add SharedLiveMedia widget to public and teacher VOD Dashboard
- Add new elements to the public VOD Dashboard :
- Transcript reader
- Video download
- playlists page
- install and configure drf-spectacular to serve a swagger ui
- Management command clean_aws_elemental_stack
- Allow site users to manage classroom documents, deposited files, and markdown images through API.
- Site url serve the build generated by CRA
- Enrich playlist serializer with organization and consumer site infos
- Refactor check_live_state management command to use the live started_at timestamp to filter logs instead of using video creation date.
- fix permission for classroom creation
- fix permission …
=> 🔖(beta) bump release to 4.0.0-beta.11

CHANGELOG.md, src/backend/marsha/bbb/api.py, src/backend/marsha/bbb/tests/api/classroom/test_list.py, src/backend/marsha/deposit/api.py, src/backend/marsha/deposit/tests/api/filedepositories/test_list.py, src/backend/marsha/markdown/api.py, src/backend/marsha/markdown/tests/api/markdown_documents/test_list.py
List endpoint for classroom, deposit and markdown was harcoded and redefining the list method from DRF. We choose to reafctor them in order to use DRF mechanism like ordering and filtering. A dedicated queryset is made for list action. Also, this new queryset includes all resources in playlist **or** organization the user is administrator
=> Refactor list filtering for classroom, deposit and markdown

.circleci/config.yml
The job "test-front" has parallelism but CRA test command doesn't support sharding, so the command are duplicated uselessly.
I create another CircleCI job without parallelism to run the standalone_site tests.
=> ✅(circleci) fix duplicate standalone_site duplicate test

src/backend/marsha/bbb/api.py, src/backend/marsha/bbb/tests/api/classroom/test_list.py, src/backend/marsha/core/api/playlist.py, src/backend/marsha/core/factories.py, src/backend/marsha/core/tests/api/organizations/test_list.py, src/backend/marsha/core/tests/api/playlists/test_list.py, src/backend/marsha/deposit/api.py, src/backend/marsha/deposit/tests/api/filedepositories/test_list.py, src/backend/marsha/markdown/api.py, src/backend/marsha/markdown/tests/api/markdown_documents/test_list.py
The filter on playlist permissions may return the same resource several times.
This can be explained with the fact we use an `OR` filter on two many-to-many relations, resulting in two `OUTER JOIN` and a filter on each on or another.
For instance:
| playlist.id                          | organization_access.id               | organization_access.user_id          | organization_access.role | playlist_access.id                   | playlist_access.user_id                            | playlist_access.role |
|--------------------------------------|--------------------------------------|--------------------------------------|--------------------------|--------------------------------------|----------------------------------------------------|----------------------|
| …
=> 🐛(backend) remove duplicated data on resources API list

src/backend/marsha/settings.py
Store Renater's federation IDP list in cache for faster list rendering.
This setting allows to use a cache to store the SAML Federation metadata in marsha's cache (redis in production).
Without the view to list all Renater's available IDP will be fetch on every display (slower).
=> 🐛(backend) add missing SAML setting to use cache

src/backend/marsha/bbb/tests/test_bbb_utils.py, src/backend/marsha/bbb/utils/bbb_utils.py, src/backend/marsha/settings.py
The record parameter was set to True when a meeting in bbb is created. We want to set this parameter optional and by default set to False to choose when to enable it and on which environment to enable it.
=> ♻️(back) make bbb record optional on meeting creation

CHANGELOG.md, src/backend/marsha/bbb/api.py, src/backend/marsha/bbb/serializers.py, src/backend/marsha/bbb/tests/api/classroom/test_list.py, src/backend/marsha/bbb/utils/bbb_utils.py, src/frontend/apps/standalone_site/src/features/ClassRooms/components/ClassRoom.tsx, src/frontend/packages/lib_classroom/src/data/queries/index.tsx, src/frontend/packages/lib_components/src/types/apps/classroom/models.ts
The classroom serializer is fetching the bbb api to find fresh
information. We don't need this information on the list endpoint.
Removing them increase the performace of this endpoint.
=> ⚡️ use a lite serializer for classroom resource on list endpoint

src/aws/lambda-configure/yarn.lock, src/aws/lambda-convert/yarn.lock, src/aws/lambda-elemental-routing/yarn.lock, src/aws/lambda-medialive/yarn.lock, src/aws/lambda-mediapackage/yarn.lock, src/aws/lambda-migrate/yarn.lock, src/aws/utils/update-state/yarn.lock
Bumps [minimatch](https://github.com/isaacs/minimatch) to 3.1.2.
- [Release notes](https://github.com/isaacs/minimatch/releases)
- [Commits](https://github.com/isaacs/minimatch/compare/v3.0.4...v3.1.2)
---
updated-dependencies:
- dependency-name: minimatch dependency-type: indirect ...
Signed-off-by: dependabot[bot] <support@github.com>
=> ⬆️(front) bump minimatch to version 3.1.2

src/backend/marsha/account/social_pipeline/organization.py, src/backend/marsha/account/tests/test_social_pipeline_organization.py, src/backend/setup.cfg
The roles provided by the Renater SSO is a list, using the new version of `social-edu-federation` provides a list of roles where we can look for a `teacher` role.
=> 🐛(backend) Renater SSO user role is a list

CHANGELOG.md, src/backend/marsha/.cookiecutter/{{cookiecutter.app_name}}/api.py, src/backend/marsha/.cookiecutter/{{cookiecutter.app_name}}/tests/test_api.py, src/backend/marsha/bbb/api.py, src/backend/marsha/bbb/tests/api/classroom/test_retrieve.py, src/backend/marsha/bbb/tests/api/classroom/test_service_join.py, src/backend/marsha/deposit/api.py, src/backend/marsha/deposit/tests/api/filedepositories/test_retrieve.py, src/backend/marsha/markdown/tests/api/markdown_documents/test_retrieve.py
Retrieve endpoints for classroom and deposit were too permissive. Having a token resource was just enought to access all classroom or deposit resources. The id in the route was not checked.
=> 🐛(back) change permission on retrieve endpoints

CHANGELOG.md, src/backend/marsha/bbb/api.py, src/backend/marsha/bbb/serializers.py, src/backend/marsha/bbb/tests/api/classroom/test_create.py, src/backend/marsha/bbb/tests/api/classroom/test_retrieve.py, src/backend/marsha/bbb/tests/api/classroom/test_update.py, src/backend/marsha/bbb/tests/test_utils_tokens.py, src/backend/marsha/bbb/tests/test_views_lti.py, src/backend/marsha/bbb/utils/tokens.py, src/backend/marsha/core/simple_jwt/tokens.py, src/backend/marsha/settings.py, src/frontend/packages/lib_classroom/src/utils/tests/factories.ts, src/frontend/packages/lib_components/src/types/apps/classroom/models.ts
Provide a resource JWT which will be used  by the frontend to authenticate students joining a classroom.
- The standalone site will forge and URL the instructor will share to their student and append this `invite_token` to it
- The standalone will provide a dedicated page for student to access the classroom and the `invite_token` will be used to authenticate requests to the backend.
The way to determine whether the user is a teacher or administrator using DRF permissions gives way to improvement. Still for a first version is help readability and understanding...
=> ✨(backend) add a new "invite token" to allow student to join a classroom from standalone site

src/frontend/packages/lib_classroom/src/components/DashboardClassroomForm/index.spec.tsx
In the `schedules a classroom` scenario, the userEvent library is not able anymore to fill the Date input. Instead of having a valid date, there is `0` as value. Changing to the fireEvent lib fix the issue.
=> 🚨(front) fix DashboardClassroomForm test

CHANGELOG.md, src/frontend/apps/lti_site/components/VideoPlayer/index.spec.tsx, src/frontend/apps/lti_site/components/VideoPlayer/index.tsx
In the VideoPlayer component, we are looking for thumbnail to use tham as poster in the video element. For a webinar, there is no thumbnail nor resolution available and sometimes the rendering of this component fails on this part of the code. We are managing this case to avoid future error.
Fixes #1835
=> 🐛(front) deal with webinar without thumbnail

.circleci/config.yml, src/frontend/package.json, src/frontend/packages/lib_components/src/common/UploadForm/index.spec.tsx, src/frontend/packages/lib_tests/src/render.tsx, src/frontend/packages/lib_tests/src/router.tsx
Front libs where built every time an app is built. This is not optimal. We choose to build them all once at the beginning of build-front job and then only build the app without rebuilding all the libs.
Also in this PR the wrapInRouter function is modified to accept, as new parameter, a function to decorate all routes with a manager like the UploadManager for example.
=> 👷(circle) build only once front libs

CHANGELOG.md, src/backend/marsha/core/api/video.py, src/backend/marsha/core/tests/test_api_video.py
The start live endpoint can be very long. It has to create a complete AWS medialive and mediapackage stack. Once created, the medialive channel is started. Between the creation and the effective start we have to wait few seconds that the medialive channel is ready to be started. In the dashboard, we can't wait this time if there are several instructors on the page. We have to inform them as soon as possible that the live is starting. In a first implementation, we changed the live_state to starting, this clone object was dispatched in the webasocket and then all the AWS work was made. If something fails or in the same time, the video object is modified and then dispatch in the websocket, the starting live_state is lost and the start button is display again in the interface. To avoid this …
=> 🐛(back) force to save the starting live state on the start action

CHANGELOG.md, src/frontend/apps/lti_site/components/VideoWidgetProvider/widgets/UploadSubtitles/ToggleSubtitlesAsTranscript/index.spec.tsx, src/frontend/apps/lti_site/components/VideoWidgetProvider/widgets/UploadSubtitles/ToggleSubtitlesAsTranscript/index.tsx, src/frontend/apps/lti_site/components/VideoWidgetProvider/widgets/UploadSubtitles/index.spec.tsx, src/frontend/apps/lti_site/components/VideoWidgetProvider/widgets/UploadSubtitles/index.tsx
Linked with https://github.com/openfun/marsha/issues/1716
It is possible to use a subtitle as a transcript. To do that, at least one subtitle should be valid and no transcript uploaded. In that case, a toggle appears allowing to use subtitles as transcript. But it disappears once there is no subtitles or at least one transcript exists.
We would like to keep always visible the toggle. Instead of hidding it, we want to disable it and add a tooltip explaining why it is disabled.
Add a useEffect hook to update the component when needed
=> Always show the "use subtitle as transcript" toggle

CHANGELOG.md, src/frontend/apps/standalone_site/src/App.spec.tsx, src/frontend/apps/standalone_site/src/App.tsx, src/frontend/apps/standalone_site/src/conf/global.ts, src/frontend/apps/standalone_site/src/utils/lang.spec.ts, src/frontend/apps/standalone_site/src/utils/lang.ts
In the standalone site, the language code is search in the navigator.language property. With this language code we try to load the translation file dynamically. But the files have a specific name base on a ISO15897 locale code and the value return navigator.language can be not compatible with this format. To fix this issue, we have to maintain a list of available react locales and thentry to guess this format from the navigatore language.
=> 🐛(front) guess ISO15897 locale code in standalone site

CHANGELOG.md, src/aws/lambda-complete/package.json, src/aws/lambda-configure/package.json, src/aws/lambda-convert/package.json, src/aws/lambda-elemental-routing/package.json, src/aws/lambda-medialive/package.json, src/aws/lambda-mediapackage/package.json, src/aws/lambda-migrate/package.json, src/aws/utils/update-state/package.json, src/backend/setup.cfg, src/frontend/apps/lti_site/package.json, src/frontend/apps/standalone_site/package.json, src/frontend/package.json, src/frontend/packages/lib_classroom/package.json, src/frontend/packages/lib_common/package.json, src/frontend/packages/lib_components/package.json, src/frontend/packages/lib_tests/package.json
- classroom (list/create/update)
- Add a new "invite" JWT in classroom API to allow students to join a classroom through a link
- Manage portability requests (list/accept/reject)
- dynamic content in homepage
- page my-contents
- access site visitor mode
- login page
- Add new elements to the teacher VOD Dashboard :
- Attendances from live session
- Allow to store link between an LTI user and a "site" user
- Allow LTI users to request for a playlist portability
- Enable recording when creating a BBB room instance
- Mutualize Eslint configuration
- Shareable classroom link
- Endpoint fetching jitsi info for a specific video (/api/videos/{video_id}/jitsi/)
- Reopen chatrooms in readonly mode when converting a live to a vod
- Number of viewer doesn't include the …
=> 🔖(beta) bump release to 4.0.0-beta.12

CHANGELOG.md, src/frontend/apps/lti_site/components/App/index.tsx
The zustand hook useJwt is using a persistent middleware. A unique name must be set and this name is the key used as local storage key. In  LTI context, we can have several iframe launched in the same page and the JWT token will be overwritten between LTI app present in the page. To fix this, we choose to create unique storage name by checking of in the DOM we have the data-context set by the LTI view. If present we know we are in a LTI context and we can pick in the LTI context the resource modl and it's unique id.
=> 🐛(frontend) create unique storage name for useJwt hook

CHANGELOG.md, src/frontend/apps/lti_site/components/LTIRoutes/index.tsx, src/frontend/apps/lti_site/components/SelectContent/SelectContentTargetedResource/index.tsx, src/frontend/apps/lti_site/components/SelectContent/index.tsx, src/frontend/packages/lib_components/src/types/AppData.ts
Every resource managed with LTI select content have their own new url parameter. Video and Webinar share the same value but they their paramter name is different. We have to reflect this in the front SelectContent component and retrieve both in the AppData.
Fixes #1922
=> 🐛(front) display valid webinar url when creating one with LTI select

CHANGELOG.md, src/frontend/apps/standalone_site/src/App.spec.tsx, src/frontend/apps/standalone_site/src/features/Header/Header.spec.tsx, src/frontend/apps/standalone_site/src/features/Header/Header.tsx, src/frontend/packages/lib_components/src/utils/tests/factories.ts
In the Header, the user full name John Doe was hardcoded. We replace it by the current user full name when available.
- display current user full name instead of John Doe
Closes #1918
=> ♻️(front) display current user full name instead of John Doe

CHANGELOG.md, src/frontend/apps/lti_site/apps/.cookiecutter/{{cookiecutter.app_name}}/utils/parseDataElements/parseDataElements.ts, src/frontend/apps/lti_site/apps/classroom/utils/parseDataElements/parseDataElements.ts, src/frontend/apps/lti_site/apps/deposit/utils/parseDataElements/parseDataElements.ts, src/frontend/apps/lti_site/apps/markdown/utils/parseDataElements/parseDataElements.ts, src/frontend/apps/lti_site/components/App/index.tsx, src/frontend/apps/lti_site/utils/parseDataElements/parseDataElements.spec.ts, src/frontend/apps/lti_site/utils/parseDataElements/parseDataElements.ts, src/frontend/packages/lib_components/src/types/AppData.ts
In the AppData, the resource property was removed once a copy made in the model property. We need to know the resource id outside any react context in order to configure the useJwt zustand storage name. This storage name needs to be unique and we want to use the resource id to make it unique.
=> ⏪️(front) keep resource in AppData

CHANGELOG.md, src/frontend/apps/standalone_site/src/features/Authentication/components/RenaterAuthenticator.tsx
On smaller screens, the select box was not displayed correctly. 
We force the width to the parent width to avoid this issue. 
We display the select box to the top if we don't have enough space at the bottom.
=> 📱(website) improve renater select box

CHANGELOG.md, src/backend/marsha/core/api/account.py, src/backend/marsha/core/api/playlist.py, src/backend/marsha/core/models/playlist.py, src/backend/marsha/core/permissions.py, src/backend/marsha/core/serializers/playlist.py, src/backend/marsha/core/tests/api/organizations/test_list.py, src/backend/marsha/core/tests/api/playlists/test_create.py, src/backend/marsha/core/tests/api/playlists/test_list.py, src/backend/marsha/core/tests/api/playlists/test_retrieve.py, src/backend/marsha/core/tests/api/playlists/test_update.py, src/backend/marsha/core/tests/test_api_playlist_portability.py, src/frontend/apps/standalone_site/src/features/Contents/features/ClassRoom/components/Create/ClassRoomCreateForm.spec.tsx, src/frontend/apps/standalone_site/src/features/Contents/features/ClassRoom/components/Create/ClassRoomCreateForm.tsx, src/frontend/apps/standalone_site/src/features/Playlist/api/usePlaylists/index.ts
Using the standalone site, instructors should be able to create their own playlist and classroom in it. Before this PR, only organization instructors can do that.
In this PR we introduce the following changes:
=> ✨(feature) give organization instructor right to create playlist

src/frontend/apps/lti_site/components/App/AppInitializer/index.spec.tsx, src/frontend/apps/lti_site/components/App/AppInitializer/index.tsx, src/frontend/apps/lti_site/components/App/index.tsx
The jwt store was initialized outside react lifecycle leading to error if the persistent store is already existing. The store initialization has been moved to the AppInitializer waiting the jwt store is fully initialized before using it.
=> 🐛(front) move jwt store initialization in LTI to AppInitializer

CHANGELOG.md, src/aws/lambda-complete/package.json, src/aws/lambda-configure/package.json, src/aws/lambda-convert/package.json, src/aws/lambda-elemental-routing/package.json, src/aws/lambda-medialive/package.json, src/aws/lambda-mediapackage/package.json, src/aws/lambda-migrate/package.json, src/aws/utils/update-state/package.json, src/backend/setup.cfg, src/frontend/apps/lti_site/package.json, src/frontend/apps/standalone_site/package.json, src/frontend/package.json, src/frontend/packages/lib_classroom/package.json, src/frontend/packages/lib_common/package.json, src/frontend/packages/lib_components/package.json, src/frontend/packages/lib_tests/package.json, src/frontend/packages/lib_video/package.json
- Display current user full name instead of John Doe
- service worker 401 reconnect
- Password reset views & API
- Renater IdP's logo display on login page
- Allow organization instructors to create playlists
- profile page and update password form in settings
- Select an organization by default in create playlist form
- Allow instructors to download recorded BBB classroom sessions
- lti:
- service worker 401 reconnect
- Add a check on video file size when uploading content
- Remove deprecated params from BBB API calls
- Keep resource property in AppData
- Create a lib to handle all components for video (VOD and live)
- Optimize LTI images
- Set unique storage name for useJwt hook for LTI
- lti_site:
- Live parameters sync between users
- Display valid webinar url …
=> 🔖(beta) bump release to 4.0.0-beta.13

CHANGELOG.md, src/backend/marsha/core/tests/test_urls.py, src/backend/marsha/urls.py
Do not catch the static or media URLs to redirect to the site.
See https://github.com/openfun/marsha/issues/1981
Ignore the "static" and "media" URL prefix in the catch all URL which provides
the standalone site.
=> 🐛(backend) fix missing URL for statics

CHANGELOG.md, src/frontend/apps/lti_site/components/App/AppInitializer/index.tsx, src/frontend/apps/standalone_site/src/features/Authentication/components/Authenticator.tsx, src/frontend/apps/standalone_site/src/index.tsx, src/frontend/apps/standalone_site/src/init.ts, src/frontend/packages/lib_components/src/hooks/stores/useJwt/index.ts, src/frontend/packages/lib_components/src/types/index.ts, src/frontend/packages/lib_components/src/types/window.ts, src/frontend/packages/lib_components/src/utils/index.ts, src/frontend/packages/lib_components/src/utils/localstorage.spec.ts, src/frontend/packages/lib_components/src/utils/localstorage.ts, src/frontend/packages/lib_video/src/utils/localstorage.spec.ts, src/frontend/packages/lib_video/src/utils/localstorage.ts
With the new authent process, we uses extensively localstorage that might be disable.
Make localstorage optional during authent or simply no longer store data in it for lti since this is not needed at all.
=> Fix localstorage disable

.circleci/config.yml
For future usage of arnold binary in our CI we muste change variable used to connect to docker hub, they are conflicting with environment variable declare in arnold binary.
Also, an improvement is made in e2e tests. We stop building front libs again and again and we use instead the cache created in the `build-libs` job. For this the `working_directory` is changed in e2e tests to use the front directory.
=> Change docker env name in circle config and optimize e2e jobs

CHANGELOG.md, src/backend/marsha/settings.py
We want to be able to configure security settings wantNameId and allowRepeatAttributeName used by the saml backend in python social auth. wantNameId defines if the presence of a name identifier is required and allowRepeatAttributeName defines if it is allowed to repeat attributes in the response.
=> 🔧(back) configure saml_fer settings wantNameId and allowRepeatAttributeName

CHANGELOG.md, src/backend/marsha/account/apps.py, src/backend/marsha/account/checks.py, src/backend/marsha/account/social_pipeline/organization.py, src/backend/marsha/account/tests/test_checks.py, src/backend/marsha/settings.py
When logging through Renater for the first time, organization access is provided, but most of the time the `teacher` role is not properly detected. This should be easy to change in production and we should not allow only one role to give the "instructor" permission but several.
This allow to customize the organization teachers' roles to look for.
The default value is still `teacher` but we can now add more roles to the list in production, such as:
- `faculty`
- `employee`
- `staff`
--
=> 🔧(backend) editable SAML FER teacher role lookup

CHANGELOG.md, src/frontend/apps/lti_site/components/App/AppContentLoader/index.spec.tsx, src/frontend/apps/lti_site/components/App/AppContentLoader/index.tsx, src/frontend/apps/lti_site/components/App/AppInitializer/index.tsx
While loading app, concurrency could occurred between state initialization and state reading causing the app to crash because jwt was net initialized yet. 
We no longer read store directly in js while the file is loaded but rather do that in a React component instead.
Also ensure jwt is initialized before loading the application content.
=> 🐛(frontend) fix lti site initialization concurrency loading

CHANGELOG.md, src/frontend/packages/lib_common/src/theme.ts
Grommet change his accessibility label when the input is required, so the css was not applied anymore and the asterisk was too big:
https://github.com/grommet/grommet/blob/v2.28.0/src/js/components/FormField/FormField.js#L456
https://github.com/grommet/grommet/blob/master/src/js/components/FormField/FormField.js#L486
=> 💄(website) fix prefill input

.circleci/config.yml
Last pip version introduces a bug with ubuntu 20
See https://github.com/pypa/pip/issues/11770
We decided to pin pip to version < 23.0
Thanks @jmaupetit @lunika
=> 💚(e2e) fix e2e pip installation

CHANGELOG.md, CONTRIBUTORS.md, src/backend/marsha/core/api/xapi.py, src/backend/marsha/core/tests/test_api_xapi_statement.py
The xapi endpoints return a 501 status code if no LRS is configured. This a while we are not using LRS configuration anymore but we use special loggers for this purpose.
Change return status code from 501 to 200 in this case, in order to reduce pollution in logs.
=> :bug:(backend) change xapi endpoints status code

CHANGELOG.md, src/backend/marsha/core/api/__init__.py, src/backend/marsha/core/api/playlist_access.py, src/backend/marsha/core/permissions.py, src/backend/marsha/core/serializers/__init__.py, src/backend/marsha/core/serializers/playlist_access.py, src/backend/marsha/core/tests/api/playlist_accesses/test_create.py, src/backend/marsha/core/tests/api/playlist_accesses/test_delete.py, src/backend/marsha/core/tests/api/playlist_accesses/test_list.py, src/backend/marsha/core/tests/api/playlist_accesses/test_retrieve.py, src/backend/marsha/core/tests/api/playlist_accesses/test_update.py, src/backend/marsha/urls.py
This introduces the API endpoints to manage authorization for playlist and their related objects.
Organization admin can list, retrieve, create, update, delete 
Playlist admin can list, retrieve, create, update, delete for their playlists
Playlist instructor can list and retrieve only.
=> ✨(backend) add playlist accesses API

src/frontend/apps/standalone_site/src/features/HomePage/components/HomePage.tsx
In the HomeBanner, two translation messages are having the same id, we can't translate both in crowdin.
=> 🐛(front) fix duplicated intl message id in HomeBanner

src/tray/vars/all/main.yml
We first separate job and pod resources. We want to set limits on pod but not on jobs. On pods, we set limits, configurable in each customer environment. This limit is set to 1 for CPU because marsha needs lot of CPU to start and the memory is set to 2.5Gb, it's a quite hight but this is what we need for now.
=> 🔧(tray) set limit to marsha pod resources

CHANGELOG.md, src/frontend/packages/lib_classroom/package.json, src/frontend/packages/lib_classroom/rollup.config.mjs, src/frontend/packages/lib_common/package.json, src/frontend/packages/lib_common/rollup.config.mjs, src/frontend/packages/lib_components/package.json, src/frontend/packages/lib_components/rollup.config.mjs, src/frontend/packages/lib_tests/package.json, src/frontend/packages/lib_tests/rollup.config.mjs, src/frontend/packages/lib_video/package.json, src/frontend/packages/lib_video/rollup.config.mjs, src/frontend/yarn.lock
Issue: https://github.com/openfun/marsha/issues/2012
Remove lib folder before rollup build to avoid stale files
Description...
=> 🔧(packages) remove lib folder before rollup build to avoid stale files

CHANGELOG.md, src/frontend/packages/lib_video/src/components/common/VideoWidgetProvider/FoldableItem/index.spec.tsx, src/frontend/packages/lib_video/src/components/common/VideoWidgetProvider/FoldableItem/index.tsx, src/frontend/packages/lib_video/src/components/common/VideoWidgetProvider/WidgetsContainer/InfoModal/index.spec.tsx, src/frontend/packages/lib_video/src/components/common/VideoWidgetProvider/WidgetsContainer/InfoModal/index.tsx, src/frontend/packages/lib_video/src/components/common/VideoWidgetProvider/WidgetsContainer/index.tsx, src/frontend/packages/lib_video/src/components/common/VideoWidgetProvider/widgets/DownloadVideo/index.spec.tsx, src/frontend/packages/lib_video/src/components/common/VideoWidgetProvider/widgets/UploadClosedCaptions/index.spec.tsx, src/frontend/packages/lib_video/src/components/common/VideoWidgetProvider/widgets/UploadSubtitles/index.spec.tsx, src/frontend/packages/lib_video/src/components/common/VideoWidgetProvider/widgets/UploadTranscripts/index.spec.tsx, src/frontend/packages/lib_video/src/components/common/VideoWidgetProvider/widgets/UploadVideo/index.spec.tsx, src/frontend/packages/lib_video/src/components/common/VideoWidgetProvider/widgets/WidgetThumbnail/index.spec.tsx, src/frontend/packages/lib_video/src/hooks/useInfoWidgetModal/index.ts
See issue: https://github.com/openfun/marsha/issues/1842
When clicking on a tooltip in the teacher dashboard, we had to scroll to see the modal that was opened. This commit fixes this issue by positioning the modal above the tooltip.
[localhost-chromium.webm](https://user-images.githubusercontent.com/25994652/217253924-e8aeacaa-680f-4348-982c-d3224307db47.webm)
[localhost.webm](https://user-images.githubusercontent.com/25994652/217254147-2391d9b6-34fd-4c99-9389-850339d283ac.webm)
=> 💄(lti) position modal above tooltip

CHANGELOG.md, src/backend/marsha/account/api.py, src/backend/marsha/account/tests/api/test_saml_fer_idp_list.py
Organizations are not sorted alphabetically in the login select box of Shibboleth. Nearly but not completely.
Remove case sensitivity from sort.
=> 🐛(backend) fix idp sort being case sensitive

CHANGELOG.md, src/aws/ecs.tf
Fargate task logs region was hardcoded in eu-west-1.
Use the region configured in the env variables instead.
=> 🔨(terraform) use configured region for fargate definition

docs/permissions.md, src/backend/marsha/core/api/schema.py, src/backend/marsha/core/tests/test_api_schema.py, src/backend/marsha/settings.py
Bootstrap a documentation about permissions and how user are allowed or not to perform actions
Two aspects are proposed here:
=> 📝(docs) add permissions documentation

CHANGELOG.md, src/frontend/packages/lib_video/src/components/common/VideoWidgetProvider/widgets/SchedulingAndDescription/index.spec.tsx, src/frontend/packages/lib_video/src/components/common/VideoWidgetProvider/widgets/SchedulingAndDescription/index.tsx
The update on the video description updated the value of the textarea, so what was written during the update was overwritten.
[localhost-8060-lti-videos-ad8f632c-6f45-472f-8c5b-aa84bdc4210d.webm](https://user-images.githubusercontent.com/25994652/217284787-4cd1a07e-c74e-4e83-aef7-d105496cf3c7.webm)
=> 🐛(LTI) bug on the textarea of the live video

Makefile, src/backend/marsha/e2e/test_lti.py
Our e2e test fails on circle-ci but not locally.
We need to get the same error on both.
Also, the test needs a fix, obviously.
=> ✅ fix e2e test video play

CHANGELOG.md, src/backend/marsha/core/tests/test_views_public_document.py, src/backend/marsha/core/tests/test_views_public_video.py, src/backend/marsha/core/views.py
Public resource view is protected with the clickjacking protection middleware. We want to allow consumer_site owner to embedded resources related to their consumer_site in an iframe on their domain and subdomain. To do that, if a consumer_site exists, we deactivate the clickjacking middleware and we configure the Content-Security-Policy frame-ancestors with the consumer_site domain and all subdomains. If there is no consumer_site, like for public resources contained in a playlist managed on the standalone_site, then we don't allow to embedded the resource in an iframe at all.
Fixes #2033
=> ♻️(back) allow public resource to be embedded in a iframe

src/backend/marsha/core/tests/test_views_public_document.py, src/backend/marsha/core/tests/test_views_public_video.py, src/backend/marsha/core/views.py, src/backend/marsha/settings.py
In commit b6b993b when a public resource is fetch and own in a consumer_site, we changed the header to allow to embedded it in an iframe using the CSP frame-ancestor header. But we didn't managed the cache. So on the first request, we query the DB to retrieve the video and then we check if there is a consumer_site. But then, for the next requests we have a cache and we didn't query the DB anymore and we loose the consumer_site information and the headers are unchanged. To fix this, we save the domain in a dedicated cache and we use this cache to determine if the current resource is owned in a consumer_site and use its domain to change the response headers.
=> 🐛(back) manage header cache on public resources view

CHANGELOG.md, src/frontend/apps/standalone_site/src/features/Contents/features/ClassRoom/components/Create/ClassRoomCreateForm.spec.tsx, src/frontend/apps/standalone_site/src/features/Contents/features/ClassRoom/components/Create/ClassRoomCreateForm.tsx, src/frontend/packages/lib_classroom/src/data/queries/index.tsx, src/frontend/packages/lib_components/src/common/queries/actionOne.spec.tsx, src/frontend/packages/lib_components/src/common/queries/actionOne.tsx, src/frontend/packages/lib_components/src/common/queries/createOne.spec.tsx, src/frontend/packages/lib_components/src/common/queries/createOne.tsx, src/frontend/packages/lib_components/src/common/queries/deleteOne.spec.tsx, src/frontend/packages/lib_components/src/common/queries/deleteOne.ts, src/frontend/packages/lib_components/src/common/queries/fetchList.tsx, src/frontend/packages/lib_components/src/common/queries/fetchOne.tsx, src/frontend/packages/lib_components/src/common/queries/fetchResponseHandler.spec.ts, src/frontend/packages/lib_components/src/common/queries/fetchResponseHandler.ts, src/frontend/packages/lib_components/src/common/queries/index.ts, src/frontend/packages/lib_components/src/common/queries/metadata.tsx, src/frontend/packages/lib_components/src/common/queries/updateOne.spec.tsx, src/frontend/packages/lib_components/src/common/queries/updateOne.tsx, src/frontend/packages/lib_components/src/utils/errors/exception.ts
We didn't get enough information from the api response to handle errors.
This commit adds a helper to handle the api response and return a consistent error object.
Before we had something like that:
```
throw new Error(`Failed to get ${endpoint}.`);
// or
throw { code: 'exception' };
```
Now we have that ([definition](https://github.com/openfun/marsha/blob/feature/anthony/apiResponseHandler/src/frontend/packages/lib_components/src/utils/errors/exception.ts#L28)):
```
FetchResponseError extends Error{
code: string;
status: number;
response: Response;
message: string;
detail?: string;
errors?: { [key in keyof T]?: string[] }[];
error?: IFetchResponseError
// From Object Error
name: string;
cause?: Error;
stack?: string;
}
```
To get a value:
```
console.debug('errorClassroom', …
```
=> 🥅(frontend) utility apiResponseHandler

src/backend/marsha/development/urls.py
To display the schema, the swagger view is using the spectacular view. To know which one to use, it uses its name and the reverseurl django mechanism. Since we moved it in the development application, the name has changed and must be prefixed by `development:`
=> 🐛(back) change schema url_name used by swagger view

CHANGELOG.md, src/frontend/packages/lib_video/src/components/common/VideoWidgetProvider/widgets/UploadClosedCaptions/index.spec.tsx, src/frontend/packages/lib_video/src/components/common/VideoWidgetProvider/widgets/UploadClosedCaptions/index.tsx, src/frontend/packages/lib_video/src/components/common/VideoWidgetProvider/widgets/UploadSubtitles/index.spec.tsx, src/frontend/packages/lib_video/src/components/common/VideoWidgetProvider/widgets/UploadSubtitles/index.tsx, src/frontend/packages/lib_video/src/components/common/VideoWidgetProvider/widgets/UploadTranscripts/index.spec.tsx, src/frontend/packages/lib_video/src/components/common/VideoWidgetProvider/widgets/UploadTranscripts/index.tsx
Format cannot be checked on these files, but a more specific help text can be convenient
See https://github.com/openfun/marsha/issues/1921
=> 💬(frontend) add format list to subtitle uploaders

src/frontend/packages/lib_video/src/components/common/DashboardControlPane/DashboardTabStatistics/index.spec.tsx, src/frontend/packages/lib_video/src/components/common/DashboardControlPane/DashboardTabStatistics/index.tsx, src/frontend/packages/lib_video/src/components/common/DashboardControlPane/index.tsx
In the DashboardTabStatistics we are displaying the number of viewers for a video, not the number of people present on the whole webinar. Also the component is a bit refactor and test is added.
=> ♻️(front) change DashboardTabStatistics label to display viewers

CHANGELOG.md, src/frontend/packages/lib_video/src/components/live/Teacher/Wrapper/Controls/TeacherLiveRecordingActions/StartRecording/index.tsx, src/frontend/packages/lib_video/src/components/live/Teacher/Wrapper/Controls/TeacherLiveRecordingActions/StopRecording/index.tsx
Start recording action label color was blue but we want it white. 
Start recording action icon was not visible either.
Stop recording action label was not visible when the button is disabled, but we want it visible.
=> 💄(frontend) fix record action style

CHANGELOG.md, docs/permissions.md, src/backend/marsha/core/api/video.py, src/backend/marsha/core/permissions.py, src/backend/marsha/core/serializers/video.py, src/backend/marsha/core/tests/api/video/test_create.py, src/backend/marsha/core/tests/api/video/test_destroy.py, src/backend/marsha/core/tests/api/video/test_harvest_live.py, src/backend/marsha/core/tests/api/video/test_initiate_upload.py, src/backend/marsha/core/tests/api/video/test_live_pairing.py, src/backend/marsha/core/tests/api/video/test_live_participants_asking_to_join.py, src/backend/marsha/core/tests/api/video/test_live_participants_joined.py, src/backend/marsha/core/tests/api/video/test_live_to_vod.py, src/backend/marsha/core/tests/api/video/test_retrieve.py, src/backend/marsha/core/tests/api/video/test_shared_live_media.py, src/backend/marsha/core/tests/api/video/test_start_live.py, src/backend/marsha/core/tests/api/video/test_start_stop_recording.py, src/backend/marsha/core/tests/api/video/test_stats.py, src/backend/marsha/core/tests/api/video/test_stop_live.py, src/backend/marsha/core/tests/api/video/test_update.py, src/backend/marsha/websocket/consumers/video.py, src/backend/marsha/websocket/tests/test_consumers_video.py
Permissions regarding videos' endpoint are made for LTI access, it needs to be updated to match future standalone site access.
=> ✨(feature) video permissions for the standalone site

CHANGELOG.md, arnold.yml, src/aws/lambda-complete/package.json, src/aws/lambda-configure/package.json, src/aws/lambda-convert/package.json, src/aws/lambda-elemental-routing/package.json, src/aws/lambda-medialive/package.json, src/aws/lambda-mediapackage/package.json, src/aws/lambda-migrate/package.json, src/aws/utils/update-state/package.json, src/backend/setup.cfg, src/frontend/apps/lti_site/package.json, src/frontend/apps/standalone_site/package.json, src/frontend/package.json, src/frontend/packages/lib_classroom/package.json, src/frontend/packages/lib_common/package.json, src/frontend/packages/lib_components/package.json, src/frontend/packages/lib_markdown/package.json, src/frontend/packages/lib_tests/package.json, src/frontend/packages/lib_video/package.json, src/tray/tray.yml
- remove lib folder before rollup build to avoid stale files
- Add stats page on VOD
- Create lib-markdown package
- Add a check on timedtexttrack file size when uploading content
- Add a check on deposited file size when uploading content
- helpers frontend api error handling
- Add accepted formats in the subtitles uploaders helptext
- Standalone website:
- Add "video" management API endpoints permissions
- Add a check on thumbnail file size when uploading content
- lti:
- position modal above tooltip
- mutualize all CronJob in a CronJobList
- make all packages shakeable
- use lib-common theme in LTI
- change docker base image to use a debian lite one
- Allow public resource to be embedded in a iframe
- the Renater IdP sort is case-insensitive
- bug on the textarea description of the …
=> 🔖(beta) bump release to 4.0.0-beta.16

CHANGELOG.md, docs/permissions.md, src/backend/marsha/bbb/api.py, src/backend/marsha/core/api/shared_live_media.py, src/backend/marsha/core/api/thumbnail.py, src/backend/marsha/core/api/timed_text_track.py, src/backend/marsha/core/permissions.py, src/backend/marsha/core/tests/api/shared_live_media/test_create.py, src/backend/marsha/core/tests/api/shared_live_media/test_delete.py, src/backend/marsha/core/tests/api/shared_live_media/test_initiate_upload.py, src/backend/marsha/core/tests/api/shared_live_media/test_retrieve.py, src/backend/marsha/core/tests/api/shared_live_media/test_update.py, src/backend/marsha/deposit/api.py, src/backend/marsha/markdown/api.py
Now playlist administrator/instructors can access playlist's video, we need to update related endpoints.
=> ✨ (backend) Update shared live media permission for standalone site

CHANGELOG.md, docs/permissions.md, src/backend/marsha/core/api/thumbnail.py, src/backend/marsha/core/serializers/thumbnail.py, src/backend/marsha/core/tests/api/thumbnails/test_create.py, src/backend/marsha/core/tests/api/thumbnails/test_delete.py, src/backend/marsha/core/tests/api/thumbnails/test_options.py, src/backend/marsha/core/tests/api/thumbnails/test_retrieve.py
Now playlist administrator/instructors can access playlist's video, we need to update related endpoints.
=> ✨(backend) add thumbnail permissions for standalone site

CHANGELOG.md, src/frontend/packages/lib_video/src/components/live/common/Chat/ChatConversationDisplayer/index.spec.tsx, src/frontend/packages/lib_video/src/components/live/common/Chat/ChatMessageGroupItem/index.tsx
See issue https://github.com/openfun/marsha/issues/2025
> Problematic Behavior : During a webinar, messages seem to not be sent in real-time on the chat. You usually have to refresh the page to view them.
Actually there is no need to refresh, but just to reload and update the component in charge of adding messages to groups. This happens when the same user sends a message right after its last one.
I added these prints to the ChatMessageGroupItem component to see if sending a new message would trigger the component update :
```
useEffect(() => {
console.log(
'Messages length triggered by length : ',
msgGroup.messages.length,
);
}, [msgGroup.messages.length]);
useEffect(() => {
console.log(
'Messages length triggered by messages : ',
msgGroup.messages.length,
);
}, [msgGroup.messages]);
``` …
=> Chat sync bug fix

src/tray/vars/vault/main.yml.j2
The tray job is failing time to time with a syntax error reading the vault file. We want to remove punctuation in the generated password to not have this syntax error
=> 🚨(tray) avoid using punctuation with password lookup

src/backend/marsha/core/api/timed_text_track.py, src/backend/marsha/core/tests/api/timed_text_tracks/test_options.py
Allow standalone users to make an OPTIONS call to the timed text track API.
This was missed in the API migration to standalone access.
=> 🐛(backend) allow timed text tracks OPTIONS

CHANGELOG.md, src/aws/user.tf, src/backend/marsha/core/api/video.py, src/backend/marsha/core/serializers/shared_live_media.py, src/backend/marsha/core/serializers/video.py, src/backend/marsha/core/tests/api/live_sessions/test_list_attendances.py, src/backend/marsha/core/tests/api/video/test_shared_live_media.py, src/backend/marsha/core/tests/api/video/test_start_live.py, src/backend/marsha/core/tests/api/video/test_stop_live.py, src/backend/marsha/core/tests/api/video/test_update_live_state.py, src/backend/marsha/core/tests/utils/test_medialive_utils.py, src/backend/marsha/core/utils/medialive_profiles/medialive-720p.json, src/backend/marsha/core/utils/medialive_utils.py, src/frontend/packages/lib_components/src/data/stores/useVideo/index.tsx, src/frontend/packages/lib_components/src/types/tracks.ts, src/frontend/packages/lib_video/src/components/common/Player/createVideojsPlayer.spec.tsx, src/frontend/packages/lib_video/src/components/common/Player/createVideojsPlayer.ts, src/frontend/packages/lib_video/src/components/live/Student/StudentLiveStarter/StudentLiveWrapper/UpdateCurrentSharedLiveMediaPage/index.spec.tsx, src/frontend/packages/lib_video/src/components/live/Student/StudentLiveStarter/StudentLiveWrapper/UpdateCurrentSharedLiveMediaPage/index.tsx, src/frontend/packages/lib_video/src/components/live/Student/StudentLiveStarter/StudentLiveWrapper/index.spec.tsx, src/frontend/packages/lib_video/src/components/live/Student/StudentLiveStarter/StudentLiveWrapper/index.tsx, src/frontend/packages/lib_video/src/components/live/Student/StudentLiveStarter/index.tsx
During a webinar, there is a latency of few seconds between what happen in the instructor side (in jitsi) and what a student is seeing. Without any interactivity this is not a problem but once the instructor start sharing a document then this latency can be a problem. The document is display and the explanation about what is display by the instructor can come few seconds later.
We would like to use id3 tags to sync events with the live stream video.
=> ✨(lib-video) use id3 tags for document sharing / end live

CHANGELOG.md, src/frontend/apps/lti_site/components/App/AppContentLoader/index.spec.tsx, src/frontend/apps/lti_site/components/App/AppContentLoader/index.tsx
See https://github.com/openfun/marsha/issues/2077
When launching the app with no jwt, there was no page displaying the error but just a console exception. This commit displays the error in an ErrorBoundary context.
Move the exception that triggers the error in an ErrorBoundary-catchable section
=> 🐛(frontend) fix AppContentLoader loading error

CHANGELOG.md, src/backend/marsha/core/serializers/account.py, src/backend/marsha/core/simple_jwt/tokens.py, src/backend/marsha/core/tests/test_api_challenge_token.py, src/frontend/apps/standalone_site/src/__mock__/fetchMockAuth.mock.ts, src/frontend/apps/standalone_site/src/features/Authentication/api/validateChallenge/index.spec.ts, src/frontend/apps/standalone_site/src/features/Authentication/api/validateChallenge/index.ts, src/frontend/apps/standalone_site/src/features/Authentication/components/Authenticator.spec.tsx, src/frontend/apps/standalone_site/src/features/Authentication/components/Authenticator.tsx
The response for the challenge request was not returning a refresh token
but only an access one. Every user connecting with shibboleth have no
refresh token and are deconnected fron the standalone site once the
access token is expired. So fix this, the challenge response has now a
refresh token.
=> add refresh token in the challenge response

CHANGELOG.md, arnold.yml, src/aws/lambda-complete/package.json, src/aws/lambda-configure/package.json, src/aws/lambda-convert/package.json, src/aws/lambda-elemental-routing/package.json, src/aws/lambda-medialive/package.json, src/aws/lambda-mediapackage/package.json, src/aws/lambda-migrate/package.json, src/aws/utils/update-state/package.json, src/backend/setup.cfg, src/frontend/apps/lti_site/package.json, src/frontend/apps/standalone_site/package.json, src/frontend/package.json, src/frontend/packages/lib_classroom/package.json, src/frontend/packages/lib_common/package.json, src/frontend/packages/lib_components/package.json, src/frontend/packages/lib_markdown/package.json, src/frontend/packages/lib_tests/package.json, src/frontend/packages/lib_video/package.json, src/tray/tray.yml
- Add Markdown wizard in LTI context
- Add subtitles download for teacher
- List the VOD in the contents section
- Integrate creation VOD
- Add playlist access management
- Allow playlist instructor to manage shared live media through API
- Allow playlist instructor to manage timed text tracks through API
- Rework Markdown UI
- Allow playlist admin/instructor to manage thumbnails through API
- Bug on chat messages synchronisation
- Static files exclusion
- Impossible to decode JWT token, there is no jwt to decode
- Add refresh token in the challenge response
=> 🔖(beta) bump release to 4.0.0-beta.17

CHANGELOG.md, src/backend/marsha/core/api/xapi.py, src/backend/marsha/core/factories.py, src/backend/marsha/core/tests/api/xapi/document/test_from_website.py, src/backend/marsha/core/tests/api/xapi/video/test_from_website.py, src/backend/marsha/core/tests/test_api_xapi_statement.py, src/backend/marsha/core/tests/test_xapi.py, src/backend/marsha/core/tests/xapi/document/test_statement_from_website.py, src/backend/marsha/core/tests/xapi/video/test_statement_from_website.py, src/backend/marsha/core/urls/__init__.py, src/backend/marsha/core/urls/converters.py, src/backend/marsha/core/xapi.py, src/backend/marsha/e2e/test_lti.py, src/backend/marsha/settings.py, src/backend/marsha/urls.py, src/frontend/apps/lti_site/components/DashboardDocument/DocumentPlayer/index.spec.tsx, src/frontend/apps/lti_site/components/DashboardDocument/DocumentPlayer/index.tsx, src/frontend/packages/lib_components/src/utils/XAPI/DocumentXapiStatement.spec.ts, src/frontend/packages/lib_components/src/utils/XAPI/DocumentXapiStatement.ts, src/frontend/packages/lib_components/src/utils/XAPI/LiveXapiStatement.spec.ts, src/frontend/packages/lib_components/src/utils/XAPI/LiveXapiStatement.ts, src/frontend/packages/lib_components/src/utils/XAPI/VideoXAPIStatement.spec.ts, src/frontend/packages/lib_components/src/utils/XAPI/VideoXAPIStatement.ts, src/frontend/packages/lib_components/src/utils/XAPI/index.tsx, src/frontend/packages/lib_components/src/utils/XAPI/sendXAPIStatement.ts
In order to manage xapi request without consumer site, aka in the standalone site context, we have to change the XAPI routes to specidy the resource id we are working. Once this done, we can split the xapi behaviour based on the presence of a resource in the JWT token or not.
Fixes #2009
=> Manage xapi request without consumer_site

CHANGELOG.md, src/frontend/packages/lib_common/src/theme.ts
After the Grommet upgrade v2.30.0, some buttons were rounded. It seems that some global theme properties are not overloaded correctly anymore.
In this case, if a button has a `primary` prop, only the base button properties plus the `primary` properties are applied,
the global button `properties` are not applied.
=> 🐛(frontend) fix rounded button style

CHANGELOG.md, src/frontend/apps/lti_site/components/RedirectOnLoad/RedirectVideo.spec.tsx, src/frontend/apps/lti_site/components/RedirectOnLoad/RedirectVideo.tsx, src/frontend/apps/lti_site/components/RedirectOnLoad/index.spec.tsx
When a video object has the value deleted in the upload_state, we want to display a page explaining that this video is not available anymore
Redirect to an appropriate error page when we detect that upload_state has the value deleted.
=> 🐛(LTI) manage deleted video

CHANGELOG.md, src/frontend/packages/lib_video/src/components/common/VideoWidgetProvider/widgets/DescriptionWidget/index.tsx
See https://github.com/openfun/marsha/issues/2099
The description for the VOD is not correctly updated.
The solution is implemented in Live mode:
https://github.com/openfun/marsha/blob/master/src/frontend/packages/lib_video/src/components/common/VideoWidgetProvider/widgets/SchedulingAndDescription/index.tsx#L99
=> 🐛(frontend) sync description widget  VOD

CHANGELOG.md, src/frontend/packages/lib_video/src/components/common/VideoPlayer/index.spec.tsx, src/frontend/packages/lib_video/src/components/common/VideoPlayer/index.tsx, src/frontend/packages/lib_video/src/components/common/VideoWidgetProvider/widgets/WidgetThumbnail/ThumbnailRemoveButton/index.spec.tsx, src/frontend/packages/lib_video/src/components/common/VideoWidgetProvider/widgets/WidgetThumbnail/ThumbnailRemoveButton/index.tsx, src/frontend/packages/lib_video/src/components/common/VideoWidgetProvider/widgets/WidgetThumbnail/index.tsx
Fixed issue https://github.com/openfun/marsha/issues/2131
When we remove the thumbnail in the VOD dashboard, the thumbnail of the player is not correctly updated.
=> 🐛(lib-video) thumbnail not reset on the video player

CHANGELOG.md, src/frontend/packages/lib_classroom/src/components/DashboardClassroomStudent/index.spec.tsx, src/frontend/packages/lib_classroom/src/components/DashboardClassroomStudent/index.tsx, src/frontend/packages/lib_classroom/src/utils/tests/factories.ts
When a classroom is not scheduled, the title and description of this one are never display
No matter if the classroom is scheduled or not, the title and the description should always be display.
=> 🐛(lib-classroom) display title / desc in waiting room

src/frontend/apps/standalone_site/src/features/Contents/components/Contents/Contents.spec.tsx, src/frontend/apps/standalone_site/src/features/Contents/components/Contents/Contents.tsx, src/frontend/apps/standalone_site/src/features/Contents/features/Live/components/Read/Live.spec.tsx, src/frontend/apps/standalone_site/src/features/Contents/features/Live/components/Read/Lives.spec.tsx, src/frontend/apps/standalone_site/src/features/Contents/features/Live/components/Read/Lives.tsx, src/frontend/apps/standalone_site/src/routes/routes.tsx
On the standalone site we don't want to use the `live` keyword anymore, we want to use `webinar`. This is already the case on the deep linking menu for example.
=> ♻️(front) replace live occurences by webinar in the standalone site

CHANGELOG.md, src/backend/marsha/core/tests/views/test_lti_video.py, src/backend/marsha/core/views.py, src/backend/marsha/development/templates/development/lti_development.html, src/backend/marsha/e2e/test_lti.py, src/frontend/packages/lib_components/src/types/AppData.ts, src/frontend/packages/lib_video/src/components/vod/Teacher/Dashboard.spec.tsx, src/frontend/packages/lib_video/src/components/vod/Teacher/Dashboard.tsx
We want to show the dashboard everywhere, except in Moodle atto plugin.
=> Dashboard collapse

CHANGELOG.md, src/backend/marsha/core/api/base.py, src/backend/marsha/core/tests/test_api_get_frontend_configuration.py, src/backend/marsha/urls.py, src/frontend/apps/lti_site/components/App/AppInitializer/index.tsx, src/frontend/apps/standalone_site/src/App.spec.tsx, src/frontend/apps/standalone_site/src/App.tsx, src/frontend/apps/standalone_site/src/components/Sentry/SentryLoader.spec.tsx, src/frontend/apps/standalone_site/src/components/Sentry/SentryLoader.tsx, src/frontend/apps/standalone_site/src/components/Sentry/index.tsx
Add sentry to the standalone site
Fixes #1982
Use a public API endpoint to get sentry config allows us to initialize it sooner than with a jwt.
Also jwt related errors will be sent.
=> Configure sentry in standalone site

CHANGELOG.md, src/frontend/packages/lib_video/src/api/useTranscriptReaderRequest/index.ts, src/frontend/packages/lib_video/src/components/common/VideoWidgetProvider/widgets/Transcripts/TranscriptReader/index.tsx
The react-query hook useTranscriptReaderRequest didn't use a unique query key. That means that when the url was changing, this new url was not use because the stale time was not over. First, we have to use a unique query key by adding the timedtextrack id to it. Secondly the usage of the `OnSuccess` on that react-query hook is not the good solution. While no new query is made, the onSuccess is called with an empty data. To fix this issue, all the logic made on this onSuccess is moved in a `useEffect` hook in the TranscriptReader responsible to update the cues. And last, there is no reason to fetch again and again the file content, it will never change. So we can set an inifinte cache and stale time.
=> 🐛(front) correctly fetch transcript content in TranscriptReader

.circleci/config.yml, CHANGELOG.md, src/backend/marsha/bbb/serializers.py, src/backend/marsha/bbb/tests/api/classroom/test_create.py, src/backend/marsha/bbb/tests/api/classroom/test_retrieve.py, src/backend/marsha/bbb/tests/api/classroom/test_update.py, src/backend/marsha/bbb/tests/test_utils_tokens.py, src/backend/marsha/bbb/tests/test_views_lti.py, src/backend/marsha/bbb/utils/tokens.py, src/backend/marsha/e2e/test_lti_bbb.py, src/backend/marsha/e2e/test_site.py, src/frontend/apps/standalone_site/src/features/Contents/features/ClassRoom/components/ClassRoomRouter.spec.tsx, src/frontend/apps/standalone_site/src/features/Contents/features/ClassRoom/components/ClassRoomRouter.tsx, src/frontend/apps/standalone_site/src/features/Contents/features/ClassRoom/components/Update/ClassRoomUpdate.spec.tsx, src/frontend/apps/standalone_site/src/features/Contents/features/ClassRoom/components/Update/ClassRoomUpdate.tsx, src/frontend/packages/lib_classroom/src/components/ClassroomWidgetProvider/widgets/Invite/index.spec.tsx, src/frontend/packages/lib_classroom/src/components/ClassroomWidgetProvider/widgets/Invite/index.tsx, src/frontend/packages/lib_classroom/src/components/DashboardClassroomInfos/index.spec.tsx, src/frontend/packages/lib_classroom/src/components/DashboardCopyClipboard/index.spec.tsx, src/frontend/packages/lib_classroom/src/components/DashboardCopyClipboard/index.tsx, src/frontend/packages/lib_classroom/src/utils/tests/factories.ts, src/frontend/packages/lib_components/src/types/apps/classroom/models.ts, src/frontend/packages/lib_components/src/utils/createContext.tsx
Give moderator classroom invite link to users.
Fixes #2159
=> Create a classroom invite link for an instructor

CHANGELOG.md, src/frontend/apps/standalone_site/src/features/Contents/features/ClassRoom/components/Create/ClassRoomCreateForm.spec.tsx, src/frontend/apps/standalone_site/src/features/Contents/features/ClassRoom/components/Create/ClassRoomCreateForm.tsx, src/frontend/apps/standalone_site/src/features/Contents/features/Live/components/Create/LiveCreateForm.spec.tsx, src/frontend/apps/standalone_site/src/features/Contents/features/Live/components/Create/LiveCreateForm.tsx, src/frontend/apps/standalone_site/src/features/Playlist/components/PlaylistForm.spec.tsx, src/frontend/apps/standalone_site/src/features/Playlist/components/PlaylistForm.tsx
Feature Request https://github.com/openfun/marsha/issues/2154
Before this commit, the button to create a classroom or a webinar was always enabled and click on it would show an error message if the form was not valid.
Now, the button is disabled until the form is valid.
[Marsha - Button disabled.webm](https://user-images.githubusercontent.com/25994652/230105508-3e55b468-f97b-415a-bd27-2eecdcd1e1f6.webm)
=> ✨(website) add disabled button create ressource form

CHANGELOG.md, src/frontend/packages/lib_classroom/src/components/ClassroomWidgetProvider/widgets/Description/index.tsx
See Issue :
[when updating the desciption of a classroom, the debounce time was set too low to type without an unwanted update.
](https://github.com/openfun/marsha/issues/2181)
Increase the debounce time
=> 🐛(frontend) increase classroom debounce time

CHANGELOG.md, UPGRADE.md, docs/env.md, renovate.json, src/backend/marsha/core/tests/test_statics.py, src/backend/marsha/settings.py, src/backend/setup.cfg
django_rest_framework is not yet compatible with django 4.2, last renovate PR has upgraded it and tests didn't show this incompatibility. We have to downgrade django to version 4.1 while a new version of DRF is not released.
=> ⬇️(back) downgrade django to version 4.1

CHANGELOG.md, src/backend/marsha/core/api/video.py, src/backend/marsha/core/utils/medialive_utils.py
When we started a live, we got an an error caused by the id3's tags upload on a not ready live channel.
We skip id3 tags upload after starting a live and instead, we upload them when aws use our callback when the live is ready.
=> 🐛(live) fix start_live upload id3 tags error

src/frontend/packages/lib_video/src/components/vod/Teacher/Dashboard.tsx
In the VODTeacherDashboard component, the DashboardContent component was declare in the component itself. For every new render, the component is redeclare and the complete dashboard is rerender leading to scroll issue, the video is fully reload etc. Extracting it but keeping it in the same file and not exporting it resolve the issue.
=> 🐛(front) extract DashboardContent from VODTeacherDashboard

CHANGELOG.md, src/backend/setup.cfg
Release 4.4 of python social auth upgrades the lxml packages and seemd to be not compatible with our code.
The issue we have is similar to this issue:
https://github.com/SAML-Toolkits/python3-saml/issues/292 In a first time we decided to downgrade python social auth to a known working version.
=> ⬇️(back) downgrade python social auth to version 4.3.0

CHANGELOG.md, src/frontend/apps/standalone_site/src/features/Contents/components/Contents/Contents.spec.tsx, src/frontend/apps/standalone_site/src/features/Contents/components/Contents/Contents.tsx, src/frontend/apps/standalone_site/src/features/Contents/components/ContentsRouter/ContentsRouter.spec.tsx, src/frontend/apps/standalone_site/src/features/Contents/components/ContentsRouter/ContentsRouter.tsx, src/frontend/apps/standalone_site/src/features/Contents/components/ContentsShuffle/ContentsShuffle.spec.tsx, src/frontend/apps/standalone_site/src/features/Contents/components/ContentsShuffle/ContentsShuffle.tsx, src/frontend/apps/standalone_site/src/features/Contents/features/ClassRoom/components/ClassRoomRouter.spec.tsx, src/frontend/apps/standalone_site/src/features/Contents/features/ClassRoom/components/ClassRoomRouter.tsx, src/frontend/apps/standalone_site/src/features/Contents/features/ClassRoom/components/Read/ClassRoomContents.spec.tsx, src/frontend/apps/standalone_site/src/features/Contents/features/ClassRoom/components/Read/ClassRoomContents.tsx, src/frontend/apps/standalone_site/src/features/Contents/features/ClassRoom/components/Read/ClassRoomShuffle.spec.tsx, src/frontend/apps/standalone_site/src/features/Contents/features/ClassRoom/components/Read/ClassRoomShuffle.tsx, src/frontend/apps/standalone_site/src/features/Contents/features/ClassRoom/index.tsx, src/frontend/apps/standalone_site/src/features/Contents/features/Live/components/LiveRouter.spec.tsx, src/frontend/apps/standalone_site/src/features/Contents/features/Live/components/LiveRouter.tsx, src/frontend/apps/standalone_site/src/features/Contents/features/Live/components/Read/LiveContents.spec.tsx, src/frontend/apps/standalone_site/src/features/Contents/features/Live/components/Read/LiveContents.tsx, src/frontend/apps/standalone_site/src/features/Contents/features/Live/index.tsx, src/frontend/apps/standalone_site/src/features/Contents/features/Video/components/Read/VideoContents.spec.tsx, src/frontend/apps/standalone_site/src/features/Contents/features/Video/components/Read/VideoContents.tsx, src/frontend/apps/standalone_site/src/features/Contents/features/Video/components/VideoRouter.spec.tsx, src/frontend/apps/standalone_site/src/features/Contents/features/Video/components/VideoRouter.tsx, src/frontend/apps/standalone_site/src/features/Contents/features/Video/index.tsx, src/frontend/apps/standalone_site/src/features/Contents/features/featureFactory.tsx, src/frontend/apps/standalone_site/src/features/Contents/index.tsx, src/frontend/apps/standalone_site/src/features/Contents/store/contentsStore.ts, src/frontend/apps/standalone_site/src/features/Profile/components/ProfilePage.spec.tsx, src/frontend/apps/standalone_site/src/features/Profile/components/ProfilePage.tsx
Refacto `Content` to be feature agnostic, to avoid potential circular dependencies.
This commit adds a featureFactory that load the contents features in a content store.
=> 🏗️(website) add featureFactory to integrate contents feature 

CHANGELOG.md, src/backend/marsha/core/management/commands/sync_medialive_video.py, src/backend/marsha/core/tests/management_commands/test_sync_medialive_video.py
#2155 
Once a live started, video states becomes indirectly linked to medialive channel state. Their is a risk that sometimes, states are not sync for an unknown reason, for example, the api was down when aws was calling our callback to update video states. This can let us with media channel "IDLE", while in our side, the video state is "RUNNING".
In this case, the video becomes soft locked, the possible actions for a "RUNNING" video will fail because the medialive channel state is "IDLE".
Create a command that iterates on medialive channels and ensure that linked videos are state synced to avoid this kind of soft lock.
=> ✨(live) sync video and medialive states command

CHANGELOG.md, src/frontend/apps/standalone_site/src/features/Contents/features/ClassRoom/components/Create/ClassRoomCreateForm.spec.tsx, src/frontend/apps/standalone_site/src/features/Contents/features/ClassRoom/components/Create/ClassRoomCreateForm.tsx, src/frontend/apps/standalone_site/src/features/Contents/features/Live/components/Create/LiveCreateForm.spec.tsx, src/frontend/apps/standalone_site/src/features/Contents/features/Live/components/Create/LiveCreateForm.tsx, src/frontend/apps/standalone_site/src/features/Contents/features/Video/components/Create/VideoCreateForm.spec.tsx, src/frontend/apps/standalone_site/src/features/Contents/features/Video/components/Create/VideoCreateForm.tsx, src/frontend/apps/standalone_site/src/features/Playlist/hooks/useSelectPlaylist.spec.tsx, src/frontend/apps/standalone_site/src/features/Playlist/hooks/useSelectPlaylist.tsx
When we want to create a new resource but there is no existing playlist,
the form display was failing because we tried to set the first available
playlist but there is no available.
Also we added a button to create a playlist on the resource creation form.
Fixes #2207
=> [site] Creating a resource fail when no playlist exists

src/frontend/apps/standalone_site/src/features/Contents/components/ContentsFilter/ContentsFilter.spec.tsx, src/frontend/apps/standalone_site/src/features/Contents/features/ClassRoom/components/Create/ClassRoomCreateForm.spec.tsx, src/frontend/apps/standalone_site/src/features/Contents/features/ClassRoom/components/Create/ClassRoomCreateForm.tsx, src/frontend/apps/standalone_site/src/features/Contents/features/Live/components/Create/LiveCreateForm.spec.tsx, src/frontend/apps/standalone_site/src/features/Contents/features/Live/components/Create/LiveCreateForm.tsx, src/frontend/apps/standalone_site/src/features/Contents/features/Video/components/Create/VideoCreateForm.spec.tsx, src/frontend/apps/standalone_site/src/features/Contents/features/Video/components/Create/VideoCreateForm.tsx, src/frontend/apps/standalone_site/src/features/Playlist/hooks/useSelectPlaylist.spec.tsx, src/frontend/apps/standalone_site/src/features/Playlist/hooks/useSelectPlaylist.tsx
We added a button allowing to create a new playlist in the useSelectPlaylist hook. But we didn't notice it was also present in the content filter. To solve this issue we added a new parameter to the hook to choose to display the button or not.
=> 🐛(site) remove creation playlist in content filter

CHANGELOG.md, src/backend/marsha/bbb/api.py, src/backend/marsha/bbb/tests/api/classroom/test_bulk_destroy.py, src/backend/marsha/bbb/urls.py, src/backend/marsha/core/api/base.py, src/backend/marsha/core/api/video.py, src/backend/marsha/core/routers.py, src/backend/marsha/core/tests/api/video/test_bulk_destroy.py, src/backend/marsha/core/tests/api/video/test_destroy.py, src/backend/marsha/core/tests/test_router.py, src/backend/marsha/urls.py
We currently can't delete several object in one request
We want to do this by creating a mixin providing a "bulk_destroy" action. This action takes ids from the body,
verify if user has permission on all of them then delete. Like "list" actions with their corresponding "retrieve" actions, "bulk_destroy" queryset filters must match "delete" action permissions. (one action can't destroy more or less than the other).
The MarshaDefaultRouter handles DELETE verb on list object URL. (eg: /api/videos/).
=> ✨(back) add bulk_destroy for video / classroom

CHANGELOG.md, src/frontend/packages/lib_components/src/utils/XAPI/VideoXAPIStatement.spec.ts, src/frontend/packages/lib_components/src/utils/XAPI/VideoXAPIStatement.ts
There is a bug in the XapiVideoStatement mergeSegments method. Once a
first overlapsed segment merge, the reduce index does not match anymore
the accumulator lenght because we removed existing index in the previous
iteration. To fix that and keep having valide merged segments at the end
we must use the current accumulator length.
Fixes #2218
=> fix wrong usage of reduce index in xapiVideo mergeSegments 

CHANGELOG.md, src/tray/templates/services/app/cronjob_pipeline.yml.j2
The bach/v1beta1 API is deprecated since kubernets 1.21 and is removed in version 1.25. We can upgrade the manifests to use it now.
=> ⬆️(tray) use batch/v1 api in cronjob_pipeline manifest

.circleci/config.yml, .gitignore, CHANGELOG.md, Makefile, docker/images/e2e/Dockerfile, renovate.json, src/backend/marsha/e2e/test_lti.py, src/backend/setup.cfg
We have a recurent e2e test failing, this is an attempt to stabilize it.
Also, we have too much differences between CI and local e2e environment.
=> ✅(e2e) use a specific playwright image tag

CHANGELOG.md, src/backend/marsha/bbb/api.py, src/backend/marsha/bbb/tests/api/classroom/test_delete.py, src/frontend/apps/standalone_site/src/features/Contents/features/Video/components/Update/VideoUpdate.tsx, src/frontend/apps/standalone_site/src/features/Playlist/api/useDeletePlaylist/index.ts, src/frontend/apps/standalone_site/src/features/Playlist/components/PlaylistForm.spec.tsx, src/frontend/apps/standalone_site/src/features/Playlist/components/PlaylistForm.tsx, src/frontend/apps/standalone_site/src/features/Playlist/features/UpdatePlaylist/components/UpdatePlaylistPage.spec.tsx, src/frontend/apps/standalone_site/src/features/Playlist/features/UpdatePlaylist/components/UpdatePlaylistPage.tsx, src/frontend/packages/lib_classroom/src/components/ClassroomWidgetProvider/index.spec.tsx, src/frontend/packages/lib_classroom/src/components/ClassroomWidgetProvider/index.tsx, src/frontend/packages/lib_classroom/src/components/ClassroomWidgetProvider/widgets/DeleteClassroom/index.spec.tsx, src/frontend/packages/lib_classroom/src/components/ClassroomWidgetProvider/widgets/DeleteClassroom/index.tsx, src/frontend/packages/lib_classroom/src/components/DashboardClassroomForm/index.spec.tsx, src/frontend/packages/lib_classroom/src/data/queries/index.spec.tsx, src/frontend/packages/lib_classroom/src/data/queries/index.tsx, src/frontend/packages/lib_common/src/theme.ts, src/frontend/packages/lib_components/src/common/ConfirmationModal/index.tsx, src/frontend/packages/lib_video/src/api/useDeleteVideo/index.spec.tsx, src/frontend/packages/lib_video/src/api/useDeleteVideo/index.ts, src/frontend/packages/lib_video/src/components/common/DashboardControlPane/index.spec.tsx, src/frontend/packages/lib_video/src/components/common/VideoWidgetProvider/index.spec.tsx, src/frontend/packages/lib_video/src/components/common/VideoWidgetProvider/index.tsx, src/frontend/packages/lib_video/src/components/common/VideoWidgetProvider/widgets/DeleteVideo/index.spec.tsx, src/frontend/packages/lib_video/src/components/common/VideoWidgetProvider/widgets/DeleteVideo/index.tsx
Add a new widget in standalone site to delete videos,  classrooms and playlists.
After adding a context provider for Video edition in otder to know if the resource is shown on site or LTI, plug the API to the right endpoints and create the components for resource deletion.
=> Delete Resource Widget

CHANGELOG.md, src/frontend/packages/lib_components/src/common/WidgetsContainer/InfoModal/index.tsx, src/frontend/packages/lib_video/src/components/common/VideoWidgetProvider/widgets/VisibilityAndInteraction/index.spec.tsx, src/frontend/packages/lib_video/src/components/common/VideoWidgetProvider/widgets/VisibilityAndInteraction/index.tsx
Feature request: #2208
When the video is_public is toggle on, after the iframe integration box, we added a box with the lti link beeing easily copy/paste.
[Marsha - LTI link.webm](https://user-images.githubusercontent.com/25994652/237046627-d28b2d16-86cd-4a71-9f10-b163cc314a73.webm)
=> ✨(lib-video) lti code to copy to clipboard

CHANGELOG.md, src/frontend/packages/lib_video/src/components/common/VideoWidgetProvider/widgets/DeleteVideo/index.spec.tsx, src/frontend/packages/lib_video/src/components/common/VideoWidgetProvider/widgets/DeleteVideo/index.tsx
use `Webinar` and `VOD` wording for the component to be more explicit
=> 🐛(frontend) change wording on DeleteVideo modals

CHANGELOG.md, src/backend/marsha/settings.py
We are using the SocialAuthExceptionMiddleware but without using the LOGIN_ERROR_URL setting. Without this setting, the user is not redirected to an error page having error info. We want to congiure it in our settings so we declare the setting SOCIAL_AUTH_LOGIN_ERROR_URL
=> 🔧(back) configure SOCIAL_AUTH_LOGIN_ERROR_URL setting

src/backend/marsha/websocket/consumers/video.py, src/backend/marsha/websocket/tests/test_consumers_video.py
When we disconnect fron a websocket, we try to reset matching livesession.
If the video has been deleted, no matching livesession could be found, resulting in an error.
Fixes #2232
If no livesession is found, there is nothing to do to reset it.
A simple try except is added to catch the ConnectionRefusedError we're raising.
=> Properly clause websocket connection on video/webinar deletion

CHANGELOG.md, src/backend/marsha/account/middleware.py, src/backend/marsha/account/tests/test_middleware.py, src/backend/marsha/account/tests/test_social_pipeline_organization.py, src/backend/marsha/account/tests/utils.py, src/backend/marsha/settings.py
The middleware provided by django social auth to redirect the user to an error page when an authentification failure exception is raised does not match our need and we can't customize it like we want. We want to redirect the user to an error page, display the error message and we don't want to lose the exception. For this, the exception is captured by sentry, then the user is redirected and the message is added in the query string.
=> ✨(back) add a middleware to deal with social auth exception

CHANGELOG.md, src/frontend/apps/standalone_site/craco.config.js, src/frontend/apps/standalone_site/src/components/Text/Text404.spec.tsx, src/frontend/apps/standalone_site/src/components/Text/Text404.tsx, src/frontend/apps/standalone_site/src/components/Text/index.ts, src/frontend/apps/standalone_site/src/features/Authentication/hooks/useAuthenticator.spec.tsx, src/frontend/apps/standalone_site/src/features/Authentication/hooks/useAuthenticator.tsx, src/frontend/apps/standalone_site/src/features/Contents/components/ContentsRouter/ContentsRouter.spec.tsx, src/frontend/apps/standalone_site/src/features/Contents/components/ContentsRouter/ContentsRouter.tsx, src/frontend/apps/standalone_site/src/features/Contents/features/ClassRoom/components/Update/ClassRoomUpdate.spec.tsx, src/frontend/apps/standalone_site/src/features/Contents/features/ClassRoom/components/Update/ClassRoomUpdate.tsx, src/frontend/apps/standalone_site/src/features/Profile/components/ProfileRouter.spec.tsx, src/frontend/apps/standalone_site/src/features/Profile/components/ProfileRouter.tsx, src/frontend/apps/standalone_site/src/routes/AppRoutes.spec.tsx, src/frontend/apps/standalone_site/src/routes/AppRoutes.tsx, src/frontend/apps/standalone_site/testSetup.js, src/frontend/packages/lib_classroom/src/components/DashboardClassroom/index.tsx, src/frontend/packages/lib_classroom/src/components/DashboardClassroomInstructor/index.tsx, src/frontend/packages/lib_components/src/hooks/stores/useJwt/index.spec.tsx, src/frontend/packages/lib_components/src/hooks/stores/useJwt/index.ts
When we displayed the dashboard classroom, we had some screens flickering
because the permissions were updating. Now we update the
permissions during the jwt init / checking, like that permissions are
set before the dashboard classroom is displayed.
Description...
=> ⚡️(frontend) improve transition to classroom dashboard.

CHANGELOG.md, src/backend/marsha/settings.py
We want to enable and configure the sentry performance and profiling feature. New settings SENTRY_TRACES_SAMPLE_RATE and SENTRY_PROFILES_SAMPLE_RATE are added to control these features.
=> 🔧(back) enable sentry performance and profiling in django

CHANGELOG.md, src/backend/marsha/bbb/tests/test_utils_tokens.py, src/backend/marsha/bbb/utils/tokens.py, src/backend/marsha/settings.py
When we build a moderator invite link for a classroom, we want to set a specific token expiration, based on a dedicated setting.
Fixes #2247 
Add a BBB_INVITE_JWT_INSTRUCTOR_DAYS_DURATION setting, and use is for calculating the lifetime of an instructor token.
=> ✨(backend) use a specific duration for moderator classroom link

CHANGELOG.md, src/frontend/apps/standalone_site/src/features/PagesApi/components/PagesApi.spec.tsx, src/frontend/apps/standalone_site/src/features/PagesApi/components/PagesApi.tsx
The location.pathname always contains the initial / as explain in the MDN documentation. This leads to a malform endpoint when fetching the api page. slash is used twice and matches the wildcard route.
=> 🐛(front) remove initial / from page slug to use it in the API fetch

CHANGELOG.md, src/frontend/packages/lib_components/src/common/queries/fetchReconnectWrapper.tsx, src/frontend/packages/lib_components/src/data/sideEffects/refreshToken/index.spec.ts, src/frontend/packages/lib_components/src/data/sideEffects/refreshToken/index.ts, src/frontend/packages/lib_components/src/hooks/stores/useJwt/index.spec.tsx, src/frontend/packages/lib_components/src/hooks/stores/useJwt/index.ts, src/frontend/packages/lib_components/src/utils/system.ts
In some cases, the refreshToken can be called twice in a row without being considerated blacklisted by the backend, this can produce some side effect and log out our user.
We added as well a blacklisting in the frontend side to prevent this kind of behavior.
=> 🐛(frontend) fix potential side effect with refreshToken

CHANGELOG.md, src/backend/marsha/bbb/api.py, src/backend/marsha/core/api/video.py, src/frontend/apps/standalone_site/src/features/Contents/features/ClassRoom/components/ClassRoomRouter.spec.tsx, src/frontend/apps/standalone_site/src/features/Contents/features/ClassRoom/components/Create/ClassRoomCreate.spec.tsx, src/frontend/apps/standalone_site/src/features/Contents/features/ClassRoom/components/Create/ClassRoomCreate.tsx, src/frontend/apps/standalone_site/src/features/Contents/features/ClassRoom/components/Read/ClassRoomItem.spec.tsx, src/frontend/apps/standalone_site/src/features/Contents/features/ClassRoom/components/Read/ClassRoomItem.tsx, src/frontend/apps/standalone_site/src/features/Contents/features/Live/components/Create/LiveCreate.spec.tsx, src/frontend/apps/standalone_site/src/features/Contents/features/Live/components/Create/LiveCreate.tsx, src/frontend/apps/standalone_site/src/features/Contents/features/Live/components/LiveRouter.spec.tsx, src/frontend/apps/standalone_site/src/features/Contents/features/Live/components/Read/Live.spec.tsx, src/frontend/apps/standalone_site/src/features/Contents/features/Live/components/Read/Live.tsx, src/frontend/apps/standalone_site/src/features/Contents/features/Video/components/Create/VideoCreate.spec.tsx, src/frontend/apps/standalone_site/src/features/Contents/features/Video/components/Create/VideoCreate.tsx, src/frontend/apps/standalone_site/src/features/Contents/features/Video/components/Read/Video.spec.tsx, src/frontend/apps/standalone_site/src/features/Contents/features/Video/components/Read/Video.tsx, src/frontend/apps/standalone_site/src/features/Contents/features/Video/components/VideoRouter.spec.tsx, src/frontend/apps/standalone_site/src/features/Contents/store/selectionStore.ts, src/frontend/apps/standalone_site/src/routes/AppRoutes.tsx, src/frontend/packages/lib_classroom/src/data/queries/index.spec.tsx, src/frontend/packages/lib_classroom/src/data/queries/index.tsx, src/frontend/packages/lib_common/src/theme.ts, src/frontend/packages/lib_components/src/common/queries/bulkDelete.spec.tsx, src/frontend/packages/lib_components/src/common/queries/bulkDelete.tsx, src/frontend/packages/lib_components/src/common/queries/index.ts, src/frontend/packages/lib_video/src/api/index.ts, src/frontend/packages/lib_video/src/api/useDeleteVideos/index.spec.tsx, src/frontend/packages/lib_video/src/api/useDeleteVideos/index.tsx
Be able to bulk delete resources (videos, webinars and classrooms) from the list page.
Use a store for each resource to keep track of the selected items, and accordingly to its state show the different edition options on the cards and banners.
=> Bulk delete resources (videos, webinars and classrooms)

CHANGELOG.md, src/backend/marsha/core/sentry.py, src/backend/marsha/core/tests/test_sentry.py, src/backend/marsha/settings.py
We want to exclude all requests made by dockerflow healthchecks because they can spam sentry profiling.
=> 🔧(back) filter dockerflow healthcheck in sentry before_send_transaction

src/frontend/packages/lib_video/package.json
The lib-video license used was not the MIT but ISC. Accordingly to the license we use in Marsha we have to change it to the MIT one.
=> 📄(front) change lib-video license to MIT

CHANGELOG.md, UPGRADE.md, docs/env.md, renovate.json, src/backend/marsha/core/tests/test_statics.py, src/backend/marsha/settings.py, src/backend/setup.cfg
With django 4.2, `STATICFILES_STORAGE` setting is deprecated in favor of `STORAGES`
https://docs.djangoproject.com/en/4.2/releases/4.2/#custom-file-storages
The env var `DJANGO_STATICFILES_STORAGE` has been replaced by `DJANGO_STORAGES_STATICFILES_BACKEND` accordilgly.
=> ⬆️(back) upgrade to django 4.2

CHANGELOG.md, src/backend/marsha/core/management/commands/clean_aws_elemental_stack.py, src/backend/marsha/core/management/commands/sync_medialive_video.py, src/backend/marsha/core/tests/management_commands/test_clean_aws_elemental_stack.py
The clean_aws_elemental_stack is failing when medialive channel exists, but its associated video does not.
It is also not catching if a medialive channel is not referenced by a live, thus unused.
When a medialive channel is unused, we should delete the stack of this medialive channel. The same way we did with sync_medialive_video
=> 🐛(back) fix clean_aws_elemental_stack command

CHANGELOG.md, src/frontend/packages/lib_video/src/components/common/VideoPlayer/index.tsx, src/frontend/packages/lib_video/src/hooks/useSetVideoState/index.tsx
When a attribute of the video was updated, the video player was reset. 
If a student was looking at the video at this moment, the video was stopped and the student had to restart the video.
=> 🐛(frontend) video player reset

CHANGELOG.md, src/aws/.terraform.lock.hcl, src/aws/bin/terraform, src/aws/provider.tf, src/aws/s3.tf
We don't want to keep indefinitely object uploaded in the source bucket.
After 21 days, an uploaded object expires and is deleted permanently.
Also, The static bucket is not used since version 3.17.0 and we never delete
it. To prepare the deletion, we must in a first version set the
force_destroy property on it to true otherwise it is not possible to
delete it using terraform
=> Configure expire rule on source bucket

CHANGELOG.md, src/frontend/packages/lib_video/src/components/common/Player/createVideojsPlayer.ts, src/frontend/packages/lib_video/src/components/common/Player/videojs/downloadVideoPlugin/components/DownloadVideoButton.ts, src/frontend/packages/lib_video/src/components/common/Player/videojs/downloadVideoPlugin/components/DownloadVideoQualityItem.ts, src/frontend/packages/lib_video/src/components/common/Player/videojs/downloadVideoPlugin/index.ts, src/frontend/packages/lib_video/src/components/common/Player/videojs/downloadVideoPlugin/types.ts, src/frontend/packages/lib_video/src/components/common/VideoPlayer/index.tsx, src/frontend/packages/lib_video/src/components/common/VideoWidgetProvider/index.spec.tsx, src/frontend/packages/lib_video/src/components/common/VideoWidgetProvider/index.tsx, src/frontend/packages/lib_video/src/components/vod/Student/Dashboard.spec.tsx, src/frontend/packages/lib_video/src/types/libs/video.js/extend.d.ts
See https://github.com/openfun/marsha/issues/2312
Some widgets are shown below the video player like downloads and transcript activation, but are not well integrated with other features like subtitles in the player : it breaks page layout and cannot be folded without losing the functionnality.
This PR focuses on the download part, and aims to simplify the UX for downloading videos as a student, by removing the widget from VideoWidgetProvider and adding a button directly on the videojs player.
=> ✨ videojs-download download button on control bar

src/tray/vars/all/main.yml
A development image was used as default image in the webtorrent tray. This image does not exists anymore. We must use the master image.
=> 🔧(tray) use webtorrent master image

CHANGELOG.md, src/frontend/packages/lib_components/src/utils/useResizer.tsx, src/frontend/packages/lib_video/src/components/common/VideoLayout/index.tsx
See issue: #2305
Fix 2 problems:
[Marsha (2).webm](https://github.com/openfun/marsha/assets/25994652/beddf82b-3cce-45bb-8e8e-490e9fa50a29)
=> 🐛(frontend) fix problem panel chat on live

src/webtorrent/src/verifyClient.ts
Since last js update, the jsonwebtoken import is not working anymore. We have to import first the pkg and then pick the verify function.
=> 🐛(webtorrent) fix jsonwebtoken import

src/tray/templates/services/webtorrent/deploy.yml.j2
The webtorrent deployment had a wrong name for the container, we change it for webtorrent. No image pull policy was defined and we must set to Always otherwise the last master image is never used.
=> 🔧(tray) change webtorrent container name and pull policy

src/backend/marsha/core/models/playlist.py, src/backend/marsha/core/tests/models/test_retention_date_object_mixin.py
The marsha module was used to import the settings. This is wrong as the settings are managed by django. The test was reflecting bad usage of the import but it was failing... the test was proving the failure...
=> 🐛(back) use django.conf module to import settings instead of marsha

CHANGELOG.md, src/tray/templates/services/app/_deploy_base.yml.j2, src/tray/templates/services/app/job_db_migrate.yml.j2, src/tray/templates/services/nginx/ingress.yml.j2, src/tray/vars/all/main.yml
We can handle mutiple sites for marsha. To use this feature with k8s, we have to declare one ingress per domain and allow this domains in the ALLOWED_HOSTS and CSRF configuration. Blue/green is also managed
=> ✨(tray) manage multiple ingresses

CHANGELOG.md, src/frontend/packages/lib_video/src/components/common/Player/createVideojsPlayer.spec.tsx, src/frontend/packages/lib_video/src/components/common/Player/createVideojsPlayer.ts, src/frontend/packages/lib_video/src/components/common/Player/videojs/id3Plugin/index.spec.tsx, src/frontend/packages/lib_video/src/components/common/Player/videojs/id3Plugin/index.ts, src/frontend/packages/lib_video/src/components/common/Player/videojs/xapiPlugin/index.spec.tsx, src/frontend/packages/lib_video/src/components/common/Player/videojs/xapiPlugin/index.ts, src/frontend/packages/lib_video/src/components/common/Player/videojs/xapiPlugin/types.ts, src/frontend/packages/lib_video/src/types/libs/video.js/extend.d.ts
Our handling of our custom features for videojs is made in one file (createVideojsPlayer). It makes this file difficult to read and maintain.
Taking example on p2p plugin or download button, we should move id3 related logic, and xapi related logic into their own plugin.
=> 🎨(frontend) refactor videojs features through plugins

src/backend/marsha/account/tests/test_views.py, src/backend/marsha/account/views.py
The complete route redirect successfuly connected shibboleth user to the default FRONTEND_HOME_URL. If the user comes from an existing site config, we want to redirect it to the same domain.
=> ♻️(back) redirect to matching site on complete shibboleth route

CHANGELOG.md, src/frontend/packages/lib_video/src/components/common/Player/createVideojsPlayer.ts, src/frontend/packages/lib_video/src/components/common/Player/videojs/downloadVideoPlugin/components/DownloadVideoButton.ts, src/frontend/packages/lib_video/src/components/common/Player/videojs/downloadVideoPlugin/components/DownloadVideoQualityItem.ts, src/frontend/packages/lib_video/src/components/common/Player/videojs/downloadVideoPlugin/index.spec.tsx
The "download video" on the videojs player was always displayed even if the video was not downloadable
=> 🐛(frontend) fix videojs download video button

renovate.json, src/backend/setup.cfg
We added lxml to our depencies to control the version installed. Since we switch to debian bookworm it is not needed to do it anymore, the libxml2 version used is more recent and we don't have the issue we had with lxml 4.7.x
=> ➖(back) remove lxml dependency management

CHANGELOG.md, src/backend/marsha/core/admin.py, src/backend/marsha/core/api/lti_user_association.py, src/backend/marsha/core/api/playlist.py, src/backend/marsha/core/permissions/organization.py, src/backend/marsha/core/tests/api/lti_user_associations/test_create.py, src/backend/marsha/core/tests/api/playlists/test_claim.py, src/backend/marsha/core/tests/api/playlists/test_is_claimed.py, src/backend/marsha/core/tests/views/test_lti_base.py, src/backend/marsha/core/tests/views/test_lti_video.py, src/backend/marsha/core/views.py, src/frontend/apps/lti_site/components/App/AppContentLoader/index.spec.tsx, src/frontend/apps/lti_site/components/App/AppContentLoader/index.tsx, src/frontend/apps/lti_site/components/ClaimLink/index.spec.tsx, src/frontend/apps/lti_site/components/ClaimLink/index.tsx, src/frontend/apps/lti_site/data/queries/index.tsx, src/frontend/apps/standalone_site/src/api/useLtiUserAssociations/index.spec.tsx, src/frontend/apps/standalone_site/src/api/useLtiUserAssociations/index.ts, src/frontend/apps/standalone_site/src/features/App/AppRoutes.tsx, src/frontend/apps/standalone_site/src/features/ClaimResource/api/useClaimResource.spec.tsx, src/frontend/apps/standalone_site/src/features/ClaimResource/api/useClaimResource.ts, src/frontend/apps/standalone_site/src/features/ClaimResource/components/ClaimResource.spec.tsx, src/frontend/apps/standalone_site/src/features/ClaimResource/components/ClaimResource.tsx, src/frontend/apps/standalone_site/src/features/ClaimResource/index.tsx, src/frontend/apps/standalone_site/src/features/PortabilityRequests/hooks/useLtiUserAssociationJwtQueryParam.tsx, src/frontend/apps/standalone_site/src/routes/routes.tsx, src/frontend/packages/lib_components/src/types/AppData.ts
We want the standalone site users to manage the resource they created through LTI.
=> LTI user association

src/frontend/apps/lti_site/components/App/AppContentLoader/index.spec.tsx, src/frontend/apps/lti_site/components/ClaimLink/index.spec.tsx, src/frontend/apps/lti_site/components/ClaimLink/index.tsx, src/frontend/apps/lti_site/data/queries/index.tsx, src/frontend/package.json
Standalone site and LTI app were not not automatically lint checked.
=> 🚨(frontend) lint all apps

CHANGELOG.md, src/frontend/apps/standalone_site/src/assets/svg/logo_marsha.svg, src/frontend/apps/standalone_site/src/conf/global.ts, src/frontend/apps/standalone_site/src/features/App/App.spec.tsx, src/frontend/apps/standalone_site/src/features/App/AppConfig.spec.tsx, src/frontend/apps/standalone_site/src/features/App/AppConfig.tsx, src/frontend/apps/standalone_site/src/features/Contents/components/Contents/Contents.tsx, src/frontend/apps/standalone_site/src/features/Header/Header.spec.tsx, src/frontend/apps/standalone_site/src/features/Header/Header.tsx, src/frontend/apps/standalone_site/src/features/Language/components/LanguagePicker.spec.tsx, src/frontend/apps/standalone_site/src/features/Language/components/LanguagePicker.tsx, src/frontend/apps/standalone_site/src/features/Language/conf.ts, src/frontend/apps/standalone_site/src/features/Language/hook/useLanguage.spec.tsx, src/frontend/apps/standalone_site/src/features/Language/hook/useLanguage.tsx, src/frontend/apps/standalone_site/src/features/Language/index.ts, src/frontend/apps/standalone_site/src/features/Language/store/languageStore.spec.ts, src/frontend/apps/standalone_site/src/features/Language/store/languageStore.ts, src/frontend/apps/standalone_site/src/features/Language/utils.spec.ts, src/frontend/apps/standalone_site/src/features/Language/utils.ts, src/frontend/apps/standalone_site/src/features/Profile/components/ProfilePage.tsx, src/frontend/apps/standalone_site/src/features/Profile/features/AccountSettings/components/AccountSettings.tsx, src/frontend/apps/standalone_site/src/styles/theme.extend.ts, src/frontend/packages/lib_common/src/theme.ts
Change the language from a select box located in the header.
[Marsha (6).webm](https://github.com/openfun/marsha/assets/25994652/c62c27ab-b7a6-47f3-a10c-6bee22ab1d53)
=> ✨(frontend) language switcher

src/frontend/apps/standalone_site/src/features/Authentication/components/RenaterAuthenticator.tsx
An previous commit removed the padding on the select field from the theme, this commit adds it back.
=> 💄(website) add padding on renater select field

src/backend/marsha/bbb/api.py, src/backend/marsha/bbb/serializers.py, src/backend/marsha/bbb/tests/api/classroom/recordings/test_create_vod.py, src/backend/marsha/bbb/tests/api/classroom/test_classroomdocuments.py, src/backend/marsha/bbb/tests/api/classroom/test_retrieve.py, src/backend/marsha/bbb/tests/api/classroomdocument/test_create.py, src/backend/marsha/bbb/tests/api/classroomdocument/test_update.py, src/backend/marsha/deposit/serializers.py, src/backend/marsha/deposit/tests/api/depositedfiles/test_create.py, src/backend/marsha/deposit/tests/api/depositedfiles/test_update.py, src/backend/marsha/deposit/tests/api/filedepositories/test_depositedfiles.py, src/frontend/apps/lti_site/apps/deposit/components/Dashboard/DashboardInstructor/index.spec.tsx, src/frontend/apps/lti_site/apps/deposit/data/queries/index.spec.tsx, src/frontend/apps/lti_site/apps/deposit/utils/tests/factories.ts, src/frontend/packages/lib_classroom/src/components/ClassroomWidgetProvider/widgets/Recordings/Recording/DeleteClassroomRecordingButton/index.spec.tsx, src/frontend/packages/lib_classroom/src/components/ClassroomWidgetProvider/widgets/Recordings/Recording/DeleteClassroomRecordingButton/index.tsx, src/frontend/packages/lib_classroom/src/components/ClassroomWidgetProvider/widgets/Recordings/Recording/index.spec.tsx, src/frontend/packages/lib_classroom/src/components/ClassroomWidgetProvider/widgets/Recordings/Recording/index.tsx, src/frontend/packages/lib_classroom/src/components/ClassroomWidgetProvider/widgets/SupportSharing/UploadDocuments/DocumentRow/index.spec.tsx, src/frontend/packages/lib_classroom/src/data/queries/index.spec.tsx, src/frontend/packages/lib_classroom/src/data/sideEffects/createClassroomDocument/index.spec.ts, src/frontend/packages/lib_classroom/src/data/sideEffects/createVOD/index.spec.ts, src/frontend/packages/lib_classroom/src/data/sideEffects/createVOD/index.ts, src/frontend/packages/lib_classroom/src/utils/tests/factories.ts, src/frontend/packages/lib_components/src/types/apps/classroom/models.ts, src/frontend/packages/lib_components/src/types/apps/deposit/models.ts
The API actually sends parent resource as id for classroom and deposit related models.
This can lead to mistakes in the frontend.
Rename the attributes, and change the type to string.
=> Api related ids

CHANGELOG.md, src/backend/marsha/core/api/xapi.py, src/backend/marsha/core/defaults.py, src/backend/marsha/core/tests/api/xapi/video/test_from_website.py, src/backend/marsha/core/tests/test_api_xapi_statement.py, src/backend/marsha/settings.py
Sometimes video xAPI statements are sent multiple times, it can happens when a client has network connections issues and the request is retried. #2343 
To avoid duplicate statements, we use the `id` field of the statement to identify if the statement has already been sent using a cache of a few minutes.
=> 🐛(backend) xapi cache to avoid duplicate statements

src/frontend/apps/lti_site/components/SelectContent/index.tsx
It's considered as a bad A11y practice to add redundant semantic. A `<form>` element has already a `form` role, specifying it again is redundant. It might make screen readers behave buggy.
I would suggest adding the `eslint-plugin-jsx-a11y` plugin to the ESLint custom configuration. It's a dependency of `react-scripts`, used by the standalone app but not the LTI app.
=> ♿️(frontend) remove redundant form role in the LTI app

src/backend/marsha/core/api/playlist.py, src/backend/marsha/core/lti/user_association.py, src/backend/marsha/core/permissions/organization.py, src/backend/marsha/core/tests/api/playlists/test_claim.py, src/backend/marsha/core/tests/api/playlists/test_is_claimed.py, src/backend/marsha/core/tests/lti/test_user_association.py, src/backend/marsha/settings.py
In edxapp studio, the lti_user_id used is an anonymous one and has all the time the value
`student`. Creating an association with this value must be forbidden.
Also, organization administrator should be able to claim a playlist
=> Exclude lister lti_user_id to playlist claim process

src/backend/marsha/bbb/api.py, src/backend/marsha/bbb/tests/api/classroomdocument/test_list.py, src/backend/marsha/core/api/shared_live_media.py, src/backend/marsha/core/api/thumbnail.py, src/backend/marsha/core/api/timed_text_track.py, src/backend/marsha/core/tests/api/shared_live_media/test_retrieve.py, src/backend/marsha/core/tests/api/thumbnails/test_retrieve.py, src/backend/marsha/core/tests/api/timed_text_tracks/test_retrieve.py, src/backend/marsha/deposit/api.py, src/backend/marsha/deposit/tests/api/depositedfiles/test_list.py
Every viewset managing a resource related to an other (thumbnail -> video, classroom documents -> classroom) are now accessible using nested URL and we have no control anymore on the current resource because the JWT token is based on the playlist on a LTI context. Every queryset must be filtered using the current related resource in the url.
=> Force filtering queryset on current related object in each viewset

CHANGELOG.md, src/frontend/package.json, src/frontend/packages/lib_classroom/src/components/ClassroomWidgetProvider/index.spec.tsx, src/frontend/packages/lib_classroom/src/components/ClassroomWidgetProvider/widgets/RetentionDate/index.spec.tsx, src/frontend/packages/lib_classroom/src/components/ClassroomWidgetProvider/widgets/RetentionDate/index.tsx, src/frontend/packages/lib_classroom/src/components/ClassroomWidgetProvider/widgets/Scheduling/index.spec.tsx, src/frontend/packages/lib_common/src/cunningham-style.css, src/frontend/packages/lib_common/src/cunningham-tokens.css, src/frontend/packages/lib_components/src/common/SchedulingFields/index.spec.tsx, src/frontend/packages/lib_components/src/common/SchedulingFields/index.tsx, src/frontend/packages/lib_components/src/common/Widgets/RetentionDate/index.spec.tsx, src/frontend/packages/lib_components/src/common/Widgets/RetentionDate/index.tsx, src/frontend/packages/lib_components/src/common/Widgets/index.tsx, src/frontend/packages/lib_components/src/common/index.tsx, src/frontend/packages/lib_tests/package.json, src/frontend/packages/lib_tests/src/cunningham.tsx, src/frontend/packages/lib_tests/src/index.ts, src/frontend/packages/lib_video/src/components/common/VideoWidgetProvider/index.spec.tsx, src/frontend/packages/lib_video/src/components/common/VideoWidgetProvider/widgets/RetentionDate/index.spec.tsx, src/frontend/packages/lib_video/src/components/common/VideoWidgetProvider/widgets/RetentionDate/index.tsx, src/frontend/packages/lib_video/src/components/common/VideoWidgetProvider/widgets/SchedulingAndDescription/index.spec.tsx, src/frontend/packages/lib_video/src/components/common/VideoWidgetProvider/widgets/SchedulingAndDescription/index.tsx, src/frontend/packages/lib_video/src/components/live/Teacher/Wrapper/index.spec.tsx, src/frontend/yarn.lock
Replace the Grommet Datepicker with the Cunningham Datepicker.
Description...
[Marsha (1).webm](https://github.com/openfun/marsha/assets/25994652/6efd5a72-a418-4872-96ee-7bd3e32cd66a)
=> 💄(frontend) replace to cunningham Datepicker

CHANGELOG.md, src/backend/marsha/core/tests/test_xapi.py, src/backend/marsha/core/tests/xapi/document/test_statement_from_website.py, src/backend/marsha/core/xapi.py
Download a video or a document are statements that were not officially defined
in xAPI profiles. A new LMS profile release in the next weeks by Gaia-X DASES
organisation defines the spec for this statement.
The `category` field in context.contextActivities traces this information: it is
added for `download a document` statement definition. `Download a video`
statement was mistakenly related to the official Video profile IRI but was not
part of its specification. It is replaced with the LMS profile IRI.
=> Change downloading statements category related activity 

CHANGELOG.md, src/frontend/apps/lti_site/components/ClaimLink/index.spec.tsx, src/frontend/apps/lti_site/components/ClaimLink/index.tsx
The claim link was display by default by setting the state based on appDatata content. This can lead to displaying the link few second and the state is changed only if the resource is-claimed. This introduce a bug because this endpoint can not be fetch by a student, so student have the link display. This fix does the opposite, when mounted, the state is set to false and then the link is display only if the request succeed and is claimed is strictly false.
=> 🐛(front) display claim link only when is-claimed request succeeded

src/backend/marsha/core/api/playlist.py, src/backend/marsha/core/serializers/playlist.py, src/backend/marsha/core/tests/api/playlists/test_claim.py, src/backend/marsha/core/tests/api/playlists/test_create.py, src/backend/marsha/core/tests/api/playlists/test_list.py, src/backend/marsha/core/tests/api/playlists/test_retrieve.py, src/frontend/apps/lti_site/components/App/AppContentLoader/index.spec.tsx, src/frontend/apps/lti_site/components/App/AppContentLoader/index.tsx, src/frontend/apps/standalone_site/src/features/App/App.tsx, src/frontend/packages/lib_components/src/utils/index.ts, src/frontend/packages/lib_components/src/utils/retryQuery.spec.ts, src/frontend/packages/lib_components/src/utils/retryQuery.ts
When we introduced playlist.is_claimable, we forgot to check this attribute on playlist claim API endpoint.
- When calling playlist claim endpoint, raise a 403 if playlist is not claimable.
- Don't retry frontend queries if we got a 403 response from API.
- Add is_claimable to playlist serializer
=> 🩹(backend) check for playlist claimability when claiming

src/frontend/packages/lib_components/src/data/stores/useSentry/index.spec.ts, src/frontend/packages/lib_components/src/data/stores/useSentry/index.ts, src/frontend/packages/lib_components/src/utils/beforeSendSentry.spec.ts, src/frontend/packages/lib_components/src/utils/beforeSendSentry.ts, src/frontend/packages/lib_components/src/utils/index.ts
As we have many errors related to a Safari bug.
https://bugs.webkit.org/show_bug.cgi?id=231150
Although it has been fixed, we decided to filter it from Sentry to avoid flooding.
Don't capture errors for TypeError("Load failed")
=> 🥅(frontend) filter TypeError from sentry capture

CHANGELOG.md, src/backend/marsha/core/forms.py, src/backend/marsha/core/tests/api/video/test_create.py
The license sent in the POST request, when a video is created was missing in the video form. We must add it in order to save the license choose by a user.
Fixes #2048
=> 🐛(back) save license on video creation

CHANGELOG.md, src/frontend/packages/lib_classroom/src/components/ClassroomWidgetProvider/widgets/Recordings/Recording/index.spec.tsx, src/frontend/packages/lib_classroom/src/components/ClassroomWidgetProvider/widgets/Recordings/Recording/index.tsx
When a user click on the convert button, to convert a recording in VOD, the button state does not change and the user can think the click didn't work. To avoid this confusion, the button is disabled while the classroom refetch is not made.
=> ✨(front) disable classroom convert button when converting

CHANGELOG.md, src/backend/marsha/deposit/serializers.py, src/backend/marsha/deposit/tests/api/depositedfiles/test_list.py
Deposited files with some unicode characters in their filename were leading to an error on cloudfront when downloading.
Fixes #2314
add urllib.parse.quote to the filename in response-content-disposition
=> 🐛(backend) quote deposited file url

CHANGELOG.md, src/frontend/apps/standalone_site/src/features/Contents/features/ClassRoom/components/Manage/ClassroomManage.spec.tsx, src/frontend/apps/standalone_site/src/features/Contents/features/ClassRoom/components/Manage/ClassroomManage.tsx, src/frontend/apps/standalone_site/src/features/Contents/features/Live/components/Manage/LiveManage.spec.tsx, src/frontend/apps/standalone_site/src/features/Contents/features/Live/components/Manage/LiveManage.tsx, src/frontend/apps/standalone_site/src/features/Contents/features/Video/components/Manage/VideoManage.spec.tsx, src/frontend/apps/standalone_site/src/features/Contents/features/Video/components/Manage/VideoManage.tsx
When we were deleting a resource, the checkbox to delete it remained displayed on the cards even on the other pages. 
See: https://github.com/openfun/marsha/issues/2409
=> 🐛(website) fix checkbox to delete resource remains displayed

CHANGELOG.md, src/frontend/apps/lti_site/components/VideoWizard/index.tsx, src/frontend/apps/standalone_site/src/features/Contents/features/ClassRoom/components/Manage/ClassRoomCreateForm.tsx, src/frontend/apps/standalone_site/src/features/Contents/features/ClassRoom/components/Manage/ClassroomManage.tsx, src/frontend/apps/standalone_site/src/features/Contents/features/Live/components/Manage/LiveCreateForm.tsx, src/frontend/apps/standalone_site/src/features/Contents/features/Live/components/Manage/LiveManage.tsx, src/frontend/apps/standalone_site/src/features/Contents/features/Video/components/Manage/VideoCreateForm.tsx, src/frontend/apps/standalone_site/src/features/Contents/features/Video/components/Manage/VideoManage.tsx, src/frontend/apps/standalone_site/src/features/Playlist/components/CreatePlaylistForm.tsx, src/frontend/apps/standalone_site/src/features/Playlist/components/PlaylistPage.tsx, src/frontend/packages/lib_classroom/src/components/ClassroomWidgetProvider/widgets/DeleteClassroom/index.tsx, src/frontend/packages/lib_markdown/src/components/MarkdownEditor/index.spec.tsx, src/frontend/packages/lib_video/src/components/common/VideoWidgetProvider/widgets/DeleteVideo/index.tsx
We were redirecting the user to his previous page, sometimes there was no previous page or the previous page was not the most relevant one. Now we redirect to the parent page.
See issue: https://github.com/openfun/marsha/issues/2404
=> 🐛(website) correctly redirect a user when a resource is deleted

src/backend/marsha/bbb/factories.py, src/backend/marsha/bbb/management/commands/refresh_bbb_recordings.py, src/backend/marsha/bbb/tests/test_command_refresh_bbb_recordings.py, src/backend/marsha/bbb/tests/test_delete_outdated_classrooms.py, src/backend/marsha/core/tests/management_commands/test_delete_outdated_videos.py, src/backend/marsha/core/tests/models/test_retention_date_object_mixin.py, src/backend/marsha/core/tests/test_api_playlist_portability.py, src/backend/marsha/deposit/tests/api/depositedfiles/test_initiate_upload.py, src/backend/marsha/markdown/factories.py
In django 5.0, lot of code related to pytz timezone is removed. Naive datetime are not supported anymore because we will use the USE_TZ setting with the value True. Also, django.utils.timezone.utc is removed.
=> ♻️(back) remove deprecation about timezone

CHANGELOG.md, renovate.json, src/backend/marsha/settings.py, src/backend/setup.cfg
Channels and channels-redis were blocked in version 3 because version 4 was not compatible with recent version of python and django. Now we are using django 4.2 and python 3.11 we can upgrade them. Upgrading them fixes an issue linked to internal usage of asyncio.
=> ⬆️(back) upgrade channels and channels-redis to version 4

CHANGELOG.md, src/backend/marsha/bbb/api.py, src/backend/marsha/bbb/tests/test_utils_tokens.py
When a user is joining a classroom, created in the standalone site, from an invite link, the JWT token does not contains user id and the resource does not belong to a consumer site. In that case, the user_id parameters set in the join url will be the same for all user using an invite link. With BBB 2.6 it seems that it is not possible anymore to have multiple time the same user with the same user_id. Surprisingly user are ejected once 4 users with the same user_id have joined and they are ejected randomly.
=> 🐛(back) force bbb user_id uniqueness

CHANGELOG.md, src/frontend/packages/lib_markdown/src/components/MarkdownEditor/index.spec.tsx, src/frontend/packages/lib_markdown/src/components/MdxRenderer/index.spec.tsx, src/frontend/packages/lib_markdown/src/components/MdxRenderer/index.tsx
Markdown save was broken, because of a gap between the real rendered content, and the one sent to the parent component callback.
Don't use the dom to retrieve generated content.
=> 🐛(frontend) fix markdown rendering

src/backend/marsha/core/management/commands/clean_aws_elemental_stack.py, src/backend/marsha/core/tests/management_commands/test_clean_aws_elemental_stack.py
When an old live without live_stopped_with_email set in live_info is cleaned, a KeyError was raised.
Check for live_stopped_with_email presence in live_info before removing it.
=> 🐛(backend) fix clean_aws_elemental_stack

CHANGELOG.md, src/backend/marsha/bbb/tests/bbb_utils/test_create.py, src/backend/marsha/bbb/utils/bbb_utils.py, src/frontend/packages/lib_classroom/src/components/DashboardClassroomForm/index.spec.tsx, src/frontend/packages/lib_classroom/src/components/DashboardClassroomForm/index.tsx
When a meeting is not correctly closed by BBB, it is not possible
to create it again. To fix this issue, we must try to force to end it
to be _maybe_ be able to create it again
See https://github.com/bigbluebutton/bigbluebutton/issues/18913
=> 🐛(back) force to end BBB meeting when creation fail

CHANGELOG.md, src/backend/setup.cfg
Django 4.2 supports psycopg 3, and will remove support for version 2 in the future.
Fix #2186 
No further modifications seems needed other than updating the dependency.
=> ⬆️(backend) update psycopg to version 3

src/frontend/apps/standalone_site/package.json, src/frontend/package.json, src/frontend/yarn.lock
the cmd `yarn start` in `standalone_site` didn't work.
The pin in the frontend packages fixed the command `yarn build` but the command `start` was still giving an error.
This PR fix this error.
=> ⬆️(frontend) update fork-ts-checker-webpack-plugin

CHANGELOG.md, src/frontend/apps/lti_site/apps/classroom/components/SelectContent/SelectContentSection/index.tsx, src/frontend/apps/lti_site/apps/deposit/components/SelectContent/SelectContentSection/index.tsx, src/frontend/apps/lti_site/apps/markdown/components/SelectContent/SelectContentSection/index.tsx, src/frontend/apps/lti_site/components/LTINav/index.tsx, src/frontend/apps/lti_site/components/SelectContent/SelectContentSection/index.tsx, src/frontend/packages/lib_components/src/common/Box/index.tsx, src/frontend/packages/lib_components/src/common/Card/ClosingCard/index.tsx, src/frontend/packages/lib_components/src/common/Card/ContentCard/index.tsx, src/frontend/packages/lib_markdown/src/components/MarkdownEditor/index.tsx, src/frontend/packages/lib_video/src/components/common/VideoLayout/DisplayNameForm/index.spec.tsx, src/frontend/packages/lib_video/src/components/live/Student/StudentLiveStarter/StudentLiveWaitingRoom/index.spec.tsx, src/frontend/packages/lib_video/src/components/live/Student/StudentLiveStarter/index.spec.tsx, src/frontend/packages/lib_video/src/components/live/common/InputDisplayName/index.spec.tsx, src/frontend/packages/lib_video/src/components/live/common/InputDisplayName/index.tsx, src/frontend/packages/lib_video/src/components/live/common/InputDisplayNameOverlay/index.spec.tsx, src/frontend/packages/lib_video/src/components/live/common/ViewersList/components/ViewersListItemContainer/index.tsx
=> ♻️(frontend) replace easy grommet components

CHANGELOG.md, src/frontend/apps/standalone_site/src/features/App/AppRoutes.spec.tsx, src/frontend/apps/standalone_site/src/features/Authentication/hooks/useAuthenticator.spec.tsx, src/frontend/apps/standalone_site/src/features/Authentication/hooks/useAuthenticator.tsx, src/frontend/apps/standalone_site/src/features/Contents/features/ClassRoom/components/Update/ClassRoomUpdate.spec.tsx, src/frontend/apps/standalone_site/src/features/Contents/features/ClassRoom/components/Update/ClassRoomUpdate.tsx, src/frontend/packages/lib_components/src/common/Typo/index.tsx, src/frontend/packages/lib_components/src/common/Typo/styleBuilder.ts, src/frontend/packages/lib_components/src/hooks/stores/useJwt/index.ts, src/frontend/packages/lib_components/src/utils/serviceWorker/serviceWorkerRefreshToken/useServiceWorkerRefreshToken/index.spec.tsx
Opening a classroom invite link switch our current token to
a student token, so when we go back to the browser instructor tab,
the resources cannot be access anymore, this is because of the
persistency of the student token. We remove this persistency,
the student token is now only valid for the current tab.
=> 🛂(frontend) remove persistance student token

CHANGELOG.md, src/frontend/packages/lib_video/src/components/common/PictureInPictureLayer/PictureActionLayer/index.tsx, src/frontend/packages/lib_video/src/components/common/PictureInPictureLayer/PictureInPictureElement/index.spec.tsx, src/frontend/packages/lib_video/src/components/common/PictureInPictureLayer/PictureInPictureElement/index.tsx, src/frontend/packages/lib_video/src/components/common/PictureInPictureLayer/PictureInPictureSwitchAction/index.tsx, src/frontend/packages/lib_video/src/components/common/PictureInPictureLayer/index.tsx, src/frontend/packages/lib_video/src/components/common/TeacherVideoInfoBar/index.tsx, src/frontend/packages/lib_video/src/components/common/VideoInfoBar/index.tsx, src/frontend/packages/lib_video/src/components/live/Student/StudentLiveStarter/StudentLiveWrapper/StudentLiveInfoBar/index.tsx, src/frontend/packages/lib_video/src/components/live/Teacher/Wrapper/Controls/TeacherLiveRecordingActions/index.tsx, src/frontend/packages/lib_video/src/components/live/Teacher/Wrapper/Controls/index.tsx, src/frontend/packages/lib_video/src/components/live/common/JitsiControls/AudioControl/index.tsx, src/frontend/packages/lib_video/src/components/live/common/JitsiControls/CameraControl/index.tsx
(live) glitch d'affichage du partage de documents en mode fenêtré sur navigateur.
https://trello.com/1/cards/654b8ab615e123d2213a9c9a/attachments/655347173d05e4332536b0e1/download/Partage_de_document_-_responsiveness.webm
https://trello.com/1/cards/654b8ab615e123d2213a9c9a/attachments/65534793bf00d478bfc1589f/download/Partage_de_document_-_responsiveness_02.webm
The width of the vignette is limited here:
https://github.com/openfun/marsha/blob/d55f4d5e95c075291f2a27e775f8a65f363b7f36/src/frontend/packages/lib_video/src/conf/pictureInPicture.ts#L3
It could have been nice to increase to 0.8, but we get a responsive problem with the height, it asks a not so small refacto to be able to make it works correctly.
=> 🐛(lib-video) fix display issues with picture shared ressource in live

CHANGELOG.md, src/frontend/packages/lib_video/src/api/useStartSharingMedia/index.ts, src/frontend/packages/lib_video/src/components/common/VideoWidgetProvider/widgets/SharedLiveMedia/SharedLiveMediaItem/ToggleSharing/index.spec.tsx, src/frontend/packages/lib_video/src/components/common/VideoWidgetProvider/widgets/SharedLiveMedia/SharedLiveMediaItem/ToggleSharing/index.tsx
Issue: #2511
When a user tried to share a resource when another one was already shared, the sharing was not started and an error was displayed.
We now stop the sharing of the first resource and start the sharing of the new one if we get the error 'Video is already sharing' from the backend.
=> ♻️(lib_video) manage sharing error when one resource is already shared

.circleci/config.yml, docker-compose.yml, docker/images/e2e/Dockerfile
The docker image version of playwright does not match anymore the python playsright package. We have to upgrade it both in our image and in the CI.
=> ⬆️(e2e) upgrade playwright docker image to v1.40.0

CHANGELOG.md, src/frontend/apps/standalone_site/src/features/App/AppRoutes.spec.tsx, src/frontend/apps/standalone_site/src/features/Authentication/hooks/useAuthenticator.spec.tsx, src/frontend/apps/standalone_site/src/features/Authentication/hooks/useAuthenticator.tsx, src/frontend/apps/standalone_site/src/features/Contents/features/ClassRoom/components/Update/ClassRoomUpdate.spec.tsx, src/frontend/apps/standalone_site/src/features/Contents/features/ClassRoom/components/Update/ClassRoomUpdate.tsx, src/frontend/packages/lib_components/src/hooks/stores/useJwt/index.spec.tsx, src/frontend/packages/lib_components/src/hooks/stores/useJwt/index.ts
The API calls were still using the persistent store instead of the local store when using the invite link. 
We removed these double stores logic and now only use 1 store that have a "withPersistency" option. 
The invite links set this option to false so that the store is not persistent.
=> 🐛(frontend) wrong store with invite link

src/backend/marsha/core/tests/utils/test_transcode.py, src/backend/marsha/core/utils/transcode.py, src/backend/marsha/settings.py, src/backend/setup.cfg
With the new version of the library, we can now update the video state to "error" when the transcoding fails.
Update the settings name and the callback function to update the video state accordingly to the transcoding result
=> ⬆️(back) upgrade django-peertube-runner-connector library

src/tray/templates/services/nginx/configs/marsha.conf.j2
The socket.io route must be upgraded to allow websocket connection. Also, we must set the Origin header because peertube does not set it when it connects to the websocket. Without this, the ALLOWED_HOSTS is blocking the connection.
Description...
=> 🔧(tray) add an nginx directive to manage socket.io route

src/backend/setup.cfg
With the new version of the library, peertube runner is no more using the marsha app to download the video.
Update the django-peertube-runner-connector library to 0.5.0
=> ⬆️(back) upgrade django-peertube-runner-connector to 0.5.0

src/backend/setup.cfg, src/tray/templates/services/app/_deploy_base.yml.j2, src/tray/templates/services/app/deploy_app.yml.j2, src/tray/templates/services/app/deploy_celery.yml.j2, src/tray/templates/services/app/deploy_xapi.yml.j2, src/tray/templates/services/nginx/configs/marsha.conf.j2, src/tray/vars/all/main.yml
In order to manage connection with the peertube runner, we must have to configure the tray. First a new location is added in nginx to manage the socket connection. This connection is made between service directly without going out of the k8s cluster, so the service name must be added to the django allowed hosts.
=> 🔧(tray) configure tray to handle connection with peertube runner

CHANGELOG.md, src/backend/marsha/core/api/video.py, src/backend/marsha/core/models/playlist.py, src/backend/marsha/core/tasks/s3.py, src/backend/marsha/core/tasks/video.py, src/backend/marsha/core/tests/api/video/test_upload_ended.py, src/backend/marsha/core/tests/tasks/test_s3.py, src/backend/marsha/core/tests/tasks/test_video.py
The upload-ended is taking too much time with S3 storage because it launch the transcoding process that is fetching uploaded video info, and create thumbnail 
Create a celery task that will launch the transcoding process
=> ✨(back) transcode video celery task

src/tray/templates/services/app/cronjob_pipeline.yml.j2, src/tray/templates/services/app/job_db_migrate.yml.j2
To execute jobs, the cloudfront signing key is now needed. This is because the module stores is entirely loaded in a management command.
=> 🐛(tray) add cloudfront signing key in jobs

CHANGELOG.md, src/backend/marsha/core/admin.py
In the PortabilityRequestAdmin fields for_resource_id and for_resource_model were still present but not existing anymore in the model.
=> 🐛(back) remove non existing fields in PortabilityRequestAdmin

renovate.json, src/backend/setup.cfg
We are not able tu use lxml >= 5.0.0. We have a segfault when using it. The solution could be to install it without binaries but it is not possible to do it using the setup.cfg file.
We have to investigate if it will be possible if we switch to pyproject.
Linked issues :
https://github.com/SAML-Toolkits/python3-saml/issues/388 
https://github.com/SAML-Toolkits/python3-saml/issues/389
=> 📌(back) pin lxml to version < 5

src/frontend/yarn.lock, src/webtorrent/yarn.lock
fixed [CVE-2023-42282](https://github.com/advisories/GHSA-78xj-cgh5-2h22)
=> Bump ip from 1.1.8 to 1.1.9

docker-compose.yml, src/aws/cloudfront.tf, src/backend/marsha/core/storage/s3.py, src/backend/marsha/core/tasks/timed_text_track.py, src/backend/marsha/core/tasks/video.py, src/backend/marsha/settings.py, src/tray/templates/services/app/_deploy_base.yml.j2, src/tray/vars/all/main.yml
The workflow to use peertube runner was not working fine, mostly due to how cloudfront was configured. Because we now have only one mp4 fragmented file for each resolution we can't protect them anymore otherwise the player can't play them.
Other commits fine tuned celery usage,
=> Finalize peertube usage

src/frontend/packages/lib_video/src/components/common/VideoWidgetProvider/widgets/Transcripts/TranscriptReader/index.tsx
The library (pycaption) we are using to convert transcript in a celery task does not keep the cue indeice anymore so we can't filter cues by there id.
=> ♻️(front) remove cue filtering in TranscriptReader

src/backend/marsha/core/tasks/timed_text_track.py, src/backend/marsha/core/tests/tasks/test_timed_test_track.py
pycaption is already escaping illegal characters. In our code we were escaping them a first time resulting on a double escape and then the transcript is not display correctly at all. Relyin on pycaption library is enough and it is not possible to disable this feature in pycaption
=> ♻️(back) rely on pycaption lib to escape illegal characters

src/tray/templates/services/app/_deploy_base.yml.j2
For all variants (app, xapi and celery), the container name is the name. It is not possible to do a filter on a specific container name. WEe change the container name using the variant name.
=> ♻️(tray) add variant name in container name

CHANGELOG.md, src/backend/marsha/core/management/commands/check_live_state.py, src/backend/marsha/core/tests/management_commands/test_check_live_state.py
Medialive has changed when the alerts are set for a medialive channels. Before alerts were set with a delay once the channel started, now they are set at the exact same time. So we have to adjust the startTime when filtering logs in the check_live_state command to be sure to have all the logs from the beginning. Otherwise some logs are missed and the command is failing.
Fix #2564
=> 🐛(back) correctly set startime with filtering medialive logs

renovate.json, src/backend/setup.cfg
With the constraint on lxml<5, an error on the collectstatic occured about lxml
and xmlsec libxml2 versions mismatch.
Pin lxml to the latest release fix this error.
=> 📌(backend) pin lxml dependency to 5.2.1

CHANGELOG.md, CONTRIBUTORS.md, src/frontend/packages/lib_classroom/src/components/DashboardClassroomAskUsername/index.spec.tsx, src/frontend/packages/lib_classroom/src/components/DashboardClassroomAskUsername/index.tsx, src/frontend/packages/lib_components/src/common/Modal/ModalButton.tsx
When users join a classroom via an invite link, they are prompted to enter a username before joining.
Previously, this form could not be submitted using the Enter key.
Adding form submission when pressing the Enter key.
Closes #2583 
[Screencast from 23-05-2024 12:21:36.webm](https://github.com/openfun/marsha/assets/18288083/635ae799-e37c-4d6b-b2bd-520e5a39756b)
=> ✨(front) enable form submission with enter key when entering a classroom

CHANGELOG.md, CONTRIBUTORS.md, src/frontend/packages/lib_classroom/src/components/DashboardClassroom/index.spec.tsx, src/frontend/packages/lib_classroom/src/components/DashboardClassroom/index.tsx, src/frontend/packages/lib_components/src/settings.ts
Currently, each time an anonymous user wants to join a classroom, it has to provide a user name. It orders to improve UX, we decide to store username provided in local storage when user join the classroom. In this way, next time it wants to join, the input will be prefilled.
=> ✨(front) persist username on classroom join

CHANGELOG.md, renovate.json, src/backend/marsha/core/serializers/video.py, src/backend/marsha/core/tests/serializers/test_video.py, src/backend/setup.cfg
the combine usage of peertube-runner and cloudfront can lead to situation where the master HLS url is cached for 24 hours without all the resolutions available. Once the first resolution is transcoded, the master HLS file is generated and available in Marsha. The websocket updates the video object and the file is in cache for 24 hours. We introduce a query parameter used to compute the resolutions hash. So every time the list of resolutions available is changing, this hash also change and a new cache is generated.
Fixes #2600
=> ♻️(back) compute hls url based on video resolutions available

CHANGELOG.md, src/backend/marsha/core/tasks/timed_text_track.py, src/backend/marsha/core/tests/tasks/test_timed_text_track.py
When reading a subtitle content file uploaded, sometimes it starts with a Byte Order Mark and the srt reader is failing to detect the content as a srt one.
We have to remove it before using the detect_format from the pycaption library.
=> 🐛(back) manage subtitles content starting with a BOM

Dockerfile, docker/images/webtorrent/Dockerfile, src/aws/Dockerfile
Since a recent version of docker, we have a warning telling us that the FROM and As instruction are not using the same case. This commit fix it.
https://docs.docker.com/reference/build-checks/from-as-casing/
=> 🔧(docker) fix FromAsCasing warning

CHANGELOG.md, src/frontend/packages/lib_classroom/src/components/DashboardClassroom/index.spec.tsx, src/frontend/packages/lib_classroom/src/components/DashboardClassroom/index.tsx, src/frontend/packages/lib_classroom/src/components/DashboardClassroomAskUsername/index.spec.tsx, src/frontend/packages/lib_classroom/src/components/DashboardClassroomAskUsername/index.tsx, src/frontend/yarn.lock
Previously, in commit 29480e5, we persist fullname on join classroom in order to
improve ux. But the current implementation has a drawback, indeed once a
username is persisted, the user directly join the classroom and is not able
anymore to update its fullname. In order to improve that, instead of joining
immediately the room, we simply use the persisted value as default value for
the full name form.
=> 🐛(front) allow to update persisted username on join classroom

docker-compose.yml
As we made a special tag for the peertube-runner image in which whisper_ctranslate2 is installed, we need to use it here.
=> 🐛(backend) update peertube-runner to latest-whisper_ctranslate2

CHANGELOG.md, src/tray/templates/services/app/deploy_ws.yml.j2, src/tray/templates/services/app/svc_ws.yml.j2, src/tray/templates/services/nginx/configs/marsha.conf.j2, src/tray/vars/all/main.yml
We have detected a memory leak in the websocket application. An issue exists on the django channels github repo about this topic. We also detected that this memory leak can have side effect on the asgi application, the application can become slower leading to timeout. To remove this side effect we decided to create a deploy dedicated to the websocket application and nginx is reponsible to use the right backend based on the request path.
https://github.com/django/channels/issues/2094
=> ♻️(tray) split websocket and asgi apps in tray

CHANGELOG.md, src/frontend/packages/lib_video/src/components/vod/Student/Dashboard.tsx
in the VOD student dashboard we are using the websocket to update the video view. Opening a websocket can consume lot of resources on the backend application for very few user experience improvement. We want to try to remove this connection to see if there is an impact on the backend load vs degrading a little bit the user experience.
=> ⚗️(front) remove websocket connection in VOD student dashboard

src/backend/setup.cfg
Upgrade django_peertube_runner_connection to v0.9.0
https://github.com/openfun/django-peertube-runner-connector/releases/ tag/v0.9.0
=> ⬆️(back) upgrade django_peertube_runner_connection to v0.9.0

src/backend/marsha/core/tasks/s3.py
In the s3 task module, the settings was imported from the marsha namesapce, it should be from django.conf
=> 🐛(back) use right settings module in s3 task

CHANGELOG.md, src/backend/marsha/account/social_pipeline/playlist.py, src/backend/marsha/account/tests/test_social_pipeline_playlist.py, src/backend/marsha/core/defaults.py
When a user is created via shibbolet, we want to create a playlist for each of us and they will be administrator of this playlist.
=> ♻️(back) allow all users created via shibboleth to have a playlist

CHANGELOG.md, src/backend/marsha/core/management/commands/delete_transcoding_temp_files.py, src/backend/marsha/core/tests/management_commands/test_delete_transcoding_temp_files.py, src/backend/marsha/core/tests/utils/test_transcode.py, src/backend/marsha/core/utils/transcode.py
When we trigger a peertube transcript task on a video, we fetch the highest resolution possible.
If the video source model instance exists, we use it.
But, the related files lives in a temporary directory, so there deleted after a given time, which leads to an error.
=> Cleanup transcoding temp files

CHANGELOG.md, src/frontend/packages/lib_classroom/src/components/DashboardClassroomAskUsername/index.spec.tsx, src/frontend/packages/lib_classroom/src/components/DashboardClassroomAskUsername/index.tsx
Currently, in the form to join a classroom, if the input is populated with the username stored into local storage, the join button remains disabled until the user changes the input value.
The user should be able to click immediately on the join button once a value populates the field.
=> 🐛(front) enable join classroom button with local storage username

CHANGELOG.md, src/backend/marsha/core/api/xapi.py, src/backend/marsha/core/tests/api/xapi/video/test_from_lti.py, src/backend/marsha/core/tests/test_xapi.py, src/backend/marsha/core/xapi.py
When a xAPI request is made from a LTI context but the video was created on the website, there is no consumer_site attached to the playlist. We are using the domain from the consumer_site when the xAPI request is made in a LTI context. To fix this issue, in the xAPI endpoint is testing if there is a consumer site and if not the one from the LTI passport is used.
Description...
=> 🐛(xAPI) use domain from lti jwt token when no consumer site used

CHANGELOG.md, src/backend/marsha/core/api/xapi.py, src/backend/marsha/core/tests/api/xapi/video/test_from_lti.py
When a video or document is used in a public view and has been created on the website, we have no information at all about the consumer site to use. In that specifice case we want to ignore the XAPI statement.
=> 🐛(back) ignore XAPI statements from public view without consumer_site

src/backend/setup.cfg
https://github.com/openfun/django-peertube-runner-connector/releases/tag/v0.11.0
=> ⬆️(back) upgrade django-peertube-runner-connector to version 0.11

.circleci/config.yml, CHANGELOG.md, Dockerfile, docker-compose.yml, docker/images/e2e/Dockerfile
Python 3.13 has been released in october 2024, we want to upgrade to python 3.12 to keep max 1 version of difference. The e2e image has been revamped and is based on the marsha:dev image.
=> ⬆️(back) upgrade to python 3.12

CHANGELOG.md, src/backend/marsha/core/api/video.py, src/backend/marsha/core/tests/api/video/test_transcript_source.py
The transcript-source video api endpoint was streaming the video content. Instead of doing this we can return a permanent redirect response to the video url. Peertube runner is able to manage this redirection, it releases pressure on our servers and will directly use a CDN URL.
=> ⚡️(back) redirect video url instead of streaming it on /transcript-source

CHANGELOG.md, src/backend/marsha/core/api/video.py, src/backend/marsha/core/tests/api/video/test_initiate_transcript.py
When a live has been harvested and transform in VOD, then it is possible to initialize a transcription process.
=> 🐛(back) authorize ended live to initiate a transcription

.circleci/config.yml, CHANGELOG.md, src/backend/marsha/core/admin.py, src/backend/marsha/core/tests/test_admin.py
In the admin, we want to display for an organization, consumer site and
playlist the addition of videos size and duration.
=> ✨(back) display in admin video duration and size

CHANGELOG.md, renovate.json, src/backend/marsha/account/tests/test_middleware.py, src/backend/marsha/bbb/tests/api/classroom/test_retrieve.py, src/backend/marsha/bbb/tests/bbb_utils/test_create.py, src/backend/marsha/core/tests/management_commands/test_send_vod_convert_reminders.py, src/backend/marsha/core/tests/utils/test_send_emails.py, src/backend/setup.cfg
Some backend dependencies were ignored by renovate. We can now upgrade part of them.
The upgrade to django 5.1 will be possible once postgresql 12 will be removed.
=> Upgrade backend dependencies

CHANGELOG.md, src/tray/templates/services/nginx/configs/marsha.conf.j2
Some requests to the `success` endpoint ends up returning a 504 Timeout, usually
for the bigger vod files.
The `success` endpoint loads the converted video file and manipulates it, which
could be taking some time.
Increasing the connection timeout on the Nginx conf to 300s so it does not
timeout for longer files.
=> 🔧(tray) increase connection timeout for peertube runner requests

CHANGELOG.md, src/backend/marsha/bbb/api.py, src/backend/marsha/bbb/tests/api/classroom/recordings/test_create_vod.py
The BigBlueButton VODs are still using the AWS transcoding pipeline by default.
Switching to use the Peertube transcoding pipeline.
=> ✨(backend) use peertube transcoding pipeline by default

CHANGELOG.md, src/aws/cloudfront.tf, src/backend/marsha/bbb/api.py, src/backend/marsha/bbb/tests/api/classroom/recordings/test_create_vod.py
- As the BBB VODs are fetched and processed by a Lambda, some deeper changes need
to be done to change the default transcoding pipeline from AWS to Peertube.
- As we are migrating from Cloudfront to Scaleway Edge Services, we cannot sign
URLs anymore.
- Reverting the changes so the default pipeline for VODs is AWS.
- Removing Cloudfront signing using Terraform (applied to staging, not to production yet)
=> 🔥(backend) revert default transcoding pipeline and remove Cloudfront URL signing

CHANGELOG.md, src/frontend/packages/lib_video/src/components/common/VideoPlayer/index.tsx
Since the Vite upgrade from 5.4.9 to 6.0.1, the download, transcript and shared
media icons were missing from the video player control bar on the standalone
site.
Based on the Vite documentation (https://vite.dev/guide/assets), when inlining
SVGs through url(), the variable needs to be wrapped within double quotes.
=> 🐛(frontend) fix svg icons import on videoplayer control bar

CHANGELOG.md, src/tray/templates/services/nginx/configs/marsha.conf.j2
Previous increases to connection timeouts had no effect due to the requests being proxied through `proxy_to_marsha_app`, which overrides those settings. 
This fix moves the timeout configuration directly into the `proxy_to_marsha_app` location block to ensure they are properly applied. 
_Note: This is a temporary, hacky workaround to avoid 504 Gateway Timeouts when the PeerTube runner POSTs to /success. A proper fix is still needed._
=> 🔧(tray) fix ineffective timeout settings for peertube runner requests

src/aws/s3_scaleway.tf
Allow users to read the `classroom` resource in the S3 SCW bucket policy.
=> 🔧(terraform) add classroom resource in SCW bucket policy

docker/files/docker-entrypoint-initdb.d/init_user_db.sh
When doing a `make bootstrap`, an error occurs:
```
Error in SQL transaction: /usr/lib/prosody/util/sql.lua:163: Error preparing statement handle: ERROR:  relation "prosody" does not exist
```
This issue has been present since the upgrade from PostgreSQL 13 to 16.
Starting with PostreSQL 15, the CREATE privilege on `public` schema is revoked from all users except the database owner.
Adding a connection to the Prosody database at container startup to manually grant all privileges on the `public` schema, ensuring Prosody can create its tables properly.
=> 🔧(docker) fix prosody table creation on startup

CHANGELOG.md, src/backend/marsha/e2e/test_lti.py, src/frontend/apps/lti_site/components/LTIRoutes/index.spec.tsx, src/frontend/apps/lti_site/components/VideoWizard/index.spec.tsx, src/frontend/apps/lti_site/components/VideoWizard/index.tsx
The `Start a live` button is still visible on the `/lti/video` page even when the `WEBINAR_ENABLED` setting is set to `False`.
- The translations will be done in another PR before the release
=> 🐛(frontend) use feature flags for LTI video/webinar buttons

CHANGELOG.md, src/backend/marsha/core/storage/filesystem.py, src/frontend/apps/lti_site/apps/deposit/components/Dashboard/DashboardStudent/UploadFiles/index.spec.tsx, src/frontend/apps/lti_site/apps/deposit/components/Dashboard/DashboardStudent/UploadFiles/index.tsx
Deposited files were correctly uploaded to Scaleway S3, but the `upload-ended`
endpoint was not being called, causing deposited files to remain in a pending
state.
Adding the confirmation call after upload completion.
=> 🐛(front) call upload-ended endpoint after deposited file upload

CHANGELOG.md, src/backend/marsha/core/api/file.py
In the preprod environment, uploading files to Marsha Document was failing due to incorrect import of the settings module from `marsha` instead of `django.conf`.
It could be nice to have a linter rule for that but it would need adding a flake8 plugin.
=> 🐛(back) fix import error preventing uploads in Marsha Document

src/backend/marsha/core/management/commands/rename_documents.py, src/backend/marsha/core/tests/management_commands/test_rename_documents.py, src/backend/marsha/deposit/management/commands/rename_deposited_files.py, src/backend/marsha/deposit/tests/test_command_rename_deposited_files.py
After some tests on preprod:
- the management commands to rename documents was not working as the documents have blank filenames. Fixing the command by using the title to create
the filename instead.
- the management commands was not working as some deposited files have an extension in their filename, but not in their object storage key. Fixing the command by using the extension field instead of
computing the extension from the filename.
=> 🐛(back) fix management command to rename deposited files and documents
